from pathlib import Path
r=Path('captain')
p=r/'roam-world184.js';s=p.read_text()
s=s.replace('xwall-side*.11,14.87,cz','xwall-side*.11,15.37,cz')
s=s.replace('return {root,solids,props,inspect:', """const roomFill=new T.PointLight(0xffe6c8,7,18,1);roomFill.visible=false;root.add(roomFill);
 function update(p){const inside=p.y<8||(Math.abs(p.x)<(p.y>20?6.2:8.6)&&p.z<(p.y>20?18:39)&&p.z>(p.y>20?-18:-42));roomFill.visible=inside;if(inside)roomFill.position.set(p.x,p.y+2.12,p.z+.25);}
 return {root,solids,props,update,inspect:""")
p.write_text(s)
p=r/'ship184.js';s=p.read_text().replace('9.5, .28, M.teak','9.82, .24, M.teak');p.write_text(s)
p=r/'chaos184.js';s=p.read_text().replace('[6,13.12,-59]','[6,13.12,-49]').replace('shipMap.update(s.time);visitedAreas.add','roam.update(p);shipMap.update(s.time);visitedAreas.add');p.write_text(s)
p=r/'shipmap184.css';s=p.read_text().replace('top:159px','top:170px');p.write_text(s)
p=r/'tools/qa184.py';s=p.read_text()
s=s.replace("('pool',(-6,13.12,-53),1.5708)","('pool',(6,13.12,-49),-1.5708)")
s=s.replace("pos(p,*xyz,yaw);p.screenshot", "pos(p,*xyz,yaw);ck('Visual fixture on actual '+name,abs(ch(p)['position']['y']-xyz[1])<.2 and abs(ch(p)['position']['z']-xyz[2])<.2,ch(p)['position']);p.wait_for_timeout(200);p.screenshot")
s=s.replace("p.screenshot(path=str(OUT/'life-recovery.png'));c.close()", """p.screenshot(path=str(OUT/'life-recovery.png'))
  pos(p,4.8,10.1,54,0)
  p.evaluate('''()=>{const t=window.__lastCall.test.chapter,a=window.__lastCall.getState().chapter.position;t.party.filter(n=>n.guard).forEach((n,i)=>{n.actor.group.position.set(a.x+Math.sin(i*Math.PI/2)*1.1,a.y,a.z+Math.cos(i*Math.PI/2)*1.1);n.attack=null;n.cooldown=3;n.state='fight';n.health=85;});t.attack('spit');}''')
  adv(p,.5);ck('An actual in-game action raises security alarm',ch(p)['alarmAt'] is not None)
  adv(p,17);ck('Slower security can still arrest and take captain to jail',ch(p)['phase']=='cell',{'phase':ch(p)['phase'],'health':ch(p)['health'],'capture':ch(p)['capture']})
  p.screenshot(path=str(OUT/'jail-continuation.png'))
  p.locator('#continueFromCell180').click();adv(p,2);p.locator('#escapeOverlayAction').click();adv(p,.1)
  ck('Existing sober escape chapter still starts',ch(p)['escape']['stage']=='escape')
  ck('No errors after jail continuation',not errors,errors);c.close()""")
p.write_text(s)
