import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export function createMaterials(){
 const cache={};
 function tex(kind){if(cache[kind])return cache[kind];const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');let seed=1972;const rng=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
  g.fillStyle={teak:'#ae9471',carpet:'#567878',metal:'#929e9e',wall:'#e1ddd3',marble:'#dbdbce',ceiling:'#e7e3d9'}[kind]||'#ccc';g.fillRect(0,0,512,512);
  if(kind==='teak'){for(let row=0;row<8;row++){const y=row*64;g.fillStyle=row%2?'#aa8e69':'#baa481';g.fillRect(0,y,512,62);g.fillStyle='#524d3c';g.fillRect(0,y+62,512,2);for(let i=0;i<100;i++){g.strokeStyle='rgba(65,37,18,'+(rng()*.18)+')';const yy=y+rng()*61;g.beginPath();g.moveTo(0,yy);g.bezierCurveTo(160,yy+2,350,yy-2,512,yy);g.stroke();}const x=row%2?128:384;g.fillStyle='#675644';g.fillRect(x,y,1,62);}}
  else if(kind==='metal'){for(let y=0;y<512;y+=20)for(let x=0;x<512;x+=30){g.strokeStyle='#526364';g.lineWidth=2;g.beginPath();g.moveTo(x,y);g.lineTo(x+9,y+8);g.stroke();g.strokeStyle='#b8c3bc';g.beginPath();g.moveTo(x+1,y-1);g.lineTo(x+10,y+7);g.stroke();}}
  else if(kind==='marble'){for(let i=0;i<140;i++){const x=rng()*512;g.strokeStyle='rgba(77,100,101,'+rng()*.12+')';g.beginPath();g.moveTo(x,0);g.bezierCurveTo(x-90,220,x+90,280,x+80,512);g.stroke();}g.strokeStyle='#5a7373';g.lineWidth=2;g.strokeRect(1,1,510,510);}
  else if(kind==='ceiling'){g.strokeStyle='#818f91';g.lineWidth=2;g.strokeRect(2,2,508,508);g.strokeStyle='#bbbcb2';g.strokeRect(12,12,488,488);}
  else{for(let i=0;i<20000;i++){g.fillStyle='rgba(20,45,48,'+rng()*(kind==='carpet'?.2:.035)+')';g.fillRect(rng()*512,rng()*512,1,kind==='carpet'?3:1);}}
  const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=4;cache[kind]=t;return t;
 }
 const std=(color,roughness=.7,metalness=0,map)=>new T.MeshStandardMaterial({color,roughness,metalness,...(map?{map:tex(map),bumpMap:tex(map),bumpScale:map==='metal'?.013:.006}:{})});
 return {ivory:std(0xf2eee2,.65,0,'wall'),white:std(0xf3f1e7),teak:std(0xffffff,.55,0,'teak'),carpet:std(0x6d8f99,.98,0,'carpet'),marble:std(0xffffff,.27,.12,'marble'),metal:std(0xb2c1c4,.38,.62,'metal'),steel:std(0xc3d1d0,.25,.8),navy:std(0x19313d,.48,.1),dark:std(0x14232a,.7,.12),brass:std(0xcead68,.3,.75),ceiling:std(0xe1e4e0,.88,0,'ceiling'),cloth:std(0x476d73,.92,0,'carpet'),red:std(0x923e36,.48,.25),engine:std(0x4b7470,.42,.5),yellow:std(0xecb847,.54,.18),glass:new T.MeshPhysicalMaterial({color:0x8ab5b9,roughness:.15,metalness:.18,transparent:true,opacity:.26,depthWrite:false}),light:new T.MeshStandardMaterial({color:0xffefc6,emissive:0xffdba2,emissiveIntensity:2.3}),green:new T.MeshStandardMaterial({color:0x68e9b0,emissive:0x2af18a,emissiveIntensity:1.1}),screen:new T.MeshStandardMaterial({color:0x123d4a,emissive:0x135566,emissiveIntensity:.6,roughness:.22})};
}
export function builder(root){
 function put(geo,mat,x,y,z,parent=root){const o=new T.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 function box(w,h,d,mat,x,y,z,parent=root){const geo=new T.BoxGeometry(w,h,d);if(mat.map){const p=geo.attributes.position,n=geo.attributes.normal,uv=geo.attributes.uv;for(let i=0;i<p.count;i++){let a,b;if(Math.abs(n.getY(i))>.5){a=p.getX(i);b=p.getZ(i);}else if(Math.abs(n.getX(i))>.5){a=p.getZ(i);b=p.getY(i);}else{a=p.getX(i);b=p.getY(i);}uv.setXY(i,a/2,b/2);}}return put(geo,mat,x,y,z,parent);}
 function round(w,h,d,r,mat,x,y,z,parent=root){const s=new T.Shape(),a=-w/2,b=-d/2;r=Math.min(r,w/3,d/3);s.moveTo(a+r,b);s.lineTo(a+w-r,b);s.quadraticCurveTo(a+w,b,a+w,b+r);s.lineTo(a+w,b+d-r);s.quadraticCurveTo(a+w,b+d,a+w-r,b+d);s.lineTo(a+r,b+d);s.quadraticCurveTo(a,b+d,a,b+d-r);s.lineTo(a,b+r);s.quadraticCurveTo(a,b,a+r,b);const geo=new T.ExtrudeGeometry(s,{depth:h,bevelEnabled:true,bevelSegments:2,bevelThickness:.012,bevelSize:.018,curveSegments:4});geo.rotateX(-Math.PI/2);return put(geo,mat,x,y-h/2,z,parent);}
 function rod(a,b,r,mat,parent=root){a=new T.Vector3(...a);b=new T.Vector3(...b);const d=b.clone().sub(a),o=put(new T.CylinderGeometry(r,r,d.length(),8),mat,0,0,0,parent);o.position.copy(a).lerp(b,.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o;}
 return {put,box,round,rod};
}
export function label(parent,text,x,y,z,w=2.4,subtitle='',color='#edddba'){
 const c=document.createElement('canvas');c.width=768;c.height=subtitle?192:128;const g=c.getContext('2d');g.fillStyle='#102b36';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#ab9362';g.lineWidth=4;g.strokeRect(3,3,762,c.height-6);g.fillStyle=color;g.textAlign='center';g.font='bold 42px sans-serif';g.fillText(text,384,subtitle?78:79,727);if(subtitle){g.font='25px sans-serif';g.fillStyle='#b7cecc';g.fillText(subtitle,384,140,718);}const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.minFilter=T.LinearFilter;const o=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:true,depthWrite:false,transparent:false,toneMapped:false}));o.position.set(x,y,z);o.scale.set(w,w*c.height/c.width,1);o.userData.wayfinding=text;o.name='READABLE / '+text;parent.add(o);return o;
}
export function batch(root){const mats=new Map();for(const o of [...root.children])if(o.isMesh&&!o.userData.dynamic&&!o.material.transparent){let list=mats.get(o.material);if(!list)mats.set(o.material,list=[]);list.push(o);}for(const [mat,list]of mats){if(list.length<2)continue;const parts=list.map(o=>{o.updateMatrix();return o.geometry.clone().applyMatrix4(o.matrix);});const geo=mergeGeometries(parts,false);if(geo){const mesh=new T.Mesh(geo,mat);mesh.castShadow=true;mesh.receiveShadow=true;mesh.name='Batched refit architecture';root.add(mesh);list.forEach(o=>{root.remove(o);o.geometry.dispose();});}parts.forEach(p=>p.dispose());}}
