"""Final gameplay consistency and bounded controller checks."""
from pathlib import Path
P=Path('captain')
p=P/'main180.js';s=p.read_text().replace('if(!chaos?.enabled)',"if(!chaos?.enabled||chaos.mode==='helm')")
s=s.replace('capture:value=>{captureFrame=Boolean(value);}', 'capture:value=>{captureFrame=Boolean(value);if(value){chaos?.updateCamera(0);renderer.setRenderTarget(renderTarget);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(fx.scene,fx.camera);}}')
p.write_text(s)
p=P/'chaos180.js';s=p.read_text()
s=s.replace("mode='helm';area.root.visible=false;", "mode='helm';for(const [group,visible] of savedVisible)group.visible=visible;area.root.visible=false;")
s=s.replace("segmentBlocked(p,player,area.walls.filter(w=>!w.vent))", "segmentBlocked(p,player,area.walls)")
s=s.replace("const ws=walls(),p=V(a.x,0,a.z)", "const ws=walls().concat(crouch?area.walls.filter(w=>w.vent):[]),p=V(a.x,0,a.z)")
s=s.replace("version:'1.8.0',mode,elapsed", "version:'1.8.0',restoredOnboard:mode==='helm'?getPeople().getSpeakers().filter(p=>p.group.visible).length:0,mode,elapsed")
s=s.replace("lastSip=-10;finished=false;statistics=", "lastSip=-10;finished=false;lastVocal=-100;shoutAt=0;sipAnim=0;statistics=")
p.write_text(s)
p=P/'performer180.js';s=p.read_text()
s=s.replace("const h=Math.sin(Math.PI*Math.min(1,n/.55));", "const h=attack.t<=attack.contact?Math.sin(attack.t/attack.contact*Math.PI/2):Math.cos(Math.min(1,(attack.t-attack.contact)/(attack.duration-attack.contact))*Math.PI/2);")
s=s.replace('inspect:()=>({arms:arms.length,', "inspect:()=>({rightHand:a.bones.get('righthand')?.getWorldPosition(V()).project(camera).toArray(),rightFoot:a.bones.get('rightfoot')?.getWorldPosition(V()).project(camera).toArray(),footVisible:legs.some(l=>l.visible),arms:arms.length,")
p.write_text(s)
p=P/'chaos180.css';p.write_text(p.read_text()+"\n#hud.chaos-roaming #camera{display:none}\n")
p=P/'tools/qa180.py';s=p.read_text()
s=s.replace("t=p.evaluate('window.__lastCall.getState().story.elapsed')+seconds\n p.wait_for_function('(t)=>window.__lastCall.getState().story.elapsed>=t',arg=t,timeout=90000)", "p.evaluate('(n)=>{const c=window.__lastCall.test.story();for(let i=0;i<Math.ceil(n*60);i++)c.tick(1/60);}',seconds)\n p.wait_for_timeout(120)")
s=s.replace("report={'checks':[]", "report={'timing':'Native browser key events; deterministic 60 Hz controller substeps; actual WebGL-rendered current state. Not a GPU performance benchmark.','checks':[]")
s=s.replace("p.keyboard.press('Numpad'+str(key));advance(p,.40 if key<3 else .43)", "p.keyboard.press('Numpad'+str(key));advance(p,.17 if key==1 else .36 if key==4 else .40)")
before="  for i in range(1,8):actor(p,i,x=3+(i%2),z=4-(i//2)*.8,stun=80,status='wander',attack=0)"
after='  p.evaluate("()=>{for(let i=1;i<8;i++)window.__lastCall.test.story().test.actor(i,{x:3+i%2,z:4-Math.floor(i/2)*.8,stun:80,status:\'wander\',attack:0});}")'
s=s.replace(before,after)
s=s.replace("check('Reclaiming bridge restores original helm',story(p)['mode']=='helm')", "check('Reclaiming bridge restores original helm',story(p)['mode']=='helm' and story(p)['restoredOnboard']>0)")
s=s.replace("if key==4:snap(p,str(OUT/'kick.png'))", "if key==4:\n    snap(p,str(OUT/'kick.png'));limbs=story(p)['hands'];check('Actual kick renders the foot in view',limbs['footVisible'] and abs(limbs['rightFoot'][0])<1 and abs(limbs['rightFoot'][1])<1,limbs)")
p.write_text(s)
compile(s,str(p),'exec')
print('Contact frames, visible limbs, guard sight and crew handoff checked.')
