from pathlib import Path
r=Path(__file__).resolve().parents[1]
p=r/'escape174.js';s=p.read_text()
s=s.replace("timer=0;time=0;aimSet=false;resetObjects()","timer=0;time=0;lastHud=-10;noteUntil=0;aimSet=false;resetObjects()")
s=s.replace("for(;d<range;d+=.2)if(!clearSight(n,{x:n.x+Math.sin(a)*d,z:n.z+Math.cos(a)*d}))break;", "for(;d<range;d+=.2){const x=n.x+Math.sin(a)*d,z=n.z+Math.cos(a)*d,c=cellAt(x,z);if(!c||c.zone==='crawl'||FURNITURE.some(o=>Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2))break;}")
s=s.replace('actor.model.rotation.x=-Math.PI/2','actor.model.rotation.x=Math.PI/2')
s=s.replace("function build(){if(built)return;built=true;", "function build(){if(built)return;built=true;box(0,-.26,38,23,.18,34,mats.dark);")
s=s.replace("box(a.x,.56,a.z,.84,.05,.85,mats.steel)", "box(a.x,.56,a.z,.84,.05,.85,new T.MeshStandardMaterial({color:0x82a7aa,transparent:true,opacity:.18,depthWrite:false}))")
p.write_text(s)
p=r/'chaos174.js';s=p.read_text().replace("s.foot=phase==='escape';setPhase(phase);","s.foot=phase==='escape';if(phase!=='escape')resetInput();setPhase(phase);")
p.write_text(s)
p=r/'tools/qa174.py';s=p.read_text()
s=s.replace("p.on('pageerror',lambda e:errors.append(str(e)))", "p.on('pageerror',lambda e:(errors.append(str(e)),print('BROWSER ERROR',str(e),flush=True)));report['browserErrors']=errors")
s=s.replace("p.locator('#continueStory').click();p.wait_for_function(\"window.__lastCall.getState().chapter.escape.mode==='play'\",timeout=20000)","p.locator('#continueStory').click();p.wait_for_function(\"window.__lastCall.getState().chapter.escape.mode==='play' || document.getElementById('errorText').textContent.length>0\",timeout=20000)\n   p.screenshot(path=str(OUT/'wake-diagnostic.png'));ck('Wake has no runtime exception',not errors,errors)")
p.write_text(s)
