"""Real HTTP/browser regression checks; never count mocked rendering as a pass."""
import json,os,traceback,pathlib,sys
from playwright.sync_api import sync_playwright
OUT=pathlib.Path(os.environ.get('CAPTAIN_QA_OUT','/tmp/captain-qa'));OUT.mkdir(parents=True,exist_ok=True)
BASE=os.environ.get('CAPTAIN_QA_URL','http://127.0.0.1:8765/captain/')
report={'version':'1.3.0','url':BASE,'checks':[],'devices':[]}
def check(name,ok,details=None):
 report['checks'].append({'name':name,'pass':bool(ok),'details':details});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
def state(page):return page.evaluate('window.__lastCall.getState()')
def frames(page,n=4):
 old=state(page)['frames'];page.wait_for_function('(n)=>window.__lastCall.getState().frames>=n',arg=old+n,timeout=30000)
def center(page,selector):
 r=page.locator(selector).bounding_box();assert r,selector
 return r['x']+r['width']/2,r['y']+r['height']/2,r
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
 try:
  ctx=browser.new_context(viewport={'width':430,'height':744},is_mobile=True,has_touch=True,device_scale_factor=1)
  page=ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  page.goto(BASE+'?test=1&v=130',wait_until='domcontentloaded',timeout=60000)
  page.wait_for_function('window.__lastCall?.getState().ready',timeout=90000)
  page.locator('#start').click();frames(page,8)
  check('Frame loop runs after Start',state(page)['playing'] and not errors,errors)
  check('Release marker visible',page.locator('#releaseBadge').inner_text()=='v1.3.0')
  check('Old half-screen panel removed',not page.locator('.controls-bottom').is_visible())
  check('Cabin arrows and actions accessible',page.locator('#helmLeft').is_visible() and page.locator('#helmRight').is_visible() and page.locator('#drink').is_visible())
  check('Arrows follow projected wheel',state(page)['controls']['layout']['projected'])
  cdp=ctx.new_cdp_session(page)
  def touch(kind,pts):cdp.send('Input.dispatchTouchEvent',{'type':kind,'touchPoints':[{'id':i,'x':x,'y':y,'radiusX':3,'radiusY':3,'force':1} for i,x,y in pts]})
  x,y,r=center(page,'#helmLeft');touch('touchStart',[(1,x,y)]);frames(page)
  check('Hold without moving steers left',state(page)['turn']<-.4,state(page)['turn'])
  touch('touchMove',[(1,x-34,y)]);frames(page)
  check('Outward slide increases steering',state(page)['turn']<-.9,state(page)['turn'])
  tx,ty,tr=center(page,'#engineLever');top=tr['y']+2;bottom=tr['y']+tr['height']-2
  touch('touchStart',[(1,x-34,y),(2,tx,top)]);frames(page)
  check('Two fingers independently steer and power',state(page)['turn']<-.9 and state(page)['throttle']>.9)
  touch('touchMove',[(1,x-34,y),(2,tx,ty)]);frames(page)
  check('Lever middle is neutral',state(page)['throttle']==0,state(page)['throttle'])
  touch('touchMove',[(1,x-34,y),(2,tx,bottom)]);frames(page)
  check('Lower half engages reverse',state(page)['throttle']<-.3,state(page)['throttle'])
  touch('touchEnd',[(1,x-34,y)]);frames(page)
  check('Power stays latched after release',state(page)['throttle']<-.3)
  touch('touchEnd',[]);frames(page)
  check('Wheel release clears steering',state(page)['turn']==0 and not state(page)['controls']['steering'])
  page.evaluate('window.__lastCall.test.step(35)');frames(page)
  check('Reverse actually moves ship backward',state(page)['speed']<0,state(page)['speed'])
  page.evaluate('window.__lastCall.test.restart()');frames(page)
  x,y,_=center(page,'#helmRight');touch('touchStart',[(3,x,y)]);frames(page)
  page.locator('#camera').click();frames(page);touch('touchEnd',[])
  check('Camera change clears held input',state(page)['turn']==0 and not state(page)['controls']['steering'])
  check('Deck has compact pad and actions',page.locator('#helmPad').is_visible() and page.locator('#drink').is_visible())
  page.locator('#camera').click();frames(page)
  check('External controls use correct mode',state(page)['controls']['mode']==0 and page.locator('#helmPad').is_visible())
  x,y,r=center(page,'#helmPad');touch('touchStart',[(4,x,y)]);touch('touchMove',[(4,x+35,y)]);frames(page)
  check('External sliding pad steers right',state(page)['turn']>.8)
  touch('touchEnd',[]);frames(page)
  page.locator('#drink').click();frames(page)
  check('Whisky action remains accessible outside',state(page)['intox']>20)
  area=page.evaluate("()=>Array.from(document.querySelectorAll('#helm130 button,#helm130 [role=slider]')).map(e=>e.getBoundingClientRect()).reduce((s,r)=>s+r.width*r.height,0)/(innerWidth*innerHeight)")
  check('Touch controls cover under 15 percent',area<.15,round(area,3))
  check('Text selection disabled',page.evaluate("getComputedStyle(document.querySelector('#helm130')).userSelect==='none'"))
  page.wait_for_function('window.__lastCall.getState().voices.loaded===18',timeout=45000)
  check('All 18 voice files decoded',state(page)['voices']['loaded']==18,state(page)['voices'])
  page.evaluate('window.__lastCall.test.restart()');frames(page)
  obs=page.evaluate('window.__lastCall.test.obstacles().find(o=>o.z>500&&o.radius<100)')
  page.evaluate('(o)=>window.__lastCall.test.setState({x:o.x,z:o.z-o.radius-170,heading:0,speed:12,panic:6,intox:0})',obs);frames(page,12)
  s=state(page)
  check('Danger detected before impact',s['danger'] is not None and s['hull']==100 and s['collisions']==0,{'danger':s['danger'],'hull':s['hull'],'collisions':s['collisions']})
  check('Passenger warning before impact',any(a['id'] in ['ice','rock','brace'] for a in s['dialogue']['history']),s['dialogue'])
  check('Actual voice playback started',s['voices']['played']>0,s['voices'])
  check('Warning belongs to a specific person',any(isinstance(a['person'],int) for a in s['dialogue']['history']))
  page.evaluate('window.__lastCall.test.restart()');frames(page,6)
  page.evaluate("document.getElementById('toast').classList.add('hidden');document.getElementById('radio').style.opacity='0'")
  page.screenshot(path=str(OUT/'bridge-portrait.png'));report['devices'].append({'name':'phone-portrait','viewport':[430,744],'state':state(page)})
  page.evaluate('window.__lastCall.test.camera(0)');frames(page,6);page.screenshot(path=str(OUT/'external-portrait.png'))
  page.evaluate('window.__lastCall.test.camera(2)');frames(page,6);page.evaluate("window.__lastCall.test.say('calm')");frames(page);page.screenshot(path=str(OUT/'deck-dialogue.png'))
  report['bubble_rendering']=page.locator('.person-bubble').evaluate_all('(els)=>els.map(e=>({person:e.dataset.person,anchored:e.dataset.anchored}))')
  page.set_viewport_size({'width':932,'height':430});page.evaluate('window.__lastCall.test.camera(1)');frames(page,6);page.screenshot(path=str(OUT/'bridge-landscape.png'))
  check('Landscape actions and lever visible',page.locator('#drink').is_visible() and page.locator('#engineLever').is_visible())
  report['devices'].append({'name':'phone-landscape','viewport':[932,430],'state':state(page)})
  page.set_viewport_size({'width':375,'height':650});frames(page,4)
  boxes=page.locator('#helm130 button,#helm130 [role=slider]').evaluate_all('(els)=>els.map(e=>{let r=e.getBoundingClientRect();return {id:e.id,x:r.x,y:r.y,w:r.width,h:r.height}}).filter(r=>r.w&&r.h)')
  check('Small-phone controls stay in viewport',all(r['x']>=-1 and r['y']>=-1 and r['x']+r['w']<=376 and r['y']+r['h']<=651 for r in boxes),boxes)
  page.screenshot(path=str(OUT/'bridge-small-phone.png'))
  page.locator('#pause').click();check('Pause clears gesture state',state(page)['paused'] and not state(page)['controls']['steering'])
  page.locator('#resume').click();frames(page,5);check('Resume restores frame loop',state(page)['playing'] and not state(page)['paused'])
  check('No uncaught phone browser errors',not errors,errors);report['errors']=errors;ctx.close()
  ctx=browser.new_context(viewport={'width':1280,'height':800},device_scale_factor=1);page=ctx.new_page();desktop_errors=[];page.on('pageerror',lambda e:desktop_errors.append(str(e)))
  page.goto(BASE+'?test=1&v=130',wait_until='domcontentloaded');page.wait_for_function('window.__lastCall?.getState().ready',timeout=90000);page.locator('#start').click();frames(page,4)
  page.keyboard.down('a');frames(page,4);check('Desktop A steers left',state(page)['turn']==-1);page.keyboard.up('a')
  page.keyboard.press('Space');frames(page);check('Desktop Space selects neutral',state(page)['throttle']==0)
  page.keyboard.press('c');frames(page);check('Desktop camera switch works',state(page)['controls']['mode']==2)
  page.screenshot(path=str(OUT/'desktop.png'));check('No uncaught desktop errors',not desktop_errors,desktop_errors)
  report['devices'].append({'name':'desktop','viewport':[1280,800],'state':state(page)});ctx.close()
 except Exception as exc:
  report['exception']=traceback.format_exc();check('Browser execution completed',False,str(exc))
  try:page.screenshot(path=str(OUT/'failure.png'))
  except Exception:pass
 finally:
  browser.close();report['passed']=all(c['pass'] for c in report['checks']);(OUT/'results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps({'passed':report['passed'],'checks':len(report['checks'])}))
sys.exit(0 if report['passed'] else 1)
