import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseHTML} from 'linkedom';
import {createCanvas} from '@napi-rs/canvas';
const root=fileURLToPath(new URL('../',import.meta.url));
const qaDirectory=await fs.mkdtemp(path.join(os.tmpdir(),'feouda-guidance-qa-'));
const mobile=process.argv.includes('mobile'),width=mobile?390:1440;
const errors=[],passes=[],defects=[],calls=[],worldCalls=[],downloads=[],timers=[];
process.on('unhandledRejection',e=>errors.push('Unhandled rejection: '+e.stack));
const html=await fs.readFile(root+'index.html','utf8');
const {window,document}=parseHTML(html);
let activeElement=document.body;
Object.defineProperty(document,'activeElement',{get:()=>activeElement,configurable:true});
Object.defineProperty(document,'hidden',{value:false,writable:true,configurable:true});
window.HTMLElement.prototype.focus=function(){activeElement=this;};
Object.defineProperty(window.HTMLElement.prototype,'inert',{get(){return this.hasAttribute('inert')},set(v){this.toggleAttribute('inert',!!v)},configurable:true});
window.HTMLElement.prototype.getBoundingClientRect=function(){return {x:0,y:0,left:0,top:0,right:this.id==='minimap'?240:width,bottom:this.id==='minimap'?164:900,width:this.id==='minimap'?240:width,height:this.id==='minimap'?164:900};};
const surfaces=new WeakMap();
window.HTMLCanvasElement.prototype.getContext=function(type){if(type!=='2d')throw Error('Unexpected real renderer request');if(!surfaces.has(this))surfaces.set(this,createCanvas(Number(this.width)||240,Number(this.height)||164));return surfaces.get(this).getContext('2d');};
const stored=new Map(),storage={getItem:k=>stored.get(k)??null,setItem:(k,v)=>stored.set(k,String(v)),removeItem:k=>stored.delete(k)};
for(const [k,v] of Object.entries({window,document,localStorage:storage,innerWidth:width,innerHeight:900,navigator:{},requestAnimationFrame:()=>0,cancelAnimationFrame:()=>{},setTimeout:(fn,delay)=>{timers.push({fn,delay});return timers.length},clearTimeout:()=>{},setInterval:()=>1,clearInterval:()=>{}}))Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});
window.innerWidth=width;window.innerHeight=900;window.devicePixelRatio=1;
const urls=new Map();URL.createObjectURL=blob=>{const id='blob:qa-'+urls.size;urls.set(id,blob);return id};URL.revokeObjectURL=()=>{};
const nativeClick=window.HTMLElement.prototype.click;
window.HTMLElement.prototype.click=function(){if(this.tagName==='A'){downloads.push({name:this.download,blob:urls.get(this.href)});return;}if(this.id==='import-file'){worldCalls.push(['filePicker']);return;}nativeClick.call(this);};
let callbacks;
globalThis.__rendererFactory=(canvas,cb)=>{callbacks=cb;queueMicrotask(()=>cb.onReady());return Object.fromEntries(['setState','setSelection','setQuality','setInsets','setInputEnabled','setMapMode','focus','zoom','home','setPlacement','clearPlacement'].map(name=>[name,(...args)=>worldCalls.push([name,...(name==='setState'?[]:args)])]).concat([['getDebugState',()=>({mocked:true})]]));};
let source=await fs.readFile(root+'app.js','utf8');
source=source.replace(/import \{createBattlefield\} from '[^']+';/,"const createBattlefield=globalThis.__rendererFactory;");
source=source.replace(/from '\.\/([^']+)'/g,(_,p)=>`from 'file://${root}${p}'`);
source+='\nglobalThis.__qa={game,view,render,setSelection};\n';
const copy=path.join(qaDirectory,`${mobile?'mobile':'desktop'}.mjs`);
await fs.writeFile(copy,source);
try{await import('file://'+copy+'?run='+Date.now());await Promise.resolve();await Promise.resolve();}catch(e){errors.push('BOOT: '+e.stack);}
const assert=(condition,message,detail='')=>{if(!condition)throw new Error(message+(detail?' :: '+detail:''));};
const check=async(name,fn)=>{try{await fn();passes.push(name)}catch(e){errors.push(name+': '+e.message)}};
const click=async(selector,props={})=>{const el=typeof selector==='string'?document.querySelector(selector):selector;assert(el,'Missing action '+selector);const event=new window.Event('click',{bubbles:true,cancelable:true});Object.assign(event,props);el.dispatchEvent(event);await Promise.resolve();return el;};
const action=(a,v)=>`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`;
const key=async(el,k,props={})=>{const e=new window.Event('keydown',{bubbles:true,cancelable:true});Object.assign(e,{key:k,code:k===' '?'Space':k,...props});el.dispatchEvent(e);await Promise.resolve();return e;};
const bank=()=>({...__qa.game.state.resources});
const expectSpend=(before,cost)=>Object.entries(before).forEach(([k,v])=>assert(Math.abs(__qa.game.state.resources[k]-(v-(cost[k]||0)))<1e-7,`${k} delta differs from displayed quote`));
const panel=async(p)=>{const v=__qa.view;if(v.panel!==p||!v.panelOpen)await click(`#left-rail ${action('panel',p)}`);};
if(globalThis.__qa){
 const {game,view,render}=__qa;
 const rawCommand=game.command;game.command=(a,p)=>{const r=rawCommand(a,p);calls.push({action:a,payload:structuredClone(p),result:r});return r};
 await check('Startup and welcome guard',async()=>{assert(view.ready,'onReady not reached');assert(!document.getElementById('welcome').hidden,'welcome not visible');assert(document.getElementById('loading-screen').hidden,'loading overlay remains');assert(game.state.paused,'pre-game simulation running');assert(view.panelOpen===!mobile,'wrong initial panel mode');assert(worldCalls.filter(c=>c[0]==='setInputEnabled').at(-1)?.[1]===false,'world accepts input during welcome');});
 await check('Required HTML ids and no duplicate SVG ids',async()=>{const required=[...source.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);assert(required.every(id=>document.getElementById(id)),'referenced static id missing');const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);assert(ids.length===new Set(ids).size,'duplicate SVG ids');});
 await check('Begin starts real campaign',async()=>{await click(action('begin'));assert(view.started&&!game.state.paused,'begin failed');assert(document.getElementById('welcome').hidden,'welcome stays');assert(stored.get('feouda-welcomed-v1')==='1','welcome flag absent');assert(worldCalls.filter(c=>c[0]==='setInputEnabled').at(-1)?.[1]===true,'world remains disabled');});
 await check('All seven panels open and close',async()=>{for(const p of ['realm','build','economy','army','research','chronicle','diplomacy']){await panel(p);assert(document.getElementById('panel-body').textContent.trim().length>30,p+' panel empty');await click(action('close-panel'));assert(!view.panelOpen&&document.getElementById('side-panel').inert,p+' close failed');}});
 await check('Worker plus/minus updates actual allocation',async()=>{await panel('economy');const n=game.state.nodes.find(n=>n.id==='oak-west'),before=n.workers,available=game.state.availableWorkers,b=bank();await click(`#panel-body ${action('worker',n.id)}[data-delta="1"]`);assert(n.workers===before+1&&game.state.availableWorkers===available-1,'worker plus does not allocate');expectSpend(b,{});await click(`#panel-body ${action('worker',n.id)}[data-delta="-1"]`);assert(n.workers===before&&game.state.availableWorkers===available,'worker minus does not release');});
 await check('Renderer selections open region and resource panels',async()=>{callbacks.onSelect({kind:'region',id:'home'},{});assert(view.panel==='realm'&&view.panelOpen,'region selection did not open council');callbacks.onSelect({kind:'node',id:'home-iron'},{});assert(view.panel==='economy'&&view.selection.id==='home-iron','resource selection did not open economy');assert(document.querySelector('#selection-deck').textContent.includes('Σίδηρος'),'resource selection deck mismatch');callbacks.onSelect({kind:'region',id:'home'},{});});
 await check('Placement preview, invalid ground, rotate and cancel never spend',async()=>{
  await panel('build');const quote=game.canCommand('build',{type:'farm',regionId:'home'}),b=bank(),jobs=game.state.jobs.length;assert(quote.ok&&quote.requiresPlacement,'fixture farm needs explicit placement');
  await click(action('build','farm'));assert(view.placement?.type==='farm'&&!view.panelOpen,'build did not enter map placement');expectSpend(b,{});assert(game.state.jobs.length===jobs,'preview queued work');
  callbacks.onPlacementHover({x:-158,z:0});assert(!view.placement.quote.ok,'castle interior plot accepted');assert(document.querySelector(action('placement-confirm')).disabled,'invalid plot confirm enabled');expectSpend(b,{});
  const orders=JSON.stringify(game.state.squads.map(u=>u.order));await key(document.body,'r');assert(view.placement.rotation===Math.PI/2,'R did not rotate ghost');assert(JSON.stringify(game.state.squads.map(u=>u.order))===orders,'R issued a military retreat during placement');
  await key(document.body,'Escape');assert(!view.placement,'Escape did not cancel ghost');expectSpend(b,{});assert(game.state.jobs.length===jobs,'cancel changed queue');assert(worldCalls.some(c=>c[0]==='clearPlacement'),'renderer ghost not cleared');
 });
 await check('Build anchors a legal point, charges once and persists exact site',async()=>{
  await panel('build');const quote=game.canCommand('build',{type:'farm',regionId:'home'}),b=bank(),workers=game.state.busyWorkers;
  const card=document.querySelector(action('build','farm')).closest('article');for(const v of Object.values(quote.cost))assert(card.querySelector('.cost').textContent.includes(String(v)),`missing displayed cost ${v}`);
  await click(action('build','farm'));const point={x:view.placement.x,z:view.placement.z};assert(view.placement.quote.ok,'initial legal preview point invalid');assert(document.querySelector(action('placement-confirm')).disabled,'unanchored preview can charge');
  callbacks.onPlacementPick(point);assert(view.placement.anchored,'map click did not anchor');assert(!document.querySelector(action('placement-confirm')).disabled,'valid anchored plot cannot confirm');
  callbacks.onPlacementHover({x:point.x+20,z:point.z});assert(view.placement.x===point.x,'anchored preview moved when cursor left for confirm button');
  await click(action('placement-confirm'));expectSpend(b,quote.cost);assert(!view.placement,'confirmed ghost remains');
  const job=game.state.jobs.find(j=>j.kind==='build'&&j.type==='farm');assert(job?.duration===quote.duration,'farm queue missing');const site=game.state.structures.find(st=>st.id===job.structureId);assert(site&&site.x===point.x&&site.z===point.z&&site.status==='building','exact chosen site not stored');assert(game.state.busyWorkers===workers+4,'build did not reserve 4 workers');assert(view.selection.kind==='structure'&&view.selection.id===site.id,'new worksite not selected');
  const callsBefore=calls.length;await key(document.body,'Enter');assert(calls.length===callsBefore,'Enter after confirm charged twice');
 });
 await check('Finished building selection exposes on-site upgrade with exact quote',async()=>{
  const st=game.state.structures.find(a=>a.regionId==='home'&&a.type==='houses'&&a.status==='ready');assert(st,'initial house missing');callbacks.onSelect({kind:'structure',id:st.id},{});assert(view.regionId==='home'&&view.panel==='build','building selection has wrong region/panel');
  const q=game.canCommand('build',{type:st.type,regionId:st.regionId,structureId:st.id});const button=document.querySelector(action('upgrade-structure',st.id));assert(button&&button.disabled===!q.ok,'upgrade action missing or wrong gate');assert(document.querySelector('#selection-deck').textContent.includes('Βαθμίδα'),'structure detail missing');
 });
 await check('Train gates and all six unit card quotes',async()=>{await panel('army');await click(action('army-tab','train'));for(const type of ['spear','sword','archer','cavalry','ram','trebuchet']){const pr=game.canCommand('train',{type,regionId:'home'}),button=document.querySelector(action('train',type));assert(button,'missing '+type+' card');assert(button.disabled===!pr.ok,'wrong enabled gate '+type);const card=button.closest('article');for(const v of Object.values(pr.cost))assert(card.querySelector('.cost').textContent.includes(String(v)),'price absent '+type);if(!pr.ok)assert(card.querySelector('.reason')?.textContent===pr.message,'disabled reason absent '+type);}assert(document.querySelector(action('train','trebuchet')).disabled,'trebuchet unlocked before engineering');});
 await check('Train spends exact resources and adds actual queue',async()=>{const quote=game.canCommand('train',{type:'spear',regionId:'home'}),b=bank();await click(action('train','spear'));expectSpend(b,quote.cost);assert(game.state.jobs.some(j=>j.kind==='train'&&j.type==='spear'&&j.duration===quote.duration),'training job absent');});
 await check('Research price, worker use and pending gate',async()=>{await panel('research');const quote=game.canCommand('research',{type:'agriculture'}),b=bank(),workers=game.state.busyWorkers;assert(quote.ok,'fixture research unavailable');await click(action('research','agriculture'));expectSpend(b,quote.cost);assert(game.state.jobs.some(j=>j.kind==='research'&&j.type==='agriculture'),'research queue absent');assert(game.state.busyWorkers===workers+2,'research workers wrong');const next=document.querySelector(action('research','steel'));assert(next.disabled,'second research allowed');assert(next.closest('article').querySelector('.reason')?.textContent.includes('ήδη μία έρευνα'),'pending reason missing');});
 await check('Unaffordable training has visible reason and cannot charge',async()=>{const saved=bank();game.state.resources.money=0;await panel('army');await click(action('army-tab','train'));const button=document.querySelector(action('train','sword'));assert(button.disabled,'unaffordable sword training enabled');assert(button.closest('article').querySelector('.reason')?.textContent.includes('CY£'),'missing money reason');const count=calls.length;await click(button);assert(calls.length===count,'disabled button dispatched command');Object.assign(game.state.resources,saved);render(true);});
 await check('Army select, shift-add and group formation',async()=>{await panel('army');await click(action('army-tab','troops'));const own=game.state.squads.filter(u=>u.owner==='player');await click(action('select-squad',own[0].id));assert(view.armyIds.length===1&&view.armyIds[0]===own[0].id,'single selection failed');await click(action('select-squad',own[1].id),{shiftKey:true});assert(view.armyIds.length===2,'shift selection failed');await click(action('select-army','all'));assert(view.armyIds.length===own.length,'select all missed units');await click(action('formation','wedge'));assert(own.every(u=>u.formation==='wedge'),'formation not applied');await click(action('army-command','hold'));assert(own.every(u=>u.order?.type==='hold'),'hold not applied');});
 await check('Move, contextual attack and explicit fortress attack dispatch',async()=>{await click(action('army-command','move'));assert(view.command==='move'&&!view.panelOpen,'move targeting did not open map');callbacks.onGround({x:-210,z:68});let c=calls.at(-1);assert(c.action==='order'&&c.payload.type==='move'&&c.payload.x===-210&&c.result.ok,'ground order failed',JSON.stringify(c));assert(view.command===null,'move targeting remains');const enemy=game.state.squads.find(u=>u.owner==='red');callbacks.onContext({x:enemy.x,z:enemy.z},{kind:'squad',id:enemy.id});c=calls.at(-1);assert(c.payload.type==='attack'&&c.payload.targetId===enemy.id&&c.result.ok,'context attack failed',JSON.stringify(c));await click(action('army-command','attack'));callbacks.onSelect({kind:'region',id:'firwood'},{});c=calls.at(-1);assert(c.payload.type==='attack'&&c.payload.regionId==='firwood'&&c.result.ok,'explicit fortress attack order failed',JSON.stringify(c));});
 await check('Default besiege with infantry dispatches capture',async()=>{await panel('army');await click(action('army-tab','troops'));await click(action('select-army','all'));assert(view.command===null,'previous tactical command leaked');callbacks.onSelect({kind:'region',id:'firwood'},{});await click(action('besiege','firwood'));const c=calls.at(-1);assert(c.action==='order'&&c.payload.type==='capture'&&c.payload.regionId==='firwood'&&c.result.ok,'default mixed besiege did not capture',JSON.stringify(c));});
 await check('Siege-only contextual and button orders attack fortress without requiring infantry',async()=>{await panel('army');await click(action('army-tab','troops'));await click(action('select-army','siege'));const selected=game.state.squads.filter(s=>view.armyIds.includes(s.id));assert(selected.length===1&&selected[0].type==='ram','siege fixture selected wrong units');callbacks.onContext({x:-167,z:-119},{kind:'region',id:'firwood'});let c=calls.at(-1);assert(c.action==='order'&&c.payload.type==='attack'&&c.payload.regionId==='firwood'&&c.result.ok,'siege-only context did not attack',JSON.stringify(c));callbacks.onSelect({kind:'region',id:'firwood'},{});await click(action('besiege','firwood'));c=calls.at(-1);assert(c.payload.type==='attack'&&c.payload.regionId==='firwood'&&c.result.ok,'siege-only besiege button did not attack',JSON.stringify(c));});
 await check('Pause and nested modal restoration',async()=>{game.setPaused(false);render(true);await click(action('help'));assert(game.state.paused&&view.modal==='help','help did not pause');assert(document.getElementById('battlefield').inert,'modal does not make world inert');await click(action('close-modal'));assert(!game.state.paused&&!view.modal,'running pause state not restored');await click(action('pause'));assert(game.state.paused,'manual pause failed');await click(action('settings'));await click('#modal-root '+action('help'));await click(action('close-modal'));assert(game.state.paused,'nested modal incorrectly resumed manual pause');game.setPaused(false);render(true);});
 await check('Settings quality, sound, save and export controls',async()=>{await click(action('settings'));const select=document.getElementById('quality-select');Object.defineProperty(select,'value',{value:'low',configurable:true});select.dispatchEvent(new window.Event('change',{bubbles:true}));assert(view.quality==='low'&&stored.get('feouda-quality')==='low','quality not stored');assert(worldCalls.some(c=>c[0]==='setQuality'&&c[1]==='low'),'quality not sent to world');const priorSound=view.sound;await click('#modal-root '+action('sound'));assert(view.sound!==priorSound&&stored.has('feouda-sound'),'sound failed');await click('#modal-root '+action('save'));assert(stored.has('feouda-1280-v1'),'manual save missing');await click('#modal-root '+action('export'));assert(downloads.length===1&&downloads[0].blob,'export anchor missing');const exported=JSON.parse(await downloads[0].blob.text());assert(exported.schema===1||exported.state?.schema===1,'invalid export format');await click('#modal-root '+action('import'));assert(worldCalls.some(c=>c[0]==='filePicker'),'import picker not dispatched');});
 await check('Settings focused select keyboard escape',async()=>{const select=document.getElementById('quality-select');select.focus();const event=await key(select,'Escape');assert(!view.modal,'Escape on focused quality selector did not close settings');assert(event.defaultPrevented,'Escape was not handled');assert(worldCalls.filter(c=>c[0]==='setInputEnabled').at(-1)?.[1]===true,'world remains disabled after select Escape');});
 await check('Atlas Enter, Space and mouse activation',async()=>{for(const [method,id] of [['Enter','sunkeep'],[' ','ironhold'],['click','quarry']]){await click(action('overview'));const target=document.querySelector(`[data-action="atlas-region"][data-value="${id}"]`);target.focus();if(method==='click')await click(target);else{const e=await key(target,method);assert(e.defaultPrevented,'atlas keyboard activation not handled');}assert(view.selection.kind==='region'&&view.selection.id===id&&!view.modal,`atlas ${method} did not focus selected region`);assert(worldCalls.some(c=>c[0]==='focus'&&c[1]===id),'atlas focus not dispatched');}});
 await check('Existing save import path retains campaign and resets modal input',async()=>{await click(action('settings'));const input=document.getElementById('import-file'),text=await downloads[0].blob.text();Object.defineProperty(input,'files',{value:[{size:text.length,text:async()=>text}],configurable:true});input.dispatchEvent(new window.Event('change',{bubbles:true}));await Promise.resolve();await Promise.resolve();assert(view.modal==='import','file change did not show import confirmation');await click(action('import-confirm'));assert(!view.modal&&view.started&&!game.state.paused,'valid import failed to restore play');assert(game.state.jobs.length>=3,'import lost in-flight jobs');assert(worldCalls.filter(c=>c[0]==='setInputEnabled').at(-1)?.[1]===true,'input disabled after import');});
 await check('Building explanations open explicitly without hover or focus scroll jumps',async()=>{
  await panel('build');await click(action('build-tab','civil'));await click(action('build-inspect','houses'));
  const before=view.buildType;let revealed=0;document.querySelector('.build-inspector').scrollIntoView=options=>{if(options?.behavior!=='smooth')revealed++};
  const mine=document.querySelector(action('build','mine'));for(const type of ['pointerover','focusin']){const e=new window.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerType:'mouse',relatedTarget:document.body});mine.dispatchEvent(e);}
  assert(view.buildType===before&&revealed===0,'hover or focus changed the explanation or scrolled the list');
  await click(action('build-inspect','houses'));assert(revealed===1,'explicit repeated detail click did not reveal explanation');
 });
 await check('Construction grid has fourteen distinct building pictures and inspectable locked costs',async()=>{
  callbacks.onSelect({kind:'region',id:'home'},{});await panel('build');const art=new Set();
  for(const tab of ['civil','military']){await click(action('build-tab',tab));const cells=[...document.querySelectorAll('.build-command-grid .build-cell')];assert(cells.length===(tab==='civil'?9:5),'incorrect build grid size');for(const cell of cells){const button=cell.querySelector('[data-action="build"]'),svg=cell.querySelector('.feouda-building-portrait');assert(button&&svg,'tile lacks direct construction/picture');assert(cell.querySelector('.cost').textContent.trim(),'tile has no visible costs');art.add(svg.getAttribute('data-art'));}}
  assert(art.size===14,'building pictures reuse the same type');const moneyBefore=game.state.resources.money;game.state.resources.money=0;await click(action('build-tab','civil'));render(true);const tile=document.querySelector(action('build','mine'));assert(tile.disabled,'locked tile enabled');await click(action('build-inspect','mine'));assert(view.buildType==='mine','disabled tile details inaccessible');assert(document.querySelector('.build-inspector .unavailable-reason')?.textContent.includes('CY£'),'locked reason lacks actual shortfall');game.state.resources.money=moneyBefore;render(true);
 });
 await check('Simulation repaint preserves navigation, price, build and focused control identities',async()=>{
  await panel('build');await click(action('build-tab','civil'));const nav=document.querySelector('#left-rail '+action('panel','build')),resource=document.querySelector(action('resource','wood')),button=document.querySelector(action('build','houses')),svg=button.querySelector('svg');button.focus();const before=game.state.resources.wood;
  for(let i=0;i<12;i++){game.state.resources.wood+=.25;render(true);assert(document.querySelector('#left-rail '+action('panel','build'))===nav,'navigation detached');assert(document.querySelector(action('resource','wood'))===resource,'resource button detached');assert(document.querySelector(action('build','houses'))===button,'build button detached');assert(button.querySelector('svg')===svg,'unchanged artwork detached');assert(document.activeElement===button,'focus lost during tick');}
  game.state.resources.wood=before;const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);assert(ids.length===new Set(ids).size,'retained artwork duplicates gradient ids');render(true);
 });
 await check('Map box selection merges with Shift; Shift click toggles membership',async()=>{
  const own=game.state.squads.filter(u=>u.owner==='player'&&u.hp>0);callbacks.onBoxSelect([own[0].id],{});callbacks.onBoxSelect([own[1].id],{shiftKey:true,additive:true});assert(view.armyIds.length===2,'Shift box lost previous member');callbacks.onSelect({kind:'squad',id:own[0].id},{shiftKey:true});assert(view.armyIds.length===1&&view.armyIds[0]===own[1].id,'Shift click did not remove member');callbacks.onBoxSelect([own[0].id,own[1].id],{doubleClick:true});assert(view.armyIds.length===2,'same-type box callback rejected');callbacks.onBoxSelect([],{});assert(view.armyIds.length===0&&!view.command,'empty box did not deselect');
 });
 await check('Control groups assign, append, recall, Shift merge and double recall focuses the real centroid',async()=>{
  const own=game.state.squads.filter(u=>u.owner==='player'&&u.hp>0);callbacks.onBoxSelect([own[0].id,own[1].id],{});await key(document.body,'1',{ctrlKey:true});assert(view.controlGroups['1'].length===2,'Ctrl assign lost member');callbacks.onBoxSelect([own[2].id],{});await key(document.body,'1',{ctrlKey:true,shiftKey:true});assert(view.controlGroups['1'].length===3,'Ctrl Shift append failed');await key(document.body,'2',{ctrlKey:true});callbacks.onBoxSelect([own[3].id],{});await key(document.body,'1',{shiftKey:true});assert(view.armyIds.length===4,'Shift recall did not merge');await key(document.body,'1');assert(view.armyIds.length===3,'plain recall did not replace selection');await key(document.body,'1');const focused=worldCalls.filter(c=>c[0]==='focus').at(-1)?.[1];const expected={x:(own[0].x+own[1].x+own[2].x)/3,z:(own[0].z+own[1].z+own[2].z)/3};assert(Math.abs(focused.x-expected.x)<1e-7&&Math.abs(focused.z-expected.z)<1e-7,'double recall centers wrong point');assert(JSON.parse(stored.get('feouda-control-groups-v1'))['1'].length===3,'groups not saved');
  const hp=own[1].hp;own[1].hp=0;await key(document.body,'1');assert(!view.armyIds.includes(own[1].id),'dead unit recalled');own[1].hp=hp;
 });
 await check('Touch multiple selection and on-screen group assignment work without a keyboard',async()=>{
  await panel('army');await click(action('army-tab','troops'));if(view.armyMulti)await click(action('multi-select'));await click(action('clear-selection'));await click(action('multi-select'));const own=game.state.squads.filter(u=>u.owner==='player'&&u.hp>0);await click('#panel-body '+action('select-squad',own[0].id));await click('#panel-body '+action('select-squad',own[1].id));assert(view.armyIds.length===2,'touch multiple selection failed');await click('#panel-body '+action('select-squad',own[0].id));assert(view.armyIds.length===1,'touch toggle did not remove');await click(action('group-assign'));await click(action('control-group','4'));assert(view.controlGroups['4'].length===1&&view.controlGroups['4'][0]===own[1].id&&!view.groupAssign,'screen group assignment failed');await click(action('multi-select'));
 });
 await check('Selected production buildings expose only their actual unit types and block unfinished sites',async()=>{
  const expected={barracks:['spear','sword'],archery:['archer'],stable:['cavalry'],siege:['ram','trebuchet']};
  for(const [type,types] of Object.entries(expected)){const st=game.state.structures.find(a=>a.regionId==='home'&&a.type===type);assert(st,'missing source building '+type);callbacks.onSelect({kind:'structure',id:st.id},{});const commands=[...document.querySelectorAll('#selection-deck .context-training [data-action="train"]')];assert(JSON.stringify(commands.map(b=>b.dataset.value))===JSON.stringify(types),'wrong context roster '+type);assert(commands.every(b=>b.dataset.structure===st.id&&b.dataset.region==='home'),'context action not tied to selected site');const status=st.status;st.status='building';render(true);assert([...document.querySelectorAll('#selection-deck .context-training [data-action="train"]')].every(b=>b.disabled),'unfinished building can train');st.status=status;render(true);}
 });
 await check('Attack on ground dispatches a real attackMove order and then clears targeting',async()=>{
  await click(action('select-army','all'));await click(action('army-command','attack'));callbacks.onGround({x:-210,z:68});const c=calls.at(-1);assert(c.action==='order'&&c.payload.type==='attackMove'&&c.result.ok,'A ground still becomes ordinary move',JSON.stringify(c));assert(view.command===null,'attack targeting remains');assert(game.state.squads.some(s=>view.armyIds.includes(s.id)&&s.order?.type==='attackMove'),'engine did not retain attackMove');
 });
 await check('Guide buttons lead to actions, and completion requires actual successful play',async()=>{
  view.guideDone={};view.guideStep=null;view.guideOpen=true;render(true);const beforeWorkers=game.state.assignedWorkers;await click(action('guide-action','workers'));assert(!view.guideDone.workers,'opening worker guide fakes completion');assert(view.panel==='economy'&&view.panelOpen,'guide did not open worker task');if(mobile)assert(!view.guideOpen,'mobile guide obscures task after opening');const plus=document.querySelector('#panel-body [data-action="worker"][data-delta="1"]:not(:disabled)');assert(plus,'no free worker fixture');await click(plus);assert(view.guideDone.workers&&game.state.assignedWorkers===beforeWorkers+1,'real assignment did not complete step');
  view.guideOpen=true;view.guideStep='build';render(true);await click(action('guide-action','build'));assert(!view.guideDone.build,'opening build grid fakes completion');const b=bank();await click(action('build','houses'));expectSpend(b,{});assert(!view.guideDone.build,'preview fakes construction completion');callbacks.onPlacementPick({x:view.placement.x,z:view.placement.z});await click(action('placement-confirm'));assert(view.guideDone.build&&game.state.jobs.some(j=>j.type==='houses'&&j.kind==='build'),'actual site did not complete guide');
  view.guideOpen=true;view.guideStep='select';render(true);await click(action('guide-action','select'));assert(view.guideDone.select&&view.armyIds.length>0,'guide select has no real selection');view.guideOpen=true;view.guideStep='move';render(true);await click(action('guide-action','move'));assert(!view.guideDone.move,'targeting mode fakes move completion');callbacks.onGround({x:-210,z:68});assert(view.guideDone.move&&calls.at(-1).result.ok,'guide move not tied to real order');view.guideOpen=true;view.guideStep='train';render(true);await click(action('guide-action','train'));assert(!view.guideDone.train,'opening recruitment fakes training');await click('#panel-body '+action('train','spear'));assert(view.guideDone.train&&calls.at(-1).action==='train'&&calls.at(-1).result.ok,'actual recruitment not recorded');assert(Object.values(JSON.parse(stored.get('feouda-guide-v24-progress'))).filter(Boolean).length===5,'guide completion not persisted');view.guideOpen=true;render(true);assert(document.querySelector('#guide-body .advice-card [data-action="advice"]'),'completed guide has no actionable next step');
 });


 await check('Local model thumbnails load without replacing fallback or focus nodes',async()=>{
  callbacks.onSelect({kind:'region',id:'home'},{});await panel('build');await click(action('build-tab','civil'));const image=document.querySelector('[data-building-thumbnail="houses"]'),frame=image.parentElement;assert(image.getAttribute('loading')==='lazy'&&image.getAttribute('alt')==='','thumbnail should be decorative and deferred');const file=root+image.getAttribute('src').replace('./','');assert((await fs.stat(file)).size>0,'model thumbnail absent');image.dispatchEvent(new window.Event('load',{bubbles:true}));assert(frame.classList.contains('image-ready'),'loaded photograph never replaces placeholder');render(true);assert(document.querySelector('[data-building-thumbnail="houses"]')===image&&frame.classList.contains('image-ready'),'tick lost thumbnail loading state');const failed=document.querySelector('[data-building-thumbnail="mine"]');failed.dispatchEvent(new window.Event('error',{bubbles:true}));assert(failed.parentElement.classList.contains('image-failed')&&failed.parentElement.querySelector('svg'),'failed image has no illustration fallback');render(true);assert(document.querySelector('[data-building-thumbnail="mine"]')===failed&&failed.parentElement.classList.contains('image-failed'),'failed fallback state not retained');
 });

 const fresh=()=>{if(view.modal)document.querySelector('[data-action="close-modal"]')?.click();game.reset();game.setPaused(true);Object.assign(view,{started:true,panel:'realm',panelOpen:true,selection:{kind:'region',id:'home'},regionId:'home',armyIds:[],command:null,armyTab:'troops',buildTab:'civil',buildType:'houses',resourceFilter:'all',guideOpen:false,guideStep:null,guideDone:{},requirementsOpen:{},helpTopic:'menus',modal:null});render(true);};
 const adviceIn=(parent,kind)=>[...parent.querySelectorAll('[data-action="advice"]')].find(el=>JSON.parse(el.dataset.value).kind===kind);
 const setRegion=async(id,kind='training')=>{const select=document.getElementById(kind+'-region-select');assert(select,'region selector missing');for(const option of select.options)option.toggleAttribute('selected',option.value===id);select.dispatchEvent(new window.Event('change',{bubbles:true}));await Promise.resolve();};
 await check('Worker cards show the exact engine output and explicit allocation labels',async()=>{
  fresh();await panel('economy');const node=game.state.nodes.find(n=>n.id==='oak-west'),card=document.querySelector('[data-node="oak-west"]');
  const {getNodeProduction}=await import('file://'+root+'feouda-engine.js');const rate=getNodeProduction(game.state,node).totalPerMinute.toLocaleString('el-CY',{maximumFractionDigits:1,minimumFractionDigits:1});
  assert(card.querySelector('.worker-yield strong').textContent==='+'+rate,'displayed rate differs from simulation');assert(card.textContent.includes('+1 εργάτη')&&card.textContent.includes('−1 εργάτη'),'worker actions ambiguous');
  const before=card.querySelector('.worker-yield strong').textContent;await click(card.querySelector('[data-delta="1"]'));assert(card.querySelector('.worker-yield strong').textContent!==before,'assignment did not refresh output');
 });
 await check('Unavailable worker assignment explains the actual engine rejection',async()=>{
  fresh();const node=game.state.nodes.find(n=>n.id==='oak-west');node.workers=12;game.canCommand('assignWorkers',{nodeId:node.id,delta:1});await panel('economy');const card=document.querySelector('[data-node="oak-west"]');assert(card.querySelector('[data-delta="1"]').disabled,'full node can add workers');assert(card.querySelector('.worker-feedback').textContent.includes('12'),'full-node reason missing');
  node.amount=0;node.workers=0;render(true);assert(card.querySelector('.worker-feedback').textContent.includes('εξαντληθεί'),'depletion reason missing');
 });
 await check('Training region selector changes the actual training destination',async()=>{
  fresh();await panel('army');await click(action('army-tab','train'));await setRegion('farmland');assert(view.regionId==='farmland','region selector does not change context');assert(document.querySelector('[data-action="train"][data-value="spear"]').disabled,'missing local barracks did not gate training');
  await setRegion('home');const button=document.querySelector('#panel-body '+action('train','spear'));assert(!button.disabled&&button.dataset.region==='home','training did not return home');await click(button);assert(calls.at(-1).payload.regionId==='home'&&calls.at(-1).result.ok,'training command ignored selected region');
 });
 await check('Missing training facility navigates to construction without charging or placing',async()=>{
  fresh();for(const r of Object.values(game.state.regions))r.buildings.stable=0;game.state.structures=game.state.structures.filter(st=>st.type!=='stable');await panel('army');await click(action('army-tab','train'));const cavalry=document.querySelector('.recruit-cell[data-ui-key="train:cavalry"]');const link=adviceIn(cavalry,'build');assert(link,'locked cavalry lacks construction route');const before=bank(),orders=JSON.stringify(game.state.squads.map(s=>s.order)),jobs=game.state.jobs.length;
  await click(link);assert(view.panel==='build'&&view.buildType==='stable'&&view.regionId==='home','wrong prerequisite destination');assert(!view.placement,'prerequisite click starts construction preview automatically');expectSpend(before,{});assert(jobs===game.state.jobs.length&&orders===JSON.stringify(game.state.squads.map(s=>s.order)),'navigation changed gameplay');
 });
 await check('Research prerequisite opens and reveals the specific technology',async()=>{
  fresh();await panel('army');await click(action('army-tab','train'));const trebuchet=document.querySelector('.recruit-cell[data-ui-key="train:trebuchet"]');const link=adviceIn(trebuchet,'research');assert(link,'trebuchet lacks technology route');const before=bank();await click(link);assert(view.panel==='research'&&document.querySelector('[data-tech="engineering"]'),'engineering card not exposed');expectSpend(before,{});
 });
 await check('Training checklist disclosure and focus survive a production refresh',async()=>{
  fresh();await panel('army');await click(action('army-tab','train'));const details=document.querySelector('[data-training-requirements="home:spear"]');details.open=true;details.dispatchEvent(new window.Event('toggle',{bubbles:false}));const summary=details.querySelector('summary');summary.focus();game.state.resources.wood+=5;render(true);assert(document.querySelector('[data-training-requirements="home:spear"]')===details&&details.open,'refresh collapsed training requirements');assert(document.activeElement===summary,'refresh moved disclosure focus');
 });
 await check('A paused serial training queue explains active and waiting jobs immediately',async()=>{
  fresh();await panel('army');await click(action('army-tab','train'));await click('#panel-body '+action('train','spear'));await click('#panel-body '+action('train','sword'));
  const local=[...document.querySelectorAll('.local-job')];assert(local.length===2,'local queue is missing jobs');assert(local[0].querySelector('.job-phase').textContent==='Σε παύση','first paused job unclear');assert(local[1].querySelector('.job-phase').textContent==='Περιμένει τη σειρά του','second job looks stuck');const global=[...document.querySelectorAll('#build-queue .queue-job')];assert(global[1].textContent.includes('Περιμένει τη σειρά του'),'global queue omits waiting reason');
  await panel('economy');await click(global[1]);assert(view.panel==='army'&&view.armyTab==='train'&&view.regionId==='home','queue click cannot locate its production');
 });
 await check('Building region selector preserves manual placement in the chosen territory',async()=>{
  fresh();await panel('build');await setRegion('farmland','building');const button=document.querySelector('[data-action="build"][data-value="houses"]');assert(button.dataset.region==='farmland','build quote belongs to wrong region');const before=bank();await click(button);assert(view.placement?.regionId==='farmland','preview ignores chosen build region');expectSpend(before,{});await click(action('placement-cancel'));expectSpend(before,{});
 });
 await check('Mission navigation has labelled rewards and cannot silently order an attack',async()=>{
  fresh();await panel('chronicle');const mission=document.querySelector('[data-ui-key="mission:frontier"]'),before=bank(),orders=JSON.stringify(game.state.squads.map(s=>s.order)),count=calls.length;assert(document.querySelector('.mission-reward').textContent.includes('Ανταμοιβή'),'reward looks like cost');await click(adviceIn(mission,'region'));assert(view.panel==='realm'&&game.state.regions[view.selection.id].owner!=='player','frontier did not open inspection');expectSpend(before,{});assert(calls.length===count&&orders===JSON.stringify(game.state.squads.map(s=>s.order)),'mission action silently attacked');
 });
 await check('Victory mission shows territory and prosperity conditions independently',async()=>{
  fresh();for(const region of Object.values(game.state.regions))region.owner='player';game.state.prosperity=42;await panel('chronicle');const card=document.querySelector('[data-ui-key="mission:unite"]');assert(card.textContent.includes('9 / 9')&&card.textContent.includes('42 / 65'),'compound objective hidden');assert(!card.classList.contains('done')&&card.textContent.includes('όρος ευημερίας'),'9/9 falsely appears won');
 });
 await check('Help has actionable menu glossary, device controls and preserves deliberate pause',async()=>{
  fresh();await click('#help-button');assert(document.querySelectorAll('.help-menu-grid button').length===7,'help menu glossary incomplete');await click(action('help-topic','controls'));await click(action('help-device','touch'));assert(document.querySelector('.help-control-list').textContent.includes('Δύο δάχτυλα'),'touch controls absent');await click(action('help-topic','menus'));const before=bank();await click(action('help-panel','economy'));assert(view.panel==='economy'&&!view.modal&&game.state.paused,'help navigation resumed a deliberately paused campaign');expectSpend(before,{});assert(document.getElementById('help-button').textContent.includes('Οδηγίες'),'visible help label missing');
 });
 await check('Guide adapts to exhausted sources, missing spears and the selected recruitment region',async()=>{
  fresh();game.state.nodes.find(n=>n.id==='oak-west').amount=0;view.guideOpen=true;view.guideStep='workers';render(true);await click(action('guide-action','workers'));assert(view.selection.kind==='node'&&game.state.nodes.find(n=>n.id===view.selection.id).amount>0,'guide chooses exhausted first node');
  for(const squad of game.state.squads)if(squad.owner==='player'&&squad.type==='spear')squad.hp=0;view.guideOpen=true;view.guideStep='select';render(true);await click(action('guide-action','select'));assert(view.armyIds.length&&view.armyIds.every(id=>game.state.squads.find(s=>s.id===id)?.hp>0),'guide cannot select a surviving alternative');view.regionId='farmland';view.guideOpen=true;view.guideStep='train';render(true);await click(action('guide-action','train'));assert(game.state.regions[view.regionId].buildings.barracks>0,'guide opens an unusable training region');
 });
 await check('Completed tutorial becomes current campaign advice without resetting progress',async()=>{
  fresh();view.guideDone={workers:true,build:true,select:true,move:true,train:true};view.guideOpen=true;view.guideStep=null;game.state.resources.food=0;game.state.foodBalance=-1;render(true);const card=document.querySelector('#guide-body .advice-card');assert(card&&card.textContent.includes('τρόφιμα'),'post-tutorial guide ignores current shortage');const before=bank();await click(card.querySelector('[data-action="advice"]'));assert(view.panel==='economy'&&view.resourceFilter==='food','advice cannot lead to food');expectSpend(before,{});assert(Object.values(view.guideDone).every(Boolean),'advice reset completed tutorial');
 });

 await check('Revisiting a completed lesson provides an explicit return to current advice',async()=>{
  fresh();view.guideDone={workers:true,build:true,select:true,move:true,train:true};view.guideOpen=true;render(true);await click(action('guide-step','workers'));assert(view.guideStep==='workers'&&document.querySelector(action('guide-advice')),'replayed lesson traps the player');await click(action('guide-advice'));assert(!view.guideStep&&document.querySelector('.advice-card'),'cannot return to current campaign advice');
 });
 await check('Help navigation clears a pending building preview and old targeting mode',async()=>{
  fresh();await panel('build');await click(action('build','houses'));const before=bank();assert(view.placement,'placement fixture absent');await click('#help-button');await click(action('help-panel','economy'));assert(!view.placement&&!view.command&&view.panel==='economy','help leaves hidden placement active');expectSpend(before,{});
  await panel('build');await click(action('build','houses'));await click('#help-button');await click(action('help-topic','start'));await click(action('help-jump','move'));assert(!view.placement&&view.command==='move','move lesson still routes ground clicks to a ghost');expectSpend(before,{});
 });

}
await Promise.resolve();
const report={mode:mobile?'mobile':'desktop',passes,errors,defects,actions:calls.map(c=>({action:c.action,payload:c.payload,ok:c.result.ok})),worldCalls:worldCalls.filter(c=>c[0]!=='setState'),downloadCount:downloads.length};
await fs.writeFile(path.join(qaDirectory,report.mode+'.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({mode:report.mode,passed:passes.length,errors,defects,downloadCount:downloads.length},null,2));
if(errors.length)process.exitCode=1;
