import * as T from 'three';
import {createEscapeWorld} from './escape-world180.js';
import {newEscape,restore,snapshot,START,HOTSPOTS,LOW,ITEMS,obstacles,move,clear,path,canSee,inside,distance,bound,angle} from './escape-model180.js';
export function createEscapeChapter({ship,camera,hud,canvas,getPeople,getVoyage,canPlay,onReturn,onSave,getHealth,audio}){
 const ui=document.createElement('section');ui.id='escape180';ui.hidden=true;hud.append(ui);
 ui.innerHTML=`<header class="escape-goal"><small>ΚΕΦΑΛΑΙΟ 02 · ΚΑΤΑΣΤΡΩΜΑ 04</small><strong id="escapeGoal"></strong><span id="escapeDetail"></span></header><div class="escape-vitals"><span>♥ ΖΩΗ <b id="escapeHealth"></b></span><span>🥃 ΜΕΘΗ <b id="escapeDrunk"></b></span><span>◉ ΕΝΤΟΠΙΣΜΟΣ <b id="escapeAlert"></b></span><i id="escapeAlertBar"></i></div><div id="escapeMessage" role="status"></div><div id="escapeObjectiveMarker">↓</div><div id="escapePad" aria-label="Κίνηση"><i></i><span>ΚΙΝΗΣΗ</span></div><div id="escapeKeys"><kbd>W</kbd><div><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></div><small>ΚΙΝΗΣΗ</small></div><div class="escape-actions"><button id="escapeUse"><kbd>F</kbd><span>↗</span><b>ΑΝΟΙΞΕ</b><small></small></button><div><button id="escapeCrouch"><kbd>C</kbd><span>↧</span><b>ΣΚΥΨΕ</b></button><button id="escapeThrow" hidden><kbd>8</kbd><span>↗</span><b>ΠΕΤΑ</b></button><button id="escapeDrink" hidden><kbd>9</kbd><span>🥃</span><b>ΠΙΕ</b></button></div></div><p id="escapeHint"></p><section id="escapeOverlay" hidden><small id="escapeOverlayKicker"></small><h2 id="escapeOverlayTitle"></h2><p id="escapeOverlayCopy"></p><button id="escapeOverlayAction">ΣΥΝΕΧΕΙΑ →</button></section>`;
 const $=id=>ui.querySelector('#'+id),keys=new Set(),plane=new T.Plane(new T.Vector3(0,1,0),0),ray=new T.Raycaster();
 let active=false,world=null,s=newEscape(),guards=[],solids=[],stick={x:0,z:0},pointer=null,nearest=null,aim=null,noise=[],stageTimer=0,lastSave=0,lastUI=-10,msgUntil=0,hipY=null,cameraReady=false,pendingDrink=0,returnPending=false;
 const touch=()=>document.documentElement.dataset.inputScheme==='touch';
 function msg(text,duration=4){$('escapeMessage').textContent=text;msgUntil=s.time+duration;}
 function resetInput(){keys.clear();stick={x:0,z:0};pointer=null;$('escapePad').querySelector('i').style.transform='translate(0,0)';}
 function save(){onSave(snapshot(s));lastSave=s.time;}
 function setup(){if(world)return;world=createEscapeWorld(ship,getPeople());hipY=world.player.bones.get('hips')?.position.y;}
 function clearNoise(){for(const n of noise){world.root.remove(n.mesh);n.mesh.geometry.dispose();n.mesh.material.dispose();}noise=[];}
 function resetGuard(g,i){const a=g.route[0],b=g.route[1];Object.assign(g,{x:a.x,z:a.z,yaw:Math.atan2(b.x-a.x,b.z-a.z),index:1,wait:1+i*.7,mode:'patrol',investigate:null,investigateUntil:0,nav:[],navUntil:0,suspect:0});}
 function resetProps(){for(const o of world.props){const base=ITEMS.find(i=>i.id===o.id);o.group.position.set(base.x,.06,base.z);o.group.rotation.set(0,0,0);o.group.visible=true;o.available=true;o.flying=false;}world.target.visible=false;}
 function start(data){setup();s=data?restore(data):newEscape();s.stage=data?'escape':'sleep';s.health=Math.max(75,getHealth());active=true;returnPending=false;stageTimer=0;pendingDrink=0;lastUI=-10;lastSave=0;cameraReady=false;clearNoise();aim=null;nearest=null;ui.hidden=false;hud.classList.add('escape-mode');world.root.visible=true;resetInput();guards=world.guards;guards.forEach(resetGuard);resetProps();world.whisky.visible=!s.bottle;world.card.visible=!s.card;world.doors.storeDoor.visible=!s.storeOpen;world.doors.hatch.children.forEach((o,i)=>{if(i>2)o.visible=!s.hatch;});getVoyage().intox=s.intox;solids=obstacles(s);
  $('escapeOverlay').hidden=true;if(!data){showOverlay('ΛΙΓΟ ΑΡΓΟΤΕΡΑ','ΞΥΠΝΑΣ ΝΗΦΑΛΙΟΣ.','Ο φύλακας θυμάται τη βάρδιά σου. Βρες τη χαμηλή θυρίδα δίπλα στο κρεβάτι. Η πόρτα του κελιού παραμένει κλειδωμένη.','ΞΥΠΝΑ ΚΑΙ ΠΑΙΞΕ →');$('escapeOverlayAction').disabled=true;}else{msg('Συνέχεια από την αποθηκευμένη απόδραση.');save();}updateUI();
 }
 function stop(){active=false;returnPending=false;ui.hidden=true;hud.classList.remove('escape-mode');if(world){world.root.visible=false;clearNoise();}resetInput();}
 function showOverlay(k,t,p,b){$('escapeOverlay').hidden=false;$('escapeOverlayKicker').textContent=k;$('escapeOverlayTitle').textContent=t;$('escapeOverlayCopy').textContent=p;$('escapeOverlayAction').textContent=b;$('escapeOverlayAction').disabled=false;}
 $('escapeOverlayAction').onclick=()=>{if(!active||!canPlay())return;if(s.stage==='sleep'){s.stage='escape';$('escapeOverlay').hidden=true;msg('Πλησίασε τη θυρίδα και πάτησε ΑΝΟΙΞΕ. Μετά ΣΚΥΨΕ για να περάσεις.',6);save();}else if(s.stage==='caught')retry();};
 function retry(){s.caught++;s.stage='escape';s.alert=0;s.held=null;s.position=s.card?{x:3.4,z:11.5}:{...START};s.yaw=Math.PI;s.crouch=false;pendingDrink=0;guards.forEach(resetGuard);clearNoise();resetProps();$('escapeOverlay').hidden=true;resetInput();cameraReady=false;msg('Συνεχίζεις από το σημείο ελέγχου — όχι από την αρχή του παιχνιδιού.');save();}
 function allowed(){return active&&canPlay()&&s.stage==='escape';}
 function crouch(){if(!allowed())return;if(s.crouch&&inside(s.position,LOW,.35)){msg('Χαμηλό πέρασμα — δεν μπορείς να σηκωθείς εδώ.');return;}s.crouch=!s.crouch;updateUI();}
 function interact(){if(!allowed()||!nearest)return;const id=nearest.id;
  if(id==='hatch'){s.hatch=true;world.doors.hatch.children.forEach((o,i)=>{if(i>2)o.visible=false;});solids=obstacles(s);msg('Η θυρίδα άνοιξε. Σκύψε για να περάσεις κάτω από το πλαίσιο.');}
  else if(id==='card'){s.card=true;s.checkpoint='card';world.card.visible=false;msg('Κάρτα αποθήκης. Αποθηκεύτηκε σημείο ελέγχου.');}
  else if(id==='storeDoor'){if(!s.card){msg('Χρειάζεται η κάρτα από το γραφείο της ασφάλειας.');return;}s.storeOpen=true;world.doors.storeDoor.visible=false;solids=obstacles(s);msg('Η αποθήκη είναι ανοιχτή. Το μπουκάλι βρίσκεται στο ράφι.');}
  else if(id==='whisky'){s.bottle=true;world.whisky.visible=false;msg('Βρήκες ολόκληρο μπουκάλι! Πάτησε ΠΙΕ — η μέθη ανεβαίνει σταδιακά.');}
  else if(id==='exit'){if(!s.bottle){msg('Πάρε πρώτα το ουίσκι από την αποθήκη.');return;}if(s.intox<25){msg('Πιες από το μπουκάλι. Περίμενε να φτάσει η μέθη στο 25%.');return;}s.stage='leaving';stageTimer=0;returnPending=true;resetInput();showOverlay('ΕΞΟΔΟΣ ΑΠΟ ΤΑ ΚΑΤΩ ΚΑΤΑΣΤΡΩΜΑΤΑ','ΠΙΣΩ ΣΤΗ ΓΕΦΥΡΑ.','Η απόδραση ολοκληρώθηκε. Η ασφάλεια περιμένει πάνω. Τα προηγούμενα χτυπήματα και οι ζημιές παραμένουν.','ΑΝΕΒΑΙΝΕΙΣ ΤΗ ΣΚΑΛΑ…');$('escapeOverlayAction').disabled=true;}
  else{const o=world.props.find(o=>o.id===id);if(o&&o.available&&!s.held){s.held=o.id;o.available=false;aim={x:s.position.x+Math.sin(s.yaw)*3,z:s.position.z+Math.cos(s.yaw)*3};msg(touch()?'Κρατάς αντικείμενο. Άγγιξε το δάπεδο για στόχο και πάτησε ΠΕΤΑ.':'Σημάδεψε το δάπεδο με κλικ και πάτησε 8 για θόρυβο.');}}
  save();nearest=nearestAction();updateUI();
 }
 function drink(){if(!allowed()||!s.bottle||pendingDrink>0)return;pendingDrink=32;getVoyage().drinks++;audio?.voice?.('captain3',{priority:0});msg('Μία μεγάλη γουλιά… Οι δυνάμεις επιστρέφουν σταδιακά.');save();}
 function throwItem(){if(!allowed()||!s.held)return;const o=world.props.find(o=>o.id===s.held);s.held=null;s.throws++;const from={...s.position},want=aim||{x:from.x+Math.sin(s.yaw)*4,z:from.z+Math.cos(s.yaw)*4};let d=distance(from,want),end={...want};if(d>6.5){end={x:from.x+(want.x-from.x)*6.5/d,z:from.z+(want.z-from.z)*6.5/d};d=6.5;}
  const n=Math.max(1,Math.ceil(d/.08));let last={...from};for(let i=1;i<=n;i++){const p={x:from.x+(end.x-from.x)*i/n,z:from.z+(end.z-from.z)*i/n};if(!clear(last,p,solids)||p.x<-6.6||p.x>6.6||p.z<.4||p.z>25.5){end=last;break;}last=p;}
  o.flying={from,end,t:0,duration:.45+distance(from,end)*.075};o.group.visible=true;world.target.visible=false;aim=null;save();updateUI();
 }
 function makeNoise(at){audio?.hit?.('block');const ring=new T.Mesh(new T.RingGeometry(.96,1,48),new T.MeshBasicMaterial({color:0xe9c56d,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.set(at.x,.05,at.z);world.root.add(ring);noise.push({mesh:ring,t:0});let heard=0;for(const g of guards){if(distance(g,at)<(clear(g,at,solids)?8:5.3)){g.mode='investigate';g.investigate={...at};g.investigateUntil=s.time+8;g.nav=[];g.navUntil=0;heard++;}}s.heard+=heard;msg(heard?'Ο θόρυβος τράβηξε την προσοχή. Κινήσου όσο ερευνούν.':'Ο θόρυβος δεν έφτασε σε κάποιον. Πάρε ξανά το αντικείμενο.');}
 function nearestAction(){let best=null,dist=1.55;for(const h of HOTSPOTS){if((h.id==='hatch'&&s.hatch)||(h.id==='card'&&s.card)||(h.id==='storeDoor'&&s.storeOpen)||(h.id==='whisky'&&s.bottle))continue;const d=distance(s.position,h),blockers=solids.filter(b=>b.id!==h.id&&!(h.id==='card'&&b.id==='desk')&&!(h.id==='whisky'&&b.id==='store'));if(d<dist&&clear(s.position,h,blockers)){best=h;dist=d;}}if(!s.held)for(const o of world.props){if(!o.available||o.flying)continue;const at={x:o.group.position.x,z:o.group.position.z},d=distance(s.position,at);if(d<dist&&clear(s.position,at,solids)){best={id:o.id,label:'ΠΑΡΕ',icon:'✊',name:o.label,...at};dist=d;}}return best;}
 function objective(){if(!s.hatch)return ['ΑΝΟΙΞΕ ΤΗ ΧΑΜΗΛΗ ΘΥΡΙΔΑ.','Πλησίασε τη θυρίδα δίπλα στο κρεβάτι.','hatch'];if(s.position.z>19.5&&s.position.x<-2)return ['ΠΕΡΑΣΕ ΣΚΥΦΤΟΣ.','Πάτησε ΣΚΥΨΕ και προχώρα κάτω από το πλαίσιο.','hatch'];if(!s.card)return ['ΒΡΕΣ ΤΗΝ ΚΑΡΤΑ ΑΠΟΘΗΚΗΣ.','Γραφείο ασφάλειας. Απόφυγε τα πεδία όρασης.','card'];if(!s.storeOpen)return ['ΑΝΟΙΞΕ ΤΗΝ ΑΠΟΘΗΚΗ.','Η κάρτα ανοίγει την μπλε πόρτα απέναντι.','storeDoor'];if(!s.bottle)return ['ΠΑΡΕ ΤΟ ΓΕΜΑΤΟ ΟΥΙΣΚΙ.','Στο ράφι μέσα στην αποθήκη.','whisky'];if(s.intox<25)return ['ΟΙ ΔΥΝΑΜΕΙΣ ΕΠΙΣΤΡΕΦΟΥΝ.','Πάτησε ΠΙΕ. Μέθη 25% για επιστροφή στο κατάστρωμα.','exit'];return ['ΠΑΡΕ ΠΙΣΩ ΤΗ ΓΕΦΥΡΑ.','Ακολούθησε τη φωτισμένη σκάλα στο τέλος του διαδρόμου.','exit'];}
 function updateUI(){const [goal,detail]=objective();$('escapeGoal').textContent=s.stage==='sleep'?'ΜΙΑ ΗΣΥΧΗ ΣΤΙΓΜΗ…':goal;$('escapeDetail').textContent=detail;$('escapeHealth').textContent=Math.round(s.health)+'%';$('escapeDrunk').textContent=Math.round(s.intox)+'%';$('escapeAlert').textContent=Math.round(s.alert)+'%';$('escapeAlertBar').style.width=s.alert+'%';const use=$('escapeUse');use.disabled=!nearest||s.stage!=='escape';use.querySelector('span').textContent=nearest?.icon||'⌖';use.querySelector('b').textContent=nearest?.label||'ΠΛΗΣΙΑΣΕ';use.querySelector('small').textContent=nearest?.name||'';$('escapeCrouch').classList.toggle('active',s.crouch);$('escapeCrouch').querySelector('b').textContent=s.crouch?'ΣΗΚΩ':'ΣΚΥΨΕ';$('escapeThrow').hidden=!s.held;$('escapeDrink').hidden=!s.bottle;$('escapeDrink').disabled=pendingDrink>0;$('escapeHint').textContent=touch()?(s.held?'Άγγιξε το δάπεδο για στόχο ρίψης':'Αριστερά: κίνηση · ΣΚΥΨΕ: χαμηλό πέρασμα'):(s.held?'Κλικ στο δάπεδο · 8 ρίψη · C σκύψιμο':'W A S D: κίνηση · F: αλληλεπίδραση · C: σκύψιμο');}
 function animateCaptain(dt,speed){const actor=world.player,hips=actor.bones.get('hips');if(hips&&hipY!==null)hips.position.y=hipY;actor.tick(dt,{speed,drunk:s.intox/100,time:s.time,held:!!s.held,drinking:pendingDrink>0?.5:0});if(s.crouch){const wave=Math.sin(s.time*8)*Math.min(.35,speed*.25);if(hips)hips.position.y=hipY-.68;for(const [name,rotation]of [['spine',.9],['leftupleg',-.95+wave],['rightupleg',-.95-wave],['leftleg',1.45],['rightleg',1.45],['leftarm',-1.0-wave],['rightarm',-1.0+wave]])actor.bones.get(name)?.rotateX(rotation);}actor.group.position.set(s.position.x,0,s.position.z);actor.group.rotation.set(0,s.yaw,0);actor.group.updateMatrixWorld(true);}
 function tickGuard(g,dt){const sees=s.stage==='escape'&&canSee(g,s.position,s.crouch,solids);g.suspect=bound(g.suspect+dt*(sees?(s.crouch?31:45):-26),0,100);if(sees){g.mode='search';g.investigate={...s.position};g.investigateUntil=s.time+4;}let dest;if((g.mode==='investigate'||g.mode==='search')&&s.time<g.investigateUntil){dest=g.investigate;if(distance(g,dest)<.5){g.yaw+=dt*.85;dest=null;}}else{g.mode='patrol';dest=g.route[g.index];if(distance(g,dest)<.3){g.wait-=dt;if(g.wait<=0){g.index=(g.index+1)%g.route.length;g.wait=.6;g.navUntil=0;}dest=null;}}if(g.mode==='search'&&distance(g,s.position)<.7){dest=null;g.yaw=Math.atan2(s.position.x-g.x,s.position.z-g.z);}
  let speed=0;if(dest){if(s.time>g.navUntil||!g.nav.length){g.nav=path(g,dest,solids,false);g.navUntil=s.time+.7;}while(g.nav.length&&distance(g,g.nav[0])<.18)g.nav.shift();const aim=g.nav[0];if(aim){const d=distance(g,aim),k=Math.min(d,dt*g.speed*(g.mode==='search'?1.3:1));speed=k/Math.max(dt,.001);g.yaw+=angle(Math.atan2(aim.x-g.x,aim.z-g.z)-g.yaw)*Math.min(1,dt*6);move(g,(aim.x-g.x)/Math.max(d,.01)*k,(aim.z-g.z)/Math.max(d,.01)*k,solids,false);}}g.actor.group.position.set(g.x,0,g.z);g.actor.group.rotation.y=g.yaw;g.actor.tick(dt,{speed,time:s.time});
  const verts=[g.x,.043,g.z],r=6.5,count=22;for(let i=0;i<=count;i++){const a=g.yaw-.62+i/count*1.24;let d=0;for(d=.25;d<r;d+=.22)if(!clear(g,{x:g.x+Math.sin(a)*d,z:g.z+Math.cos(a)*d},solids))break;d=Math.max(.2,d-.22);verts.push(g.x+Math.sin(a)*d,.043,g.z+Math.cos(a)*d);}const idx=[];for(let i=1;i<=count;i++)idx.push(0,i,i+1);g.cone.geometry.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.cone.geometry.setIndex(idx);g.cone.geometry.computeBoundingSphere();g.cone.material.color.setHex(sees?0xec7158:g.mode==='patrol'?0xd5ac55:0x6ec1d4);return sees;
 }
 function update(dt){if(!active)return;dt=bound(dt,0,.05);s.time+=dt;stageTimer+=dt;solids=obstacles(s);if(s.stage==='sleep'){animateCaptain(dt,0);if(stageTimer>1.6)$('escapeOverlayAction').disabled=false;return;}if(s.stage==='leaving'){if(stageTimer>1.6&&returnPending){returnPending=false;const result=snapshot(s);stop();onReturn(result);}return;}if(s.stage==='caught')return;
  const dx=stick.x+(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),dz=stick.z+(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),len=Math.max(1,Math.hypot(dx,dz)),speed=s.crouch?1.22:2.2;const before={...s.position};let moved=move(s.position,dx/len*speed*dt,dz/len*speed*dt,solids,s.crouch);if(guards.some(g=>distance(g,s.position)<.52)){s.position=before;moved=0;}if(moved>.0001)s.yaw+=angle(Math.atan2(dx,dz)-s.yaw)*Math.min(1,dt*10);animateCaptain(dt,moved/Math.max(dt,.001));const amount=Math.min(pendingDrink,dt*8);pendingDrink-=amount;s.intox=bound(s.intox+amount,0,100);getVoyage().intox=s.intox;
  for(const o of world.props){if(o.id===s.held){o.group.position.set(s.position.x+Math.sin(s.yaw)*.45,s.crouch?.48:1.12,s.position.z+Math.cos(s.yaw)*.45);}else if(o.flying){const f=o.flying;f.t+=dt;const k=Math.min(1,f.t/f.duration);o.group.position.set(T.MathUtils.lerp(f.from.x,f.end.x,k),.12+Math.sin(k*Math.PI)*1.5,T.MathUtils.lerp(f.from.z,f.end.z,k));o.group.rotation.x+=dt*8;if(k>=1){o.flying=false;o.available=true;o.group.rotation.set(0,0,0);makeNoise(f.end);}}}
  for(let i=noise.length-1;i>=0;i--){const n=noise[i];n.t+=dt;n.mesh.scale.setScalar(1+n.t*4);n.mesh.material.opacity=Math.max(0,.6-n.t*.4);if(n.t>1.5){world.root.remove(n.mesh);n.mesh.geometry.dispose();n.mesh.material.dispose();noise.splice(i,1);}}for(const g of guards)tickGuard(g,dt);s.alert=Math.max(...guards.map(g=>g.suspect));if(s.alert>=100){s.stage='caught';s.held=null;resetInput();showOverlay('ΣΕ ΕΝΤΟΠΙΣΑΝ','ΟΧΙ ΑΠΟ ΤΗΝ ΑΡΧΗ.','Ο φύλακας σε σταμάτησε. Η βαθμολογία χάους και η κάρτα που βρήκες διατηρούνται. Δοκίμασε άλλη διαδρομή ή έναν αντιπερισπασμό.','ΞΑΝΑ ΑΠΟ ΤΟ ΣΗΜΕΙΟ ΕΛΕΓΧΟΥ →');return;}nearest=nearestAction();if(s.time>msgUntil)$('escapeMessage').textContent='';if(s.time-lastUI>.1){updateUI();lastUI=s.time;}if(s.time-lastSave>2)save();
 }
 function cameraUpdate(){if(!active||!world)return false;world.root.updateWorldMatrix(true,true);const p=s.position,portrait=innerHeight>innerWidth,h=portrait?12.4:14.8;const pos=world.root.localToWorld(new T.Vector3(p.x,h,p.z+7.6)),to=world.root.localToWorld(new T.Vector3(p.x,0,p.z-1));camera.position.copy(pos);camera.up.set(0,1,0).applyQuaternion(ship.group.quaternion);camera.lookAt(to);camera.fov=portrait?61:57;camera.updateProjectionMatrix();camera.updateMatrixWorld();cameraReady=true;const id=objective()[2],goal=HOTSPOTS.find(h=>h.id===id),mark=$('escapeObjectiveMarker'),v=world.root.localToWorld(new T.Vector3(goal.x,.2,goal.z)).project(camera);mark.style.left=bound((v.x*.5+.5)*innerWidth,26,innerWidth-26)+'px';mark.style.top=bound((-v.y*.5+.5)*innerHeight,portrait?225:145,Math.max(portrait?240:170,innerHeight-180))+'px';mark.textContent=Math.abs(v.y)>1?(v.y>0?'↑':'↓'):'↓';mark.style.display=s.stage==='escape'?'block':'none';for(const [key,ring]of Object.entries(world.markers)){ring.visible=key===id;ring.material.opacity=.5+.25*Math.sin(s.time*3);}return true;}
 function pointAt(e){if(!active||!cameraReady)return false;if(s.held&&s.stage==='escape'){const b=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const rr=ray.ray.clone().applyMatrix4(world.root.matrixWorld.clone().invert()),pt=new T.Vector3();if(rr.intersectPlane(plane,pt)){aim={x:pt.x,z:pt.z};world.target.position.set(pt.x,.045,pt.z);world.target.visible=true;}}return true;}
 function keyDown(e){if(!active)return false;if(!canPlay())return true;if(e.code==='Escape')return false;keys.add(e.code);if(e.repeat)return true;if(e.code==='KeyC')crouch();if(['KeyF','KeyE','Digit7','Numpad7'].includes(e.code))interact();if(['Digit8','Numpad8'].includes(e.code))throwItem();if(['Digit9','Numpad9'].includes(e.code))drink();return true;}
 function keyUp(e){keys.delete(e.code);}
 const pad=$('escapePad');function padMove(e){const b=pad.getBoundingClientRect(),x=(e.clientX-b.left-b.width/2)/34,z=(e.clientY-b.top-b.height/2)/34,l=Math.max(1,Math.hypot(x,z));stick={x:x/l,z:z/l};pad.querySelector('i').style.transform=`translate(${stick.x*30}px,${stick.z*30}px)`;}
 pad.addEventListener('pointerdown',e=>{if(!allowed()||pointer!==null)return;e.preventDefault();pointer=e.pointerId;pad.setPointerCapture(pointer);padMove(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===pointer)padMove(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(type,e=>{if(e.pointerId!==pointer||e.type==='lostpointercapture'&&e.target!==pad)return;pointer=null;stick={x:0,z:0};pad.querySelector('i').style.transform='translate(0,0)';});$('escapeUse').onclick=interact;$('escapeCrouch').onclick=crouch;$('escapeThrow').onclick=throwItem;$('escapeDrink').onclick=drink;window.addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(active&&s.stage==='escape')save();resetInput();}});
 return {start,stop,update,cameraUpdate,keyDown,keyUp,resetInput,pointerDown:pointAt,get active(){return active;},get state(){return s;},inspect:()=>active?{...snapshot(s),stage:s.stage,alert:s.alert,crouch:s.crouch,held:s.held,nearest:nearest?.id||null,guards:guards.map(g=>({x:g.x,z:g.z,yaw:g.yaw,mode:g.mode,suspect:g.suspect})),items:world.props.map(o=>({id:o.id,x:o.group.position.x,z:o.group.position.z,available:o.available,flying:!!o.flying}))}:null,test:{moveTo:(x,z)=>{s.position={x,z};},wake:()=>{s.stage='escape';$('escapeOverlay').hidden=true;},interact,crouch,throwItem,drink,aim:(x,z)=>{aim={x,z};},advance:n=>{for(let i=0;i<n*60;i++)update(1/60);}}};
}
