import {floorCandidates,floorAt,onFloor,circleBox,moveCharacter} from './shipwalk184.js';
export {captureStep,guardQuota} from './combat184.js';
const STEP=1,R=.26,key=(x,z)=>Math.round(x/STEP)+','+Math.round(z/STEP);
const indexes=new WeakMap();
function nearby(p,solids){let index=indexes.get(solids);if(!index){index=new Map();for(const b of solids){if(b.active===false)continue;for(let x=Math.floor((b.x-b.w/2-.3)/2);x<=Math.floor((b.x+b.w/2+.3)/2);x++)for(let z=Math.floor((b.z-b.d/2-.3)/4);z<=Math.floor((b.z+b.d/2+.3)/4);z++){const k=x+','+z;if(!index.has(k))index.set(k,[]);index.get(k).push(b);}}indexes.set(solids,index);}return index.get(Math.floor(p.x/2)+','+Math.floor(p.z/4))||[];}
function clear(p,solids){return onFloor(p.x,p.z,R,p.y)&&!nearby(p,solids).some(b=>b.active!==false&&p.y+.12<(b.y??p.y)+(b.h??2.2)&&p.y+1.65>(b.y??p.y)+.1&&circleBox(p.x,p.z,R,b));}
function travel(a,b,solids){const d=Math.hypot(b.x-a.x,b.z-a.z),n=Math.max(1,Math.ceil(d/.20));let p={x:a.x,y:a.y,z:a.z};for(let i=1;i<=n;i++){const t=i/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t,h=floorAt(x,z,p.y);if(h===null||Math.abs(h-p.y)>.65)return false;p={x,y:h,z};if(!clear(p,solids))return false;}return Math.abs(p.y-b.y)<.75;}
class Heap{a=[];push(id,f){const n={id,f};let i=this.a.length;this.a.push(n);while(i){const p=(i-1)>>1;if(this.a[p].f<=f)break;this.a[i]=this.a[p];i=p;}this.a[i]=n;}pop(){const top=this.a[0],v=this.a.pop();if(this.a.length){let i=0;while(i*2+1<this.a.length){let c=i*2+1;if(c+1<this.a.length&&this.a[c+1].f<this.a[c].f)c++;if(this.a[c].f>=v.f)break;this.a[i]=this.a[c];i=c;}this.a[i]=v;}return top.id;}}
export function createShipNavigator(){let stamp='',nodes=[],lookup=new Map(),builds=0;
 function rebuild(solids){const sig=solids.filter(b=>b.active!==false).map(b=>[b.x,b.y,b.z,b.w,b.d,b.h].join(',')).join('|');if(sig===stamp&&nodes.length)return;stamp=sig;nodes=[];lookup.clear();builds++;
  for(let z=-66;z<=71;z+=STEP)for(let x=-12;x<=13;x+=STEP){const entries=[];for(const c of floorCandidates(x,z)){const n={x,z,y:c.y,index:nodes.length,edges:[]};if(entries.some(a=>Math.abs(a.y-n.y)<.12)||!clear(n,solids))continue;nodes.push(n);entries.push(n);}if(entries.length)lookup.set(key(x,z),entries);}
  for(const a of nodes)for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]])for(const b of lookup.get(key(a.x+dx*STEP,a.z+dz*STEP))||[]){if(Math.abs(a.y-b.y)<.66&&travel(a,b,solids))a.edges.push(b.index);}
 }
 function nearest(p,solids){let best=null,cost=Infinity;for(let radius=1;radius<=3&&!best;radius++)for(let dz=-radius;dz<=radius;dz++)for(let dx=-radius;dx<=radius;dx++)for(const n of lookup.get(key(p.x+dx,p.z+dz))||[]){const d=Math.hypot(p.x-n.x,p.z-n.z)+Math.abs(p.y-n.y)*3;if(d<cost&&Math.abs(p.y-n.y)<.7&&travel(p,n,solids)){best=n;cost=d;}}return best;}
 function path(a,b,solids){rebuild(solids);const start=nearest(a,solids),end=nearest(b,solids);if(!start||!end)return [];const cost=new Float64Array(nodes.length);cost.fill(Infinity);const from=new Int32Array(nodes.length);from.fill(-1);const closed=new Uint8Array(nodes.length),heap=new Heap();cost[start.index]=0;heap.push(start.index,0);
  while(heap.a.length){const id=heap.pop();if(closed[id])continue;if(id===end.index){const out=[{...b}];for(let at=id;at!==start.index&&at>=0;at=from[at])out.unshift({x:nodes[at].x,y:nodes[at].y,z:nodes[at].z});return out;}closed[id]=1;const n=nodes[id];for(const next of n.edges){if(closed[next])continue;const q=nodes[next],d=cost[id]+Math.hypot(n.x-q.x,n.y-q.y,n.z-q.z);if(d<cost[next]){cost[next]=d;from[next]=id;heap.push(next,d+Math.hypot(q.x-end.x,q.y-end.y,q.z-end.z));}}}return [];
 }
 function steer(actor,p,target,solids,time){if(travel(p,target,solids)){actor.nav=null;return target;}if(!actor.nav||actor.nav.until<time||Math.hypot(actor.nav.target.x-target.x,actor.nav.target.z-target.z)>3||Math.abs(actor.nav.target.y-target.y)>1){actor.nav={points:path(p,target,solids),target:{...target},until:time+2.6+(actor.id%3)*.2};}while(actor.nav.points.length&&Math.hypot(actor.nav.points[0].x-p.x,actor.nav.points[0].z-p.z)<.35&&Math.abs(actor.nav.points[0].y-p.y)<.6)actor.nav.points.shift();return actor.nav.points[0]||p;}
 return {steer,path,travel:(a,b,s)=>travel(a,b,s),clear:(p,s)=>clear({...p,y:p.y??10.1},s),reset:()=>{stamp='';nodes=[];lookup.clear();},inspect:()=>({nodes:nodes.length,builds})};
}
