import {worldRings} from './geometry.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dialog,worker,controller,epoch=0,scene,file,buffer,result,baseCrop,crop,onApply,timer;
const $=id=>document.getElementById(id);
function terminate(){worker?.terminate();worker=null;controller?.abort();controller=null;clearTimeout(timer);}
function job(url,data,signal){return new Promise((resolve,reject)=>{const w=new Worker(new URL(url,import.meta.url),{type:'module'});worker=w;const timeout=setTimeout(()=>finish(Error('Η μετατροπή ξεπέρασε τα 45 δευτερόλεπτα. Διάλεξε μικρότερο αρχείο/περιοχή.')),45000);function finish(error,value){clearTimeout(timeout);signal?.removeEventListener('abort',abort);w.terminate();if(worker===w)worker=null;error?reject(error):resolve(value);}const abort=()=>finish(new DOMException('Ακυρώθηκε','AbortError'));signal?.addEventListener('abort',abort,{once:true});w.onmessage=e=>e.data.error?finish(Error(e.data.error)):finish(null,e.data);w.onerror=e=>finish(Error(e.message||'Δεν ξεκίνησε ο αποκωδικοποιητής.'));w.postMessage(data);});}
function create(){if(dialog)return;dialog=document.createElement('dialog');dialog.id='drawing-dialog';dialog.innerHTML=`<div class="drawing-heading"><div><span class="eyebrow">ΕΙΣΑΓΩΓΗ ΚΑΤΟΨΗΣ</span><h2 id="drawing-name"></h2></div><button id="drawing-close" aria-label="Ακύρωση εισαγωγής">×</button></div><p id="drawing-status" role="status">Ανάγνωση αρχείου…</p><div class="drawing-layout"><div class="drawing-view"><div class="drawing-tabs"><button id="drawing-source" aria-pressed="true">Αρχικό σχέδιο</button><button id="drawing-result" aria-pressed="false">Μετατροπή</button></div><svg id="drawing-preview" aria-label="Προεπισκόπηση σχεδίου" tabindex="0"></svg><p class="small">Σύρε στο αρχικό σχέδιο για επιλογή περιοχής. Η εισαγωγή δημιουργεί επεξεργάσιμα στοιχεία.</p></div><div class="drawing-options"><label id="drawing-page-row" hidden>Σελίδα PDF<select id="drawing-page"></select></label><label>Κάτοψη / περιοχή<select id="drawing-region"></select></label><button id="drawing-all" class="wide-button">Ολόκληρη επιλεγμένη περιοχή</button><label id="drawing-unit-row">Μονάδα DWG<select id="drawing-unit"><option value="0">Χωρίς γνωστή κλίμακα</option><option value="100">Μέτρα (m)</option><option value="1">Εκατοστά (cm)</option><option value="0.1">Χιλιοστά (mm)</option><option value="2.54">Ίντσες</option><option value="30.48">Πόδια</option></select></label><label id="drawing-scale-row" hidden>Κλίμακα PDF · 1 προς<input id="drawing-scale" type="number" placeholder="π.χ. 100 · επιβεβαίωσε στο σχέδιο" min="1" max="10000" inputmode="decimal"></label><label>Ύψος τοίχων / χώρων (m)<input id="drawing-height" type="number" value="2.8" min="0.2" max="100" step="0.1" inputmode="decimal"></label><details class="drawing-advanced"><summary>Αναγνώριση χώρων</summary><label>Μέγιστο κενό για κλειστό χώρο (m)<input id="drawing-gap" type="number" value="8" min="0" max="20" step="0.1"></label><label>Ελάχιστο εμβαδόν χώρου (m²)<input id="drawing-room-min" type="number" value="2" min="0.1" max="100" step="0.1"></label><p class="small">Μείωσε το κενό για λιγότερες υποθετικές συνδέσεις. Τα μη κλειστά τμήματα παραμένουν τοίχοι.</p></details><details class="drawing-layers" open><summary>Layers / ομάδες γραμμών</summary><div id="drawing-layers"></div></details></div></div><p id="drawing-count" role="status"></p><ul id="drawing-warnings"></ul><div class="drawing-actions"><button id="drawing-cancel">Ακύρωση</button><button id="drawing-apply" class="primary" disabled>Εισαγωγή επεξεργάσιμου σχεδίου</button></div>`;document.body.append(dialog);
 $('drawing-close').onclick=$('drawing-cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{epoch++;terminate();scene=result=buffer=file=null;$('drawing-preview').replaceChildren();$('drawing-layers').replaceChildren();});
 $('drawing-source').onclick=()=>setPreview(false);$('drawing-result').onclick=()=>setPreview(true);
 $('drawing-region').onchange=()=>{baseCrop=scene.regions[Number($('drawing-region').value)]||scene.bounds;crop={...baseCrop};schedule();};$('drawing-all').onclick=()=>{crop={...baseCrop};schedule();};
 for(const id of ['drawing-unit','drawing-scale','drawing-height','drawing-gap','drawing-room-min'])$(id).oninput=schedule;
 $('drawing-layers').onchange=schedule;$('drawing-page').onchange=()=>read(Number($('drawing-page').value));
 $('drawing-apply').onclick=()=>{if(!result)return;onApply(result.plan);dialog.close();};
 const svg=$('drawing-preview');let drag;
 const point=e=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());};
 svg.onpointerdown=e=>{if(!scene||$('drawing-source').getAttribute('aria-pressed')!=='true')return;drag={id:e.pointerId,start:point(e)};svg.setPointerCapture(e.pointerId);};
 svg.onpointermove=e=>{if(drag?.id!==e.pointerId)return;const p=point(e);crop={x:Math.min(p.x,drag.start.x),y:Math.min(p.y,drag.start.y),w:Math.abs(p.x-drag.start.x),h:Math.abs(p.y-drag.start.y)};const r=$('drawing-crop');if(r)for(const key of ['x','y','w','h'])r.setAttribute(key,crop[key]);};
 svg.onpointerup=e=>{if(drag?.id!==e.pointerId)return;drag=null;svg.releasePointerCapture(e.pointerId);if(crop.w<baseCrop.w*.01||crop.h<baseCrop.h*.01)crop={...baseCrop};schedule();};svg.onpointercancel=()=>{drag=null;crop={...baseCrop};schedule();};
}
function setPreview(converted){$('drawing-source').setAttribute('aria-pressed',!converted);$('drawing-result').setAttribute('aria-pressed',converted);renderPreview();}
function renderPreview(){if(!scene)return;const svg=$('drawing-preview'),converted=$('drawing-result').getAttribute('aria-pressed')==='true';
 if(converted&&result){const b={x:50,y:50,w:crop.w*(result.plan.measurement?Number($('drawing-unit').value)||Number($('drawing-scale').value)*2.54/72:1000/Math.max(crop.w,crop.h))+100,h:crop.h*(result.plan.measurement?Number($('drawing-unit').value)||Number($('drawing-scale').value)*2.54/72:1000/Math.max(crop.w,crop.h))+100};svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);svg.innerHTML=result.plan.items.map(i=>i.type==='room'?`<path d="${worldRings(i).map(r=>r.map((p,n)=>`${n?'L':'M'}${p.x} ${p.y}`).join(' ')+' Z').join(' ')}" fill="#c1e3d3" fill-opacity=".6" stroke="#167a78" stroke-width="2"/>`:`<g transform="translate(${i.x+i.w/2} ${i.y+i.h/2}) rotate(${i.rotation})"><rect x="${-i.w/2}" y="${-i.h/2}" width="${i.w}" height="${i.h}" fill="${i.type==='door'?'#3686b4':i.type==='window'?'#8dc9dc':'#53636c'}"/></g>`).join('');return;}
 const b=baseCrop,selected=new Set([...$('drawing-layers').querySelectorAll('input:checked')].map(i=>i.value)),inside=p=>p.x>=b.x&&p.y>=b.y&&p.x<=b.x+b.w&&p.y<=b.y+b.h,width=Math.max(b.w,b.h)/800;svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);svg.innerHTML=scene.paths.filter(p=>p.points.every(inside)&&selected.has(p.layer)).slice(0,12000).map(p=>`<path d="${p.points.map((p,n)=>`${n?'L':'M'}${p.x} ${p.y}`).join(' ')}${p.closed?' Z':''}" fill="${p.fill||'none'}" stroke="${p.stroke||'none'}" stroke-width="${width}" opacity="${p.eligible===false?'.2':'.85'}"/>`).join('')+`<rect id="drawing-crop" x="${crop.x}" y="${crop.y}" width="${crop.w}" height="${crop.h}" fill="none" stroke="#db822c" stroke-width="${width*2}" stroke-dasharray="${width*6}"/>`;
}
function schedule(){if(!scene)return;result=null;$('drawing-apply').disabled=true;clearTimeout(timer);renderPreview();timer=setTimeout(convert,250);}
async function convert(){if(!scene||!dialog.open)return;controller?.abort();controller=new AbortController();const current=++epoch;$('drawing-status').textContent='Αναγνώριση τοίχων και κλειστών χώρων…';
 try{const cmPerSourceUnit=scene.kind==='dwg'?Number($('drawing-unit').value):Number($('drawing-scale').value)*2.54/72,options={layers:[...$('drawing-layers').querySelectorAll('input:checked')].map(i=>i.value),crop,cmPerSourceUnit,heightM:Number($('drawing-height').value),closeGapM:Number($('drawing-gap').value),minRoomM2:Number($('drawing-room-min').value),title:file.name.replace(/\.[^.]+$/,'')};if(!Number.isFinite(options.heightM)||options.heightM<.2||options.heightM>100)throw Error('Δώσε ύψος από 0,2 έως 100 m.');const data=await job('./drawing-worker.mjs',{scene,options},controller.signal);if(current!==epoch||!dialog.open)return;result=data.result;const s=result.stats;$('drawing-count').textContent=`${s.rooms} χώροι · ${s.walls} τοίχοι · ${s.doors} πόρτες · ${s.windows} παράθυρα`;$('drawing-warnings').innerHTML=result.warnings.map(w=>`<li>${esc(w)}</li>`).join('');$('drawing-status').textContent='Έτοιμη η προεπισκόπηση · έλεγξε σχήμα και κλίμακα πριν από την εισαγωγή.';$('drawing-apply').disabled=false;dialog.dataset.convertMs=data.ms.toFixed(1);renderPreview();}catch(error){if(error.name!=='AbortError'&&current===epoch)$('drawing-status').textContent=error.message;}
}
async function read(page=1){terminate();controller=new AbortController();const current=++epoch;result=null;$('drawing-apply').disabled=true;$('drawing-status').textContent='Ανάγνωση '+file.name+' στη συσκευή…';
 try{if(file.size>30_000_000)throw Error('Μέγιστο αρχείο 30 MB. Εξήγαγε μία κάτοψη σε μικρότερο αρχείο.');const start=performance.now();const data=await file.arrayBuffer();if(current!==epoch)return;buffer=data;const pdf=new TextDecoder().decode(new Uint8Array(data,0,Math.min(8,data.byteLength))).startsWith('%PDF');scene=pdf?(await(await import('./pdf-drawing.mjs')).readPDF(data,page,controller.signal)):(await job('./dwg-worker.mjs',{buffer:data},controller.signal)).result;if(current!==epoch||!dialog.open)return;dialog.dataset.readMs=(performance.now()-start).toFixed(1);
  $('drawing-page-row').hidden=!pdf;$('drawing-page').innerHTML=Array.from({length:Math.min(200,scene.pages||1)},(_,n)=>`<option value="${n+1}" ${n+1===page?'selected':''}>Σελίδα ${n+1}</option>`).join('');$('drawing-unit-row').hidden=pdf;$('drawing-scale-row').hidden=!pdf;$('drawing-unit').value=String(scene.cmPerSourceUnit||0);
  $('drawing-layers').innerHTML=scene.layers.map(l=>`<label><input type="checkbox" value="${esc(l.name)}" ${l.recommended?'checked':''}><span>${esc(l.name)} <small>(${l.count})</small></span></label>`).join('');$('drawing-region').innerHTML=scene.regions.map((r,n)=>`<option value="${n}">Κάτοψη ${n+1}</option>`).join('')+'<option value="-1">Ολόκληρο αρχείο / σελίδα</option>';baseCrop=scene.regions[0]||scene.bounds;crop={...baseCrop};setPreview(false);await convert();
 }catch(error){if(error.name!=='AbortError'&&current===epoch)$('drawing-status').textContent=error.message;}
}
export function openDrawingImport(input,apply){create();terminate();file=input;scene=result=null;onApply=apply;$('drawing-name').textContent=input.name;$('drawing-count').textContent='';$('drawing-warnings').innerHTML='';$('drawing-scale').value='';dialog.showModal();read();}
