import {worldRings,polygonBounds,validOutline,contains} from './geometry.mjs';
import {doorOnWall,openingLine} from './architecture.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dialog,worker,controller,epoch=0,scene,file,buffer,result,baseCrop,crop,onApply,timer;
let mapping,reviewView,selectedId,reviewTool='select',history=[],edited=false,pendingOptions=false,pendingPage=null;
const $=id=>document.getElementById(id);
const typeName=i=>i.floorOnly?'Δάπεδο':({room:'Χώρος',wall:'Τοίχος',door:'Πόρτα',window:'Παράθυρο'}[i.type]||i.type);
export function reviewOutline(item,rings){
 const angle=item.rotation*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),local=rings.map(r=>r.map(p=>({x:p.x*c+p.y*s,y:-p.x*s+p.y*c}))),b=polygonBounds(local);
 if(b.w<8||b.h<8)throw Error('Το περίγραμμα είναι πολύ μικρό.');
 const outline=local.map(r=>r.map(p=>({x:(p.x-b.x)/b.w,y:(p.y-b.y)/b.h})));
 const edges=local.flatMap((ring,r)=>ring.map((a,n)=>({a,b:ring[(n+1)%ring.length],r,n,size:ring.length}))),epsilon=Math.max(b.w,b.h)*1e-9;
 const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
 const touching=(a,b,p)=>Math.abs(cross(a,b,p))<epsilon&&p.x>=Math.min(a.x,b.x)-epsilon&&p.x<=Math.max(a.x,b.x)+epsilon&&p.y>=Math.min(a.y,b.y)-epsilon&&p.y<=Math.max(a.y,b.y)+epsilon;
 const crossing=edges.some((e,n)=>edges.slice(n+1).some(f=>{if(e.r===f.r&&(Math.abs(e.n-f.n)===1||Math.abs(e.n-f.n)===e.size-1))return false;const x=cross(e.a,e.b,f.a),y=cross(e.a,e.b,f.b),u=cross(f.a,f.b,e.a),v=cross(f.a,f.b,e.b);return x*y<0&&u*v<0||touching(e.a,e.b,f.a)||touching(e.a,e.b,f.b)||touching(f.a,f.b,e.a)||touching(f.a,f.b,e.b);}));
 if(!validOutline(outline)||crossing||local.slice(1).some(r=>r.some(p=>!contains([local[0]],p))))throw Error('Οι πλευρές τέμνονται ή το περίγραμμα δεν είναι έγκυρο.');
 const cx=(b.x+b.w/2)*c-(b.y+b.h/2)*s,cy=(b.x+b.w/2)*s+(b.y+b.h/2)*c;
 return {...item,x:cx-b.w/2,y:cy-b.h/2,w:b.w,h:b.h,outline};
}
export function reviewSize(item,{width,length,height,label,floorOnly},cmPerUnit=1){
 if([width,length,height].some(n=>!Number.isFinite(n)||n<=0||n>100000)||height<20||height>10000||cmPerUnit<=0)throw Error('Δώσε θετικές διαστάσεις έως 1000 m και ύψος από 0,2 έως 100 m.');
 const w=width/cmPerUnit,h=length/cmPerUnit,cx=item.x+item.w/2,cy=item.y+item.h/2;
 if(w<8||h<8||w>100000||h>100000)throw Error('Οι διαστάσεις ξεπερνούν τα όρια του επεξεργάσιμου σχεδίου.');
 return {...item,x:cx-w/2,y:cy-h/2,w,h,heightCm:height,label:String(label).slice(0,100),...(item.type==='room'?{floorOnly:!!floorOnly}:{})};
}
export function reviewOpening(plan,type,point,id,template){
 const cm=plan.measurement?.cmPerUnit||1,w=template?.w||90/cm,h=template?.h||(type==='door'?w:14/cm),base={id,type,x:point.x-w/2,y:point.y-h/2,w,h,rotation:0,label:type==='door'?'Πόρτα':'Παράθυρο',number:'',color:type==='door'?'#3686b4':'#8dc9dc',floor:plan.activeFloor,heightCm:type==='door'?210:120,locked:false,hidden:false,...template};
 let best;
 for(const room of plan.items.filter(i=>['room','wall'].includes(i.type)&&!i.floorOnly)){
  const match=doorOnWall(type==='window'?{...base,h:0}:base,room,point,cm);if(!match)continue;
  const positioned={...base,...match,...(type==='window'?{y:match.y-h/2}:{})},[a,b]=openingLine(positioned,1),distance=Math.hypot((a.x+b.x)/2-point.x,(a.y+b.y)/2-point.y);
  if(!best||distance<best.distance)best={item:positioned,distance};
 }
 if(!best||best.distance*cm>100)throw Error('Πάτησε κοντά σε έναν τοίχο. Τα περιγράμματα δαπέδου χρειάζονται πρώτα επιβεβαίωση τοίχων.');
 return best.item;
}
export function reviewAttached(items,roomId,cmPerUnit=1){
 const room=items.find(i=>i.id===roomId);return items.map(item=>{
  if(item.attachment?.roomId!==roomId)return item;
  const match=doorOnWall(item.type==='window'?{...item,h:0}:item,room,null,cmPerUnit,item.attachment);
  if(!match)throw Error('Το νέο όριο είναι πολύ μικρό για ένα συνδεδεμένο άνοιγμα.');
  return {...item,...match,...(item.type==='window'?{y:match.y-item.h/2}:{})};
 });
}
function terminate(){worker?.terminate();worker=null;controller?.abort();controller=null;clearTimeout(timer);}
function job(url,data,signal){return new Promise((resolve,reject)=>{const w=new Worker(new URL(url,import.meta.url),{type:'module'});worker=w;const timeout=setTimeout(()=>finish(Error('Η μετατροπή ξεπέρασε τα 45 δευτερόλεπτα. Διάλεξε μικρότερο αρχείο/περιοχή.')),45000);function finish(error,value){clearTimeout(timeout);signal?.removeEventListener('abort',abort);w.terminate();if(worker===w)worker=null;error?reject(error):resolve(value);}const abort=()=>finish(new DOMException('Ακυρώθηκε','AbortError'));signal?.addEventListener('abort',abort,{once:true});w.onmessage=e=>e.data.error?finish(Error(e.data.error)):finish(null,e.data);w.onerror=e=>finish(Error(e.message||'Δεν ξεκίνησε ο αποκωδικοποιητής.'));w.postMessage(data);});}
function create(){if(dialog)return;dialog=document.createElement('dialog');dialog.id='drawing-dialog';dialog.innerHTML=`<div class="drawing-heading"><div><span class="eyebrow">ΕΙΣΑΓΩΓΗ ΚΑΤΟΨΗΣ</span><h2 id="drawing-name"></h2></div><button id="drawing-close" aria-label="Ακύρωση εισαγωγής">×</button></div><p id="drawing-status" role="status">Ανάγνωση αρχείου…</p><div class="drawing-layout"><div class="drawing-view"><div class="drawing-tabs"><button id="drawing-source" aria-pressed="true">Πρωτότυπο PDF / DWG</button><button id="drawing-result" aria-pressed="false">Επεξεργάσιμο αποτέλεσμα</button></div><svg id="drawing-preview" aria-label="Προεπισκόπηση σχεδίου" tabindex="0"></svg><p class="small">Οι καρτέλες αλλάζουν μόνο την προεπισκόπηση. Εισάγεται πάντα το επεξεργάσιμο αποτέλεσμα. Σύρε στο πρωτότυπο για επιλογή περιοχής.</p></div><div class="drawing-options"><label id="drawing-page-row" hidden>Σελίδα PDF<select id="drawing-page"></select></label><label>Κάτοψη / περιοχή<select id="drawing-region"></select></label><button id="drawing-all" class="wide-button">Ολόκληρη επιλεγμένη περιοχή</button><label id="drawing-unit-row">Μονάδα DWG<select id="drawing-unit"><option value="0">Χωρίς γνωστή κλίμακα</option><option value="100">Μέτρα (m)</option><option value="1">Εκατοστά (cm)</option><option value="0.1">Χιλιοστά (mm)</option><option value="2.54">Ίντσες</option><option value="30.48">Πόδια</option></select></label><label id="drawing-scale-row" hidden>Κλίμακα PDF · 1 προς<input id="drawing-scale" type="number" placeholder="π.χ. 100 · επιβεβαίωσε στο σχέδιο" min="1" max="10000" inputmode="decimal"></label><label>Ύψος τοίχων / χώρων (m)<input id="drawing-height" type="number" value="2.8" min="0.2" max="100" step="0.1" inputmode="decimal"></label><details class="drawing-advanced"><summary>Αναγνώριση χώρων</summary><label>Μέγιστο κενό για κλειστό χώρο (m)<input id="drawing-gap" type="number" value="8" min="0" max="20" step="0.1"></label><label>Ελάχιστο εμβαδόν χώρου (m²)<input id="drawing-room-min" type="number" value="2" min="0.1" max="100" step="0.1"></label><p class="small">Μείωσε το κενό για λιγότερες υποθετικές συνδέσεις. Τα μη κλειστά τμήματα παραμένουν τοίχοι.</p></details><details class="drawing-layers" open><summary>Layers / ομάδες γραμμών</summary><div id="drawing-layers"></div></details></div></div><p id="drawing-count" role="status"></p><ul id="drawing-warnings"></ul><div class="drawing-actions"><button id="drawing-cancel">Ακύρωση</button><button id="drawing-apply" class="primary" disabled>Εισαγωγή επεξεργάσιμου σχεδίου</button></div>`;document.body.append(dialog);
 $('drawing-close').onclick=$('drawing-cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{epoch++;terminate();scene=result=buffer=file=null;mapping=reviewView=null;history=[];selectedId=null;edited=pendingOptions=false;$('drawing-preview').replaceChildren();$('drawing-layers').replaceChildren();});
 $('drawing-source').onclick=()=>setPreview(false);$('drawing-result').onclick=()=>setPreview(true);
 $('drawing-region').onchange=()=>{baseCrop=scene.regions[Number($('drawing-region').value)]||scene.bounds;crop={...baseCrop};schedule();};$('drawing-all').onclick=()=>{crop={...baseCrop};schedule();};
 for(const id of ['drawing-unit','drawing-scale','drawing-height','drawing-gap','drawing-room-min'])$(id).oninput=schedule;
 $('drawing-layers').onchange=schedule;$('drawing-page').onchange=()=>{const page=Number($('drawing-page').value);if(edited&&result){pendingPage=page;$('drawing-page').value=String(scene.pageNumber);pendingOptions=true;$('drawing-reviewed').checked=false;$('drawing-recalculate').hidden=false;$('drawing-status').textContent='Η αλλαγή σελίδας αντικαθιστά τις διορθώσεις. Πάτησε επαναμετατροπή για συνέχεια.';syncReviewControls(false);}else read(page);};
 const rasterOptions=document.createElement('label');rasterOptions.id='drawing-raster-row';rasterOptions.hidden=true;rasterOptions.innerHTML='Ευαισθησία εικόνας<input id="drawing-raster-threshold" type="range" min="80" max="220" value="210" step="5"><small>Μεγαλύτερη τιμή: περισσότερες αχνές γραμμές.</small>';$('drawing-height').closest('label').after(rasterOptions);$('drawing-raster-threshold').oninput=schedule;
 const rasterFilter=document.createElement('label');rasterFilter.id='drawing-raster-filter';rasterFilter.className='check-label';rasterFilter.hidden=true;rasterFilter.innerHTML='<input id="drawing-skip-small" type="checkbox" checked><span>Παράλειψη μικρών σχημάτων χωρίς όνομα χώρου</span>';dialog.querySelector('.drawing-advanced').append(rasterFilter);$('drawing-skip-small').onchange=schedule;
 $('drawing-apply').onclick=()=>{if(!result||pendingOptions||scene.raster&&!$('drawing-reviewed').checked)return;onApply(result.plan);dialog.close();};
 const svg=$('drawing-preview');let drag;
 const point=e=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());};
 svg.onpointerdown=e=>{if(!scene||$('drawing-source').getAttribute('aria-pressed')!=='true')return;drag={id:e.pointerId,start:point(e)};svg.setPointerCapture(e.pointerId);};
 svg.onpointermove=e=>{if(drag?.id!==e.pointerId)return;const p=point(e);crop={x:Math.min(p.x,drag.start.x),y:Math.min(p.y,drag.start.y),w:Math.abs(p.x-drag.start.x),h:Math.abs(p.y-drag.start.y)};const r=$('drawing-crop');if(r)for(const key of ['x','y','w','h'])r.setAttribute(key,crop[key]);};
 svg.onpointerup=e=>{if(drag?.id!==e.pointerId)return;drag=null;svg.releasePointerCapture(e.pointerId);if(crop.w<baseCrop.w*.01||crop.h<baseCrop.h*.01)crop={...baseCrop};schedule();};svg.onpointercancel=()=>{drag=null;crop={...baseCrop};schedule();};
 setupReview();
}
function setPreview(converted){$('drawing-source').setAttribute('aria-pressed',!converted);$('drawing-result').setAttribute('aria-pressed',converted);renderPreview();}
function setupReview(){
 const toolbar=document.createElement('div');toolbar.id='drawing-review-tools';toolbar.hidden=true;toolbar.innerHTML=`<div class="drawing-review-buttons" role="toolbar" aria-label="Διόρθωση μετατροπής"><button data-review-tool="select" aria-pressed="true">Επιλογή</button><button data-review-tool="pan" aria-pressed="false">Μετακίνηση όψης</button><details id="drawing-add-menu"><summary>Προσθήκη / περίγραμμα</summary><div class="drawing-review-buttons"><button data-review-tool="room" aria-pressed="false">＋ Χώρος</button><button data-review-tool="wall" aria-pressed="false">＋ Τοίχος</button><button data-review-tool="door" aria-pressed="false">＋ Πόρτα</button><button data-review-tool="window" aria-pressed="false">＋ Παράθυρο</button><button data-review-tool="vertex" aria-pressed="false">＋ Κορυφή χώρου</button></div></details></div><div class="drawing-review-buttons"><label class="check-label"><input id="drawing-overlay" type="checkbox" checked>Πρωτότυπο από κάτω</label><button id="drawing-review-out" aria-label="Σμίκρυνση προεπισκόπησης">−</button><button id="drawing-review-in" aria-label="Μεγέθυνση προεπισκόπησης">＋</button><button id="drawing-review-fit">Ολόκληρο</button><button id="drawing-review-undo" disabled>Αναίρεση διόρθωσης</button></div>`;
 $('drawing-preview').before(toolbar);$('drawing-preview').nextElementSibling.id='drawing-preview-help';
 const panel=document.createElement('section');panel.id='drawing-review-panel';panel.hidden=true;panel.innerHTML=`<h3>Έλεγχος στοιχείων</h3><label>Επιλογή στοιχείου<select id="drawing-review-item"><option value="">Πάτησε στο σχέδιο</option></select></label><div id="drawing-review-fields" hidden><label>Όνομα<input id="drawing-review-label" maxlength="100"></label><div class="drawing-review-size"><label>Πλάτος<input id="drawing-review-width" type="number" min="0.01" step="0.01" inputmode="decimal"></label><label>Μήκος<input id="drawing-review-length" type="number" min="0.01" step="0.01" inputmode="decimal"></label><label>Ύψος<input id="drawing-review-height" type="number" min="0.01" step="0.01" inputmode="decimal"></label><label>Μονάδα<select id="drawing-review-unit"><option value="100">m</option><option value="1">cm</option></select></label></div><label id="drawing-review-wall-row" class="check-label"><input id="drawing-review-walls" type="checkbox">Περιμετρικοί τοίχοι στη 3D όψη</label><button id="drawing-review-delete" class="danger wide-button">Διαγραφή στοιχείου</button></div><p id="drawing-review-error" role="status"></p><p class="small">Μεγέθυνε για έλεγχο. Σύρε ένα στοιχείο ή τις κορυφές του επιλεγμένου χώρου. Οι αλλαγές γίνονται στο σχέδιο που θα εισαχθεί.</p></section>`;
 dialog.querySelector('.drawing-options').prepend(panel);
 const confirmation=document.createElement('label');confirmation.id='drawing-confirm-row';confirmation.className='check-label';confirmation.hidden=true;confirmation.innerHTML='<input id="drawing-reviewed" type="checkbox"><span>Έλεγξα την κάτοψη, την κλίμακα και τα ανοίγματα στο επεξεργάσιμο αποτέλεσμα.</span>';dialog.querySelector('.drawing-actions').before(confirmation);
 const recalculate=document.createElement('button');recalculate.id='drawing-recalculate';recalculate.hidden=true;recalculate.textContent='Επαναμετατροπή · αντικατάσταση διορθώσεων';$('drawing-count').before(recalculate);recalculate.onclick=()=>{edited=pendingOptions=false;if(pendingPage!==null){const page=pendingPage;pendingPage=null;read(page);}else schedule();};
 toolbar.querySelectorAll('[data-review-tool]').forEach(button=>button.onclick=()=>{reviewTool=button.dataset.reviewTool;toolbar.querySelectorAll('[data-review-tool]').forEach(b=>b.setAttribute('aria-pressed',b===button));$('drawing-add-menu').open=false;syncReviewControls();});
 $('drawing-overlay').onchange=renderPreview;$('drawing-reviewed').onchange=()=>syncReviewControls(false);$('drawing-review-item').onchange=()=>{selectedId=$('drawing-review-item').value;syncReviewControls();renderPreview();};
 $('drawing-review-unit').onchange=()=>syncReviewControls();
 const update=()=>{const item=result?.plan.items.find(i=>i.id===selectedId);if(!item)return;const factor=Number($('drawing-review-unit').value);editReview(()=>{if(item.type==='room'&&!$('drawing-review-walls').checked&&result.plan.items.some(i=>i.attachment?.roomId===item.id))throw Error('Μετακίνησε ή διέγραψε πρώτα τα συνδεδεμένα ανοίγματα.');Object.assign(item,reviewSize(item,{width:Number($('drawing-review-width').value)*factor,length:Number($('drawing-review-length').value)*factor,height:Number($('drawing-review-height').value)*factor,label:$('drawing-review-label').value,floorOnly:!$('drawing-review-walls').checked},result.plan.measurement?.cmPerUnit||1));result.plan.items=reviewAttached(result.plan.items,item.id,result.plan.measurement?.cmPerUnit||1);},false);};
 for(const id of ['drawing-review-label','drawing-review-width','drawing-review-length','drawing-review-height','drawing-review-walls'])$(id).onchange=update;
 $('drawing-review-delete').onclick=()=>editReview(()=>{result.plan.items=result.plan.items.filter(i=>i.id!==selectedId&&i.attachment?.roomId!==selectedId);selectedId=null;});
 $('drawing-review-undo').onclick=()=>{if(!history.length)return;result.plan.items=history.pop();selectedId=null;$('drawing-reviewed').checked=false;syncReviewControls();renderPreview();};
 $('drawing-review-fit').onclick=()=>{reviewView=reviewBounds();renderPreview();};$('drawing-review-in').onclick=()=>zoomReview(.7);$('drawing-review-out').onclick=()=>zoomReview(1/.7);
 reviewPointers();
}
function reviewBounds(){const items=result?.plan.items||[],rings=items.flatMap(worldRings);if(!rings.length)return {x:50,y:50,w:1000,h:700};const b=polygonBounds(rings),pad=Math.max(b.w,b.h)*.06;return {x:b.x-pad,y:b.y-pad,w:b.w+pad*2,h:b.h+pad*2};}
function resetReview(cm){mapping={...crop,unit:cm||1000/Math.max(crop.w,crop.h)};reviewView=reviewBounds();history=[];selectedId=null;reviewTool='select';edited=pendingOptions=false;$('drawing-reviewed').checked=false;$('drawing-recalculate').hidden=true;dialog.querySelectorAll('[data-review-tool]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.reviewTool===reviewTool));syncReviewControls();}
function syncReviewControls(fill=true){
 const converted=$('drawing-result').getAttribute('aria-pressed')==='true',ready=!!result,item=result?.plan.items.find(i=>i.id===selectedId);
 $('drawing-review-tools').hidden=!converted||!ready;$('drawing-review-panel').hidden=!converted||!ready;$('drawing-confirm-row').hidden=!scene?.raster||!ready||!converted;
 $('drawing-review-fields').hidden=!item;$('drawing-review-undo').disabled=!history.length;$('drawing-apply').disabled=!ready||!result.plan.items.length||pendingOptions||!!scene?.raster&&!$('drawing-reviewed').checked;
 $('drawing-review-item').innerHTML='<option value="">Πάτησε στο σχέδιο</option>'+(result?.plan.items||[]).map((i,n)=>`<option value="${esc(i.id)}" ${i.id===selectedId?'selected':''}>${esc(typeName(i)+' · '+(i.label||n+1))}</option>`).join('');
 if(item&&fill){const cm=result.plan.measurement?.cmPerUnit||1,factor=Number($('drawing-review-unit').value);$('drawing-review-label').value=item.label;$('drawing-review-width').value=+(item.w*cm/factor).toFixed(3);$('drawing-review-length').value=+(item.h*cm/factor).toFixed(3);$('drawing-review-height').value=+((item.heightCm||280)/factor).toFixed(3);$('drawing-review-walls').checked=!item.floorOnly;$('drawing-review-wall-row').hidden=item.type!=='room';}
 $('drawing-preview-help').textContent=converted?({select:'Πάτησε ένα στοιχείο. Σύρε για θέση ή τις κορυφές για σχήμα. Δύο δάχτυλα: pan / zoom.',pan:'Σύρε για μετακίνηση όψης. Ροδέλα ή δύο δάχτυλα για zoom.',room:'Σύρε ένα ορθογώνιο για νέο χώρο. Μετά μετακίνησε τις κορυφές για το σωστό περίγραμμα.',wall:'Σύρε από την αρχή έως το τέλος του νέου τοίχου.',door:'Πάτησε πάνω σε τοίχο για πόρτα. Η θέση και το άνοιγμα είναι επεξεργάσιμα.',window:'Πάτησε πάνω σε τοίχο για παράθυρο.',vertex:'Επίλεξε έναν χώρο και πάτησε κοντά στην πλευρά όπου χρειάζεται νέα κορυφή.'}[reviewTool]):'Το πρωτότυπο είναι αναφορά. Σύρε για επιλογή περιοχής. Εισάγεται πάντα το επεξεργάσιμο αποτέλεσμα.';
 if(result){const items=result.plan.items,s={rooms:items.filter(i=>i.type==='room'&&!i.floorOnly).length,surfaces:items.filter(i=>i.floorOnly).length,walls:items.filter(i=>i.type==='wall').length,doors:items.filter(i=>i.type==='door').length,windows:items.filter(i=>i.type==='window').length};result.stats={...result.stats,...s};$('drawing-count').textContent=`${s.rooms} χώροι · ${s.surfaces} δάπεδα χωρίς τοίχους · ${s.walls} τοίχοι · ${s.doors} πόρτες · ${s.windows} παράθυρα${edited?' · με διορθώσεις':''}`;}
}
function editReview(action,fill=true){if(!result)return;const before=structuredClone(result.plan.items);try{action();if(JSON.stringify(before)!==JSON.stringify(result.plan.items)){history.push(before);if(history.length>30)history.shift();edited=true;$('drawing-reviewed').checked=false;}$('drawing-review-error').textContent='';syncReviewControls(fill);renderPreview();}catch(error){result.plan.items=before;$('drawing-review-error').textContent=error.message;}}
function renderReviewPreview(svg){
 const b=reviewView||reviewBounds();svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);svg.dataset.review='true';
 const original=$('drawing-overlay').checked&&scene.preview&&mapping?`<image href="${scene.preview}" x="${100-mapping.x*mapping.unit}" y="${100-mapping.y*mapping.unit}" width="${scene.bounds.w*mapping.unit}" height="${scene.bounds.h*mapping.unit}" opacity=".65"/>`:'';
 const path=i=>worldRings(i).map(r=>r.map((p,n)=>`${n?'L':'M'}${p.x} ${p.y}`).join(' ')+' Z').join(' '),radius=b.w/Math.max(250,svg.clientWidth)*8;
 svg.innerHTML=original+result.plan.items.map(i=>`<path data-review-id="${esc(i.id)}" d="${path(i)}" role="button" tabindex="0" aria-label="${esc(typeName(i)+' · '+i.label)}" fill="${i.type==='room'?(i.floorOnly?'#dca347':'#32a68d'):i.type==='wall'?'#db554a':'#3686b4'}" fill-opacity="${i.type==='room'?'.12':'.38'}" fill-rule="evenodd" stroke="${i.id===selectedId?'#bd247b':i.floorOnly?'#b97f1e':i.type==='room'?'#167a78':i.type==='wall'?'#bb483e':'#237bba'}" stroke-width="${i.id===selectedId?3:2}" vector-effect="non-scaling-stroke" ${i.floorOnly?'stroke-dasharray="8 5"':''}/>`).join('');
 const item=result.plan.items.find(i=>i.id===selectedId);if(item?.type==='room'&&reviewTool==='select')svg.innerHTML+=worldRings(item).map((ring,r)=>ring.map((p,n)=>`<circle data-review-vertex="${r},${n}" cx="${p.x}" cy="${p.y}" r="${radius}" fill="white" stroke="#bd247b" stroke-width="2" vector-effect="non-scaling-stroke" role="button" tabindex="0" aria-label="Κορυφή ${r+1}.${n+1}"/>`).join('')).join('');
 syncReviewControls(false);
}
function zoomReview(factor,p){if(!result)return;const b=reviewView||reviewBounds(),point=p||{x:b.x+b.w/2,y:b.y+b.h/2},w=Math.max(20,Math.min(reviewBounds().w*10,b.w*factor)),ratio=w/b.w;reviewView={x:point.x-(point.x-b.x)*ratio,y:point.y-(point.y-b.y)*ratio,w,h:b.h*ratio};renderPreview();}
export function reviewRectangle(type,a,b,rotation,id,floor,heightCm=280,cmPerUnit=1){
 const angle=rotation*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),local=p=>({x:p.x*c+p.y*s,y:-p.x*s+p.y*c});
 const p=local(a),q=local(b),x=Math.min(p.x,q.x),y=Math.min(p.y,q.y),w=Math.abs(p.x-q.x),h=Math.abs(p.y-q.y);
 if(type==='wall'){const length=Math.hypot(b.x-a.x,b.y-a.y);if(length*cmPerUnit<10)throw Error('Σύρε τουλάχιστον 10 cm για τοίχο.');return {id,type,x:(a.x+b.x)/2-length/2,y:(a.y+b.y)/2-7/cmPerUnit,w:length,h:14/cmPerUnit,rotation:Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,label:'Τοίχος',number:'',color:'#53636c',floor,heightCm,hidden:false,locked:false};}
 if(w*cmPerUnit<20||h*cmPerUnit<20)throw Error('Σύρε ένα μεγαλύτερο περίγραμμα ή δώσε διαστάσεις μετά την προσθήκη.');
 const cx=(x+w/2)*c-(y+h/2)*s,cy=(x+w/2)*s+(y+h/2)*c;
 return {id,type:'room',x:cx-w/2,y:cy-h/2,w,h,rotation,label:'Νέος χώρος',number:'',color:'#e3ece9',floor,heightCm,hidden:false,locked:false};
}
function reviewPointers(){
 const svg=$('drawing-preview'),source={down:svg.onpointerdown,move:svg.onpointermove,up:svg.onpointerup,cancel:svg.onpointercancel},pointers=new Map();let drag,gesture;
 const converted=()=>!!result&&$('drawing-result').getAttribute('aria-pressed')==='true';
 const at=(clientX,clientY,matrix=svg.getScreenCTM().inverse())=>{const p=svg.createSVGPoint();p.x=clientX;p.y=clientY;return p.matrixTransform(matrix);};
 const center=()=>{const [a,b]=[...pointers.values()];return {x:(a.x+b.x)/2,y:(a.y+b.y)/2,d:Math.hypot(a.x-b.x,a.y-b.y)};};
 const changed=before=>{if(JSON.stringify(before)!==JSON.stringify(result.plan.items)){history.push(before);if(history.length>30)history.shift();edited=true;$('drawing-reviewed').checked=false;}syncReviewControls();renderPreview();};
 svg.onpointerdown=e=>{
  if(!converted()){source.down(e);return;}e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});svg.setPointerCapture(e.pointerId);
  if(pointers.size===2){if(drag?.before)result.plan.items=drag.before;drag=null;gesture={...center(),view:{...reviewView},matrix:svg.getScreenCTM().inverse()};return;}
  if(pointers.size!==1)return;
  const point=at(e.clientX,e.clientY),matrix=svg.getScreenCTM().inverse();
  if(reviewTool==='vertex'){const item=result.plan.items.find(i=>i.id===selectedId);if(item?.type!=='room'){$('drawing-review-error').textContent='Διάλεξε πρώτα έναν χώρο από το σχέδιο ή τη λίστα.';return;}editReview(()=>{const rings=worldRings(item);let best;for(const [r,ring]of rings.entries())for(let n=0;n<ring.length;n++){const a=ring[n],b=ring[(n+1)%ring.length],dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy,t=l2?Math.max(.05,Math.min(.95,((point.x-a.x)*dx+(point.y-a.y)*dy)/l2)):0,p={x:a.x+dx*t,y:a.y+dy*t},distance=Math.hypot(p.x-point.x,p.y-point.y);if(!best||distance<best.distance)best={r,n,p,distance};}if(!best||best.distance>reviewView.w/Math.max(250,svg.clientWidth)*24)throw Error('Πάτησε κοντά σε μια πλευρά του επιλεγμένου χώρου.');rings[best.r].splice(best.n+1,0,best.p);Object.assign(item,reviewOutline(item,rings));reviewTool='select';dialog.querySelector('[data-review-tool="select"]').click();});return;}
  if(['door','window'].includes(reviewTool)){editReview(()=>{const item=reviewOpening(result.plan,reviewTool,point,crypto.randomUUID());result.plan.items.push(item);selectedId=item.id;});return;}
  if(['room','wall'].includes(reviewTool)){drag={id:e.pointerId,kind:'draw',point,matrix,last:point};return;}
  const vertex=e.target.dataset.reviewVertex,id=e.target.closest('[data-review-id]')?.dataset.reviewId;
  if(vertex&&selectedId)drag={id:e.pointerId,kind:'vertex',vertex:vertex.split(',').map(Number),point,matrix,before:structuredClone(result.plan.items)};
  else if(id&&reviewTool==='select'){selectedId=id;drag={id:e.pointerId,kind:'item',point,matrix,before:structuredClone(result.plan.items)};}
  else{drag={id:e.pointerId,kind:'pan',point,matrix,view:{...reviewView}};if(reviewTool==='select')selectedId=null;}
  syncReviewControls();renderPreview();
 };
 svg.onpointermove=e=>{
  if(!converted()){source.move(e);return;}if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(gesture&&pointers.size===2){const now=center(),anchor=at(gesture.x,gesture.y,gesture.matrix),current=at(now.x,now.y,gesture.matrix),ratio=Math.max(.1,Math.min(10,gesture.d/Math.max(1,now.d))),b=gesture.view;reviewView={x:anchor.x-(current.x-b.x)*ratio,y:anchor.y-(current.y-b.y)*ratio,w:b.w*ratio,h:b.h*ratio};renderPreview();return;}
  if(drag?.id!==e.pointerId)return;const p=at(e.clientX,e.clientY,drag.matrix),dx=p.x-drag.point.x,dy=p.y-drag.point.y;
  if(drag.kind==='pan'){reviewView={...drag.view,x:drag.view.x-dx,y:drag.view.y-dy};renderPreview();return;}
  if(drag.kind==='draw'){drag.last=p;renderPreview();try{const item=reviewRectangle(reviewTool,drag.point,p,scene.rasterCache?.angle||0,'draft',result.plan.activeFloor);const ns='http://www.w3.org/2000/svg',path=document.createElementNS(ns,'path');path.setAttribute('d',worldRings(item)[0].map((p,n)=>`${n?'L':'M'}${p.x} ${p.y}`).join(' ')+' Z');path.setAttribute('fill','#167a7822');path.setAttribute('stroke','#bd247b');path.setAttribute('stroke-width','2');path.setAttribute('vector-effect','non-scaling-stroke');svg.append(path);}catch{}return;}
  const base=drag.before.find(i=>i.id===selectedId),item=result.plan.items.find(i=>i.id===selectedId);if(!base||!item)return;
  const trial=structuredClone(result.plan.items);
  try{if(drag.kind==='vertex'){const rings=worldRings(base),[r,n]=drag.vertex;rings[r][n]={x:rings[r][n].x+dx,y:rings[r][n].y+dy};Object.assign(item,reviewOutline(base,rings));}
   else if(['door','window'].includes(base.type))Object.assign(item,reviewOpening(result.plan,base.type,{x:base.x+base.w/2+dx,y:base.y+base.h/2+dy},base.id,base));
   else Object.assign(item,{x:base.x+dx,y:base.y+dy});
   result.plan.items=reviewAttached(result.plan.items,item.id,result.plan.measurement?.cmPerUnit||1);$('drawing-review-error').textContent='';syncReviewControls();renderPreview();
  }catch(error){result.plan.items=trial;$('drawing-review-error').textContent=error.message;}
 };
 svg.onpointerup=e=>{if(!converted()){source.up(e);return;}pointers.delete(e.pointerId);if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);if(gesture){gesture=null;drag=null;return;}if(drag?.id!==e.pointerId)return;
  const finished=drag;drag=null;
  if(finished.kind==='draw')editReview(()=>{const item=reviewRectangle(reviewTool,finished.point,finished.last,scene.rasterCache?.angle||0,crypto.randomUUID(),result.plan.activeFloor,Number($('drawing-height').value)*100,result.plan.measurement?.cmPerUnit||1);result.plan.items.push(item);selectedId=item.id;});else if(finished.before)changed(finished.before);
 };
 svg.onpointercancel=e=>{pointers.delete(e.pointerId);if(!converted()){source.cancel(e);return;}if(drag?.before)result.plan.items=drag.before;drag=gesture=null;syncReviewControls();renderPreview();};
 svg.onwheel=e=>{if(!converted())return;e.preventDefault();zoomReview(Math.exp(Math.max(-.5,Math.min(.5,e.deltaY*.001))),at(e.clientX,e.clientY));};
 svg.onkeydown=e=>{if(!converted())return;const id=e.target.dataset.reviewId;if(id&&['Enter',' '].includes(e.key)){e.preventDefault();selectedId=id;syncReviewControls();renderPreview();return;}if(e.key==='Delete'&&selectedId){e.preventDefault();$('drawing-review-delete').click();}if(e.key.toLowerCase()==='z'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('drawing-review-undo').click();}};
}
function renderPreview(){if(!scene)return;const svg=$('drawing-preview'),converted=$('drawing-result').getAttribute('aria-pressed')==='true';
 if(converted&&result){renderReviewPreview(svg);return;}
 syncReviewControls(false);svg.dataset.review="false";
 const b=scene.kind==='pdf'?scene.bounds:baseCrop,selected=new Set([...$('drawing-layers').querySelectorAll('input:checked')].map(i=>i.value)),inside=p=>p.x>=b.x&&p.y>=b.y&&p.x<=b.x+b.w&&p.y<=b.y+b.h,width=Math.max(b.w,b.h)/800;svg.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);svg.innerHTML=(scene.preview?`<image href="${scene.preview}" x="0" y="0" width="${scene.bounds.w}" height="${scene.bounds.h}"/>`:scene.paths.filter(p=>p.points.every(inside)&&selected.has(p.layer)).slice(0,12000).map(p=>`<path d="${p.points.map((p,n)=>`${n?'L':'M'}${p.x} ${p.y}`).join(' ')}${p.closed?' Z':''}" fill="${p.fill||'none'}" stroke="${p.stroke||'none'}" stroke-width="${width}" opacity="${p.eligible===false?'.2':'.85'}"/>`).join(''))+`<rect id="drawing-crop" x="${crop.x}" y="${crop.y}" width="${crop.w}" height="${crop.h}" fill="none" stroke="#db822c" stroke-width="${width*2}" stroke-dasharray="${width*6}"/>`;
}
function schedule(){if(!scene)return;if(edited&&result){pendingOptions=true;$('drawing-reviewed').checked=false;$('drawing-recalculate').hidden=false;$('drawing-status').textContent='Οι ρυθμίσεις άλλαξαν. Η επαναμετατροπή αντικαθιστά τις διορθώσεις· μέχρι τότε το σχέδιο διατηρείται.';syncReviewControls(false);return;}result=null;$('drawing-apply').disabled=true;clearTimeout(timer);renderPreview();timer=setTimeout(convert,250);}
async function convert(){if(!scene||!dialog.open)return;controller?.abort();controller=new AbortController();const current=++epoch;$('drawing-status').textContent='Αναγνώριση τοίχων και κλειστών χώρων…';
 try{const cmPerSourceUnit=scene.kind==='dwg'?Number($('drawing-unit').value):Number($('drawing-scale').value)*2.54/72,options={layers:[...$('drawing-layers').querySelectorAll('input:checked')].map(i=>i.value),crop,cmPerSourceUnit,rasterThreshold:Number($('drawing-raster-threshold').value),skipSmallUnlabelled:$('drawing-skip-small').checked,heightM:Number($('drawing-height').value),closeGapM:Number($('drawing-gap').value),minRoomM2:Number($('drawing-room-min').value),title:file.name.replace(/\.[^.]+$/,'')};if(!Number.isFinite(options.heightM)||options.heightM<.2||options.heightM>100)throw Error('Δώσε ύψος από 0,2 έως 100 m.');const data=await job('./drawing-worker.mjs',{scene:{...scene,preview:undefined},options},controller.signal);if(current!==epoch||!dialog.open)return;result=data.result;if(scene.raster&&data.rasterThreshold)$('drawing-raster-threshold').value=String(data.rasterThreshold);resetReview(cmPerSourceUnit);const s=result.stats;$('drawing-count').textContent=`${s.rooms} χώροι${s.surfaces?' · '+s.surfaces+' περιγράμματα δαπέδου':''} · ${s.walls} τοίχοι · ${s.doors} πόρτες · ${s.windows} παράθυρα`;$('drawing-warnings').innerHTML=result.warnings.map(w=>`<li>${esc(w)}</li>`).join('');$('drawing-status').textContent=scene.raster?(result.quality?.partial?'Μερική μετατροπή εικόνας · έλεγξε τα περιγράμματα και τα στοιχεία που λείπουν.':'Μετατροπή από εικόνα · έλεγξε τους τοίχους πριν από την εισαγωγή.'):'Έτοιμη η προεπισκόπηση · έλεγξε σχήμα και κλίμακα πριν από την εισαγωγή.';syncReviewControls();dialog.dataset.convertMs=data.ms.toFixed(1);renderPreview();}catch(error){if(error.name!=='AbortError'&&current===epoch){result=null;$('drawing-apply').disabled=true;$('drawing-count').textContent='Δεν δημιουργήθηκε επεξεργάσιμο σχέδιο.';$('drawing-status').textContent=error.message;}}
}
async function read(page=0){terminate();controller=new AbortController();const current=++epoch;result=null;scene=null;history=[];mapping=reviewView=null;selectedId=null;edited=pendingOptions=false;pendingPage=null;$('drawing-reviewed').checked=false;$('drawing-recalculate').hidden=true;syncReviewControls(false);$('drawing-preview').replaceChildren();$('drawing-count').textContent='';$('drawing-warnings').replaceChildren();$('drawing-apply').disabled=true;$('drawing-status').textContent='Ανάγνωση '+file.name+' στη συσκευή…';
 try{if(file.size>30_000_000)throw Error('Μέγιστο αρχείο 30 MB. Εξήγαγε μία κάτοψη σε μικρότερο αρχείο.');const start=performance.now();const data=await file.arrayBuffer();if(current!==epoch)return;buffer=data;const pdf=new TextDecoder().decode(new Uint8Array(data,0,Math.min(8,data.byteLength))).startsWith('%PDF');const decoded=pdf?(await(await import('./pdf-drawing.mjs')).readPDF(data,page,controller.signal)):(await job('./dwg-worker.mjs',{buffer:data},controller.signal)).result;if(current!==epoch||!dialog.open)return;scene=decoded;dialog.dataset.readMs=(performance.now()-start).toFixed(1);
  $('drawing-page-row').hidden=!pdf;$('drawing-page').innerHTML=Array.from({length:Math.min(200,scene.pages||1)},(_,n)=>`<option value="${n+1}" ${n+1===scene.pageNumber?'selected':''}>Σελίδα ${n+1}${scene.pageChoices?.[n]?.name?' · '+esc(scene.pageChoices[n].name):''}</option>`).join('');$('drawing-unit-row').hidden=pdf;$('drawing-scale-row').hidden=!pdf;$('drawing-unit').value=String(scene.cmPerSourceUnit||0);$('drawing-raster-row').hidden=!scene.raster;$('drawing-raster-filter').hidden=!scene.raster;if(pdf)$('drawing-scale').value=scene.scaleDenominator||'';$('drawing-gap').value=scene.raster?'6':'8';
  if(scene.raster){$('drawing-status').textContent='Αναγνώριση τοίχων από την εικόνα…';const cm=scene.scaleDenominator*2.54/72,threshold=Number($('drawing-raster-threshold').value),analysis=(await job('./drawing-worker.mjs',{scene:{...scene,preview:undefined},options:{mode:'analyse',cmPerSourceUnit:cm,rasterThreshold:threshold}},controller.signal)).result;if(current!==epoch||!dialog.open)return;scene.rasterCache={angle:analysis.angle};scene.regions=analysis.regions;scene.layers.find(l=>l.name==='Τοίχοι από εικόνα').count=analysis.paths.length;}
  $('drawing-layers').innerHTML=scene.layers.map(l=>`<label><input type="checkbox" value="${esc(l.name)}" ${l.recommended?'checked':''}><span>${esc(l.name)} <small>(${l.count})</small></span></label>`).join('');$('drawing-region').innerHTML=scene.regions.map((r,n)=>`<option value="${n}">Κάτοψη ${n+1}</option>`).join('')+'<option value="-1">Ολόκληρο αρχείο / σελίδα</option>';baseCrop=scene.regions[0]||scene.bounds;crop={...baseCrop};setPreview(false);await convert();
 }catch(error){if(error.name!=='AbortError'&&current===epoch)$('drawing-status').textContent=error.message;}
}
export function openDrawingImport(input,apply){create();terminate();file=input;scene=result=null;onApply=apply;$('drawing-name').textContent=input.name;$('drawing-count').textContent='';$('drawing-warnings').innerHTML='';$('drawing-scale').value='';dialog.showModal();read();}
