import {getDocument,GlobalWorkerOptions,OPS} from './vendor/pdfjs/pdf.min.mjs';
import {drawingBounds} from './drawing-geometry.mjs';
GlobalWorkerOptions.workerSrc=new URL('./vendor/pdfjs/pdf.worker.min.mjs',import.meta.url).href;
const multiply=(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
function fittedArc(p){if(p.closed||p.fill||p.points.length<6||p.points.length>512)return null;const a=p.points[0],b=p.points[Math.floor(p.points.length/2)],c=p.points.at(-1),d=2*(a.x*(b.y-c.y)+b.x*(c.y-a.y)+c.x*(a.y-b.y));if(Math.abs(d)<1e-5)return null;const aa=a.x*a.x+a.y*a.y,bb=b.x*b.x+b.y*b.y,cc=c.x*c.x+c.y*c.y,center={x:(aa*(b.y-c.y)+bb*(c.y-a.y)+cc*(a.y-b.y))/d,y:(aa*(c.x-b.x)+bb*(a.x-c.x)+cc*(b.x-a.x))/d},radius=Math.hypot(a.x-center.x,a.y-center.y);if(radius<12||p.points.some(v=>Math.abs(Math.hypot(v.x-center.x,v.y-center.y)-radius)>radius*.035))return null;let start=Math.atan2(a.y-center.y,a.x-center.x),end=Math.atan2(c.y-center.y,c.x-center.x);if((end-start+Math.PI*2)%(Math.PI*2)>Math.PI)[start,end]=[end,start];const sweep=(end-start+Math.PI*2)%(Math.PI*2);return sweep>1.2&&sweep<1.95?{center,radius,start,end,layer:p.layer}:null;}
function lineArcs(paths){
 const nodes=new Map(),edges=[],key=(p,layer)=>layer+':'+Math.round(p.x*20)+','+Math.round(p.y*20),node=(p,layer)=>{const k=key(p,layer);if(!nodes.has(k))nodes.set(k,{...p,edges:[]});return nodes.get(k);};
 for(const p of paths.filter(p=>p.stroke&&!p.fill&&!p.closed))for(let n=1;n<p.points.length;n++){const a=node(p.points[n-1],p.layer),b=node(p.points[n],p.layer);if(a===b)continue;const e={a,b,layer:p.layer,used:false};a.edges.push(e);b.edges.push(e);edges.push(e);}
 const result=[],unique=new Set();for(const edge of edges){if(edge.used)continue;let start=edge.a.edges.length!==2?edge.a:edge.b.edges.length!==2?edge.b:edge.a,current=start,e=edge,points=[{x:start.x,y:start.y}];for(let n=0;n<600;n++){if(e.used)break;e.used=true;current=e.a===current?e.b:e.a;points.push({x:current.x,y:current.y});if(current.edges.length!==2)break;e=current.edges.find(v=>v!==e);if(current===start)break;}if(current===start)continue;for(const trim of [0,1,2]){const arc=fittedArc({points:points.slice(trim,points.length-trim||undefined),layer:edge.layer});if(!arc)continue;const k=Math.round(arc.center.x)+','+Math.round(arc.center.y)+','+Math.round(arc.radius);if(!unique.has(k)){unique.add(k);result.push(arc);}break;}}
 return result;
}
const normalized=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[AKOTEHPXYB]/g,c=>({A:'Α',K:'Κ',O:'Ο',T:'Τ',E:'Ε',H:'Η',P:'Ρ',X:'Χ',Y:'Υ',B:'Β'}[c]));
function canvasFor(width,height){const canvas=typeof document!=='undefined'?document.createElement('canvas'):new OffscreenCanvas(width,height);canvas.width=width;canvas.height=height;return canvas;}
export async function readPDF(buffer,pageNumber=0,signal){
 const task=getDocument({data:new Uint8Array(buffer),useSystemFonts:true,isEvalSupported:false,stopAtErrors:true}),cancel=()=>task.destroy();signal?.addEventListener('abort',cancel,{once:true});const doc=await task.promise;
 try{
  const pages=[];let automatic=1,score=-1;
  for(let n=1;n<=Math.min(30,doc.numPages);n++){if(signal?.aborted)throw new DOMException('Ακυρώθηκε','AbortError');const p=await doc.getPage(n),t=(await p.getTextContent()).items.map(v=>v.str||'').join(' '),name=t.match(/(?:ΚΑΤΟΨΗ|KATOΨΗ|ΚΑΤΟΨ|FLOOR PLAN)[^\d]{0,35}/i)?.[0]?.trim()||'',key=normalized(name||t),rank=/ΚΑΤΟΨ.*ΙΣΟΓΕΙ|GROUND FLOOR/i.test(key+' '+t)?10:/ΚΑΤΟΨ|FLOOR PLAN/i.test(key+' '+t)?5:0;pages.push({number:n,name});if(rank>score){score=rank;automatic=n;}}
  pageNumber=pageNumber||automatic;
  const page=await doc.getPage(pageNumber),viewport=page.getViewport({scale:1}),ops=await page.getOperatorList(),text=await page.getTextContent(),paths=[],arcs=[],texts=[],stack=[];let matrix=viewport.transform.slice(),stroke='#000000',fill='#000000',lineWidth=1,imageArea=0;
  const at=(x,y)=>({x:x*matrix[0]+y*matrix[2]+matrix[4],y:x*matrix[1]+y*matrix[3]+matrix[5]});
  for(let n=0;n<ops.fnArray.length;n++){if(n%2000===0){if(signal?.aborted)throw new DOMException('Ακυρώθηκε','AbortError');await new Promise(r=>setTimeout(r,0));}const op=ops.fnArray[n],args=ops.argsArray[n];if(op===OPS.save)stack.push({matrix:matrix.slice(),stroke,fill,lineWidth});else if(op===OPS.restore){const v=stack.pop();if(v)({matrix,stroke,fill,lineWidth}=v);}else if(op===OPS.transform)matrix=multiply(matrix,args);else if(op===OPS.setStrokeRGBColor)stroke=args[0];else if(op===OPS.setFillRGBColor)fill=args[0];else if(op===OPS.setLineWidth)lineWidth=args[0];else if(op===OPS.constructPath){
   const paint=args[0],draw=args[1][0],isStroke=[OPS.stroke,OPS.closeStroke,OPS.fillStroke,OPS.eoFillStroke,OPS.closeFillStroke,OPS.closeEOFillStroke].includes(paint),isFill=[OPS.fill,OPS.eoFill,OPS.fillStroke,OPS.eoFillStroke,OPS.closeFillStroke,OPS.closeEOFillStroke].includes(paint);let points=[],curved=false,closed=false;
   const emit=()=>{if(points.length<2)return;const colour=isFill?fill:stroke,layer=(isFill?'Πλήρωση ':'Γραμμές ')+colour,b=drawingBounds([{points}]);const rgb=/^#[0-9a-f]{6}$/i.test(colour)?[1,3,5].map(k=>parseInt(colour.slice(k,k+2),16)):[0,0,0],grey=Math.max(...rgb)-Math.min(...rgb)<20;const eligible=points.length<=24&&!curved&&b.w+b.h>Math.max(viewport.width,viewport.height)/80,recommended=eligible&&grey&&Math.min(...rgb)>90&&Math.max(...rgb)<180;paths.push({points,closed:closed||isFill,curved,layer,stroke:isStroke?stroke:null,fill:isFill?fill:null,lineWidth,recommended,eligible,bounds:b});};
   for(let k=0;k<draw.length;){const command=draw[k++];if(command===0){emit();points=[at(draw[k++],draw[k++])];closed=false;curved=false;}else if(command===1)points.push(at(draw[k++],draw[k++]));else if(command===2){const p0=points.at(-1),p1=at(draw[k++],draw[k++]),p2=at(draw[k++],draw[k++]),p3=at(draw[k++],draw[k++]);if(p0)for(let i=1;i<=8;i++){const t=i/8,s=1-t;points.push({x:s*s*s*p0.x+3*s*s*t*p1.x+3*s*t*t*p2.x+t*t*t*p3.x,y:s*s*s*p0.y+3*s*s*t*p1.y+3*s*t*t*p2.y+t*t*t*p3.y});}curved=true;}else if(command===3){k+=4;curved=true;}else if(command===4)closed=true;else break;}emit();
  }else if([OPS.paintImageXObject,OPS.paintInlineImageXObject,OPS.paintImageXObjectRepeat,OPS.paintImageMaskXObject].includes(op))imageArea+=Math.abs(matrix[0]*matrix[3]-matrix[1]*matrix[2]);}
  for(const t of text.items){if(!t.str?.trim())continue;const m=multiply(viewport.transform,t.transform);texts.push({x:m[4],y:m[5],text:t.str.trim(),layer:'Κείμενο'});}
  const layerMap=new Map();for(const p of paths){if(p.stroke==='#2776bb'&&p.eligible)p.recommended=true;if(p.stroke==='#2776bb'&&p.closed&&p.points.length<=6&&Math.max(p.bounds.w,p.bounds.h)>Math.min(p.bounds.w,p.bounds.h)*8&&p.eligible){p.kind='window';p.recommended=true;}const arc=fittedArc(p);if(arc){arcs.push(arc);p.curved=true;}if(!layerMap.has(p.layer))layerMap.set(p.layer,{name:p.layer,count:0,recommended:false});const l=layerMap.get(p.layer);l.count++;l.recommended ||= p.recommended;}
  arcs.push(...lineArcs(paths));const warnings=['Οι ομάδες PDF βασίζονται σε χρώματα γραμμών, όχι σε CAD layers.'];if(!texts.length)warnings.push('Τα γράμματα του PDF είναι σχήματα/εικόνες. Τα ονόματα χώρων θα συμπληρωθούν στο editor.');
  if(!paths.length&&!imageArea)throw Error('Η σελίδα δεν περιέχει γραμμές ή εικόνα κάτοψης. Διάλεξε άλλη σελίδα.');
  for(const l of layerMap.values())if(l.recommended&&paths.filter(p=>p.layer===l.name&&p.recommended).length<3&&l.name.startsWith('Πλήρωση '))l.recommended=paths.some(p=>p.layer===l.name&&p.recommended&&p.bounds.w*p.bounds.h>=viewport.width*viewport.height*.01);
  if(![...layerMap.values()].some(l=>l.recommended)){const black=[...layerMap.values()].find(l=>l.name==='Γραμμές #000000');if(black)black.recommended=true;}
  const renderViewport=page.getViewport({scale:Math.min(2200/viewport.width,2200/viewport.height,3)}),canvas=canvasFor(Math.ceil(renderViewport.width),Math.ceil(renderViewport.height)),ctx=canvas.getContext('2d');
  await page.render({canvasContext:ctx,viewport:renderViewport}).promise;
  const imageFraction=imageArea/(viewport.width*viewport.height),preview=canvas.toDataURL('image/jpeg',.9),rasterDominant=imageFraction>.5||(imageFraction>.15&&paths.filter(p=>p.eligible).length<12)||(!paths.length&&imageArea>0);let raster;
  if(rasterDominant){
   const keep=new Set([OPS.save,OPS.restore,OPS.transform,OPS.dependency,OPS.setGState,OPS.setFillRGBColor,OPS.paintImageXObject,OPS.paintInlineImageXObject,OPS.paintImageXObjectRepeat,OPS.paintInlineImageXObjectGroup,OPS.paintImageMaskXObject,OPS.paintImageMaskXObjectGroup,OPS.paintImageMaskXObjectRepeat]);
   ctx.clearRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:renderViewport,operationsFilter:i=>keep.has(ops.fnArray[i])}).promise;
   const rgba=ctx.getImageData(0,0,canvas.width,canvas.height).data,data=new Uint8Array(canvas.width*canvas.height);for(let n=0;n<data.length;n++)data[n]=Math.round((rgba[n*4]+rgba[n*4+1]+rgba[n*4+2])/3);
   raster={width:canvas.width,height:canvas.height,data,imagesOnly:true};for(const l of layerMap.values())l.recommended=false;layerMap.set('Τοίχοι από εικόνα',{name:'Τοίχοι από εικόνα',count:0,recommended:true});
   warnings.push('Αναγνώριση από εικόνα: έλεγξε τοίχους, χώρους και κλίμακα. Πόρτες και παράθυρα μπορεί να χρειαστούν συμπλήρωση στο editor.');
  }
  canvas.width=canvas.height=1;
  const printedScale=text.items.map(t=>t.str||'').join(' ').match(/\b1\s*:\s*(\d{2,4})\b/),scaleDenominator=printedScale?Number(printedScale[1]):0;
  const scene={kind:'pdf',paths,arcs,texts,layers:[...layerMap.values()].sort((a,b)=>Number(b.recommended)-Number(a.recommended)||b.count-a.count),bounds:{x:0,y:0,w:viewport.width,h:viewport.height},regions:[],cmPerSourceUnit:0,warnings,pages:doc.numPages,pageNumber,pageChoices:pages,scaleDenominator,preview,raster};return scene;
 }finally{signal?.removeEventListener('abort',cancel);await doc.destroy();}
}
