"""Run with: xvfb-run -a python3 tests/browser4.py.
Exact production modules are loaded as local blobs because the test container's
browser intentionally blocks network navigation. No renderer or physics mocks.
"""
import json, os, time
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_harness import load
OUT=Path(os.environ.get('BUBBLE_TEST_OUTPUT',str(Path(__file__).parent)))
OUT.mkdir(parents=True,exist_ok=True)
results=[]
def check(name,condition,detail=None):
 results.append(dict(name=name,pass_=bool(condition),detail=detail))
 print(('PASS ' if condition else 'FAIL ')+name+(' '+str(detail) if not condition else ''),flush=True)
with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-webgl','--ignore-gpu-blocklist'])
 page=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)));load(page)
 page.evaluate("__bubble.game.renderer.resize('low');__bubble.start()")
 check('Actual WebGL 2 renderer boots v0.4.0',page.evaluate("__bubble.version==='0.4.0' && !!__bubble.game.renderer.gl.getParameter(__bubble.game.renderer.gl.VERSION)"))
 def run(source):return page.evaluate('()=>{const g=__bubble.game;'+source+'}')
 def reset():run("__bubble.start();g.aiDisabled=true;g.god=true;g.tool='splat';g.form='mass';g.player.yaw=Math.PI;g.refreshTools();")
 data=run("__bubble.step(8);return {hp:g.player.hp,combat:g.knights.filter(a=>a.brain.mode==='combat').length,count:g.knights.length,shown:g.knights.filter(a=>g.visibleActor(a)).length};")
 check('Eight idle seconds never trigger a global enemy rush',data['hp']==100 and data['combat']==0 and data['count']==22,data)
 check('Hidden room patrols are not exposed through the cutaway camera',data['shown']<8,data)
 reset();page.keyboard.press('Space');data=run("__bubble.step(.25);return {y:g.player.p[1],vy:g.player.vy};")
 check('Normal jump uses upward motion',data['y']>1 and data['vy']>0,data)
 reset();page.keyboard.down('w');run('__bubble.step(1)');page.keyboard.up('w');walk=run('return g.player.p[2]');reset();page.keyboard.down('Shift');page.keyboard.down('w');run('__bubble.step(1)');page.keyboard.up('w');page.keyboard.up('Shift');data=run('return {z:g.player.p[2],stamina:g.player.stamina}')
 check('Sprint remains faster and consumes stamina',data['z']<walk-.8 and data['stamina']<99,data)
 reset();run("g.testAim=[0,0,22];g.updateAim();");page.mouse.click(700,440);data=run('__bubble.step(.5);return {ammo:g.ammo,n:g.volume.values.size};')
 check('Real pointer tap fires one splat and consumes one unit',data['ammo']==179 and data['n']>0,data)
 reset();run("g.testAim=[0,0,18];g.updateAim();");page.mouse.down();run('__bubble.step(2.9)');check('Full charge reaches entire 180-unit capacity',run('return g.chargeAmmo()===180'));page.mouse.up();check('Full charge consumes all tank ammunition',run('return g.ammo===0'))
 page.keyboard.press('r');run('__bubble.step(1.8)');check('Reload restores the existing 180-unit tank',run('return g.ammo===180'))
 reset();page.mouse.down();run('__bubble.step(.7)');page.keyboard.press('Escape');check('Pause cancels a held charge without firing or spending ammunition',run('return g.paused&&!g.fireDown&&g.ammo===180&&g.projectiles.length===0'));page.keyboard.press('Escape');check('Pause/resume restores play',run('return g.playing()'))
 reset();data=run("g.knights=g.knights.slice(0,1);const a=g.knights[0];a.p=[0,0,18];a.home=a.p.slice();a.yaw=0;g.testAim=[0,1.3,18];g.updateAim();g.beginFire();__bubble.step(2.9);g.endFire();__bubble.step(1);return {front:a.coverage.filter(x=>x>.6).length,back:a.coverage.filter(x=>x<.1).length,down:a.down,coat:a.coat,ammo:g.ammo,captured:a.captured};")
 check('Frontal charged impact covers one half, not the unseen back',data['front']==4 and data['back']==4 and not data['captured'],data)
 check('Frontal charged impact knocks the guard off balance',data['down']>0 and data['coat']['chest']>1,data)
 reset();data=run("g.knights=g.knights.slice(0,1);const a=g.knights[0];a.p=[0,0,16];a.home=a.p.slice();a.yaw=0;g.testAim=[0,1.7,16];g.updateAim();g.shoot(180,true);let high=-100;for(let i=0;i<160;i++){g.step(1/60);if(g.projectiles[0])high=Math.max(high,g.projectiles[0].p[1]);}return {high,head:a.coat.head,covered:a.coverage.filter(x=>x>.5).length};")
 check('Lob is a ballistic projectile passing above head height',data['high']>3,data)
 check('Descending charged splash covers more directions than frontal splash',data['covered']>4 and data['head']>.7,data)
 reset();data=run("g.tool='flow';g.testAim=[0,0,22];g.updateAim();g.beginFire();__bubble.step(2);g.endFire();return {n:g.volume.values.size,ammo:g.ammo,hit:g.volume.ray([0,4,22],[0,-1,0],5)};")
 check('Infinite FLOW builds collidable volume without spending tank ammo',data['n']>30 and data['ammo']==180 and data['hit'] is not None,data)
 reset();data=run("g.tool='flow';g.form='wall';g.testAim=[0,0,23];g.updateAim();g.beginFire();__bubble.step(1.7);g.endFire();const h=g.world.ray([0,1.5,26],[0,0,-1],6);return{gum:!!h?.gum,n:g.volume.values.size};")
 check('Cover tool builds an actual head-height projectile barrier',data['gum'] and data['n']>100,data)
 data=run("g.testAim=[0,1.4,23];g.tool='erase';g.updateAim();g.beginFire();__bubble.step(1.8);g.endFire();return !!g.volume.ray([0,1.4,26],[0,0,-1],6);")
 check('Eraser opens a passable shot hole in built cover',not data,data)
 reset();page.keyboard.press('b');page.keyboard.down('w');run('__bubble.step(2)');page.keyboard.up('w');page.keyboard.down('d');run('__bubble.step(2)');page.keyboard.up('d');data=run('return {p:g.player.p,on:g.player.pathOn,n:g.volume.values.size,grounded:g.player.grounded}')
 check('Left-hand PATH creates a rising walkable route while moving',data['p'][1]>2.8 and data['grounded'],data)
 check('PATH can turn and is not a straight filament bridge',data['p'][0]>5 and data['p'][2]<21 and data['n']>250,data)
 page.keyboard.press('v');check('Grade toggle supports downhill and level paths',run('return g.grade<0'));page.keyboard.press('v');check('Second grade toggle selects level construction',run('return g.grade===0'))
 reset();data=run("g.player.p=[-7,0,21.25];g.player.lastSafe=g.player.p.slice();for(let y=.2;y<5.4;y+=.2)g.volume.stamp([-7,y,20.45],[.7,.45,.33],3);g.player.gripping=true;g.input.keys.add('KeyW');__bubble.step(1.5);g.input.keys.clear();return {p:g.player.p,grip:g.gripContact,stamina:g.player.stamina};")
 check('Active gloves climb gum-covered walls with a stamina cost',data['p'][1]>1 and data['stamina']<100,data)
 data=run("const before=g.player.p[1];__bubble.step(.4);return {before,after:g.player.p[1]};")
 check('Active gloves can hold position on the wall without movement input',abs(data['before']-data['after'])<.08,data)
 reset();data=run("g.testAim=[-4,.6,24];g.updateAim();const a=g.props.find(x=>x.type==='crate');const before=a.p.slice();g.use();const grabbed=g.tethers.grab===a;g.input.keys.add('KeyD');__bubble.step(1.5);g.input.keys.clear();return {grabbed,before,after:a.p};")
 check('Object tether moves a physical crate rather than teleporting it',data['grabbed'] and abs(data['after'][0]-data['before'][0])>1,data)
 reset();data=run("g.knights=g.knights.slice(0,1);const a=g.knights[0];a.p=[0,0,20];Object.keys(a.coat).forEach(k=>a.coat[k]=1);g.testAim=[0,1.2,20];g.updateAim();g.use();const grabbed=g.tethers.grab===a;g.use();__bubble.step(.1);const first=a.p[1];__bubble.step(3.5);return {grabbed,first,after:a.p[1],hanging:a.hanging,captured:a.captured,count:g.captures};")
 check('Ceiling suspension requires existing gum and lifts over time',data['grabbed'] and data['first']<.1 and data['after']>1.8 and data['hanging'],data)
 check('Suspended immobilization awards a capture exactly once',data['captured'] and data['count']==1,data)
 reset();data=run("g.testAim=[-7,6.25,20];g.updateAim();g.use();const on=!!g.tethers.swing;g.input.keys.add('KeyW');__bubble.step(.8);g.input.keys.clear();const before=g.player.vel.slice();g.jump();return{on,p:g.player.p,before,after:g.player.vel.slice(),released:!g.tethers.swing};")
 check('SWING attaches to high geometry and moves the body',data['on'] and data['p'][1]>.2,data)
 check('Releasing SWING preserves momentum',data['released'] and data['before']==data['after'],data)
 reset();data=run("const a=g.props.find(x=>x.type==='crate');a.p=[-24,0,19.2];__bubble.step(1.4);return{active:g.plate.active,height:g.gate.p[1]};")
 check('A moved crate operates the pressure plate and opens a physical gate',data['active'] and data['height']>2.5,data)
 reset();data=run("g.player.p=[28,-5,-17.5];g.testAim=[28.8,-4.25,-19.9];g.updateAim();g.use();__bubble.step(1.4);return {lever:g.lever.open,height:g.vaultGate.p[1]};")
 check('Gum interaction pulls the lever and opens the vault gate',data['lever'] and data['height']>-2.5,data)
 reset();data=run("for(const s of g.seals){g.player.p=[s.p[0],s.p[1]-.7,s.p[2]];g.pickups(.1);}__bubble.step(3.2);return {seals:g.collected,boss:!!g.boss};")
 check('Collecting the three objectives summons ARACHNE-09',data['seals']==3 and data['boss'],data)
 data=run("const before=g.boss.hp;g.impact({used:180,lob:false,v:[0,0,-22],source:[0,0,8],owner:'player'},{boss:true,p:[0,2,1.7],n:[0,0,1]});const chargedDamage=before-g.boss.hp;g.boss.hp=1;g.impact({used:1,owner:'player'},{boss:true,p:[0,2,1.7],n:[0,0,1]});__bubble.step(3);return {chargedDamage,win:g.ended,tier:g.progress.p.unlockedTier,legendary:g.progress.p.items.filter(x=>x.rarity===4).length};")
 check('Charged projectile impacts damage the boss; victory preserves progression and three Legendary items',data['chargedDamage']>=120 and data['win'] and data['tier']>=2 and data['legendary']>=3,data)
 reset();page.keyboard.press('i');check('BAG opens the real existing progression/Forge interface',page.locator('#inventory').is_visible() and run('return g.paused'))
 page.locator('#closeBag').click();check('Closing BAG restores active gameplay',run('return g.playing()'))
 check('No runtime exceptions in desktop integration',not errors,errors)
 page.close()
 for width,height,safe in ([] if os.environ.get('BUBBLE_SKIP_MOBILE') else [(430,932,False),(932,430,False),(375,667,False),(932,430,True)]):
  ctx=browser.new_context(viewport={'width':width,'height':height},device_scale_factor=1,has_touch=True,is_mobile=True);page=ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)));load(page);page.evaluate("__bubble.game.renderer.resize('low');__bubble.start();__bubble.game.aiDisabled=true;__bubble.game.god=true;__bubble.game.player.pathOn=true;__bubble.game.refreshTools()")
  if safe:page.evaluate("document.documentElement.style.setProperty('--safe-l','59px');document.documentElement.style.setProperty('--safe-r','59px');document.documentElement.style.setProperty('--safe-b','21px')")
  name=f'{width}x{height}'+(' safe areas' if safe else '')
  layout=page.evaluate('''()=>{const ids=['moveStick','aimStick','jumpBtn','gaitBtn','pathBtn','gripBtn','gradeBtn','fireBtn','modeBtn','zoneBtn','useBtn','reloadBtn'];const all=ids.map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{id,x:r.x,y:r.y,w:r.width,h:r.height}});let overlaps=[];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const a=all[i],b=all[j];if(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>1&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>1)overlaps.push([a.id,b.id]);}return{all,overlaps,off:all.filter(r=>r.x<0||r.y<0||r.x+r.w>innerWidth+1||r.y+r.h>innerHeight+1),small:all.filter(r=>r.w<44||r.h<44),center:all.filter(r=>r.x<innerWidth*.55&&r.x+r.w>innerWidth*.45&&r.y>innerHeight*.5)}}''')
  check(name+' thumb targets do not overlap',not layout['overlaps'],layout['overlaps']);check(name+' controls remain on screen',not layout['off'],layout['off']);check(name+' controls are at least 44px',not layout['small'],layout['small']);check(name+' lower central play area contains no controls',not layout['center'],layout['center'])
  # True touch events through CDP, not just calls into an input mock.
  cdp=ctx.new_cdp_session(page);r=page.locator('#aimStick').bounding_box();x=r['x']+r['width']/2;y=r['y']+r['height']/2
  page.evaluate("__bubble.game.player.pathOn=false;__bubble.game.tool='splat';__bubble.game.testAim=[0,0,22];__bubble.game.updateAim();__bubble.game.refreshTools()")
  cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y-12,'id':1}]});page.evaluate('__bubble.step(.5)');held=page.evaluate('__bubble.game.fireDown&&__bubble.game.charge>0');cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});spent=page.evaluate('__bubble.game.ammo<180');check(name+' right joystick can aim and charge/release with one thumb',held and spent)
  page.evaluate('__bubble.game.ammo=180');cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y-12,'id':2}]});page.evaluate('__bubble.step(.4)');cdp.send('Input.dispatchTouchEvent',{'type':'touchCancel','touchPoints':[]});check(name+' interrupted touches cancel without accidental shots',page.evaluate('!__bubble.game.fireDown&&__bubble.game.ammo===180'))
  check(name+' no runtime exceptions',not errors,errors)
  print('Closing touch context '+name,flush=True);ctx.close();print('Closed '+name,flush=True)
 browser.close()
report={'version':'0.4.0','environment':'Chromium 144 + SwiftShader; emulated touch, not physical iPhone or Safari','passed':sum(r['pass_'] for r in results),'total':len(results),'results':results}
(OUT/'browser-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(f"{report['passed']}/{report['total']} passed",flush=True)
if report['passed']!=report['total']:raise SystemExit(1)
