import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {World} from '../src/world.js';
import {GumVolume,attachPhysics,moveBody,deflect,TetherPhysics,ISO} from '../src/material4.js';
import {makeKnights,GROUPS,pose,hitActor,hitRegion,canFire,isBlind,seePlayer,hear,updateKnight,coatedCapture,coating} from '../src/knights4.js';
import {Progression,freshProfile,validateProfile} from '../src/progression.js';
import {norm,sub,dist,dot} from '../src/engine.js';
const results=[];
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.message);}}
const world=new World(),volume=new GumVolume(22000),props=[];attachPhysics(world,volume,props);
const body=(p=[0,0,24])=>({id:-1,p:p.slice(),home:p.slice(),lastSafe:p.slice(),height:2,radius:.40,vel:[0,0,0],vy:0,grounded:true,yaw:0});
const knight=()=>makeKnights(world)[0];
test('22 enemies are distributed in 2/3/6 local squads',()=>{assert.equal(makeKnights(world).length,22);assert.deepEqual(GROUPS.map(g=>g.points.length),[2,3,6,3,2,6]);});
test('Starting the castle does not aggro the hidden squads',()=>{const p=body([0,0,27]);for(const a of makeKnights(world)){assert.equal(seePlayer(a,p,world),false);for(let i=0;i<120;i++)updateKnight(a,p,world,1/60,i/60,()=>assert.fail('startup shot'));assert.notEqual(a.brain.mode,'combat');}});
test('A stamped gum mass has an actual external ray surface',()=>{volume.reset();volume.stamp([0,0,20],[.7,.27,.7],2.7);const h=volume.ray([0,3,20],[0,-1,0],4);assert(h?.gum);assert(h.p[1]>.05&&h.p[1]<.5);});
test('Subsequent splats attach to existing outer surface and increase height',()=>{volume.reset();volume.stamp([0,0,20],[.7,.27,.7],2.7);const before=volume.ray([0,5,20],[0,-1,0],6).p[1];for(let i=0;i<12;i++){const h=volume.ray([0,5,20],[0,-1,0],6);volume.stamp([0,h.p[1]+.04,20],[.65,.30,.65],2.7);}const after=volume.ray([0,5,20],[0,-1,0],6).p[1];assert(after>before+.8);});
test('Adjacent stamps fuse in the same continuous field',()=>{volume.reset();volume.stamp([0,0,20],[.8,.3,.8],3);volume.stamp([.8,0,20],[.8,.3,.8],3);assert(volume.value([.4,0,20])>ISO);});
test('Rendering is a generated mesh, not a decorative sphere stack',()=>{const arrays=[...volume.chunks].map(k=>volume.meshChunk(k));assert(arrays.some(a=>a.positions.length>0));for(const a of arrays){assert.equal(a.positions.length%9,0);assert.equal(a.positions.length,a.normals.length);assert([...a.positions,...a.normals].every(Number.isFinite));}});
test('Wall mass blocks a real projectile path',()=>{volume.reset();for(let y=.0;y<3.4;y+=.25)volume.stamp([0,y,20],[1.8,.45,.55],3);assert(world.ray([0,1.3,23],[0,0,-1],6)?.gum);});
test('Wall mass blocks player movement rather than only rendering cover',()=>{const p=body([0,0,22]);for(let i=0;i<120;i++)moveBody(world,p,0,-4/60,1/60);assert(p.p[2]>20.7);});
test('The same wall also blocks AI line of sight',()=>{const a=knight();a.p=[0,0,18];a.yaw=0;assert.equal(seePlayer(a,body([0,0,22]),world),false);});
test('Removing gum opens a real hole, not a decal-only erasure',()=>{volume.erase([0,1.4,20],1.25);volume.erase([0,1.4,20],1.25);assert.equal(volume.ray([0,1.4,22],[0,0,-1],4),null);});
test('Construction budget stops new material and never deletes existing support',()=>{const v=new GumVolume(18);v.stamp([0,0,0],[.8,.8,.8],3);const known=[...v.values][0];for(let i=0;i<10;i++)v.stamp([3+i,0,0],[.8,.8,.8],3);assert(v.full);assert(v.values.size<=18);assert.equal(v.values.get(known[0]),known[1]);});
test('Invalid material input is rejected',()=>{const v=new GumVolume;assert.equal(v.stamp([NaN,0,0]),0);assert.equal(v.values.size,0);});
test('Saturated density does not continually remesh unchanged terrain',()=>{const v=new GumVolume;for(let i=0;i<15;i++)v.stamp([0,0,0],[.2,.2,.2],5);v.dirty.clear();v.stamp([0,0,0],[.2,.2,.2],5);assert.equal(v.dirty.size,0);});
test('Gum platforms support feet at the rendered surface',()=>{volume.reset();volume.stamp([0,.8,20],[2,.5,2],4);const p=body([0,3,20]);p.grounded=false;for(let i=0;i<100;i++)moveBody(world,p,0,0,1/60);const h=volume.ray([0,4,20],[0,-1,0],5).p[1];assert(p.grounded);assert(Math.abs(p.p[1]-h)<.035);assert(p.onGum);});
test('Thick sloped paths can be climbed without collider snagging',()=>{volume.reset();for(let z=25;z>14;z-=.20)volume.stamp([0,-.25+(25-z)*.25,z],[1.1,.38,1.1],3.2);const p=body([0,0,25.5]);for(let i=0;i<150;i++)moveBody(world,p,0,-3.4/60,1/60);assert(p.p[1]>1.6);assert(p.p[2]<18);});
test('A gum cushion prevents unsupported ground fall-through',()=>{volume.reset();volume.stamp([0,0,20],[1.5,.3,1.5],3);const p=body([0,5,20]);p.grounded=false;let bounced=false;for(let i=0;i<90;i++){moveBody(world,p,0,0,1/60,{bounce:true});if(p.vy>5)bounced=true;}assert(bounced);});
test('Deflection reverses only the normal component and loses energy',()=>{const v=[7,0,-2],n=[0,0,1],r=deflect(v,n);assert(r[2]>0);assert(r[0]>0);assert(Math.hypot(...r)<Math.hypot(...v));});
test('Projectile intersection distinguishes head from torso',()=>{volume.reset();const a=knight();a.p=[0,0,18];a.yaw=0;const h=hitActor(a,[0,1.88,23],[0,0,-1],8,0);assert.equal(h.region,'head');});
test('Torso hit regions follow the knocked-down skeleton',()=>{const a=knight();a.p=[0,0,18];a.yaw=0;a.down=2;const chest=pose(a,0).chest;const o=[chest[0]+4,chest[1],chest[2]],h=hitActor(a,o,[-1,0,0],5,0);assert(h);assert(['chest','armR','armL'].includes(h.region));});
test('Arm and leg targets have genuinely distinct hit shapes',()=>{const a=knight();a.p=[0,0,18];a.yaw=0;const p=pose(a,0);const hand=hitActor(a,[2,p.handR[1],p.handR[2]],[-1,0,0],3,0);const leg=hitActor(a,[2,p.kneeR[1],p.kneeR[2]],[-1,0,0],3,0);assert.equal(hand.region,'armR');assert.equal(leg.region,'legR');});
test('One head hit does not magically fully blind',()=>{const a=knight();hitRegion(a,'head',[0,0,23],pose(a,0).head,1,world);assert(!isBlind(a));});
test('Accumulated head coating actually removes vision and firing',()=>{const a=knight();a.p=[0,0,18];for(let i=0;i<3;i++)hitRegion(a,'head',[0,0,23],pose(a,0).head,1,world);assert(isBlind(a));assert(!canFire(a));assert(!seePlayer(a,body([0,0,23]),world));});
test('Binding the weapon arm stops shots, not just an animation',()=>{const a=knight();for(let i=0;i<3;i++)hitRegion(a,'armR',[0,0,23],pose(a,0).handR,1,world);assert(!canFire(a));});
test('Chest accumulation causes impulse and loss of balance',()=>{const a=knight();a.p=[0,0,18];for(let i=0;i<4;i++)hitRegion(a,'chest',[0,0,23],pose(a,0).chest,1,world);assert(a.vel[2]<-1);assert(a.down>0);});
test('Grounded leg coating creates a foot-to-ground anchor',()=>{const a=knight();a.p=[0,0,18];for(let i=0;i<3;i++)hitRegion(a,'legL',[0,0,23],pose(a,0).footL,1,world);assert(a.anchors.legL);});
test('Zero health alone never counts as a full capture',()=>{const a=knight();a.hp=0;assert.equal(coatedCapture(a),false);});
test('Full directional coating and region coating can finish a capture',()=>{const a=knight();for(const k in a.coat)a.coat[k]=1;a.coverage.fill(1);assert(coatedCapture(a));});
test('A guard cannot see the player behind its facing cone',()=>{const a=knight();a.p=[0,0,18];a.yaw=Math.PI;assert(!seePlayer(a,body([0,0,23]),world));});
test('Nearby sound produces investigation, not instant combat',()=>{const a=knight();a.p=[0,0,18];hear(a,[0,0,21],6,world);assert.equal(a.brain.mode,'investigate');assert.deepEqual(a.brain.lastKnown,[0,0,21]);});
test('Last-known hearing position does not track the unseen player',()=>{const a=knight();a.p=[0,0,18];hear(a,[0,0,21],6,world);hear(a,[1,0,22],6,world);assert.deepEqual(a.brain.lastKnown,[0,0,21]);});
test('Sight confirmation is required before a patrol fires',()=>{const a=knight();a.p=[0,0,18];a.home=a.p.slice();a.yaw=0;let shots=0;const p=body([0,0,23]);for(let i=0;i<20;i++)updateKnight(a,p,world,1/60,i/60,()=>shots++);assert.equal(shots,0);for(let i=0;i<140;i++)updateKnight(a,p,world,1/60,i/60,()=>shots++);assert(shots>0);});
test('Distant squad does not hear a local fight',()=>{const a=knight();a.p=[-24,0,11];hear(a,[20,0,15],12,world);assert.equal(a.brain.mode,'patrol');});
test('A suspended guard rises over time without teleportation',()=>{const a=knight();a.p=[0,0,18];a.vel=[0,0,0];const tether=new TetherPhysics(world);tether.add(a,[0,6,18],{hanging:true});tether.step(1/60,body());moveBody(world,a,0,0,1/60);assert(a.p[1]<.05);for(let i=0;i<220;i++){tether.step(1/60,body());moveBody(world,a,a.vel[0]/60,a.vel[2]/60,1/60);}assert(a.p[1]>1.5);assert(a.hanging);});
test('Cutting a suspended tether resumes gravity',()=>{const a=knight();a.p=[0,2,18];a.grounded=false;a.hanging=true;const t=new TetherPhysics(world);t.add(a,[0,6,18],{hanging:true});t.cutNear([0,6,18]);assert.equal(t.links.length,0);assert(!a.hanging);for(let i=0;i<120;i++)moveBody(world,a,0,0,1/60);assert(a.grounded);});
test('Swing release preserves existing momentum',()=>{const a=body();a.vel=[4,0,7];a.vy=2;const t=new TetherPhysics(world);t.add(a,[0,7,20],{swing:true});t.releasePlayer();assert.deepEqual(a.vel,[4,0,7]);assert.equal(a.vy,2);});
test('Movable props block rays at their actual current position',()=>{volume.reset();const a={...body([0,0,20]),id:100,movable:true,type:'crate',radius:.6,height:1.2};props.push(a);assert.equal(world.ray([0,.6,24],[0,0,-1],8).prop,a);a.p[0]=4;assert.equal(world.ray([0,.6,24],[0,0,-1],8),null);props.pop();});
test('Existing v3 character saves remain compatible',()=>{const p=freshProfile();p.level=3;p.skillPoints=2;p.xpNext=174;const valid=validateProfile(p);assert(valid);assert.equal(valid.level,3);assert.equal(valid.skillPoints,2);});
test('Equipped items are protected from Forge sacrifice',()=>{const p=new Progression();p.p.level=2;p.p.gold=100;p.p.dust=10;const a=p.item(),b=p.item();p.pickup(a);p.pickup(b);p.equip(b.id);assert(p.plan(a.id,b.id).error);});
test('Auto Forge defaults to explicit opt-in',()=>{const p=new Progression();assert.equal(p.p.autoForge,false);assert.equal(p.auto(),null);});
const report={version:'0.4.0',suite:'material-and-rules',passed:results.filter(x=>x.pass).length,total:results.length,results};
writeFileSync(new URL('logic-results.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(`${report.passed}/${report.total} passed`);if(report.passed!==report.total)process.exitCode=1;
