import {createGame,PROJECTS,ROLES,MISSIONS,RESOURCES,NPCS,BARTERS,CHAPTERS,formatMoney,formatDuration,getProjectStatus,getMissionStatus,getDialogueStatus,getEconomyRates,getFreeWorkers,getChapter} from './engine.js?v=1.2.0';
import {LOCATIONS,LOCATION_MAP} from './locations.js?v=1.2.0';
import {createVillageRenderer} from './world.js?v=1.2.0';
import {icon,portrait,buildingIllustration,welcomeArt} from './icons.js?v=1.2.0';

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,dec=0)=>Number(v||0).toLocaleString('el-CY',{maximumFractionDigits:dec,minimumFractionDigits:dec});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const storage={getItem:k=>{try{return localStorage.getItem(k)}catch{return null}},setItem:(k,v)=>{try{localStorage.setItem(k,v)}catch(error){storage.failed=true;throw error}},removeItem:k=>{try{localStorage.removeItem(k)}catch{}}};
const safeStore=(k,v)=>{try{storage.setItem(k,v)}catch{}};
const game=createGame({storage});
const initialStorageWarning=game.state.storageWarning;
const view={panel:'overview',selected:'office',mode:'office',filter:'all',layer:'normal',peopleSection:'requests',pendingTalk:null,panelOpen:window.innerWidth>600,modal:null,welcomeMode:'campaign',sound:false,history:[],historyError:false,lastPanelAt:0,lastLogId:null,started:!!storage.getItem('moutoullas-welcomed-v1')};
let audioCtx=null,renderer=null,rendering=false,lastJobIds=[],tickTimer=null,panelPointerDown=false;
const NAV=[['overview','office','Γραφείο'],['projects','hammer','Έργα'],['people','people','Κάτοικοι'],['treasury','ledger','Ταμείο'],['market','market','Αγορά'],['missions','flag','Αποστολές'],['history','book','Ο τόπος']];
const PANELS={overview:['ΚΟΙΝΟΤΙΚΟ ΓΡΑΦΕΙΟ','Καλώς ήρθες, μουχτάρη.'],projects:['Η ΑΝΑΓΕΝΝΗΣΗ ΤΟΥ ΧΩΡΙΟΥ','Έργα & φροντίδα'],people:['ΚΑΝΕΝΑΣ ΔΕΝ ΠΕΡΙΣΣΕΥΕΙ','Οι άνθρωποί μας'],treasury:['ΚΑΘΕ ΛΙΡΑ ΜΕΤΡΑ','Το τεφτέρι'],market:['ΑΠΟ ΤΟΝ ΤΟΠΟ ΜΑΣ','Η μικρή αγορά'],missions:['ΒΗΜΑ ΒΗΜΑ, ΜΑΖΙ','Το χρονικό μας'],history:['ΠΡΑΓΜΑΤΙΚΟΣ ΤΟΠΟΣ · ΑΛΗΘΙΝΕΣ ΡΙΖΕΣ','Γνωρίζοντας τον Μουτουλλά']};
const CATEGORIES={all:'Όλα',urgent:'Επείγοντα',production:'Παραγωγή',housing:'Σπίτια',community:'Κοινότητα',heritage:'Κληρονομιά',nature:'Φύση',tourism:'Φιλοξενία'};
const METRICS={trust:['Εμπιστοσύνη','trust'],order:['Ηρεμία','order'],heritage:['Χαρακτήρας','heritage'],nature:['Φύση','nature']};

$('brand-mark').innerHTML=icon('mountain');
$('help-btn').innerHTML=icon('help');$('settings-btn').innerHTML=icon('settings');$('sound-btn').innerHTML=icon('mute');
$('reset-camera').innerHTML=icon('target');$('layer-btn').innerHTML=icon('layers');
$('office-mode').innerHTML=icon('office')+'<span>Στο γραφείο</span>';$('walk-mode').innerHTML=icon('walk')+'<span>Στο χωριό</span>';
$('reopen-panel').innerHTML=icon('ledger')+'<span>Διοίκηση</span>';

function tone(type='click'){
 if(!view.sound)return;
 try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(type==='success'?620:type==='error'?185:360,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='success'?930:type==='error'?120:270,audioCtx.currentTime+.12);gain.gain.setValueAtTime(.035,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.19);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.2)}catch{}
}
function toast(message,error=false){if(!message)return;const el=document.createElement('div');el.className='toast'+(error?' error':'');el.innerHTML=icon(error?'warning':'check')+`<span>${esc(message)}</span>`;$('toasts').append(el);setTimeout(()=>el.remove(),4500);while($('toasts').children.length>3)$('toasts').firstElementChild.remove();tone(error?'error':'success')}
function act(result){if(result?.message)toast(result.message,!result.ok);render(true);return result}
function rateTime(s){return s.mode==='sandbox'?'ανά ημέρα χωριού · 15 πραγματικά δευτερόλεπτα':'ανά πραγματική ώρα'}
function timer(seconds,s=game.state){return formatDuration(Math.max(0,seconds)/(s.mode==='sandbox'?240:1))}
function costText(cost={}){return Object.entries(cost).filter(([,v])=>v>0).map(([k,v])=>k==='money'?formatMoney(v):`${num(v)} ${RESOURCES[k]?.short||k}`).join(' · ')}
function effectsText(effects={}){return Object.entries(effects).filter(([,v])=>v).map(([k,v])=>`${v>0?'+':''}${v} ${METRICS[k]?.[0]||k}`).join(' · ')}
function canPay(cost={}){return Object.entries(cost).every(([k,v])=>game.state.resources[k]>=v)}
function progressBar(value,kind=''){return `<div class="metric-track ${kind}"><i style="width:${clamp(value,0,100)}%"></i></div>`}
function metrics(s){return `<div class="metric-grid">${Object.entries(METRICS).map(([key,[name,ico]])=>`<div class="metric"><div class="metric-top"><span>${icon(ico)}${name}</span><strong>${num(s.metrics[key])}<small>%</small></strong></div>${progressBar(s.metrics[key],key==='trust'?'rust':key==='heritage'?'gold':'')}</div>`).join('')}</div>`}
function getTarget(p){return p.allowHouses?(LOCATION_MAP[view.selected]?.type==='house'?view.selected:null):p.buildingId}
function projectCard(p,s,compact=false){
 const target=getTarget(p),status=getProjectStatus(s,p,target),job=s.jobs.find(j=>j.projectId===p.id&&(!target||j.buildingId===target));
 const done=!p.repeatable&&s.completedProjects.includes(p.id);
 const remaining=job?.remaining??0;
 let reason=status.reason||'';
 const needsHouse=p.allowHouses&&!target;
 if(needsHouse)reason='Επίλεξε ένα πέτρινο σπίτι στον χάρτη.';
 return `<article class="project-card${done?' completed':''}"><div style="display:flex;align-items:center;justify-content:space-between;gap:7px"><h3>${esc(p.name)}</h3>${done?`<span class="tag green">${icon('check')}Έτοιμο</span>`:job?'<span class="tag gold">Σε εξέλιξη</span>':''}</div><p>${esc(p.description)}</p>${done?'':`<div class="project-meta"><span>${icon('clock')}${timer(status.duration||p.duration,s)}</span><span>${icon('people')}${p.workers} εργάτες</span>${Object.entries(status.cost||p.cost).filter(([,v])=>v>0).map(([k,v])=>`<span>${icon(k)}${k==='money'?formatMoney(v):num(v)}</span>`).join('')}</div>${job?`${progressBar((1-remaining/job.duration)*100,'gold')}<p>${timer(remaining,s)} απομένουν</p>`:`${reason&&!status.available?`<p class="blocked">${icon('lock')}${esc(reason)}</p>`:''}<button class="button full${status.available?'':' secondary'}" data-action="${needsHouse?'choose-house':'project'}" data-value="${p.id}" data-target="${target||''}" ${!status.available&&!needsHouse?'disabled':''}>${icon(needsHouse?'target':'hammer')}${needsHouse?'Διάλεξε σπίτι':'Ανάθεση έργου'}${status.available?icon('arrow'):''}</button>`}`}</article>`;
}
function missionCard(m,s){const st=getMissionStatus(s,m);return `<article class="mission-card${st.claimed?' claimed':''}"><span class="tag ${st.claimed?'green':st.available?'gold':''}">${st.claimed?icon('check')+'Ολοκληρώθηκε':st.available?'Στο βιβλίο του μουχτάρη':icon('lock')+'Αργότερα'}</span><h3>${esc(m.name||m.title)}</h3><p>${esc(m.description)}</p><div class="mission-progress"><span>${esc(st.description||'')}</span><span>${num(st.progress)}/${num(st.target)}</span></div>${progressBar(st.target?st.progress/st.target*100:0,'gold')}${st.checks?.length>1?`<div class="mission-checks">${st.checks.map(c=>`<p class="check-line ${c.complete?'is-done':''}">${icon(c.complete?'check':'clock')} ${esc(c.description)}</p>`).join('')}</div>`:''}<div class="reward-row">${icon('gift')}${costText(m.reward)}</div>${!st.claimed?`<button class="button full ${st.complete?'gold':'secondary'}" data-action="claim" data-value="${m.id}" ${!st.complete||!st.available?'disabled':''}>${st.complete?'Παραλαβή ανταμοιβής':'Σε εξέλιξη'}</button>`:''}</article>`}
function overview(s){
 const nextMission=MISSIONS.find(m=>{const st=getMissionStatus(s,m);return st.available&&!st.claimed}),mst=nextMission?getMissionStatus(s,nextMission):null;
 const missionGoals=nextMission?(nextMission.goal.type==='all'?nextMission.goal.goals:[nextMission.goal]):[];
 const nextProject=PROJECTS.find(p=>missionGoals.some(g=>g.type==='project'&&g.id===p.id)&&getProjectStatus(s,p,p.buildingId).available);
 const score=Math.round(LOCATIONS.reduce((sum,b)=>sum+(s.buildings[b.id]?.condition||0),0)/LOCATIONS.length);
 const active=s.jobs.slice(0,2);
 return `<div class="office-greeting"><div class="portrait">${portrait()}</div><div><span class="eyebrow">ΤΟ ΠΡΩΤΟ ΒΗΜΑ ΕΙΝΑΙ ΔΙΚΟ ΣΟΥ</span><strong>Ο τόπος μάς περιμένει.</strong></div></div><p class="intro-text">Σπασμένες στέγες, άδεια εργαστήρια, γεμάτα τεφτέρια. <strong>Ξαναδίνουμε ζωή στο χωριό, μαζί με τους ανθρώπους του.</strong></p>${metrics(s)}${officeInbox(s)}${eventBlock(s)}${nextMission?`<div class="mission-highlight"><div class="mission-tag">${icon('flag')}Η ΕΠΟΜΕΝΗ ΜΙΚΡΗ ΝΙΚΗ</div><h3>${esc(nextMission.name||nextMission.title)}</h3><p>${esc(mst.description||nextMission.description)}</p>${mst.complete?`<button class="button gold full" data-action="claim" data-value="${nextMission.id}">${icon('gift')}Πάρε την ανταμοιβή ${icon('arrow')}</button>`:nextProject?`<button class="button full" data-action="show-project" data-value="${nextProject.id}">${esc(nextProject.name)} ${icon('arrow')}</button>`:`<button class="button full" data-action="panel" data-value="missions">Δες την αποστολή ${icon('arrow')}</button>`}</div>`:''}<div class="village-score"><div class="score-dial" style="--score:${score}%"><strong>${score}%</strong></div><div class="score-copy"><strong>Το χωριό ξαναζωντανεύει</strong><small>${s.completedProjects.length} ολοκληρωμένα έργα · ${s.jobs.length} σε εξέλιξη</small></div></div><div class="section-label">ΣΤΟ ΓΡΑΦΕΙΟ ΣΗΜΕΡΑ<button data-action="panel" data-value="projects">Όλα τα έργα →</button></div>${active.length?active.map(j=>`<div class="task-mini">${icon('hammer')}<div class="task-copy">${esc(j.name)}<small>${timer(j.remaining,s)} · ${j.workers} εργάτες</small></div><button data-action="select" data-value="${j.buildingId}" aria-label="Δες το έργο">${icon('arrow')}</button></div>`).join(''):`<div class="task-mini">${icon('people')}<div class="task-copy">${getFreeWorkers(s)} κάτοικοι περιμένουν ανάθεση<small>Οι μικρές δουλειές αλλάζουν τη μεγάλη εικόνα.</small></div><button data-action="panel" data-value="people" data-section="assignments" aria-label="Ανάθεση εργασίας">${icon('arrow')}</button></div>`}<div class="task-mini">${icon('speech')}<div class="task-copy">Η Σοφία έχει το τεφτέρι έτοιμο<small>Μίλησε με τη γραμματέα της κοινότητας.</small></div><button data-action="talk" data-value="sofia" aria-label="Μίλησε με τη Σοφία">${icon('arrow')}</button></div>`;
}
function buildingPanel(s){const b=LOCATION_MAP[view.selected];if(!b)return '';const condition=s.buildings[b.id]?.condition??b.condition;const projects=PROJECTS.filter(p=>p.buildingId===b.id||(p.allowHouses&&b.type==='house'));const npcs=NPCS.filter(n=>n.buildingId===b.id);return `<div class="building-hero">${buildingIllustration(b.type)}<span class="tag">${b.real?'Πραγματικό τοπόσημο':'Χώρος του παιχνιδιού'}</span></div><p class="intro-text">${esc(b.description||'Ένα παραδοσιακό πέτρινο σπίτι της φανταστικής κοινότητας. Φρόντισε τη στέγη και τη λιθοδομή, για να επιστρέψει η ζωή στην αυλή.')}</p><div class="condition-line"><span>Κατάσταση κτιρίου / χώρου</span><strong>${num(condition)}% · ${condition>=75?'Φροντισμένο':condition>=45?'Χρειάζεται φροντίδα':'Επείγουσα φροντίδα'}</strong></div>${progressBar(condition,condition<45?'rust':'')}<div style="display:flex;gap:8px;margin-top:15px"><button class="button secondary full small" data-action="focus" data-value="${b.id}">${icon('target')}Εντοπισμός</button><button class="button full small" data-action="go-visit" data-value="${b.id}">${icon('walk')}${view.mode==='walk'?'Επίβλεψη':'Πήγαινε στο χωριό'}</button></div>${npcs.map(n=>npcCard(n)).join('')}<div class="section-label">ΕΡΓΑ ΣΤΟ ΣΗΜΕΙΟ<span>${projects.length}</span></div>${projects.length?projects.map(p=>projectCard(p,s)).join(''):'<p class="intro-text">Από εδώ ξεκινά η διοίκηση. Δες τα έργα και μοίρασε τα συνεργεία.</p><button class="button full" style="margin-top:14px" data-action="panel" data-value="projects">Άνοιξε τον κατάλογο έργων</button>'}`}
function projectsPanel(s){const projects=PROJECTS.filter(p=>view.filter==='all'||p.category===view.filter);return `<p class="intro-text">Επισκευάζουμε ό,τι υπάρχει. Διάλεξε έργο, δες το κόστος και δώσε δουλειά στα συνεργεία.</p><div class="workforce-total"><span>${icon('people')} Διαθέσιμοι για έργα</span><strong>${getFreeWorkers(s)}</strong></div><div class="filter-row">${Object.entries(CATEGORIES).map(([k,v])=>`<button class="${view.filter===k?'active':''}" data-action="filter" data-value="${k}">${v}</button>`).join('')}</div>${projects.map(p=>projectCard(p,s)).join('')}`}
function dialogueWait(n,s=game.state){return Math.max(0,(s.dialogueCooldowns[n.id]||0)-s.elapsed)}
function officeInbox(s){const ready=NPCS.filter(n=>!dialogueWait(n,s)).length;return `<article class="village-inbox"><div class="section-label">ΥΠΟΘΕΣΕΙΣ ΧΩΡΙΟΥ<small>${ready} διαθέσιμες συζητήσεις</small></div><p class="intro-text">Αιτήματα κατοίκων, επισκέπτες και αποφάσεις για όλο το χωριό φτάνουν στο γραφείο σου.</p><button class="button full" style="margin-top:12px" data-action="open-affairs">${icon('speech')}Άνοιξε τις υποθέσεις ${icon('arrow')}</button></article>`}
function npcCard(n){const waiting=dialogueWait(n);return `<article class="npc-card"><div class="portrait">${portrait(n.color,NPCS.indexOf(n))}</div><div class="npc-copy"><strong>${esc(n.name)}</strong><small>${esc(n.role)} · ${esc(LOCATION_MAP[n.buildingId]?.name)}</small><p>«${esc(n.text.slice(0,105))}${n.text.length>105?'…':''}»</p><small class="npc-availability">${waiting?`Νέα απάντηση σε ${timer(waiting)}`:'Περιμένει την άποψή σου'}</small><button class="arrow-link" data-action="talk" data-value="${n.id}">${icon('speech')}${waiting?'Δες τη συζήτηση':view.mode==='office'?'Απάντηση στο γραφείο':'Μια κουβέντα'} ${icon('arrow')}</button></div></article>`}
function peoplePanel(s){
 const requests=view.peopleSection!=='assignments';
 const tabs=`<div class="filter-row resident-tabs" aria-label="Κατηγορίες κατοίκων"><button class="${requests?'active':''}" data-action="people-section" data-value="requests" aria-pressed="${requests}">${icon('speech')}Υποθέσεις</button><button class="${!requests?'active':''}" data-action="people-section" data-value="assignments" aria-pressed="${!requests}">${icon('hammer')}Συνεργεία</button></div>`;
 if(requests)return `${tabs}<p class="intro-text">Εδώ απαντάς σε όλα τα θέματα των κατοίκων. Στο γραφείο δέχεσαι τα αιτήματά τους· στο χωριό μπορείς να τους συναντήσεις από κοντά.</p>${eventBlock(s)}<div class="section-label">ΟΙ ΦΩΝΕΣ ΤΟΥ ΧΩΡΙΟΥ<small>${NPCS.length} πρόσωπα</small></div>${NPCS.map(npcCard).join('')}<p class="notice">Οι χαρακτήρες και τα περιστατικά ανήκουν στο φανταστικό σενάριο του παιχνιδιού.</p>`;
 const rates=getEconomyRates(s);
 return `${tabs}<p class="intro-text">Τα συνεργεία παράγουν όσο λείπεις. Κράτησε ελεύθερα χέρια για τις αποκαταστάσεις.</p><div class="workforce-total"><span><strong style="font-size:13px">${s.workers.total} εργαζόμενοι</strong><small style="display:block;margin-top:4px;color:var(--muted)">${s.jobs.reduce((a,j)=>a+j.workers,0)} σε έργα · ${getFreeWorkers(s)} διαθέσιμοι</small></span>${icon('people')}</div>${ROLES.map(role=>{const value=s.workers.assignments[role.id]||0,cond=s.buildings[role.buildingId]?.condition||0,locked=role.minCondition&&cond<role.minCondition;const produced=role.resource==='money'?rates.income.tourism:rates.production[role.resource];return `<div class="role-row"><div class="role-main"><span class="resource-icon">${icon(role.resource)}</span><div class="role-copy"><strong>${esc(role.name)}</strong><small>${locked?'Χρειάζεται πρώτα επισκευή':`${role.resource==='money'?formatMoney(produced):num(produced,1)+' '+(RESOURCES[role.resource]?.unit||'μον.')} / ημέρα χωριού`}</small></div><div class="stepper"><button data-action="assign" data-value="${role.id}" data-delta="-1" aria-label="Λιγότεροι ${esc(role.name)}" ${value<=0?'disabled':''}>−</button><strong>${value}</strong><button data-action="assign" data-value="${role.id}" data-delta="1" aria-label="Περισσότεροι ${esc(role.name)}" ${getFreeWorkers(s)<=0||locked?'disabled':''}>+</button></div></div><p class="role-note">${esc(role.description)}</p></div>`}).join('')}`;
}
function treasuryPanel(s){const rates=getEconomyRates(s);return `<div class="pound-note actual"><img src="./assets/1pound.jpg" alt="Μπροστινή όψη κυπριακής λίρας της σειράς 1997, καφέ, με κοπέλα σε παραδοσιακή ενδυμασία"><span>ΚΥΠΡΙΑΚΗ ΛΙΡΑ<br><small>1 λίρα = 100 σεντ</small></span></div><p class="note-caption">Ιστορικό χαρτονόμισμα · Κεντρική Τράπεζα της Κύπρου. Χρησιμοποιείται ως νόμισμα του φανταστικού σεναρίου.</p><div class="treasury-balance"><small>ΔΙΑΘΕΣΙΜΟ ΚΟΙΝΟΤΙΚΟ ΤΑΜΕΙΟ</small><strong>${formatMoney(s.resources.money)}</strong></div><div class="ledger-summary"><div class="ledger-stat income"><small>Έσοδα / ημέρα χωριού</small><strong>+${formatMoney(rates.income.total)}</strong></div><div class="ledger-stat expense"><small>Έξοδα / ημέρα χωριού</small><strong>−${formatMoney(rates.expenses.total)}</strong></div></div><p class="intro-text">Καθαρή ροή: <strong class="${rates.net>=0?'income':'expense'}">${rates.net>=0?'+':''}${formatMoney(rates.net)}</strong> ${rateTime(s)}. Οι αγορές, πωλήσεις και τα έργα καταγράφονται χωριστά.</p><div class="finance-breakdown"><span>Εισφορές κατοίκων<strong>${formatMoney(rates.income.taxes)}</strong></span><span>Φιλοξενία<strong>${formatMoney(rates.income.tourism)}</strong></span><span>Κοινοτικά έσοδα<strong>${formatMoney(rates.income.community)}</strong></span><span>Ημερομίσθια<strong>−${formatMoney(rates.expenses.wages)}</strong></span><span>Συντήρηση<strong>−${formatMoney(rates.expenses.upkeep)}</strong></span></div><div class="tax-control"><label for="tax-input">Κοινοτική εισφορά <strong id="tax-value">${num(s.tax*100)}%</strong></label><input type="range" min="0" max="16" step="1" value="${Math.round(s.tax*100)}" id="tax-input" aria-label="Ποσοστό κοινοτικής εισφοράς"><p>Συμμόρφωση πληρωμών: ${num(rates.paymentRate*100)}%. Η εμπιστοσύνη και η ηρεμία επηρεάζουν τις εισπράξεις. Η υψηλή εισφορά πιέζει την εμπιστοσύνη.</p></div><div class="section-label">ΠΡΟΣΦΑΤΕΣ ΚΙΝΗΣΕΙΣ</div><table class="ledger-table"><tbody>${s.ledger.slice(0,18).map(l=>`<tr><td>${esc(l.description)}<small>Ημέρα ${Math.floor(l.at/3600)+1}</small></td><td class="${l.kind}">${l.kind==='income'?'+':'−'}${formatMoney(l.amount)}</td></tr>`).join('')}</tbody></table><div class="section-label">ΑΝ ΧΡΕΙΑΣΤΕΙΣ ΣΤΗΡΙΞΗ</div><p class="intro-text">Κοινοτικό βοήθημα όταν οι λίρες ή τα τρόφιμα είναι πολύ χαμηλά. Διατίθεται με χρόνο αναμονής.</p><button class="button secondary full" style="margin-top:10px" data-action="aid">Αίτηση βοήθειας ανάγκης</button>`}
function marketPanel(s){const bonus=s.completedProjects.includes('cooperative_restore')?1.1:1;return `<p class="intro-text">Πούλησε το πλεόνασμα και κράτα υλικά για τα έργα. Οι σκάφες φέρνουν περισσότερα από την ακατέργαστη ξυλεία.</p><div class="section-label">ΕΜΠΟΡΙΟ ΠΡΟΪΟΝΤΩΝ<small>ανά 5 μονάδες</small></div>${Object.entries(RESOURCES).filter(([k])=>k!=='money').map(([k,r])=>`<article class="trade-card"><div class="trade-top">${icon(k)}<strong>${esc(r.name)}</strong><span>Απόθεμα ${num(s.resources[k])}</span></div><div class="trade-actions"><button class="button secondary small" data-action="trade" data-value="${k}" data-side="buy" ${s.resources.money<r.buy*5?'disabled':''}>Αγόρασε 5 · ${formatMoney(r.buy*5)}</button><button class="button small" data-action="trade" data-value="${k}" data-side="sell" ${s.resources[k]<5?'disabled':''}>Πούλησε 5 · ${formatMoney(r.sell*5*bonus)}</button></div></article>`).join('')}<div class="section-label">ΧΩΡΙΣ ΛΙΡΕΣ · ΑΝΤΑΛΛΑΓΕΣ</div>${BARTERS.map(b=>`<div class="barter"><p><strong>${esc(b.name||b.title||'Ανταλλαγή')}</strong><small>${costText(b.cost||b.give)} → ${costText(b.reward||b.receive)}</small></p><button class="button secondary small" data-action="barter" data-value="${b.id}" ${!canPay(b.cost||b.give)?'disabled':''}>Ανταλλαγή</button></div>`).join('')}<div class="section-label">ΗΜΕΡΑ ΑΓΟΡΑΣ</div>${PROJECTS.filter(p=>['market_restore','market_day'].includes(p.id)).map(p=>projectCard(p,s)).join('')}`}
function eventBlock(s){const ev=s.event;if(!ev)return '';return `<article class="event-card"><span class="eyebrow">ΠΕΡΙΣΤΑΤΙΚΟ ΤΟΥ ΧΩΡΙΟΥ</span><h3>${esc(ev.title||ev.name)}</h3><p>${esc(ev.text)}</p>${ev.choices.map(c=>`<button class="event-choice" data-action="event" data-value="${c.id}" ${!canPay(c.cost)?'disabled':''}><strong>${esc(c.label)}</strong><small>${esc(c.description)}${Object.keys(c.cost||{}).length?'<br>Κόστος: '+costText(c.cost):'<br>Χωρίς κόστος'}${effectsText(c.effects)?'<br>'+effectsText(c.effects):''}${Object.keys(c.reward||{}).length?'<br>Έσοδα / προμήθειες: '+costText(c.reward):''}</small></button>`).join('')}</article>`}
function missionsPanel(s){const chapter=getChapter(s);return `<p class="intro-text">${esc(chapter.description)} Η ανάκαμψη χτίζεται σε πέντε κεφάλαια, με ανθρώπους, έργα και συνέπεια.</p><div class="chapter-list">${Array.from({length:CHAPTERS.length},(_,i)=>`<span class="${i+1<chapter.id?'done':i+1===chapter.id?'current':''}"></span>`).join('')}</div>${chapter.id<CHAPTERS.length?`<p class="notice">Επόμενο κεφάλαιο: <strong>${esc(chapter.nextName)}</strong> σε ${timer(Math.max(0,chapter.nextAt-s.elapsed),s)}.</p>`:''}${eventBlock(s)}<div class="section-label">ΑΠΟΣΤΟΛΕΣ<small>${s.missionClaims.length} / ${MISSIONS.length}</small></div>${MISSIONS.map(m=>missionCard(m,s)).join('')}<div class="section-label">ΤΟ ΗΜΕΡΟΛΟΓΙΟ ΤΟΥ ΜΟΥΧΤΑΡΗ</div>${s.log.slice(0,20).map(l=>`<div class="timeline-item"><span class="timeline-dot"></span><div><p>${esc(l.text)}</p><small>Ημέρα ${Math.floor(l.at/3600)+1}</small></div></div>`).join('')}`}
function historyPanel(){return `<p class="intro-text history-intro">Ο τόπος και οι παραδόσεις είναι αληθινά. Οι γειτονιές έχουν αποδοθεί ελεύθερα για το παιχνίδι. Οι ζημιές, οι διαφωνίες και όλοι οι χαρακτήρες ανήκουν στη μυθοπλασία.</p>${view.history.length?view.history.map(h=>`<article class="source-card"><h3>${esc(h.title)}</h3><p>${esc(h.text)}</p><a href="${esc(h.url)}" target="_blank" rel="noopener noreferrer">${esc(h.source)} ${icon('external')}</a></article>`).join(''):`<div class="empty-state">${view.historyError?'Η τεκμηρίωση δεν μπόρεσε να φορτώσει. Δοκίμασε ξανά όταν έχεις σύνδεση.':'Φόρτωση της ιστορίας του τόπου…'}</div>`}`}
function renderResources(s){const rates=getEconomyRates(s);$('resources').innerHTML=Object.keys(RESOURCES).map(k=>`<button class="resource-item ${k}" data-action="panel" data-value="${k==='money'?'treasury':'market'}" title="${esc(RESOURCES[k].name)}"><span class="resource-icon">${icon(k)}</span><span class="resource-info"><strong>${k==='money'?formatMoney(s.resources[k]):num(Math.floor(s.resources[k]))}</strong>${k!=='money'?`<em>${(rates.netResources[k]||0)>=0?'+':''}${num(rates.netResources[k],1)}/ημ.</em>`:''}<small>${k==='money'?'ΚΟΙΝΟΤΙΚΟ ΤΑΜΕΙΟ':RESOURCES[k].short.toLocaleUpperCase('el')}</small></span></button>`).join('')+`<button class="resource-item workers" data-action="panel" data-value="people" data-section="assignments"><span class="resource-icon">${icon('people')}</span><span class="resource-info"><strong>${getFreeWorkers(s)} / ${s.workers.total} διαθέσιμοι</strong><small>ΚΑΤΟΙΚΟΙ ΓΙΑ ΔΟΥΛΕΙΑ</small></span></button>`}
function renderStatus(s){const chapter=getChapter(s);$('day-display').innerHTML=`<strong>${icon('sun')} Ημέρα ${s.day} <span style="color:var(--gold)">·</span> ${s.mode==='sandbox'?'Ελεύθερο ×240':'Η θητεία σου'}</strong><small>${s.paused?'Σε παύση':`Ώρα χωριού ${String(Math.floor((s.elapsed%3600)/150)).padStart(2,'0')}:${String(Math.floor((s.elapsed%150)/2.5)).padStart(2,'0')}`} · 1 ημέρα = ${s.mode==='sandbox'?'15 δευτ.':'1 ώρα'}</small>`;$('chapter-caption').innerHTML=`<small>Κεφάλαιο ${chapter.id} / ${CHAPTERS.length}</small><br>${esc(chapter.name)}`;const ev=$('event-alert');ev.hidden=!s.event;if(s.event)ev.innerHTML=`<button data-action="open-affairs">${icon('speech')}<span><strong>${esc(s.event.title||s.event.name)}</strong>Μια απόφαση για το χωριό περιμένει την απάντησή σου.</span>${icon('arrow')}</button>`;$('tool-rail').innerHTML=NAV.map(([id,ic,label],i)=>`${i===6?'<span class="rail-divider"></span>':''}<button class="rail-button${view.panel===id&&view.panelOpen?' active':''}" data-action="panel" data-value="${id}" title="${label}" aria-label="${label}" ${view.panel===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span>${id==='missions'&&s.event?'<i class="nav-dot"></i>':''}</button>`).join('');if(storage.failed)$('save-indicator').innerHTML=icon('warning')+' Εξήγαγε αντίγραφο προόδου';}
function renderJobs(s){$('active-jobs').innerHTML=s.jobs.slice(0,4).map(j=>`<button class="job-chip" data-action="select" data-value="${j.buildingId}" title="Δες το έργο"><strong>${esc(j.name)}</strong><small><span>${j.workers} εργάτες στο σημείο</span><span>${timer(j.remaining,s)}</span></small>${progressBar((1-j.remaining/j.duration)*100)}</button>`).join('')}
function renderPanel(s){const wasScroll=$('panel-content').scrollTop,active=document.activeElement,focusData=$('panel-content').contains(active)&&active?.matches?.('[data-action]')?{...active.dataset}:null;const title=view.panel==='building'?['ΦΡΟΝΤΙΔΑ ΤΟΥ ΤΟΠΟΥ',LOCATION_MAP[view.selected]?.name||'Τοποθεσία']:PANELS[view.panel]||PANELS.overview;$('panel-header').innerHTML=`<div><div class="eyebrow">${title[0]}</div><h2>${esc(title[1])}</h2></div><button class="close-panel" data-action="close-panel" aria-label="Κλείσιμο πίνακα">${icon('close')}</button>`;const draw={overview,building:buildingPanel,projects:projectsPanel,people:peoplePanel,treasury:treasuryPanel,market:marketPanel,missions:missionsPanel,history:historyPanel};$('panel-content').innerHTML=(draw[view.panel]||overview)(s);if(focusData){const target=[...$('panel-content').querySelectorAll('[data-action]')].find(el=>Object.entries(focusData).every(([key,value])=>el.dataset[key]===value));if(target&&!target.disabled)target.focus({preventScroll:true})}$('panel-content').scrollTop=wasScroll;$('side-panel').classList.toggle('wide',['projects','missions'].includes(view.panel));$('side-panel').classList.toggle('closed',!view.panelOpen);$('side-panel').setAttribute('aria-hidden',String(!view.panelOpen));$('side-panel').inert=!view.panelOpen;$('reopen-panel').hidden=view.panelOpen;view.lastPanelAt=Date.now()}
function render(force=false){
 if(rendering)return;rendering=true;
 try{
  const s=game.state;renderer?.setState(s);
  // A timer must not replace a button between pointerdown and click.
  if(!panelPointerDown||force){renderResources(s);renderStatus(s);renderJobs(s)}
  if((force||Date.now()-view.lastPanelAt>4500)&&!panelPointerDown){
   const active=document.activeElement;
   if(active?.id!=='tax-input')renderPanel(s);
  }
  syncDialogue();
  const ids=s.jobs.map(j=>j.id);
  if(lastJobIds.length&&ids.length<lastJobIds.length){const fresh=s.log?.find(l=>/ολοκληρ|τελείω|έτοιμ/i.test(l.text));if(fresh&&fresh.id!==view.lastLogId){toast(fresh.text);view.lastLogId=fresh.id}}
  lastJobIds=ids;
 }catch(err){console.error('Game render',err)}finally{rendering=false}
}
function panel(id,selected){if(selected)view.selected=selected;view.panel=id;view.panelOpen=true;view.filter=id==='projects'?view.filter:'all';$('panel-content').scrollTop=0;render(true);updateInsets()}
function select(id){if(!LOCATION_MAP[id])return;view.selected=id;renderer?.setSelected(id);panel('building',id)}
function canTalkHere(n){
 if(view.mode==='office')return game.state.selectedBuilding==='office';
 const b=LOCATION_MAP[n.buildingId],d=renderer?.getDebugState?.();
 return view.mode==='walk'&&b&&d?.player&&Math.hypot(d.player.x-b.x,d.player.z-b.z)<8.5&&game.state.selectedBuilding===n.buildingId;
}
function handleVisit(id){
 const result=act(game.visit(id));if(!result.ok)return;select(id);
 const n=NPCS.find(n=>n.id===view.pendingTalk);
 if(n?.buildingId===id){view.pendingTalk=null;showModal('talk:'+n.id);}
}
function setMode(mode){
 if(!['office','walk'].includes(mode))return;
 view.pendingTalk=null;view.mode=mode;$('world-area').classList.toggle('walk',mode==='walk');renderer?.setMode(mode);
 if(mode==='office')game.returnToOffice();
 $('office-mode').classList.toggle('selected',mode==='office');$('walk-mode').classList.toggle('selected',mode==='walk');
 $('map-mode-label').textContent=mode==='office'?'ΑΠΟ ΤΟ ΓΡΑΦΕΙΟ ΤΟΥ ΜΟΥΧΤΑΡΗ':'ΣΤΑ ΣΤΕΝΑ ΤΟΥ ΜΟΥΤΟΥΛΛΑ';
 $('walk-hint').hidden=mode!=='walk';$('walk-hint').innerHTML=`<strong>Πάμε μια βόλτα, μουχτάρη.</strong>${matchMedia('(pointer:coarse)').matches?'Σύρε τον μοχλό ή πάτησε στο έδαφος.':'Κινήσου με WASD / βελάκια ή πάτησε στο έδαφος.'}<br>Πλησίασε ένα κτίριο για επίβλεψη.`;
 $('walk-joystick').hidden=mode!=='walk'||!matchMedia('(pointer:coarse)').matches;
 if(mode==='walk')view.panelOpen=false;else{view.panel='overview';view.panelOpen=true}
 render(true);updateInsets();tone();
}
function updateInsets(){const mobile=window.innerWidth<=600;renderer?.setViewportInsets?.({left:mobile?0:90,right:!mobile&&view.panelOpen?380:0,top:mobile?45:25,bottom:mobile?(view.panelOpen?250:100):65})}
function showModal(kind){view.modal=kind;const root=$('modal-root');let html='';if(kind==='welcome')html=welcomeModal();if(kind==='help')html=helpModal();if(kind==='settings')html=settingsModal();if(kind==='reset')html=resetModal();if(kind==='offline')html=offlineModal();if(kind==='victory')html=victoryModal();if(kind?.startsWith('talk:'))html=dialogueModal(kind.slice(5));root.innerHTML=`<div class="modal-scrim" data-action="dismiss-scrim"><section class="modal ${kind==='welcome'?'welcome-modal':''}" role="dialog" aria-modal="true" aria-label="${kind==='welcome'?'Καλώς ήρθες στο παιχνίδι':'Παράθυρο παιχνιδιού'}">${kind!=='welcome'?`<button class="modal-close" data-action="close-modal" aria-label="Κλείσιμο">${icon('close')}</button>`:''}${html}</section></div>`;renderer?.setInputEnabled?.(false);renderer?.clearMovement?.();renderer?.setMovement({x:0,y:0});$('game-shell').inert=true;const focusEl=root.querySelector('button.chosen,button:not(.modal-close)');focusEl?.focus()}
function closeModal(){if(view.modal==='welcome')return;if(view.modal==='offline')game.clearOfflineSummary?.();renderer?.setInputEnabled?.(true);$('modal-root').innerHTML='';view.modal=null;$('game-shell').inert=false;$('village').focus({preventScroll:true})}
function welcomeModal(){return `<div class="welcome-art">${welcomeArt()}<div class="art-caption">Ένας τόπος.<br>Οι άνθρωποί του.<br>Εσύ.<small>ΜΑΡΑΘΑΣΑ · ΚΥΠΡΟΣ · ~800 Μ.</small></div></div><div class="welcome-copy"><div class="eyebrow">ΜΟΥΤΟΥΛΛΑΣ — Ο ΜΟΥΧΤΑΡΗΣ</div><h2>Το χωριό χρειάζεται<br>μια καινούρια αρχή.</h2><p>Στέγες που στάζουν. Τεφτέρια που δεν κλείνουν. Και μια παρέα που πάντα… θα πληρώσει αύριο.</p><p>Πιάνεις δουλειά ως μουχτάρης. Θα ξανανοίξεις εργαστήρια, θα φροντίσεις τα σπίτια και θα φέρεις τον κόσμο κοντά. <strong>Το χωριό θα προκόψει, κρατώντας τον χαρακτήρα του.</strong></p><div class="modal-grid"><button class="mode-option${view.welcomeMode==='campaign'?' chosen':''}" data-action="choose-mode" data-value="campaign"><strong>Η θητεία του μουχτάρη</strong><small>Κανονικός χρόνος. Τα συνεργεία δουλεύουν όσο λείπεις. Πορεία τουλάχιστον 3 ημερών.</small><span class="tag">Η προτεινόμενη εμπειρία</span></button><button class="mode-option${view.welcomeMode==='sandbox'?' chosen':''}" data-action="choose-mode" data-value="sandbox"><strong>Ελεύθερη δοκιμή</strong><small>Ο χρόνος τρέχει ×240. Δοκίμασε την οικονομία και τις αποφάσεις με γρήγορη εξέλιξη.</small><span class="tag">Ξεχωριστή νέα παρτίδα</span></button></div><button class="button full" data-action="begin">${icon('key')}Αναλαμβάνω το χωριό ${icon('arrow')}</button><p class="welcome-footnote">Φανταστικό σενάριο με ιστορικές αναφορές και κυπριακές λίρες. Η ερειπωμένη αρχή και οι χαρακτήρες δεν περιγράφουν το πραγματικό χωριό. Αυτόματη αποθήκευση σε αυτή τη συσκευή.</p></div>`}
function helpModal(){return `<div class="eyebrow">ΤΟ ΜΙΚΡΟ ΒΙΒΛΙΟ ΤΟΥ ΜΟΥΧΤΑΡΗ</div><h2>Κάθε αρχή, μια μικρή δουλειά.</h2><div class="help-steps"><div class="help-step"><div><strong>Ξεκίνα με νερό και πλατεία</strong><p>Στα Έργα, ανάθεσε «Νερό ξανά στη βρύση». Χρειάζεται δύο εργάτες, CY£30, λίγο ξύλο και πέτρα. Η πρώτη αλλαγή φαίνεται σε 45 δευτερόλεπτα.</p></div></div><div class="help-step"><div><strong>Μοίρασε σωστά τα χέρια</strong><p>Στους Κατοίκους ορίζεις παραγωγή ξύλου, πέτρας, τροφίμων, σκαφών και φιλοξενίας. Όποιος δουλεύει στην παραγωγή δεν είναι διαθέσιμος σε κατασκευές.</p></div></div><div class="help-step"><div><strong>Κράτα το τεφτέρι σε τάξη</strong><p>Το Ταμείο δείχνει εισφορές, έσοδα, ημερομίσθια και συντήρηση. Πούλησε πλεόνασμα στην Αγορά ή αντάλλαξε προϊόντα. Υπάρχει βοήθημα ανάγκης όταν δυσκολέψουν τα πράγματα.</p></div></div><div class="help-step"><div><strong>Άκου τον κόσμο</strong><p>Στο Γραφείο → Υποθέσεις χωριού ή στους Κατοίκους → Υποθέσεις απαντάς σε όλους τους κατοίκους και στα περιστατικά. Μπορείς επίσης να τους συναντήσεις περπατώντας στο χωριό. Κάθε επιλογή γράφει το κόστος και τις συνέπειες. Οι γιορτές κοστίζουν, αλλά χτίζουν εμπιστοσύνη.</p></div></div><div class="help-step"><div><strong>Βγες για επίβλεψη</strong><p>Πάτησε «Στο χωριό». Κινείσαι με <span class="keyboard-key">W</span><span class="keyboard-key">A</span><span class="keyboard-key">S</span><span class="keyboard-key">D</span>, βελάκια ή πάτημα στο έδαφος. Στο κινητό εμφανίζεται μοχλός. Πλησίασε ένα έργο και πάτησε Ε ή «Επίβλεψη» για να βοηθήσεις μία φορά.</p></div></div></div><p class="notice"><strong>Ο χρόνος της θητείας:</strong> μία ημέρα χωριού = μία πραγματική ώρα. Το τελευταίο κεφάλαιο ανοίγει στις 48 ώρες. Η τελική αποστολή ολοκληρώνεται μετά από τουλάχιστον 72 πραγματικές ώρες. Υπολογίζονται έως 48 ώρες προόδου ανά απουσία. Η παύση σταματά την πρόοδο. Στην ελεύθερη δοκιμή ο χρόνος επιταχύνεται ×240.</p><p>Στον χάρτη: σύρε για μετακίνηση, ροδέλα ή δύο δάχτυλα για ζουμ. Το κουμπί επιπέδων χρωματίζει τα κτίρια ανάλογα με την κατάστασή τους. Με Escape κλείνεις τον πίνακα.</p><button class="button full" data-action="close-modal">Πάμε στο χωριό</button>`}
function settingsModal(){const s=game.state;return `<div class="eyebrow">Η ΠΡΟΟΔΟΣ ΤΗΣ ΘΗΤΕΙΑΣ ΣΟΥ</div><h2>Αποθήκευση & ρυθμίσεις</h2>${initialStorageWarning?`<p class="notice">${esc(initialStorageWarning)}</p>`:''}<p>Η πρόοδος αποθηκεύεται αυτόματα στον browser αυτής της συσκευής. Πάρε ένα αντίγραφο για μεταφορά σε άλλο κινητό ή υπολογιστή.</p><div class="settings-line"><div><strong>Αυτόματη αποθήκευση</strong><small>${storage.failed?'Ο browser δεν επιτρέπει μόνιμη αποθήκευση. Κατέβασε αντίγραφο.':'Ενεργή · αποθήκευση κάθε λίγα δευτερόλεπτα.'}</small></div><button class="button secondary small" data-action="save">Αποθήκευση τώρα</button></div><div class="settings-line"><div><strong>Αντίγραφο της παρτίδας</strong><small>Λίρες, έργα, αποστολές και κάτοικοι.</small></div><button class="button small" data-action="export">${icon('export')}Εξαγωγή</button></div><div class="settings-line"><div><strong>Εισαγωγή αντιγράφου</strong><small>Αντικαθιστά την πρόοδο αυτής της συσκευής.</small></div><button class="button secondary small" data-action="import">${icon('import')}Εισαγωγή</button><input id="save-file" type="file" accept=".json,application/json" hidden></div><div class="settings-line"><div><strong>${s.paused?'Το χωριό είναι σε παύση':'Η ζωή στο χωριό συνεχίζεται'}</strong><small>Η παύση σταματά παραγωγή, έξοδα και έργα, και όσο λείπεις.</small></div><button class="button secondary small" data-action="pause">${icon(s.paused?'play':'pause')}${s.paused?'Συνέχεια':'Παύση'}</button></div><div class="settings-line"><div><strong>Διακριτικοί ήχοι</strong><small>Ήχοι ενεργειών και ολοκλήρωσης.</small></div><button class="button secondary small" data-action="sound">${view.sound?'Κλείσιμο':'Ενεργοποίηση'}</button></div><div class="settings-line"><div><strong>Νέα θητεία</strong><small>Τώρα: ${s.mode==='sandbox'?'Ελεύθερη δοκιμή ×240':'Κανονικός χρόνος'} · ημέρα ${s.day}.</small></div><button class="button secondary small" data-action="modal" data-value="reset">Νέα παρτίδα</button></div><p class="notice">Η παρτίδα δεν συγχρονίζεται αυτόματα μεταξύ συσκευών. Για μεταφορά: Εξαγωγή εδώ και Εισαγωγή εκεί. Κράτα αντίγραφο πριν καθαρίσεις δεδομένα browser.</p><p style="font-size:9px">Μουτουλλάς — Ο Μουχτάρης · v1.1<br>Τοπική αποθήκευση και λειτουργία χωρίς σύνδεση μετά την πρώτη πλήρη φόρτωση, όπου υποστηρίζεται από τον browser.</p>`}
function resetModal(){return `<div class="eyebrow">ΜΙΑ ΝΕΑ ΘΗΤΕΙΑ</div><h2>Από την πρώτη μέρα;</h2><p>Η νέα παρτίδα θα αντικαταστήσει την αποθηκευμένη πρόοδο. Αν θέλεις να κρατήσεις το σημερινό χωριό, εξήγαγε πρώτα ένα αντίγραφο.</p><button class="button secondary full" data-action="export">${icon('export')}Κατέβασε την τωρινή πρόοδο</button><div class="modal-grid"><button class="mode-option" data-action="new-game" data-value="campaign"><strong>Κανονική θητεία</strong><small>Νέα αρχή σε κανονικό χρόνο. Τουλάχιστον 3 ημέρες εξέλιξης.</small></button><button class="mode-option" data-action="new-game" data-value="sandbox"><strong>Ελεύθερη δοκιμή ×240</strong><small>Νέα αρχή με επιταχυνόμενο χρόνο.</small></button></div><button class="button secondary full" data-action="modal" data-value="settings">Επιστροφή χωρίς αλλαγή</button>`}
function dialogueChoiceStatus(n,c){
 const status=getDialogueStatus(game.state,n.id,c.id,view.mode==='office'?'office':'onsite');
 if(status.code==='cooldown')status.reason=`Νέα συζήτηση σε ${timer(status.remaining)}.`;
 return status;
}
function dialogueStatusText(n){const remaining=dialogueWait(n);return remaining?`Η προηγούμενη απάντησή σου καταγράφηκε. Νέα συζήτηση σε ${timer(remaining)}.`:'Διάλεξε μία απάντηση. Κάθε επιλογή έχει το δικό της κόστος και αποτέλεσμα.'}
function dialogueModal(id){
 const n=NPCS.find(n=>n.id===id);if(!n)return '';
 const here=canTalkHere(n),office=view.mode==='office',location=LOCATION_MAP[n.buildingId]?.name;
 const choices=n.choices.map(c=>{const status=dialogueChoiceStatus(n,c);return `<button class="event-choice" data-action="dialogue" data-value="${n.id}" data-choice="${c.id}" ${!status.available?'disabled':''} title="${esc(status.available?'':status.reason)}"><strong>${esc(c.label)}</strong><small>${esc(c.description)}<br>${Object.keys(c.cost||{}).length?'Κόστος: '+costText(c.cost):'Χωρίς κόστος'}${effectsText(c.effects)?'<br>'+effectsText(c.effects):''}${Object.keys(c.reward||{}).length?'<br>Έσοδα / προμήθειες: '+costText(c.reward):''}</small><span class="choice-blocked" data-choice-reason="${c.id}" ${status.code!=='cost'?'hidden':''}>${status.code==='cost'?esc(status.reason):''}</span></button>`}).join('');
 return `<div class="dialogue-portrait portrait">${portrait(n.color,NPCS.indexOf(n))}</div><div class="eyebrow">${esc(n.role)}</div><h2>${esc(n.name)}</h2><p class="dialogue-context">${office?'Αίτημα στο κοινοτικό γραφείο':here?'Συνάντηση στο χωριό':'Σημείο συνάντησης'} · ${esc(location)}</p><div class="dialogue-bubble">«${esc(n.text)}»</div>${here?`<p class="dialogue-status notice" data-dialogue-status role="status">${esc(dialogueStatusText(n))}</p>${choices}`:`<p class="notice">Θα βρεις ${esc(n.name)} στο σημείο «${esc(location)}». Μπορείς να συναντηθείτε εκεί ή να απαντήσεις στο αίτημα από το γραφείο σου.</p><button class="button full" data-action="office-reply" data-value="${n.id}">${icon('office')}Απάντηση από το γραφείο ${icon('arrow')}</button>`}${!here||office?`<button class="button secondary full" style="margin-top:14px" data-action="find-npc" data-value="${n.id}">${icon('walk')}Συνάντηση στο χωριό ${icon('arrow')}</button>`:''}<p class="welcome-footnote" style="margin-top:17px">${office?'Η απάντηση στο γραφείο δεν μετρά ως επίσκεψη ή επίβλεψη έργου. ':''}Φανταστικός χαρακτήρας. Νέα ουσιαστική συζήτηση σε ${timer(21600)} πραγματικού χρόνου μετά από κάθε απάντηση. Η παύση σταματά την αναμονή.</p>`;
}
function syncDialogue(){
 if(!view.modal?.startsWith('talk:'))return;
 const n=NPCS.find(n=>n.id===view.modal.slice(5));if(!n)return;
 const notice=$('modal-root').querySelector('[data-dialogue-status]'),statusText=dialogueStatusText(n);if(notice&&notice.textContent!==statusText)notice.textContent=statusText;
 for(const c of n.choices){const button=$('modal-root').querySelector(`[data-action="dialogue"][data-choice="${c.id}"]`);if(!button)continue;const status=dialogueChoiceStatus(n,c);button.disabled=!canTalkHere(n)||!status.available;button.title=status.available?'':status.reason;const reason=button.querySelector('[data-choice-reason]');if(reason){reason.hidden=status.code!=='cost';reason.textContent=status.code==='cost'?status.reason:''}}
}
function offlineModal(){const sum=game.state.offlineSummary;if(!sum)return '<h2>Καλώς επέστρεψες.</h2>';return `<div class="eyebrow">ΟΣΟ ΕΛΕΙΠΕΣ</div><h2>Το χωριό συνέχισε τη μέρα του.</h2><p>Προχώρησαν ${num(sum.seconds/3600,2)} ημέρες χωριού όσο έλειπες. Ολοκληρώθηκαν <strong>${sum.completedJobs} έργα</strong>${sum.newEvents?' και υπάρχει νέο περιστατικό για να αποφασίσεις':''}.</p><div class="offline-grid">${Object.entries(sum.netResources).map(([k,v])=>`<div><span>${icon(k)}${RESOURCES[k]?.short}</span><strong class="${v>=0?'income':'expense'}">${v>=0?'+':''}${k==='money'?formatMoney(v):num(v,1)}</strong></div>`).join('')}</div>${sum.clamped?'<p class="notice">Υπολογίστηκαν έως 48 ώρες απουσίας. Το υπόλοιπο διάστημα δεν χρέωσε το χωριό.</p>':''}<p>Οι τιμές περιλαμβάνουν παραγωγή, ημερομίσθια και κατανάλωση. Το τεφτέρι έχει τις αναλυτικές κινήσεις.</p><button class="button full" data-action="close-modal">${icon('office')}Πίσω στο γραφείο</button>`;}
function victoryModal(){return `<div class="eyebrow">Η ΘΗΤΕΙΑ ΕΓΡΑΨΕ ΙΣΤΟΡΙΑ</div><div style="text-align:center;color:var(--gold);margin:15px">${icon('festival')}</div><h2>Ο Μουτουλλάς ξαναβρήκε τη ζωή του.</h2><p>Σπίτια με φροντισμένες στέγες. Χέρια με δουλειά. Ένα κοινό τραπέζι και ένα τεφτέρι που ανήκει σε όλους.</p><p>Ολοκλήρωσες την κύρια αποστολή διατηρώντας την κληρονομιά, τη φύση και τη συνοχή του χωριού. Η παρτίδα συνεχίζεται, με τις αποκαταστάσεις και τις ιστορίες που απομένουν.</p>${metrics(game.state)}<div class="modal-actions"><button class="button secondary" data-action="export">${icon('export')}Κράτα τη θητεία</button><button class="button" data-action="close-modal">Η ζωή συνεχίζεται ${icon('arrow')}</button></div>`;}
function exportSave(){const data=game.exportSave();const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`moutoullas-imera-${game.state.day}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);toast('Το αντίγραφο της θητείας σου είναι έτοιμο.')}
async function importFile(file){if(!file)return;if(file.size>2_000_000){toast('Το αρχείο είναι πολύ μεγάλο για αντίγραφο παρτίδας.',true);return}try{const raw=await file.text();const result=game.importSave(raw);act(result);if(result.ok){safeStore('moutoullas-welcomed-v1','1');view.started=true;closeModal();panel('overview');renderer?.setState(game.state)}}catch{toast('Το αρχείο δεν μπόρεσε να διαβαστεί.',true)}}
async function onAction(e){const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const action=el.dataset.action,value=el.dataset.value;if(action==='dismiss-scrim'){if(e.target===el)closeModal();return}tone();switch(action){
 case 'panel':if(value==='people'&&el.dataset.section)view.peopleSection=el.dataset.section;panel(value);break;
 case 'people-section':view.peopleSection=value==='assignments'?'assignments':'requests';panel('people');break;
 case 'open-affairs':view.peopleSection='requests';panel('people');break;
 case 'close-panel':view.panelOpen=false;render(true);updateInsets();break;
 case 'open-panel':view.panelOpen=true;render(true);updateInsets();break;
 case 'select':select(value);renderer?.focus(value);break;
 case 'focus':renderer?.focus(value);if(window.innerWidth<=600){view.panelOpen=false;render(true)}break;
 case 'show-project':{const p=PROJECTS.find(x=>x.id===value);if(p?.buildingId){select(p.buildingId);renderer?.focus(p.buildingId)}else panel('projects');break;}
 case 'project':act(game.startProject(value,el.dataset.target||undefined));break;
 case 'choose-house':view.filter='housing';panel('projects');view.panelOpen=false;render(true);toast('Πάτησε ένα πέτρινο σπίτι στον χάρτη για να του αναθέσεις επισκευή.');break;
 case 'filter':view.filter=value;render(true);$('panel-content').scrollTop=0;break;
 case 'assign':act(game.assign(value,Number(el.dataset.delta)));break;
 case 'trade':act(game.trade(value,el.dataset.side,5));break;
 case 'barter':act(game.barter(value));break;
 case 'claim':{const won=game.state.won;act(game.claimMission(value));if(!won&&game.state.won)showModal('victory');break;}
 case 'event':act(game.resolveEvent(value));break;
 case 'talk':if(view.mode==='office')game.returnToOffice();showModal('talk:'+value);break;
 case 'office-reply':{if(!NPCS.some(n=>n.id===value))break;closeModal();setMode('office');showModal('talk:'+value);break;}
 case 'find-npc':{const n=NPCS.find(n=>n.id===value);if(!n)break;closeModal();setMode('walk');view.pendingTalk=n.id;view.selected=n.buildingId;renderer?.setSelected(n.buildingId);const r=renderer?.walkToBuilding?.(n.buildingId,{visitOnArrival:true});if(r?.ok===false){view.pendingTalk=null;toast(r.message,true)}else if(!r?.arrived){view.panelOpen=false;render(true);updateInsets();toast(`Ο μουχτάρης πηγαίνει να συναντήσει ${n.name}.`)}break;}
 case 'dialogue':{const n=NPCS.find(n=>n.id===value);if(!n||!canTalkHere(n)){toast('Συνάντησε τον κάτοικο ή άνοιξε το αίτημα από το γραφείο.',true);break}const r=view.mode==='office'?game.replyAtOffice(value,el.dataset.choice):game.talk(value,el.dataset.choice);act(r);if(r.ok)closeModal();else syncDialogue();break;}
 case 'go-visit':{view.pendingTalk=null;if(view.mode!=='walk')setMode('walk');view.selected=value;renderer?.setSelected(value);const r=renderer?.walkToBuilding?.(value,{visitOnArrival:true});if(r?.ok===false)toast(r.message,true);else if(!r?.arrived){view.panelOpen=false;render(true);updateInsets();toast('Ο μουχτάρης πηγαίνει στο σημείο για επίβλεψη.')}break;}
 case 'mode':setMode(value);break;
 case 'zoom':renderer?.zoom(Number(value));break;
 case 'camera':renderer?.resetCamera();break;
 case 'layer':view.layer=view.layer==='normal'?'condition':'normal';renderer?.setLayer(view.layer);$('layer-btn').classList.toggle('active',view.layer!=='normal');toast(view.layer==='condition'?'Κατάσταση κτιρίων: κόκκινο χρειάζεται φροντίδα · πράσινο αποκατεστημένο.':'Επιστροφή στην κανονική θέα.');break;
 case 'sound':view.sound=!view.sound;$('sound-btn').innerHTML=icon(view.sound?'volume':'mute');$('sound-btn').setAttribute('aria-label',view.sound?'Απενεργοποίηση ήχου':'Ενεργοποίηση ήχου');if(view.sound)tone();if(view.modal==='settings')showModal('settings');break;
 case 'modal':showModal(value);break;
 case 'close-modal':closeModal();break;
 case 'choose-mode':view.welcomeMode=value;showModal('welcome');break;
 case 'begin':{game.reset(view.welcomeMode);game.setPaused(false);safeStore('moutoullas-welcomed-v1','1');view.started=true;view.modal=null;closeModal();view.panel='overview';view.panelOpen=window.innerWidth>600;render(true);updateInsets();toast('Καλωσόρισες, μουχτάρη. Ας δώσουμε πρώτα νερό στο χωριό.');break;}
 case 'save':game.save();toast(storage.failed?'Η αποθήκευση δεν είναι διαθέσιμη. Εξήγαγε ένα αντίγραφο.':'Η θητεία σου αποθηκεύτηκε.',!!storage.failed);break;
 case 'export':exportSave();break;
 case 'import':$('save-file')?.click();break;
 case 'pause':act(game.setPaused(!game.state.paused));showModal('settings');break;
 case 'aid':act(game.requestAid());break;
 case 'new-game':game.reset(value);game.setPaused(false);closeModal();setMode('office');renderer?.resetCamera();toast('Ξεκίνησε μια καινούρια θητεία.');break;
}}
document.addEventListener('click',onAction);
document.addEventListener('pointerdown',e=>{panelPointerDown=!!e.target.closest?.('#side-panel,#modal-root,#tool-rail,#resources,#event-alert')});
document.addEventListener('pointerup',()=>{panelPointerDown=false});
document.addEventListener('pointercancel',()=>{panelPointerDown=false});
window.addEventListener('blur',()=>{panelPointerDown=false});
document.addEventListener('input',e=>{if(e.target.id==='tax-input')$('tax-value').textContent=e.target.value+'%'});
document.addEventListener('change',e=>{if(e.target.id==='tax-input')act(game.setTax(Number(e.target.value)/100));if(e.target.id==='save-file')importFile(e.target.files[0])});
document.addEventListener('keydown',e=>{if(view.modal){if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=[...$('modal-root').querySelectorAll('button:not(:disabled),a,input:not([hidden])')];if(!els.length)return;const f=els[0],l=els[els.length-1];if(e.shiftKey&&document.activeElement===f){e.preventDefault();l.focus()}else if(!e.shiftKey&&document.activeElement===l){e.preventDefault();f.focus()}}return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='Escape'){view.panelOpen=!view.panelOpen;render(true);updateInsets()}if(e.key==='1')setMode('office');if(e.key==='2')setMode('walk')});
window.addEventListener('resize',updateInsets);
window.addEventListener('pagehide',()=>game.save());
document.addEventListener('visibilitychange',()=>{if(document.hidden){game.save();renderer?.setMovement({x:0,y:0})}else{game.tick();render(true)}});
const joystick=$('walk-joystick');let stickPointer=null;
function moveStick(e){if(stickPointer!==e.pointerId)return;const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy),scale=Math.min(1,32/(len||1)),x=dx*scale,y=dy*scale;joystick.querySelector('span').style.transform=`translate(${x}px,${y}px)`;renderer?.setMovement({x:x/32,y:y/32});e.preventDefault()}
joystick.addEventListener('pointerdown',e=>{stickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e)});joystick.addEventListener('pointermove',moveStick);function releaseStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;joystick.querySelector('span').style.transform='';renderer?.setMovement({x:0,y:0})}joystick.addEventListener('pointerup',releaseStick);joystick.addEventListener('pointercancel',releaseStick);

try{renderer=createVillageRenderer($('village'),{onSelect:id=>select(id),onVisit:id=>handleVisit(id),onHover:()=>{}});renderer.setState(game.state);renderer.setSelected('office');updateInsets()}catch(err){console.error('Village renderer failed',err);toast('Η απεικόνιση του χωριού δεν φορτώθηκε. Κάνε ανανέωση της σελίδας.',true)}
game.subscribe(()=>render());
render(true);
if(initialStorageWarning)toast(initialStorageWarning,true);
if(!view.started){game.setPaused(true);showModal('welcome')}else if(game.state.offlineSummary){showModal('offline')}
tickTimer=setInterval(()=>{if(view.started)game.tick();render()},1000);
fetch('./history.json').then(r=>{if(!r.ok)throw new Error('history');return r.json()}).then(data=>{view.history=Array.isArray(data)?data:data.entries||[];if(view.panel==='history')render(true)}).catch(()=>{view.historyError=true;if(view.panel==='history')render(true)});
if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{})})}
// Read-only UI diagnostics make failures inspectable without altering the simulation.
window.moutoullas={getState:()=>JSON.parse(JSON.stringify(game.state)),getView:()=>({...view,history:undefined}),getMap:()=>renderer?.getDebugState?.()};
