import * as THREE from './vendor/three.module.js';
import {MAP,REGIONS,RESOURCE_NODES,FACTIONS,BRIDGES,UNIT_TYPES,BUILDINGS,heightAt,riverX,regionAt} from './feouda-data.js?v=2.3.0';
import {BUILDING_FOOTPRINTS,PLACEMENT_ROADS,UNIT_CLEARANCE,isWorldPointWalkable,isWorldSegmentWalkable} from './feouda-engine.js?v=2.3.0';
import {createAssetLibrary} from './feouda-assets.js?v=2.3.0';
import {createSoftwareRenderer} from './feouda-software.js?v=2.3.0';
import {createMaterials} from './feouda-materials.js?v=2.3.0';
import {createFortress,setFortressState,createHouse,createBuilding,createBridge,createSiege,createResource,soldierGeometries,box,cylinder,mergeStatic} from './feouda-models.js?v=2.3.0';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
const random=seed=>()=>{seed=Math.imul(seed^seed>>>15,1|seed);seed^=seed+Math.imul(seed^seed>>>7,61|seed);return((seed^seed>>>14)>>>0)/4294967296;};
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const factionColor=o=>FACTIONS[o]?.color||'#9c9a82';
const BRIDGE_DECKS=BRIDGES.map(b=>({...b,deckY:Math.max(heightAt(b.x-17,b.z),heightAt(b.x+17,b.z))+.4}));
function walkHeight(x,z){let ground=heightAt(x,z);for(const fort of REGIONS){const radius=(fort.kind==='castle'?18:fort.kind==='town'?12:9)*1.12;if(Math.hypot(x-fort.x,z-fort.z)<radius)ground=Math.max(ground,heightAt(fort.x,fort.z)+.875);}for(const b of BRIDGE_DECKS){const d=Math.abs(x-b.x);if(d<25&&Math.abs(z-b.z)<4.1){const t=clamp((25-d)/8,0,1);return Math.max(ground,mix(ground,b.deckY,t));}}return ground;}
function environmentHeight(x,z){const edge=Math.max(Math.abs(x)-MAP.maxX,Math.abs(z)-MAP.maxZ,0),far=clamp(edge/100,0,1);return heightAt(x,z)+far*(26+30*Math.sin(x*.007+1.8)**2+35*Math.cos(z*.009+.4)**2+18*Math.sin(x*.019+z*.014));}
function pathGeometry(points,width,y=.095){const p=[],uv=[],index=[];for(let i=0;i<points.length;i++){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],dx=next[0]-prev[0],dz=next[1]-prev[1],len=Math.hypot(dx,dz)||1;for(const side of[-1,1]){const x=points[i][0]-dz/len*width*.5*side,z=points[i][1]+dx/len*width*.5*side;p.push(x,walkHeight(x,z)+y,z);uv.push(side<0?0:1,i*.06);}if(i){const j=i*2;index.push(j-2,j,j-1,j-1,j,j+1);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(index);g.computeVertexNormals();return g;}
function smoothPath(points,step=3){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],0,p[1])));return curve.getSpacedPoints(Math.max(4,Math.ceil(curve.getLength()/step))).map(p=>[p.x,p.z]);}
function makeTerrain(m){const width=1280,depth=1040,sx=256,sz=208,geometry=new THREE.PlaneGeometry(width,depth,sx,sz);geometry.rotateX(-Math.PI/2);const p=geometry.attributes.position,colors=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),h=environmentHeight(x,z);p.setY(i,h);const lush=(Math.sin(x*.046+z*.029)*Math.cos(z*.031)+Math.sin(x*.011-z*.007))*.13;const bank=Math.abs(x-riverX(z)),grassy=bank<24?-.03:0;const c=new THREE.Color().setRGB(clamp(.77+lush+grassy,.48,.99),clamp(.91+lush,.53,1),clamp(.63+lush,.43,.9));if(h>40)c.lerp(new THREE.Color('#bcb7a1'),clamp((h-35)/100,0,.64));colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,m.ground);mesh.receiveShadow=true;mesh.userData.ground=true;return mesh;}
function makeRiver(m){const group=new THREE.Group(),p=[],uv=[],idx=[],left=[],right=[];for(let i=0;i<=300;i++){const z=-510+i*3.4,x=riverX(z),s=.3+Math.sin(z*.043)*.4;let edge=5.6;for(let j=0;j<12;j++){if(heightAt(x+edge,z)>MAP.waterLevel)break;edge+=.6;}p.push(x-edge,MAP.waterLevel+s*.015,z,x+edge,MAP.waterLevel-s*.015,z);uv.push(0,i/20,1,i/20);left.push(new THREE.Vector3(x-edge+.1,MAP.waterLevel+.045,z));right.push(new THREE.Vector3(x+edge-.1,MAP.waterLevel+.045,z));if(i){const a=i*2;idx.push(a-2,a-1,a,a-1,a+1,a);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const surface=new THREE.Mesh(geo,m.water);surface.receiveShadow=true;group.add(surface);for(const points of[left,right])group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#b9c9ad',transparent:true,opacity:.37})));return group;}
function makeSky(scene){const geometry=new THREE.SphereGeometry(1800,32,20),material=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#789faa')},bottom:{value:new THREE.Color('#d4d7c6')}},vertexShader:'varying vec3 vPosition;void main(){vPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPosition;void main(){float h=normalize(vPosition).y;gl_FragColor=vec4(mix(bottom,top,pow(max(h,0.),.58)),1.);}'});scene.add(new THREE.Mesh(geometry,material));}
function treeGeometry(){const g=new THREE.CylinderGeometry(.015,1,1,11,6,true);g.translate(0,.5,0);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),a=Math.atan2(z,x),n=1+Math.sin(a*7+y*19)*.17+Math.cos(a*11-y*13)*.075;p.setXYZ(i,x*n,y+Math.sin(a*5+y*25)*.038*(1-y),z*n);}g.computeVertexNormals();return g;}
function addNature(scene,m){const r=random(813992),treePoints=[];const isRoad=(x,z)=>Math.abs(z)<5&&x<0;
 for(let i=0;i<2300;i++){let x=mix(-390,390,r()),z=mix(-305,305,r());if(Math.abs(x-riverX(z))<14||REGIONS.some(a=>Math.hypot(a.x-x,a.z-z)<(a.kind==='castle'?37:29))||isRoad(x,z))continue;const cluster=(Math.sin(x*.044)*Math.cos(z*.052)+Math.sin(x*.019+z*.047));if(cluster<.15&&r()>.14)continue;if(RESOURCE_NODES.some(n=>n.type!=='wood'&&Math.hypot(n.x-x,n.z-z)<8))continue;treePoints.push({x,z,h:environmentHeight(x,z),scale:5.8+r()*6.7,pine:r()>.34,yaw:r()*Math.PI*2});}
 for(const n of RESOURCE_NODES.filter(n=>n.type==='wood'))for(let j=0;j<24;j++){const a=j*2.399,d=5+Math.sqrt(j)*2,x=n.x+Math.cos(a)*d,z=n.z+Math.sin(a)*d;treePoints.push({x,z,h:heightAt(x,z),scale:6.1+r()*5.4,pine:r()>.2,yaw:r()*Math.PI*2});}
 const trunk=new THREE.InstancedMesh(new THREE.CylinderGeometry(.18,.27,1,7),m.trunk,treePoints.length),pine=new THREE.InstancedMesh(treeGeometry(),m.foliage,treePoints.length*3),leaf=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),m.foliageLight,treePoints.length*4);const d=new THREE.Object3D(),c=new THREE.Color;let pi=0,li=0;treePoints.forEach((p,i)=>{p.parts={trunk:i,pine:pi,leaf:li};d.position.set(p.x,p.h+p.scale*.28,p.z);d.scale.set(p.scale*.45,p.scale*.64,p.scale*.45);d.rotation.set(0,p.yaw,0);d.updateMatrix();trunk.setMatrixAt(i,d.matrix);if(p.pine){for(let j=0;j<3;j++){d.position.set(p.x,p.h+p.scale*(.27+j*.21),p.z);d.scale.set(p.scale*(.38-j*.067),p.scale*(.73-j*.13),p.scale*(.38-j*.067));d.updateMatrix();pine.setMatrixAt(pi,d.matrix);pine.setColorAt(pi++,c.setHSL(.21+r()*.045,.22+r()*.2,.43+r()*.15));}}else{for(let j=0;j<4;j++){d.position.set(p.x+Math.cos(j*2.4)*p.scale*.18,p.h+p.scale*(.58+(j%2)*.2),p.z+Math.sin(j*2.4)*p.scale*.18);d.scale.set(p.scale*.33,p.scale*.38,p.scale*.32);d.updateMatrix();leaf.setMatrixAt(li,d.matrix);leaf.setColorAt(li++,c.setHSL(.18+r()*.065,.25+r()*.15,.52+r()*.17));}}});pine.count=pi;leaf.count=li;trunk.userData.softwareLOD='trunk';pine.userData.softwareLOD='pine';leaf.userData.softwareLOD='leaf';for(const mesh of[trunk,pine,leaf]){mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();scene.add(mesh);}
 const rockPoints=[];const rocks=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1,0),m.rock,420);let ri=0;for(let i=0;i<500;i++){const x=mix(-390,390,r()),z=mix(-305,305,r());if(REGIONS.some(a=>Math.hypot(a.x-x,a.z-z)<34)||Math.abs(x-riverX(z))<10)continue;const scale=1+r()*3.5;d.position.set(x,environmentHeight(x,z)+scale*.22,z);d.rotation.set(r(),r()*6,r());d.scale.set(scale,scale*.61,scale*.8);d.updateMatrix();rockPoints.push({x,z,index:ri});rocks.setMatrixAt(ri++,d.matrix);if(ri>=420)break;}rocks.count=ri;rocks.userData.softwareLOD='rock';rocks.castShadow=rocks.receiveShadow=true;scene.add(rocks);return{treeCount:treePoints.length,treePoints,rockPoints,trees:[trunk,pine,leaf],rocks};}
function addRoads(scene,m){for(const road of PLACEMENT_ROADS){const path=road.points;let start=0;for(let i=0;i<=path.length;i++){const river=i<path.length&&Math.abs(path[i][0]-riverX(path[i][1]))<8;if(river||i===path.length){if(i-start>1){const mesh=new THREE.Mesh(pathGeometry(path.slice(start,i),road.width),m.road);mesh.receiveShadow=true;scene.add(mesh);}start=i+1;}}}}
function createPools(scene,m){const ge=soldierGeometries(),pools={},capacity=720;const cloth=m.cloth.clone();cloth.color.set('#ffffff');const materials={torso:cloth,armor:m.iron,head:m.skin,helmet:m.iron,leg:m.leather,foot:m.boots,arm:cloth,shield:cloth,spear:m.wood,spearhead:m.iron,sword:m.iron,bow:m.wood,horse:m.leather,horseArmor:cloth};for(const [key,geometry]of Object.entries(ge)){const mesh=new THREE.InstancedMesh(geometry,materials[key],key==='leg'||key==='foot'||key==='arm'?capacity*4:capacity);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.count=0;mesh.castShadow=true;mesh.receiveShadow=false;mesh.frustumCulled=false;scene.add(mesh);pools[key]={mesh,count:0};}return pools;}

export function createBattlefield(canvas,callbacks={}){
 let renderer,renderMode='webgl';try{const context=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!context)throw new Error('WebGL 2 is unavailable');renderer=new THREE.WebGLRenderer({canvas,context,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(webglError){try{renderer=createSoftwareRenderer({canvas});canvas=renderer.domElement;renderMode='software';}catch(error){callbacks.onError?.(error);throw error;}}callbacks.onMode?.(renderMode);
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#bbc9be',.00165);const camera=new THREE.PerspectiveCamera(43,1,.25,2100),materials=createMaterials();materials.water.userData.softwareSurface=1;materials.road.userData.softwareSurface=2;makeSky(scene);scene.add(new THREE.HemisphereLight('#d1e5e8','#675735',2.05));const sun=new THREE.DirectionalLight('#fff0cb',3.3);sun.position.set(-160,250,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-140;sun.shadow.camera.right=140;sun.shadow.camera.top=140;sun.shadow.camera.bottom=-140;sun.shadow.camera.near=1;sun.shadow.camera.far=650;sun.shadow.normalBias=.045;sun.shadow.bias=-.00015;sun.shadow.radius=2;scene.add(sun);scene.add(sun.target);
 const terrain=makeTerrain(materials);scene.add(terrain);const river=makeRiver(materials);scene.add(river);
 const rippleData=new Uint8Array(128*128*4);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=(y*128+x)*4,a=x/128*Math.PI*2,b=y/128*Math.PI*2;rippleData[i]=128+Math.sin(a*7+b*3)*22+Math.sin(a*15-b*8)*9;rippleData[i+1]=128+Math.cos(a*5-b*9)*19;rippleData[i+2]=249;rippleData[i+3]=255;}const ripple=new THREE.DataTexture(rippleData,128,128);ripple.wrapS=ripple.wrapT=THREE.RepeatWrapping;ripple.repeat.set(2,9);ripple.needsUpdate=true;materials.water.normalMap=ripple;materials.water.normalScale=new THREE.Vector2(.22,.22);materials.water.needsUpdate=true;addRoads(scene,materials);const nature=addNature(scene,materials);
 const forts=new Map(),nodes=new Map(),pickers=[],territories=[],politicalFills=[],growth=new Map(),construction=new Map(),structureTargets=new Map(),sieges=new Map(),squadTargets=new Map(),squadFlags=new Map();
 const pickMat=new THREE.MeshBasicMaterial({visible:false}),pickGeo=new THREE.SphereGeometry(1,8,6);function targetMesh(kind,id,x,z,r,y=2){const a=new THREE.Mesh(pickGeo,pickMat);a.position.set(x,heightAt(x,z)+y,z);a.scale.set(r,r,r);a.userData={kind,id};a.updateMatrixWorld(true);pickers.push(a);return a;}
 for(const r of REGIONS){const g=createFortress(r,materials);g.position.set(r.x,heightAt(r.x,r.z),r.z);scene.add(g);forts.set(r.id,g);targetMesh('region',r.id,r.x,r.z,r.kind==='castle'?21:r.kind==='town'?14:11,7);const points=[];for(let j=0;j<r.polygon.length;j++){const a=r.polygon[j],b=r.polygon[(j+1)%r.polygon.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]);for(let k=0;k<len;k+=3){const t=k/len,x=mix(a[0],b[0],t),z=mix(a[1],b[1],t);points.push(new THREE.Vector3(x,heightAt(x,z)+.19,z));}}points.push(points[0].clone());const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:factionColor(r.owner),transparent:true,opacity:.24,depthWrite:false}));line.userData.regionId=r.id;scene.add(line);territories.push(line);}
 const cells=new Map(REGIONS.map(r=>[r.id,[]]));for(let x=MAP.minX;x<MAP.maxX;x+=5)for(let z=-175;z<175;z+=5){const id=regionAt(x+2.5,z+2.5);if(!cells.has(id))continue;const p=cells.get(id),corners=[[x,z],[x+5,z],[x,z+5],[x+5,z+5]];for(const i of[0,2,1,1,2,3]){const[a,b]=corners[i];p.push(a,heightAt(a,b)+.15,b);}}for(const r of REGIONS){const ge=new THREE.BufferGeometry();ge.setAttribute('position',new THREE.Float32BufferAttribute(cells.get(r.id),3));const fill=new THREE.Mesh(ge,new THREE.MeshBasicMaterial({color:factionColor(r.owner),transparent:true,opacity:.17,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2}));fill.userData.regionId=r.id;fill.userData.softwareSurface=3;fill.visible=false;scene.add(fill);politicalFills.push(fill);}
 for(const n of RESOURCE_NODES){const model=createResource(n.type,materials);model.position.set(n.x,heightAt(n.x,n.z),n.z);scene.add(model);nodes.set(n.id,model);targetMesh('node',n.id,n.x,n.z,4.8,2);if(n.type==='food'){const farm=createBuilding('farm',materials);farm.position.set(n.x+5,heightAt(n.x+5,n.z-5),n.z-5);farm.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,p.getY(i)+heightAt(farm.position.x+p.getX(i),farm.position.z+p.getZ(i))-farm.position.y);p.needsUpdate=true;o.geometry.computeVertexNormals();});scene.add(farm);}}
 for(const b of BRIDGE_DECKS){const g=createBridge(materials,34,8,b.deckY+1.1);g.rotation.y=Math.PI/2;g.position.set(b.x,b.deckY-.6,b.z);scene.add(g);for(const sign of[-1,1]){const points=[];for(let d=16;d<=26;d+=1)points.push([b.x+sign*d,b.z]);const ramp=new THREE.Mesh(pathGeometry(points,7.1,.01),materials.stone);ramp.receiveShadow=ramp.castShadow=true;scene.add(ramp);const wallGroup=new THREE.Group();for(let d=17;d<25;d+=1){const x=b.x+sign*d,ground=heightAt(x,b.z),top=walkHeight(x,b.z);if(top-ground>.12)box(wallGroup,materials.darkStone,x,(ground+top)/2,b.z,1.1,top-ground,7);}mergeStatic(wallGroup);scene.add(wallGroup);}}
 const placementGroup=new THREE.Group();placementGroup.userData.softwareDynamic=true;scene.add(placementGroup);const pools=createPools(scene,materials),selectionGroup=new THREE.Group(),ordersGroup=new THREE.Group(),effectsGroup=new THREE.Group();effectsGroup.userData.softwareDynamic=true;scene.add(selectionGroup,ordersGroup,effectsGroup);
 const overlay=document.createElement('canvas');overlay.className='battlefield-labels';Object.assign(overlay.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'1'});canvas.parentNode?.appendChild(overlay);const ctx=overlay.getContext('2d');
 let state=null,selection=null,placement=null,placementModel=null,assetRevision=0,assetsSettled=renderMode==='software',lastPlacementHover=0,vegetationSignature='',mapMode='terrain',inputEnabled=true,quality='high',width=1,height=1,pixelRatio=1,lastTime=0,animationTime=0,raf=0,disposed=false,frame=0,ready=false,insets={left:0,right:0,top:0,bottom:0},labelBoxes=[],pointer=null,boxSelect=null,pinch=null;
 const assets=createAssetLibrary({software:renderMode==='software',onStatus:status=>callbacks.onAssetStatus?.(status),onAsset(){assetRevision++;refreshStructures();}});assets.ready.then(()=>{assetsSettled=true;refreshStructures();});
 const actors=new Map(),actorPositions=new Map(),activeActors=new Set();let actorDelta=0,detailFrameCount=0;
 const homeRegion=REGIONS.find(r=>r.id==='home')||REGIONS[0],view={x:homeRegion.x+10,z:homeRegion.z+12,distance:175,azimuth:.65,elevation:.86},desired={...view},keys=new Set(),pointers=new Map(),clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),projected=new THREE.Vector3(),temp=new THREE.Object3D(),matrix=new THREE.Matrix4(),local=new THREE.Matrix4(),q=new THREE.Quaternion(),v=new THREE.Vector3(),one=new THREE.Vector3(1,1,1),color=new THREE.Color();
 function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);pixelRatio=Math.min(window.devicePixelRatio||1,quality==='low'?1.25:1.65);renderer.setPixelRatio(pixelRatio);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();overlay.width=Math.round(width*pixelRatio);overlay.height=Math.round(height*pixelRatio);overlay.style.width=width+'px';overlay.style.height=height+'px';if(!ready&&width<700){view.distance=desired.distance=168;view.azimuth=desired.azimuth=.58;}}
 const resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;resizeObserver?.observe(canvas);resize();
 function updateCamera(dt){const f=renderMode==='software'?1:1-Math.exp(-dt*8);for(const k of['x','z','distance','azimuth','elevation'])view[k]=mix(view[k],desired[k],f);const close=clamp((90-view.distance)/58,0,1),elevation=mix(view.elevation,.5,close),h=heightAt(view.x,view.z)+mix(5,2.4,close),dist=view.distance,horizontal=Math.cos(elevation)*dist;const target=new THREE.Vector3(view.x,h,view.z);camera.position.set(view.x+Math.sin(view.azimuth)*horizontal,h+Math.sin(elevation)*dist,view.z+Math.cos(view.azimuth)*horizontal);camera.lookAt(target);camera.updateMatrixWorld();const offsetX=(insets.left-insets.right)/2,offsetY=(insets.top-insets.bottom)/2;camera.setViewOffset(width,height,-offsetX,-offsetY,width,height);sun.position.set(view.x-170,240+h,view.z+130);sun.target.position.set(view.x,h,view.z);sun.target.updateMatrixWorld();}
 function screenPoint(x,y,z){projected.set(x,y,z).project(camera);return{x:(projected.x+1)*width/2,y:(1-projected.y)*height/2,visible:projected.z<1&&projected.z>-1};}
 function ray(x,y){mouse.set(x/width*2-1,-y/height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster;}
 function groundAt(x,y){const hit=ray(x,y).intersectObject(terrain,false)[0];return hit?{x:clamp(hit.point.x,MAP.minX+2,MAP.maxX-2),z:clamp(hit.point.z,MAP.minZ+2,MAP.maxZ-2)}:null;}
 function pick(x,y){for(let i=labelBoxes.length-1;i>=0;i--){const a=labelBoxes[i];if(x>=a.x&&x<=a.x+a.w&&y>=a.y&&y<=a.y+a.h)return{kind:a.kind,id:a.id};}const hit=ray(x,y).intersectObjects(pickers,false);return hit.length?{kind:hit[0].object.userData.kind,id:hit[0].object.userData.id}:null;}
 function clearGroup(g){for(const a of[...g.children]){a.traverse(o=>o.userData.disposeAnimation?.());a.removeFromParent();a.geometry?.dispose();if(a.material?.userData?.transient)a.material.dispose();}}
 function circlePoints(x,z,r){const points=[];for(let i=0;i<=80;i++){const a=i*Math.PI/40,px=x+Math.cos(a)*r,pz=z+Math.sin(a)*r;points.push(new THREE.Vector3(px,walkHeight(px,pz)+.27,pz));}return points;}
 function drawSelection(){clearGroup(selectionGroup);clearGroup(ordersGroup);if(!selection||!state)return;let items=[];if(selection.kind==='army'||selection.kind==='squad'){const ids=selection.ids||[selection.id];items=state.squads.filter(s=>ids.includes(s.id)).map(s=>({...s,r:s.type==='cavalry'?5.6:4.2}));}else if(selection.kind==='region'){const r=REGIONS.find(r=>r.id===selection.id);if(r)items=[{...r,r:r.kind==='castle'?25:r.kind==='town'?19:15}];}else if(selection.kind==='structure'){const st=state.structures?.find(a=>a.id===selection.id);if(st){const f=BUILDING_FOOTPRINTS[st.type];items=[{...st,r:Math.max(f?.width||8,f?.depth||8)*.66}];}}else{const n=state.nodes.find(n=>n.id===selection.id);if(n)items=[{...n,r:6.3}];}for(const a of items){const mat=new THREE.LineBasicMaterial({color:'#e4d3a3',transparent:true,opacity:.94,depthWrite:false});mat.userData.transient=true;selectionGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(circlePoints(a.x,a.z,a.r)),mat));if(a.order&&a.order.type!=='hold'){let dest=a.order;if(dest.targetId){dest=state.squads.find(s=>s.id===dest.targetId)||REGIONS.find(r=>r.id===dest.targetId)||dest;}if(dest.regionId)dest=REGIONS.find(r=>r.id===dest.regionId)||dest;if(Number.isFinite(dest.x)&&Number.isFinite(dest.z)){const path=a.path?.length?[{x:a.x,z:a.z},...a.path]:[{x:a.x,z:a.z},{x:dest.x,z:dest.z}],p=path.map(v=>new THREE.Vector3(v.x,heightAt(v.x,v.z)+.35,v.z));const mm=new THREE.LineDashedMaterial({color:a.order.type==='attack'?'#d58365':'#ddd5b9',dashSize:1.9,gapSize:1.4,transparent:true,opacity:.64,depthWrite:false});mm.userData.transient=true;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),mm);line.computeLineDistances();ordersGroup.add(line);}}}}
 function removeTarget(target){const i=pickers.indexOf(target);if(i>=0)pickers.splice(i,1);}
 function disposeModel(model){if(!model)return;model.removeFromParent();model.traverse(o=>{o.userData.disposeAnimation?.();if(o.geometry&&!o.userData.sharedAsset&&!o.geometry.userData?.sharedPrimitive)o.geometry.dispose();});}
 const vegetationOriginals=new Map([...nature.trees,nature.rocks].map(m=>[m,new Float32Array(m.instanceMatrix.array)]));
 function pointInPlot(x,z,plot,padding=.5){const fp=BUILDING_FOOTPRINTS[plot.type];if(!fp)return false;const dx=x-plot.x,dz=z-plot.z,c=Math.cos(plot.rotation||0),sn=Math.sin(plot.rotation||0),lx=dx*c-dz*sn,lz=dx*sn+dz*c;return Math.abs(lx)<fp.width/2+padding&&Math.abs(lz)<fp.depth/2+padding;}
 function clearVegetation(){const plots=state.structures||[],signature=plots.map(p=>[p.id,p.type,p.x,p.z,p.rotation].join(':')).join('|');if(signature===vegetationSignature)return;vegetationSignature=signature;for(const [mesh,original]of vegetationOriginals)mesh.instanceMatrix.array.set(original);const hide=(mesh,index)=>{const a=mesh.instanceMatrix.array;for(let n=0;n<12;n++)a[index*16+n]=0;a[index*16+15]=1;};for(const p of nature.treePoints){if(!plots.some(plot=>pointInPlot(p.x,p.z,plot)))continue;hide(nature.trees[0],p.parts.trunk);if(p.pine)for(let n=0;n<3;n++)hide(nature.trees[1],p.parts.pine+n);else for(let n=0;n<4;n++)hide(nature.trees[2],p.parts.leaf+n);}for(const p of nature.rockPoints)if(plots.some(plot=>pointInPlot(p.x,p.z,plot)))hide(nature.rocks,p.index);for(const mesh of vegetationOriginals.keys())mesh.instanceMatrix.needsUpdate=true;}
 const detailedTrees=new THREE.Group();scene.add(detailedTrees);const treeBuckets=new Map();let treeLodSignature='';
 function treeBucket(type,capacity){if(treeBuckets.has(type))return treeBuckets.get(type);const model=assets.create('tree',type,{height:1});if(!model)return null;const bucket={meshes:[],matrices:[],count:0};model.updateMatrixWorld(true);model.traverse(o=>{if(!o.isMesh)return;const mesh=new THREE.InstancedMesh(o.geometry,o.material,capacity);mesh.castShadow=type==='fir';mesh.receiveShadow=true;mesh.userData.sharedAsset=true;mesh.frustumCulled=false;detailedTrees.add(mesh);bucket.meshes.push(mesh);bucket.matrices.push(o.matrixWorld.clone());});treeBuckets.set(type,bucket);return bucket;}
 function updateDetailedNature(){
  if(renderMode!=='webgl'||!state||!assets.has('tree','fir'))return;
  const closeCount=quality==='low'?12:24,farCount=quality==='low'?80:160,signature=[Math.round(view.x/5),Math.round(view.z/5),Math.round(view.distance/8),Math.round(view.azimuth*8),closeCount,assetRevision,vegetationSignature].join(':');if(signature===treeLodSignature)return;treeLodSignature=signature;
  const close=treeBucket('fir',24),far=treeBucket('fir-lod',160);for(const bucket of treeBuckets.values())bucket.count=0;
  vegetationSignature='';clearVegetation();const plots=state.structures||[],candidates=nature.treePoints.filter(p=>{if(plots.some(st=>pointInPlot(p.x,p.z,st,.7)))return false;const q=screenPoint(p.x,p.h+p.scale*.5,p.z);return q.visible&&q.x>-60&&q.x<width+60&&q.y>-80&&q.y<height+60;}).sort((a,b)=>Math.hypot(a.x-view.x,a.z-view.z)-Math.hypot(b.x-view.x,b.z-view.z)).slice(0,closeCount+(far?farCount:0));
  const hide=(mesh,index)=>{const array=mesh.instanceMatrix.array;for(let i=0;i<12;i++)array[index*16+i]=0;array[index*16+15]=1;},transform=new THREE.Object3D(),composed=new THREE.Matrix4();
  candidates.forEach((p,i)=>{const bucket=i<closeCount?close:far;if(!bucket)return;const at=bucket.count++;transform.position.set(p.x,p.h,p.z);transform.rotation.y=p.yaw;transform.scale.setScalar(p.scale);transform.updateMatrix();for(let n=0;n<bucket.meshes.length;n++){composed.multiplyMatrices(transform.matrix,bucket.matrices[n]);bucket.meshes[n].setMatrixAt(at,composed);}hide(nature.trees[0],p.parts.trunk);if(p.pine)for(let j=0;j<3;j++)hide(nature.trees[1],p.parts.pine+j);else for(let j=0;j<4;j++)hide(nature.trees[2],p.parts.leaf+j);});
  for(const bucket of treeBuckets.values())for(const mesh of bucket.meshes){mesh.count=bucket.count;mesh.instanceMatrix.needsUpdate=true;}for(const mesh of nature.trees)mesh.instanceMatrix.needsUpdate=true;
  treeLodSignature=[Math.round(view.x/5),Math.round(view.z/5),Math.round(view.distance/8),Math.round(view.azimuth*8),closeCount,assetRevision,vegetationSignature].join(':');
 }
 function fitBuilding(model,type){
  model.scale.setScalar(.78);model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(model,true),size=bounds.getSize(new THREE.Vector3()),fp=BUILDING_FOOTPRINTS[type]||{width:10,depth:10},factor=Math.min(1,(fp.width-.7)/Math.max(.1,size.x),(fp.depth-.7)/Math.max(.1,size.z));
  model.scale.multiplyScalar(factor);model.updateMatrixWorld(true);bounds.setFromObject(model,true);const center=bounds.getCenter(new THREE.Vector3());model.position.x-=center.x;model.position.y-=bounds.min.y;model.position.z-=center.z;return model;
 }
 function buildModel(type,variant=0){
  const fp=BUILDING_FOOTPRINTS[type]||{width:10,depth:10},spec=assets.getSpec('building',type),dimensions={width:fp.width-.7,depth:fp.depth-.7};if(spec?.maxHeight)dimensions.height=spec.maxHeight;
  const model=spec?.animated?assets.createAnimated('building',type,dimensions,variant):assets.create('building',type,dimensions,variant);
  return model||fitBuilding(createBuilding(type,materials,variant),type);
 }
 const wheelPosition=new THREE.Vector3();
 function updateWorkshops(time){
  for(const group of growth.values()){
   const model=group.userData.model;if(!model?.userData.animationInfo)continue;
   if(model.userData.waterPowered===undefined){
    // The authored wheel sits beside the building. Its actual world location,
    // rather than the centre of the plot, decides whether river water drives it.
    group.updateMatrixWorld(true);const socket=model.userData.socketLocal?.('wheel',wheelPosition);if(socket)wheelPosition.applyMatrix4(model.matrixWorld);else wheelPosition.copy(group.position);
    const riverDistance=Math.abs(wheelPosition.x-riverX(wheelPosition.z)),bankHeight=heightAt(wheelPosition.x,wheelPosition.z);
    model.userData.waterPowered=riverDistance<28&&bankHeight<MAP.waterLevel+7;
   }
   const operating=model.userData.waterPowered&&!group.userData.scaffold;
   model.userData.poseClip('idle',operating?time:0,true);model.userData.operating=operating;
  }
 }
 function scaffold(type){const f=BUILDING_FOOTPRINTS[type]||{width:9,depth:9},g=new THREE.Group(),w=f.width*.36,d=f.depth*.36;for(const x of[-w,w])for(const z of[-d,d])box(g,materials.wood,x,3,z,.14,6,.14);for(const y of[1.5,3.4,5.3]){for(const x of[-w,w])box(g,materials.wood,x,y,0,.13,.15,d*2+.3);for(const z of[-d,d])box(g,materials.wood,0,y,z,w*2+.3,.15,.13);}return mergeStatic(g);}
 function refreshStructures(){if(!state)return;for(const r of REGIONS){let fort=forts.get(r.id);if(fort.userData.assetRevision!==assetRevision&&assets.has('fortress',r.kind)){disposeModel(fort);fort=createFortress(r,materials,assets);fort.position.set(r.x,heightAt(r.x,r.z),r.z);fort.userData.assetRevision=assetRevision;scene.add(fort);forts.set(r.id,fort);}setFortressState(fort,state.regions[r.id],materials);}for(const line of [...territories,...politicalFills])line.material.color.set(factionColor(state.regions[line.userData.regionId]?.owner));
 const alive=new Set;for(const st of state.structures||[]){if(!BUILDING_FOOTPRINTS[st.type])continue;alive.add(st.id);const fp=BUILDING_FOOTPRINTS[st.type],signature=[st.type,st.status,st.level,st.x,st.z,st.rotation,st.baseY,st.terrainMin,assetRevision].join(':');let group=growth.get(st.id);if(!group||group.userData.signature!==signature){if(group)disposeModel(group);group=new THREE.Group();group.position.set(st.x,Number.isFinite(st.baseY)?st.baseY:heightAt(st.x,st.z),st.z);group.rotation.y=st.rotation||0;group.userData.signature=signature;group.userData.structureId=st.id;const rise=Math.max(.15,group.position.y-(st.terrainMin??group.position.y)+.15);box(group,materials.darkStone,0,-rise/2+.06,0,fp.width-.4,rise,fp.depth-.4);if(st.status!=='building'){const model=buildModel(st.type,st.variant||0);group.add(model);group.userData.model=model;}if(st.status==='building'||st.status==='upgrading'){const poles=scaffold(st.type);poles.userData.softwareDynamic=true;group.add(poles);group.userData.scaffold=poles;}scene.add(group);growth.set(st.id,group);}
 if(group.userData.scaffold){const job=state.jobs.find(j=>j.id===st.jobId),progress=job?clamp(1-job.remaining/job.duration,0,1):.1;group.userData.scaffold.scale.y=.5+.5*progress;}
 let target=structureTargets.get(st.id);if(!target){target=targetMesh('structure',st.id,st.x,st.z,Math.max(fp.width,fp.depth)*.43,3);structureTargets.set(st.id,target);}target.position.set(st.x,(Number.isFinite(st.baseY)?st.baseY:heightAt(st.x,st.z))+2.8,st.z);target.scale.set(Math.max(fp.width,fp.depth)*.43,4,Math.max(fp.width,fp.depth)*.43);target.updateMatrixWorld(true);
 }for(const [id,group]of growth)if(!alive.has(id)){disposeModel(group);growth.delete(id);const target=structureTargets.get(id);if(target){removeTarget(target);structureTargets.delete(id);}}clearVegetation();}
 const ghostMat=new THREE.MeshStandardMaterial({color:'#86c891',emissive:'#275836',emissiveIntensity:.35,roughness:.9,transparent:true,opacity:.38,depthWrite:false});const ghostOutline=new THREE.LineBasicMaterial({color:'#b8e7b4',transparent:true,opacity:.95,depthWrite:false});const ghostFill=new THREE.MeshBasicMaterial({color:'#7abd89',transparent:true,opacity:.12,depthWrite:false,side:THREE.DoubleSide});
 function showPlacement(next){if(!next){placement=null;placementModel=null;clearGroup(placementGroup);return;}const changedType=placement?.type!==next.type,fp=BUILDING_FOOTPRINTS[next.type]||{width:next.width||10,depth:next.depth||10};placement={...next,width:next.width||fp.width,depth:next.depth||fp.depth};if(changedType||!placementModel){clearGroup(placementGroup);placementModel=buildModel(next.type);placementModel.traverse(o=>{if(o.isMesh){o.material=ghostMat;o.castShadow=false;o.receiveShadow=false;}});placementGroup.add(placementModel);const rect=new THREE.Mesh(new THREE.PlaneGeometry(placement.width,placement.depth),ghostFill);rect.rotation.x=-Math.PI/2;rect.position.y=.08;placementGroup.add(rect);const w=placement.width/2,d=placement.depth/2;placementGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([[-w,.13,-d],[w,.13,-d],[w,.13,d],[-w,.13,d],[-w,.13,-d]].map(p=>new THREE.Vector3(...p))),ghostOutline));}
 placementGroup.position.set(next.x,Number.isFinite(next.baseY)?next.baseY:heightAt(next.x,next.z)+.12,next.z);placementGroup.rotation.y=next.rotation||0;const valid=next.valid!==false;ghostMat.color.set(valid?'#86c891':'#d4695d');ghostMat.emissive.set(valid?'#275836':'#61251e');ghostOutline.color.set(valid?'#b8e7b4':'#ee8a7b');ghostFill.color.set(valid?'#7abd89':'#cb6659');}

 function addPart(key,base,pos=[0,0,0],rotX=0,scale=[1,1,1],tint=null){const pool=pools[key];if(!pool||pool.count>=pool.mesh.instanceMatrix.count)return;temp.position.set(...pos);temp.rotation.set(rotX,0,0);temp.scale.set(...scale);temp.updateMatrix();matrix.multiplyMatrices(base,temp.matrix);pool.mesh.setMatrixAt(pool.count,matrix);if(tint)pool.mesh.setColorAt(pool.count,color.set(tint));pool.count++;}
 function safeActorPoint(key,x,z,anchor,radius=.8){
  let target={x,z};const valid=p=>isWorldPointWalkable(state,p,radius),clear=(a,b)=>isWorldSegmentWalkable(state,a,b,radius),origin=anchor||target;
  if(!valid(target)||(valid(origin)&&!clear(origin,target))){let found=null;if(valid(origin)){for(const t of[.82,.62,.4,.2,0]){const p={x:mix(origin.x,x,t),z:mix(origin.z,z,t)};if(valid(p)&&clear(origin,p)){found=p;break;}}}if(!found)for(let d=.7;d<=10&&!found;d+=.7)for(let i=0;i<16;i++){const a=i*Math.PI/8,p={x:x+Math.cos(a)*d,z:z+Math.sin(a)*d};if(valid(p)){found=p;break;}}if(!found)return null;target=found;}
  const previous=actorPositions.get(key);if(previous&&valid(previous)&&!clear(previous,target)){
   // A formation changes shape before a wall. Its outer members cannot jump
   // across the obstacle while the squad centre walks around the corner.
   let found=null;if(valid(origin)&&clear(previous,origin))found=origin;
   else{const direction=Math.atan2(target.z-previous.z,target.x-previous.x),step=Math.min(1.6,Math.max(.12,actorDelta*9));for(const turn of[.35,-.35,.7,-.7,1.2,-1.2,1.57,-1.57,2,-2]){const a=direction+turn,p={x:previous.x+Math.cos(a)*step,z:previous.z+Math.sin(a)*step};if(valid(p)&&clear(previous,p)){found=p;break;}}}
   target=found||previous;
  }
  actorPositions.set(key,target);activeActors.add(key);return target;
 }
 const gearCache=new Map(),rightHand=new THREE.Vector3(),leftHand=new THREE.Vector3();
 function equipment(type,owner){
  const key=type+':'+owner;if(gearCache.has(key)){const a=gearCache.get(key);return{weapon:a.weapon?.clone(true)||null,shield:a.shield?.clone(true)||null};}
  const weapon=new THREE.Group();let shield=null;
  if(type==='spear'||type==='cavalry'){
   cylinder(weapon,materials.wood,0,.3,0,.024,2.75,8);cylinder(weapon,materials.iron,0,1.68,0,.041,.17,8);
   const blade=new THREE.Mesh(new THREE.ConeGeometry(.085,.39,4),materials.iron);blade.position.y=1.91;weapon.add(blade);
  }else if(type==='sword'){
   box(weapon,materials.leather,0,0,0,.045,.22,.045);cylinder(weapon,materials.iron,0,-.145,0,.06,.055,10);box(weapon,materials.iron,0,.14,0,.32,.037,.046);
   const blade=new THREE.Mesh(new THREE.CylinderGeometry(.004,.063,.84,4),materials.iron);blade.position.y=.57;blade.rotation.y=Math.PI/4;weapon.add(blade);box(weapon,materials.darkIron,0,.54,.029,.013,.67,.002);
  }else if(type==='archer'){
   const points=[];for(let i=0;i<=20;i++){const a=-1.1+i/20*2.2;points.push(new THREE.Vector3(Math.cos(a)*.44-.28,Math.sin(a)*.79,0));}
   const bow=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),20,.022,5,false),materials.wood);weapon.add(bow);
   const string=new THREE.Line(new THREE.BufferGeometry().setFromPoints([points[0],points[20]]),new THREE.LineBasicMaterial({color:'#b5a58b'}));weapon.add(string);box(weapon,materials.leather,.16,0,0,.057,.18,.047);
  }
  if(type==='spear'||type==='sword'||type==='cavalry'){
   shield=new THREE.Group();const shape=new THREE.Shape();shape.moveTo(-.34,.36);shape.lineTo(.34,.36);shape.quadraticCurveTo(.4,-.02,0,-.56);shape.quadraticCurveTo(-.4,-.02,-.34,.36);
   const ge=new THREE.ExtrudeGeometry(shape,{depth:.055,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.018,bevelThickness:.012});const face=new THREE.Mesh(ge,materials.flags[owner]||materials.flagNeutral);shield.add(face);
   box(shield,materials.paleStone,0,-.01,.087,.067,.61,.012);box(shield,materials.paleStone,0,.1,.087,.37,.057,.013);
   for(const [x,y]of[[-.29,.28],[.29,.28],[-.27,-.04],[.27,-.04],[0,-.44]]){const rivet=new THREE.Mesh(new THREE.SphereGeometry(.023,6,4),materials.iron);rivet.position.set(x,y,.087);shield.add(rivet);}
  }
  mergeStatic(weapon);if(shield)mergeStatic(shield);for(const g of[weapon,shield])g?.traverse(o=>{if(o.isMesh)o.userData.sharedAsset=true;});gearCache.set(key,{weapon:type==='civilian'?null:weapon,shield});return{weapon:type==='civilian'?null:weapon.clone(true),shield:shield?.clone(true)||null};
 }
 const saddlePoint=new THREE.Vector3(),pelvisPoint=new THREE.Vector3(),mountedUp=new THREE.Vector3(0,1,0);
 function positionMount(actor,x,z,yaw,walking,scale,phase){
  if(!assets.has('mount','horse'))return false;
  if(!actor.mount){actor.mount=assets.createAnimated('mount','horse',{height:2.06,width:1.3,depth:2.96});if(!actor.mount)return false;actor.mount.userData.mounted=true;scene.add(actor.mount);}
  const mount=actor.mount,info=mount.userData.animationInfo;mount.visible=true;mount.position.set(x,walkHeight(x,z),z);mount.rotation.y=yaw;mount.scale.setScalar(scale);
  const prior=mount.userData.lastGround,travel=prior?Math.hypot(x-prior.x,z-prior.z):0;mount.userData.lastGround={x,z};mount.userData.travel=(mount.userData.travel||0)+travel;
  if(mount.userData.gaitOffset===undefined)mount.userData.gaitOffset=(phase*.13)%1;
  const speed=actorDelta>0?travel/actorDelta:0;mount.userData.gaitSpeed=mix(mount.userData.gaitSpeed||0,speed,.25);
  const gait=walking?(mount.userData.gaitSpeed<1.8&&info.walk?'walk':'trot'):'idle';
  if(gait==='idle')mount.userData.poseClip('idle',animationTime+mount.userData.gaitOffset*(info.idleDuration||1),true);
  else{const stride=info.strideLength[gait]||1.45,duration=info[gait+'Duration'];mount.userData.poseClip(gait,(mount.userData.travel/stride+mount.userData.gaitOffset)*duration,true);}
  mount.userData.gait=gait;
  const anchor=mount.userData.socketLocal?.('rider',saddlePoint)||mount.userData.socketLocal?.('saddle',saddlePoint);if(!anchor)saddlePoint.set(0,mount.userData.dimensions.height*.7,-.14);
  saddlePoint.applyMatrix4(mount.matrixWorld);actor.socket('hips',pelvisPoint).multiplyScalar(scale).applyAxisAngle(mountedUp,yaw);actor.object.position.copy(saddlePoint).sub(pelvisPoint);actor.object.updateMatrixWorld(true);actor.mountSeat=saddlePoint.clone();return true;
 }
 function detailedSoldier(key,x,z,yaw,owner,type,phase,walking,scale,attacking){
  if(renderMode!=='webgl'||!assets.has('unit',type))return false;
  const projectedActor=screenPoint(x,walkHeight(x,z)+1,z),inFrame=projectedActor.visible&&projectedActor.x>-55&&projectedActor.x<width+55&&projectedActor.y>-70&&projectedActor.y<height+70;let existing=actors.get(key);if(!inFrame){if(existing){existing.object.visible=false;if(existing.mount)existing.mount.visible=false;}return 'culled';}
  const distant=Math.hypot(x-camera.position.x,z-camera.position.z)> (quality==='low'?185:280),limit=quality==='low'?64:112;if(detailFrameCount>=limit||(distant&&view.distance>280)){if(existing){existing.object.visible=false;if(existing.mount)existing.mount.visible=false;}return false;}detailFrameCount++;
  let actor=existing;if(!actor){actor=assets.createCharacter(type,{height:type==='civilian'?1.74:1.9,variant:Math.round(phase*3)%31});if(!actor)return false;actor.gear=equipment(type,owner);if(actor.gear.weapon)actor.object.add(actor.gear.weapon);if(actor.gear.shield)actor.object.add(actor.gear.shield);scene.add(actor.object);const disposeActor=actor.dispose;actor.dispose=()=>{if(actor.mount){actor.mount.userData.disposeAnimation?.();actor.mount.removeFromParent();}disposeActor();};actors.set(key,actor);}
  actor.object.visible=true;actor.lastVisibleFrame=frame;actor.object.scale.setScalar(scale);actor.object.position.set(x,walkHeight(x,z)+(type==='cavalry'?.9:0),z);actor.object.rotation.y=yaw;
  actor.update({time:animationTime,phase,walking:walking&&type!=='cavalry',attacking,role:type});
  const mounted=type==='cavalry'&&positionMount(actor,x,z,yaw,walking,scale,phase);
  if(actor.gear.weapon){actor.socket(type==='archer'?'left':'right',rightHand);actor.gear.weapon.position.copy(rightHand);actor.gear.weapon.rotation.set(type==='sword'?(attacking?-.35+Math.sin(animationTime*5)*.65:-.16):type==='cavalry'?-.35:0,0,type==='archer'?-.12:.05);}
  if(actor.gear.shield){actor.socket('left',leftHand);actor.gear.shield.position.copy(leftHand).add(new THREE.Vector3(-.04,.06,.04));actor.gear.shield.rotation.set(.08,-.3,.13);}
  return mounted?'mounted':'humanoid';
 }
 function soldier(key,x,z,yaw,owner,type,phase,walking,scale=1,anchor=null,attacking=false){
  const point=safeActorPoint(key,x,z,anchor,type==='cavalry'?UNIT_CLEARANCE.cavalry:UNIT_CLEARANCE.spear);if(!point)return;x=point.x;z=point.z;
  const detailed=detailedSoldier(key,x,z,yaw,owner,type,phase,walking,scale,attacking);
  if(!detailed||type==='cavalry'&&detailed==='humanoid')primitiveSoldier(x,z,yaw,owner,type,phase,walking,scale,!!detailed);
 }
 function primitiveSoldier(x,z,yaw,owner,type,phase,walking,scale=1,horseOnly=false){const y=walkHeight(x,z),horse=type==='cavalry',lift=horse?1.68:0;temp.position.set(x,y,z);temp.rotation.set(0,yaw,0);temp.scale.setScalar(scale);temp.updateMatrix();const base=temp.matrix.clone(),cloth=factionColor(owner);if(horse){addPart('horse',base);addPart('horseArmor',base,[0,0,0],0,[1,1,1],cloth);for(const sx of[-.32,.32])for(const zz of[-.6,.63]){const sway=walking?Math.sin(phase+(sx*zz>0?Math.PI:0))*.55:0;addPart('leg',base,[sx,.66,zz],sway,[1.45,1.5,1.45]);addPart('foot',base,[sx,.14,zz+Math.sin(sway)*.25],0,[1.2,1.1,1.45]);}}
 if(horseOnly)return;const rider=base.clone().multiply(new THREE.Matrix4().makeTranslation(0,lift,0));addPart('torso',rider,[0,0,0],0,[1,1,1],cloth);addPart('head',rider);if(type!=='civilian'){addPart('helmet',rider);if(type!=='archer')addPart('armor',rider);}for(const s of[-1,1]){const sway=horse?0:walking?Math.sin(phase+(s<0?Math.PI:0))*.5:0;addPart('leg',rider,[s*.18,.49,0],sway,horse?[1,.8,1]:[1,1,1]);addPart('foot',rider,[s*(horse?.4:.18),horse?.2:.12,Math.sin(sway)*.35+.07]);addPart('arm',rider,[s*.4,1.3,0],-sway*.67,[1,1,1],cloth);}if(type==='spear'||horse){addPart('spear',rider);addPart('spearhead',rider);addPart('shield',rider,[0,0,0],0,[1,1,1],cloth);}else if(type==='sword'){addPart('sword',rider);addPart('shield',rider,[0,0,0],0,[1,1,1],cloth);}else if(type==='archer')addPart('bow',rider);}
 const siegeLaunches=new Map(),launchLocal=new THREE.Vector3();
 function updateSiegePose(s,model,time,moving){
  const combat=['attack','siege'].includes(s.activity),info=model.userData.animationInfo,cooldown=UNIT_TYPES[s.type].cooldown;
  const projectile=s.type==='trebuchet'?(state.effects||[]).find(e=>e.type==='stone'&&e.sourceId===s.id):null;
  if(projectile&&model.userData.lastShotId!==projectile.id){
   model.userData.lastShotId=projectile.id;model.userData.lastShotAt=state.t-projectile.age;
   const point=model.userData.socketAt?.('attack',info?.releaseAt||0,'launch',launchLocal);
   if(point){const sn=Math.sin(s.heading||0),cs=Math.cos(s.heading||0);siegeLaunches.set(projectile.id,{x:projectile.x+point.x*cs+point.z*sn,y:walkHeight(projectile.x,projectile.z)+point.y,z:projectile.z-point.x*sn+point.z*cs,sourceId:s.id,releaseAt:info.releaseAt});}
  }
  const recovering=Number.isFinite(model.userData.lastShotAt)&&state.t-model.userData.lastShotAt<cooldown;
  if(info?.attackDuration&&model.userData.poseClip&&!moving&&(combat||recovering)){
   const since=clamp(cooldown-(s.attackClock||0),0,cooldown),sourceTime=(info.releaseAt+since/cooldown*info.attackDuration)%info.attackDuration;
   model.userData.poseClip('attack',sourceTime,true);if(info.loadedObject)model.userData.setNodeVisible(info.loadedObject,sourceTime<info.releaseAt||sourceTime>=info.reloadAt);
   model.userData.firingPhase={sourceTime,releaseAt:info.releaseAt,cooldown,attackClock:s.attackClock};
  }else{model.userData.animate?.(time,false,moving);if(info?.loadedObject)model.userData.setNodeVisible(info.loadedObject,true);model.userData.firingPhase=null;}
  if(model.userData.mechanism){if(s.type==='ram')model.userData.mechanism.position.z=combat?Math.sin(time*4)*.48:0;else model.userData.mechanism.rotation.x=-.53+(combat?Math.sin(time*1.12)*.25:0);}
 }
 function updateTroops(time){if(!state)return;activeActors.clear();detailFrameCount=0;for(const p of Object.values(pools))p.count=0;const live=new Set();for(const s of state.squads){if(s.hp<=0)continue;live.add(s.id);let target=squadTargets.get(s.id);if(!target){target=targetMesh('squad',s.id,s.x,s.z,s.type==='cavalry'?5.3:4.2,2);squadTargets.set(s.id,target);}target.position.set(s.x,walkHeight(s.x,s.z)+2,s.z);target.updateMatrixWorld(true);const moving=s.activity==='march';let yaw=Number.isFinite(s.heading)?s.heading:0;if(moving&&s.path?.length){const next=s.path[0];if(Number.isFinite(next.x))yaw=Math.atan2(next.x-s.x,next.z-s.z);}const count=Math.max(1,Math.min(s.men||UNIT_TYPES[s.type]?.men||6,12)),spacing=s.type==='cavalry'?3.2:1.5;
 let banner=squadFlags.get(s.id);if(!banner){banner=new THREE.Group();banner.userData.softwareDynamic=true;cylinder(banner,materials.darkWood,0,2.25,0,.037,4.5,6);const cloth=new THREE.Mesh(new THREE.PlaneGeometry(1.3,.75,3,1),materials.flags[s.owner]||materials.flagNeutral);cloth.position.set(.67,3.75,0);cloth.castShadow=true;banner.add(cloth);banner.userData.cloth=cloth;scene.add(banner);squadFlags.set(s.id,banner);}banner.position.set(s.x-Math.sin(yaw)*2.7,walkHeight(s.x,s.z),s.z-Math.cos(yaw)*2.7);banner.rotation.y=yaw+.4;banner.userData.cloth.rotation.y=Math.sin(time*2.1+s.x)*.13;

 if(s.type==='ram'||s.type==='trebuchet'){let model=sieges.get(s.id);if(model&&!model.userData.assetId&&assets.has('siege',s.type)){disposeModel(model);model=null;}if(!model){model=assets.createAnimated('siege',s.type,{width:4.4,depth:7.1,height:s.type==='ram'?4.3:8.5})||createSiege(s.type,materials,s.owner);model.userData.softwareDynamic=true;scene.add(model);sieges.set(s.id,model);}model.position.set(s.x,walkHeight(s.x,s.z),s.z);model.rotation.y=yaw;updateSiegePose(s,model,time,moving);for(let i=0;i<2;i++){const side=i?1:-1,dx=Math.cos(yaw)*side*2.7,dz=-Math.sin(yaw)*side*2.7;soldier('crew:'+s.id+':'+i,s.x+dx,s.z+dz,yaw,s.owner,'civilian',time*7+i,moving,1,s);}}
 else for(let i=0;i<count;i++){let ox,oz;const bridgeCrossing=BRIDGE_DECKS.some(b=>Math.abs(s.x-b.x)<27&&Math.abs(s.z-b.z)<10);if(bridgeCrossing){const columns=s.type==='cavalry'?1:2;ox=(i%columns-(columns-1)/2)*1.25;oz=(Math.floor(i/columns)-1)*1.5;}else if(s.formation==='line'){ox=(i-(count-1)/2)*spacing;oz=0;}else if(s.formation==='column'){ox=(i%2-.5)*spacing;oz=(Math.floor(i/2)-1)*spacing;}else if(s.formation==='wedge'){const row=Math.floor((Math.sqrt(8*i+1)-1)/2),col=i-row*(row+1)/2;ox=(col-row/2)*spacing;oz=-row*spacing;}else{ox=(i%3-1)*spacing;oz=(Math.floor(i/3)-.5)*spacing;}const x=s.x+Math.cos(yaw)*ox+Math.sin(yaw)*oz,z=s.z-Math.sin(yaw)*ox+Math.cos(yaw)*oz;soldier('squad:'+s.id+':'+i,x,z,yaw,s.owner,s.type,time*(s.type==='cavalry'?10:7)+i*.73,moving,1,s,['attack','siege'].includes(s.activity));}}
 for(const [id,p]of squadTargets)if(!live.has(id)){const i=pickers.indexOf(p);if(i>=0)pickers.splice(i,1);squadTargets.delete(id);const banner=squadFlags.get(id);if(banner){banner.removeFromParent();squadFlags.delete(id);}const model=sieges.get(id);if(model){disposeModel(model);sieges.delete(id);}}
 for(const n of state.nodes){const count=Math.min(n.workers||0,4);for(let i=0;i<count;i++){const phase=time*.55+i*2.4,a=phase*.3,r=3.5+i*.6,x=n.x+Math.cos(a)*r,z=n.z+Math.sin(a)*r;soldier('worker:'+n.id+':'+i,x,z,-a,n.owner||state.regions[n.regionId]?.owner||'neutral','civilian',time*6+i,true,1);}}
 for(const st of state.structures||[]){if(!['building','upgrading'].includes(st.status))continue;const fp=BUILDING_FOOTPRINTS[st.type];for(let i=0;i<2;i++){const a=time*.09+i*Math.PI,x=st.x+Math.cos(a)*(fp.width/2+1.7),z=st.z+Math.sin(a)*(fp.depth/2+1.7);soldier('builder:'+st.id+':'+i,x,z,Math.atan2(st.x-x,st.z-z),'player','civilian',time*6+i,true,1);}}
 for(const r of REGIONS){if(state.regions[r.id]?.owner!=='player')continue;for(let i=0;i<3;i++){const t=time*.06+i*2.09,rad=r.kind==='castle'?27:20,x=r.x+Math.cos(t)*rad,z=r.z+Math.sin(t)*rad;soldier('citizen:'+r.id+':'+i,x,z,-t,'neutral','civilian',time*6+i,true,1);}}
 for(const [id,actor]of actors)if(!activeActors.has(id)){actor.dispose();actors.delete(id);}
 // Keep a small reusable cache, rather than retaining every rig ever seen in a
 // long campaign. Visible meshes remain under the separate per-frame budget.
 const cacheLimit=quality==='low'?96:160;if(actors.size>cacheLimit){const dormant=[...actors].filter(([,a])=>!a.object.visible).sort((a,b)=>(a[1].lastVisibleFrame||0)-(b[1].lastVisibleFrame||0));for(const[id,actor]of dormant){if(actors.size<=cacheLimit)break;actor.dispose();actors.delete(id);}}
 for(const id of actorPositions.keys())if(!activeActors.has(id))actorPositions.delete(id);
 for(const p of Object.values(pools)){p.mesh.count=p.count;p.mesh.instanceMatrix.needsUpdate=true;if(p.mesh.instanceColor)p.mesh.instanceColor.needsUpdate=true;}
 }
 const effectModels=new Map();
 function flyingStone(effect){
  const source=sieges.get(effect.sourceId),name=source?.userData.animationInfo?.loadedObject,loaded=name?source.getObjectByName(name):null;
  if(loaded){loaded.updateWorldMatrix(true,true);const stone=loaded.clone(true),root=new THREE.Group(),scale=new THREE.Vector3(),orientation=new THREE.Quaternion();loaded.getWorldScale(scale);loaded.getWorldQuaternion(orientation);stone.position.set(0,0,0);stone.quaternion.copy(orientation);stone.scale.copy(scale);stone.visible=true;root.add(stone);root.updateMatrixWorld(true);const center=new THREE.Box3().setFromObject(root).getCenter(new THREE.Vector3());stone.position.sub(center);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.userData.sharedAsset=true;}});root.userData.projectileAsset=source.userData.assetId;return root;}
  return new THREE.Mesh(new THREE.DodecahedronGeometry(.62,0),materials.rock);
 }
 function updateEffects(time){
  if(!state)return;const live=new Set();
  for(const e of state.effects||[]){
   live.add(e.id);let model=effectModels.get(e.id);
   if(!model){
    if(e.type==='arrow'){model=new THREE.Mesh(new THREE.CylinderGeometry(.07,.05,1.7,4),materials.darkWood);model.rotation.x=Math.PI/2;}
    else if(e.type==='stone')model=flyingStone(e);
    else model=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:e.type==='capture'?'#e4c678':'#c5b18b',transparent:true,opacity:.5,depthWrite:false,wireframe:false}));
    if(e.type==='stone'){model.userData.launch=siegeLaunches.get(e.id)||{x:e.x,y:walkHeight(e.x,e.z)+2,z:e.z,sourceId:e.sourceId};model.userData.effectId=e.id;}
    effectsGroup.add(model);effectModels.set(e.id,model);
   }
   const t=clamp(e.age/(e.life||1),0,1),tx=e.tx??e.x,tz=e.tz??e.z,start=model.userData.launch;
   const x=mix(start?.x??e.x,tx,t),z=mix(start?.z??e.z,tz,t),h=mix(start?.y??(walkHeight(e.x,e.z)+2),walkHeight(tx,tz)+2,t);
   if(e.type==='arrow'||e.type==='stone'){
    const arc=e.type==='stone'?15:7;model.position.set(x,h+Math.sin(t*Math.PI)*arc,z);
    if(e.type==='arrow'){const tangent=new THREE.Vector3(tx-e.x,Math.cos(t*Math.PI)*arc*Math.PI,tz-e.z).normalize();model.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),tangent);}else model.rotation.set(time*3,time*2,0);
   }else{model.position.set(x,h-1.6+t*3,z);model.scale.setScalar(.8+t*4);model.material.opacity=(1-t)*.28;}
  }
  for(const [id,model]of effectModels)if(!live.has(id)){model.removeFromParent();model.traverse(o=>{if(o.geometry&&!o.userData.sharedAsset)o.geometry.dispose();if(o.material&&!o.userData.sharedAsset&&o.material!==materials.darkWood&&o.material!==materials.rock)o.material.dispose();});effectModels.delete(id);}
  for(const id of siegeLaunches.keys())if(!live.has(id))siegeLaunches.delete(id);
 }
 function label(text,x,y,{small=false,color='#9eac9a',kind,id,sub,health}={}){if(x<18||x>width-18||y<5||y>height-12)return;ctx.font=`${small?'500 10':'600 11'}px Inter, system-ui, sans-serif`;const w=ctx.measureText(text).width+18,h=sub?34:21;const left=x-w/2,top=y-h;ctx.fillStyle='rgba(17,23,22,.79)';ctx.beginPath();ctx.roundRect(left,top,w,h,3);ctx.fill();ctx.fillStyle=color;ctx.fillRect(left,top,2,h);ctx.fillStyle='#ece7d9';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,top+11);if(sub){ctx.font='9px Inter,system-ui,sans-serif';ctx.fillStyle='#c0c4b3';ctx.fillText(sub,x,top+26);}if(Number.isFinite(health)){ctx.fillStyle='rgba(10,14,13,.9)';ctx.fillRect(left+4,top+h+3,w-8,3);ctx.fillStyle=color;ctx.fillRect(left+4,top+h+3,(w-8)*health,3);}if(kind)labelBoxes.push({x:left,y:top,w,h:h+6,kind,id});}
 function drawOverlay(){ctx.setTransform(pixelRatio,0,0,pixelRatio,0,0);ctx.clearRect(0,0,width,height);labelBoxes=[];if(!state)return;const mobile=width<700;
 for(const r of REGIONS){const s=state.regions[r.id];if(!s)continue;const selected=selection?.kind==='region'&&selection.id===r.id,distanceToView=Math.hypot(r.x-view.x,r.z-view.z);if(mobile&&distanceToView>view.distance*.8&&!selected)continue;const p=screenPoint(r.x,heightAt(r.x,r.z)+(r.kind==='castle'?29:21),r.z);if(!p.visible)continue;label(r.name,p.x,p.y,{color:factionColor(s.owner),kind:'region',id:r.id,health:s.fortHp/s.maxFortHp,sub:selected?(s.owner==='player'?'ΤΟ ΦΕΟΥΔΟ ΣΟΥ':FACTIONS[s.owner]?.shortName):null});}
 if(selection?.kind==='structure'){const st=state.structures?.find(a=>a.id===selection.id);if(st){const p=screenPoint(st.x,(st.baseY??heightAt(st.x,st.z))+10,st.z);if(p.visible)label(BUILDINGS[st.type]?.name||st.type,p.x,p.y,{kind:'structure',id:st.id,color:factionColor(state.regions[st.regionId]?.owner),sub:st.status==='building'?'ΕΡΓΟΤΑΞΙΟ':`ΒΑΘΜΙΔΑ ${st.level}`});}}
 for(const s of state.squads){const isSelected=selection?.id===s.id||selection?.ids?.includes(s.id),p=screenPoint(s.x,walkHeight(s.x,s.z)+(s.type==='trebuchet'?8:5.2),s.z);if(!p.visible||p.x<0||p.x>width||p.y<0||p.y>height)continue;const w=isSelected?45:24;ctx.fillStyle='rgba(12,19,17,.78)';ctx.fillRect(p.x-w/2,p.y,w,4);ctx.fillStyle=factionColor(s.owner);ctx.fillRect(p.x-w/2+1,p.y+1,(w-2)*clamp(s.hp/s.maxHp,0,1),2);if(isSelected){ctx.fillStyle='#f0e9d5';ctx.font='600 10px Inter,system-ui,sans-serif';ctx.textAlign='center';ctx.fillText(UNIT_TYPES[s.type]?.name||s.type,p.x,p.y-8);}else if(view.distance>250){ctx.beginPath();ctx.arc(p.x,p.y+10,4,0,Math.PI*2);ctx.fillStyle=factionColor(s.owner);ctx.fill();}labelBoxes.push({x:p.x-17,y:p.y-7,w:34,h:22,kind:'squad',id:s.id});}
 if(mapMode==='resources'||selection?.kind==='node'){for(const n of state.nodes){if(mapMode!=='resources'&&n.id!==selection.id)continue;const p=screenPoint(n.x,heightAt(n.x,n.z)+5,n.z);if(p.visible)label(({wood:'ΞΥΛΕΙΑ',food:'ΤΡΟΦΙΜΑ',stone:'ΠΕΤΡΑ',iron:'ΣΙΔΗΡΟΣ'})[n.type],p.x,p.y,{small:true,kind:'node',id:n.id,color:'#b6a770',sub:n.workers?`${n.workers} εργάτες`:undefined});}}
 if(boxSelect){const x=Math.min(boxSelect.x0,boxSelect.x1),y=Math.min(boxSelect.y0,boxSelect.y1),w=Math.abs(boxSelect.x1-boxSelect.x0),h=Math.abs(boxSelect.y1-boxSelect.y0);ctx.strokeStyle='#d9cca9';ctx.fillStyle='rgba(201,183,140,.12)';ctx.lineWidth=1;ctx.fillRect(x,y,w,h);ctx.strokeRect(x+.5,y+.5,w,h);}
 }
 function frameLoop(now){if(disposed)return;raf=requestAnimationFrame(frameLoop);if(renderMode==='software'&&now-lastTime<100)return;const dt=clamp((now-lastTime)/1000,0,renderMode==='software'?.2:.08);lastTime=now;if(document.hidden)return;const time=clock.getElapsedTime();if(inputEnabled){const speed=desired.distance*.46*dt,forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);desired.x+=(-Math.sin(view.azimuth)*forward+Math.cos(view.azimuth)*side)*speed;desired.z+=(-Math.cos(view.azimuth)*forward-Math.sin(view.azimuth)*side)*speed;if(keys.has('KeyQ'))desired.azimuth+=dt*.65;if(keys.has('KeyE'))desired.azimuth-=dt*.65;desired.x=clamp(desired.x,MAP.minX-30,MAP.maxX+30);desired.z=clamp(desired.z,MAP.minZ-30,MAP.maxZ+30);}materials.water.normalMap.offset.y=time*.018;materials.water.normalMap.offset.x=time*.005;updateCamera(dt);actorDelta=state?.paused?0:dt*(state?.speed||1);if(!state?.paused)animationTime+=actorDelta;updateTroops(animationTime);updateWorkshops(animationTime);updateEffects(animationTime);if(frame%8===0)updateDetailedNature();if(frame%6===0)drawSelection();renderer.render(scene,camera);drawOverlay();frame++;if(!ready&&assetsSettled){ready=true;callbacks.onReady?.({renderer:renderMode,assets:assets.getStats()});}}
 const localPoint=e=>{const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};};
 function pointerDown(e){if(!inputEnabled||e.button>2)return;const p=localPoint(e);pointers.set(e.pointerId,p);canvas.setPointerCapture?.(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:desired.distance};if(pointer)pointer.moved=true;return;}pointer={id:e.pointerId,x:p.x,y:p.y,lastX:p.x,lastY:p.y,button:e.button,shift:e.shiftKey,moved:false};if(e.shiftKey&&e.button===0&&!placement)boxSelect={x0:p.x,y0:p.y,x1:p.x,y1:p.y};}
 function pointerMove(e){if(!inputEnabled)return;const p=localPoint(e);if(placement&&e.pointerType!=='touch'&&(!pointer||!pointer.moved)&&performance.now()-lastPlacementHover>30){const point=groundAt(p.x,p.y);if(point){lastPlacementHover=performance.now();callbacks.onPlacementHover?.(point);}}if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(pinch&&pointers.size===2){const[a,b]=[...pointers.values()];desired.distance=clamp(pinch.zoom*pinch.distance/Math.max(10,Math.hypot(a.x-b.x,a.y-b.y)),32,680);return;}if(!pointer||pointer.id!==e.pointerId)return;const dx=p.x-pointer.lastX,dy=p.y-pointer.lastY;pointer.lastX=p.x;pointer.lastY=p.y;if(Math.hypot(p.x-pointer.x,p.y-pointer.y)>6)pointer.moved=true;if(boxSelect){boxSelect.x1=p.x;boxSelect.y1=p.y;return;}if(pointer.moved){const scale=desired.distance*.00138;desired.x-=Math.cos(view.azimuth)*dx*scale+Math.sin(view.azimuth)*dy*scale*1.6;desired.z-= -Math.sin(view.azimuth)*dx*scale+Math.cos(view.azimuth)*dy*scale*1.6;}}
 function pointerUp(e){const p=localPoint(e);pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;pointer=null;return;}if(!pointer)return;const start=pointer;pointer=null;if(boxSelect){const b=boxSelect;boxSelect=null;if(state&&start.moved){const ids=state.squads.filter(s=>s.owner==='player').filter(s=>{const p=screenPoint(s.x,walkHeight(s.x,s.z)+1,s.z);return p.x>=Math.min(b.x0,b.x1)&&p.x<=Math.max(b.x0,b.x1)&&p.y>=Math.min(b.y0,b.y1)&&p.y<=Math.max(b.y0,b.y1);}).map(s=>s.id);callbacks.onBoxSelect?.(ids);return;}}if(!inputEnabled||start.moved)return;const point=groundAt(p.x,p.y);if(placement){if(point&&start.button===0)callbacks.onPlacementPick?.(point);return;}const selection=pick(p.x,p.y);if(start.button===2){if(point)callbacks.onContext?.(point,selection);return;}if(selection)callbacks.onSelect?.(selection,{shiftKey:!!e.shiftKey,button:start.button});else if(point)callbacks.onGround?.(point,{shiftKey:!!e.shiftKey,button:start.button});}
 function wheel(e){if(!inputEnabled)return;e.preventDefault();desired.distance=clamp(desired.distance*Math.exp(e.deltaY*.001),32,680);}
 function keyDown(e){if(e.defaultPrevented||!inputEnabled||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName)||e.target?.isContentEditable)return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE'].includes(e.code)){keys.add(e.code);e.preventDefault();}}
 function keyUp(e){keys.delete(e.code);}
 const contextmenu=e=>e.preventDefault(),blur=()=>{keys.clear();pointers.clear();pointer=null;pinch=null;};canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',blur);canvas.addEventListener('contextmenu',contextmenu);canvas.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);window.addEventListener('resize',resize);canvas.style.touchAction='none';raf=requestAnimationFrame(frameLoop);
 return{
 setState(s){if(state&&state!==s){actorPositions.clear();siegeLaunches.clear();for(const model of sieges.values()){delete model.userData.lastShotId;delete model.userData.lastShotAt;}}state=s;refreshStructures();},
 setSelection(s){selection=s;drawSelection();},
 setPlacement(next){showPlacement(next);},
 clearPlacement(){showPlacement(null);},
 focus(target){const p=typeof target==='string'?REGIONS.find(r=>r.id===target):target;if(p){desired.x=p.x;desired.z=p.z;desired.distance=width<700?150:165;}},
 home(){desired.x=homeRegion.x+10;desired.z=homeRegion.z+12;desired.distance=width<700?168:175;desired.azimuth=.65;desired.elevation=.86;},
 zoom(delta){desired.distance=clamp(desired.distance*Math.exp(delta*.13),32,680);},
 setMapMode(mode){mapMode=mode;for(const l of territories)l.material.opacity=mode==='political'?.8:mode==='resources'?.11:.24;for(const fill of politicalFills)fill.visible=mode==='political';},
 setQuality(q){quality=q;renderer.setQuality?.(q);renderer.shadowMap.enabled=q!=='low';scene.fog.density=q==='low'?.002:.00165;resize();},
 setInsets(next){insets={...insets,...next};},
 setInputEnabled(value){inputEnabled=!!value;if(!value){blur();boxSelect=null;}},
 getDebugState(){return{ready,frame,renderer:renderMode==='software'?'three-software':'three-webgl',software:renderer.info.software||null,camera:{...view},desired:{...desired},viewport:{width,height},selection,placement:placement?{...placement}:null,structures:[...growth.keys()],workshops:[...growth].filter(([,group])=>group.userData.model?.userData.animationInfo).map(([id,group])=>({id,assetId:group.userData.model.userData.assetId,waterPowered:group.userData.model.userData.waterPowered,operating:group.userData.model.userData.operating,animation:group.userData.model.userData.animationState?.()})),mapMode,inputEnabled,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,treeCount:nature.treeCount,detailedTreeCount:[...treeBuckets.values()].reduce((sum,b)=>sum+b.count,0),treeLods:[...treeBuckets].map(([type,b])=>({type,count:b.count})),assets:assets.getStats(),detailedActors:actors.size,visibleDetailedActors:detailFrameCount,mountedActors:[...actors].filter(([,actor])=>actor.mount?.visible).map(([id,actor])=>({id,assetId:actor.mount.userData.assetId,seat:actor.mountSeat?.toArray(),animation:actor.mount.userData.animationState?.(),gait:actor.mount.userData.gait,travel:actor.mount.userData.travel})),actorBudget:quality==='low'?64:112,siegeModels:[...sieges].map(([id,model])=>({id,assetId:model.userData.assetId||null,phase:model.userData.firingPhase,animation:model.userData.animationState?.()})),projectiles:[...effectModels].filter(([,model])=>model.userData.launch).map(([id,model])=>({id,assetId:model.userData.projectileAsset||null,launch:model.userData.launch,position:model.position.toArray()})),actorPositions:[...actorPositions].map(([id,p])=>({id,...p})),fortresses:forts.size,labels:labelBoxes.map(l=>({...l})),squads:state?.squads.map(s=>({id:s.id,type:s.type,x:s.x,z:s.z,y:walkHeight(s.x,s.z),screen:screenPoint(s.x,walkHeight(s.x,s.z)+1,s.z)}))||[]};},
 destroy(){disposed=true;cancelAnimationFrame(raf);resizeObserver?.disconnect();for(const [name,fn]of[['pointerdown',pointerDown],['pointermove',pointerMove],['pointerup',pointerUp],['pointercancel',blur],['contextmenu',contextmenu],['wheel',wheel]])canvas.removeEventListener(name,fn);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);overlay.remove();scene.traverse(o=>{if(o.geometry&&!o.isInstancedMesh)o.geometry.dispose();});for(const actor of actors.values())actor.dispose();actors.clear();assets.dispose();materials.dispose();renderer.dispose();}
 };
}
