import * as THREE from './vendor/three.module.js';
import {MAP,REGIONS,RESOURCE_NODES,FACTIONS,BRIDGES,UNIT_TYPES,BUILDINGS,heightAt,riverX,regionAt} from './feouda-data.js?v=2.0.0';
import {createMaterials} from './feouda-materials.js?v=2.0.0';
import {createFortress,setFortressState,createHouse,createBuilding,createBridge,createSiege,createResource,soldierGeometries,box,cylinder,mergeStatic} from './feouda-models.js?v=2.0.0';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
const random=seed=>()=>{seed=Math.imul(seed^seed>>>15,1|seed);seed^=seed+Math.imul(seed^seed>>>7,61|seed);return((seed^seed>>>14)>>>0)/4294967296;};
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const factionColor=o=>FACTIONS[o]?.color||'#9c9a82';
const BRIDGE_DECKS=BRIDGES.map(b=>({...b,deckY:Math.max(heightAt(b.x-17,b.z),heightAt(b.x+17,b.z))+.4}));
function walkHeight(x,z){const ground=heightAt(x,z);for(const b of BRIDGE_DECKS){const d=Math.abs(x-b.x);if(d<25&&Math.abs(z-b.z)<4.1){const t=clamp((25-d)/8,0,1);return Math.max(ground,mix(ground,b.deckY,t));}}return ground;}
function environmentHeight(x,z){const edge=Math.max(Math.abs(x)-MAP.maxX,Math.abs(z)-MAP.maxZ,0),far=clamp(edge/100,0,1);return heightAt(x,z)+far*(26+30*Math.sin(x*.007+1.8)**2+35*Math.cos(z*.009+.4)**2+18*Math.sin(x*.019+z*.014));}
function pathGeometry(points,width,y=.095){const p=[],uv=[],index=[];for(let i=0;i<points.length;i++){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],dx=next[0]-prev[0],dz=next[1]-prev[1],len=Math.hypot(dx,dz)||1;for(const side of[-1,1]){const x=points[i][0]-dz/len*width*.5*side,z=points[i][1]+dx/len*width*.5*side;p.push(x,walkHeight(x,z)+y,z);uv.push(side<0?0:1,i*.06);}if(i){const j=i*2;index.push(j-2,j,j-1,j-1,j,j+1);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(index);g.computeVertexNormals();return g;}
function smoothPath(points,step=3){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],0,p[1])));return curve.getSpacedPoints(Math.max(4,Math.ceil(curve.getLength()/step))).map(p=>[p.x,p.z]);}
function makeTerrain(m){const width=1280,depth=1040,sx=256,sz=208,geometry=new THREE.PlaneGeometry(width,depth,sx,sz);geometry.rotateX(-Math.PI/2);const p=geometry.attributes.position,colors=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),h=environmentHeight(x,z);p.setY(i,h);const lush=(Math.sin(x*.046+z*.029)*Math.cos(z*.031)+Math.sin(x*.011-z*.007))*.13;const bank=Math.abs(x-riverX(z)),grassy=bank<24?-.03:0;const c=new THREE.Color().setRGB(clamp(.77+lush+grassy,.48,.99),clamp(.91+lush,.53,1),clamp(.63+lush,.43,.9));if(h>40)c.lerp(new THREE.Color('#bcb7a1'),clamp((h-35)/100,0,.64));colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,m.ground);mesh.receiveShadow=true;mesh.userData.ground=true;return mesh;}
function makeRiver(m){const group=new THREE.Group(),p=[],uv=[],idx=[],left=[],right=[];for(let i=0;i<=300;i++){const z=-510+i*3.4,x=riverX(z),s=.3+Math.sin(z*.043)*.4;let edge=5.6;for(let j=0;j<12;j++){if(heightAt(x+edge,z)>MAP.waterLevel)break;edge+=.6;}p.push(x-edge,MAP.waterLevel+s*.015,z,x+edge,MAP.waterLevel-s*.015,z);uv.push(0,i/20,1,i/20);left.push(new THREE.Vector3(x-edge+.1,MAP.waterLevel+.045,z));right.push(new THREE.Vector3(x+edge-.1,MAP.waterLevel+.045,z));if(i){const a=i*2;idx.push(a-2,a-1,a,a-1,a+1,a);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const surface=new THREE.Mesh(geo,m.water);surface.receiveShadow=true;group.add(surface);for(const points of[left,right])group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#b9c9ad',transparent:true,opacity:.37})));return group;}
function makeSky(scene){const geometry=new THREE.SphereGeometry(1800,32,20),material=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#789faa')},bottom:{value:new THREE.Color('#d4d7c6')}},vertexShader:'varying vec3 vPosition;void main(){vPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPosition;void main(){float h=normalize(vPosition).y;gl_FragColor=vec4(mix(bottom,top,pow(max(h,0.),.58)),1.);}'});scene.add(new THREE.Mesh(geometry,material));}
function treeGeometry(){const g=new THREE.CylinderGeometry(.015,1,1,11,6,true);g.translate(0,.5,0);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),a=Math.atan2(z,x),n=1+Math.sin(a*7+y*19)*.17+Math.cos(a*11-y*13)*.075;p.setXYZ(i,x*n,y+Math.sin(a*5+y*25)*.038*(1-y),z*n);}g.computeVertexNormals();return g;}
function addNature(scene,m){const r=random(813992),treePoints=[];const isRoad=(x,z)=>Math.abs(z)<5&&x<0;
 for(let i=0;i<2300;i++){let x=mix(-390,390,r()),z=mix(-305,305,r());if(Math.abs(x-riverX(z))<14||REGIONS.some(a=>Math.hypot(a.x-x,a.z-z)<(a.kind==='castle'?37:29))||isRoad(x,z))continue;const cluster=(Math.sin(x*.044)*Math.cos(z*.052)+Math.sin(x*.019+z*.047));if(cluster<.15&&r()>.14)continue;if(RESOURCE_NODES.some(n=>n.type!=='wood'&&Math.hypot(n.x-x,n.z-z)<8))continue;treePoints.push({x,z,h:environmentHeight(x,z),scale:5.8+r()*6.7,pine:r()>.34,yaw:r()*Math.PI*2});}
 for(const n of RESOURCE_NODES.filter(n=>n.type==='wood'))for(let j=0;j<24;j++){const a=j*2.399,d=5+Math.sqrt(j)*2,x=n.x+Math.cos(a)*d,z=n.z+Math.sin(a)*d;treePoints.push({x,z,h:heightAt(x,z),scale:6.1+r()*5.4,pine:r()>.2,yaw:r()*Math.PI*2});}
 const trunk=new THREE.InstancedMesh(new THREE.CylinderGeometry(.18,.27,1,7),m.trunk,treePoints.length),pine=new THREE.InstancedMesh(treeGeometry(),m.foliage,treePoints.length*3),leaf=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),m.foliageLight,treePoints.length*4);const d=new THREE.Object3D(),c=new THREE.Color;let pi=0,li=0;treePoints.forEach((p,i)=>{d.position.set(p.x,p.h+p.scale*.28,p.z);d.scale.set(p.scale*.45,p.scale*.64,p.scale*.45);d.rotation.set(0,p.yaw,0);d.updateMatrix();trunk.setMatrixAt(i,d.matrix);if(p.pine){for(let j=0;j<3;j++){d.position.set(p.x,p.h+p.scale*(.27+j*.21),p.z);d.scale.set(p.scale*(.38-j*.067),p.scale*(.73-j*.13),p.scale*(.38-j*.067));d.updateMatrix();pine.setMatrixAt(pi,d.matrix);pine.setColorAt(pi++,c.setHSL(.21+r()*.045,.22+r()*.2,.43+r()*.15));}}else{for(let j=0;j<4;j++){d.position.set(p.x+Math.cos(j*2.4)*p.scale*.18,p.h+p.scale*(.58+(j%2)*.2),p.z+Math.sin(j*2.4)*p.scale*.18);d.scale.set(p.scale*.33,p.scale*.38,p.scale*.32);d.updateMatrix();leaf.setMatrixAt(li,d.matrix);leaf.setColorAt(li++,c.setHSL(.18+r()*.065,.25+r()*.15,.52+r()*.17));}}});pine.count=pi;leaf.count=li;for(const mesh of[trunk,pine,leaf]){mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();scene.add(mesh);}
 const rocks=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1,0),m.rock,420);let ri=0;for(let i=0;i<500;i++){const x=mix(-390,390,r()),z=mix(-305,305,r());if(REGIONS.some(a=>Math.hypot(a.x-x,a.z-z)<34)||Math.abs(x-riverX(z))<10)continue;const scale=1+r()*3.5;d.position.set(x,environmentHeight(x,z)+scale*.22,z);d.rotation.set(r(),r()*6,r());d.scale.set(scale,scale*.61,scale*.8);d.updateMatrix();rocks.setMatrixAt(ri++,d.matrix);if(ri>=420)break;}rocks.count=ri;rocks.castShadow=rocks.receiveShadow=true;scene.add(rocks);return{treeCount:treePoints.length,trees:[trunk,pine,leaf],rocks};}
function addRoads(scene,m){const pairs=[['home','firwood'],['home','farmland'],['home','crossing'],['farmland','quarry'],['ironhold','pass'],['ironhold','highlands'],['highlands','sunkeep'],['sunkeep','quarry'],['crossing','pass'],['crossing','highlands']];for(const [aId,bId]of pairs){const a=REGIONS.find(r=>r.id===aId),b=REGIONS.find(r=>r.id===bId);let points=[[a.x,a.z+18]];if((a.x-riverX(a.z))*(b.x-riverX(b.z))<0){const bridge=BRIDGES.reduce((best,v)=>Math.hypot(a.x-v.x,a.z-v.z)+Math.hypot(b.x-v.x,b.z-v.z)<Math.hypot(a.x-best.x,a.z-best.z)+Math.hypot(b.x-best.x,b.z-best.z)?v:best);const sign=a.x<bridge.x?-1:1;points.push([bridge.x+sign*22,bridge.z],[bridge.x+sign*9,bridge.z],[bridge.x-sign*9,bridge.z],[bridge.x-sign*22,bridge.z]);}else points.push([mix(a.x,b.x,.5)+6,mix(a.z,b.z,.5)]);points.push([b.x,b.z+13]);const path=smoothPath(points,2.2);let start=0;for(let i=0;i<=path.length;i++){const river=i<path.length&&Math.abs(path[i][0]-riverX(path[i][1]))<8;if(river||i===path.length){if(i-start>1){const mesh=new THREE.Mesh(pathGeometry(path.slice(start,i),3.5),m.road);mesh.receiveShadow=true;scene.add(mesh);}start=i+1;}}}}
function createPools(scene,m){const ge=soldierGeometries(),pools={},capacity=720;const cloth=m.cloth.clone();cloth.color.set('#ffffff');const materials={torso:cloth,armor:m.iron,head:m.skin,helmet:m.iron,leg:m.leather,foot:m.boots,arm:cloth,shield:cloth,spear:m.wood,spearhead:m.iron,sword:m.iron,bow:m.wood,horse:m.leather,horseArmor:cloth};for(const [key,geometry]of Object.entries(ge)){const mesh=new THREE.InstancedMesh(geometry,materials[key],key==='leg'||key==='foot'||key==='arm'?capacity*4:capacity);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.count=0;mesh.castShadow=true;mesh.receiveShadow=false;mesh.frustumCulled=false;scene.add(mesh);pools[key]={mesh,count:0};}return pools;}

export function createBattlefield(canvas,callbacks={}){
 let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(error){callbacks.onError?.(error);throw error;}
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#bbc9be',.00165);const camera=new THREE.PerspectiveCamera(43,1,.25,2100),materials=createMaterials();makeSky(scene);scene.add(new THREE.HemisphereLight('#d1e5e8','#675735',2.05));const sun=new THREE.DirectionalLight('#fff0cb',3.3);sun.position.set(-160,250,180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-140;sun.shadow.camera.right=140;sun.shadow.camera.top=140;sun.shadow.camera.bottom=-140;sun.shadow.camera.near=1;sun.shadow.camera.far=650;sun.shadow.normalBias=.045;sun.shadow.bias=-.00015;sun.shadow.radius=2;scene.add(sun);scene.add(sun.target);
 const terrain=makeTerrain(materials);scene.add(terrain);const river=makeRiver(materials);scene.add(river);
 const rippleData=new Uint8Array(128*128*4);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=(y*128+x)*4,a=x/128*Math.PI*2,b=y/128*Math.PI*2;rippleData[i]=128+Math.sin(a*7+b*3)*22+Math.sin(a*15-b*8)*9;rippleData[i+1]=128+Math.cos(a*5-b*9)*19;rippleData[i+2]=249;rippleData[i+3]=255;}const ripple=new THREE.DataTexture(rippleData,128,128);ripple.wrapS=ripple.wrapT=THREE.RepeatWrapping;ripple.repeat.set(2,9);ripple.needsUpdate=true;materials.water.normalMap=ripple;materials.water.normalScale=new THREE.Vector2(.22,.22);materials.water.needsUpdate=true;addRoads(scene,materials);const nature=addNature(scene,materials);
 const forts=new Map(),nodes=new Map(),pickers=[],territories=[],politicalFills=[],growth=new Map(),construction=new Map(),sieges=new Map(),squadTargets=new Map(),squadFlags=new Map();
 const pickMat=new THREE.MeshBasicMaterial({visible:false}),pickGeo=new THREE.SphereGeometry(1,8,6);function targetMesh(kind,id,x,z,r,y=2){const a=new THREE.Mesh(pickGeo,pickMat);a.position.set(x,heightAt(x,z)+y,z);a.scale.set(r,r,r);a.userData={kind,id};a.updateMatrixWorld(true);pickers.push(a);return a;}
 for(const r of REGIONS){const g=createFortress(r,materials);g.position.set(r.x,heightAt(r.x,r.z),r.z);scene.add(g);forts.set(r.id,g);targetMesh('region',r.id,r.x,r.z,r.kind==='castle'?21:r.kind==='town'?14:11,7);const points=[];for(let j=0;j<r.polygon.length;j++){const a=r.polygon[j],b=r.polygon[(j+1)%r.polygon.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]);for(let k=0;k<len;k+=3){const t=k/len,x=mix(a[0],b[0],t),z=mix(a[1],b[1],t);points.push(new THREE.Vector3(x,heightAt(x,z)+.19,z));}}points.push(points[0].clone());const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:factionColor(r.owner),transparent:true,opacity:.24,depthWrite:false}));line.userData.regionId=r.id;scene.add(line);territories.push(line);}
 const cells=new Map(REGIONS.map(r=>[r.id,[]]));for(let x=MAP.minX;x<MAP.maxX;x+=5)for(let z=-175;z<175;z+=5){const id=regionAt(x+2.5,z+2.5);if(!cells.has(id))continue;const p=cells.get(id),corners=[[x,z],[x+5,z],[x,z+5],[x+5,z+5]];for(const i of[0,2,1,1,2,3]){const[a,b]=corners[i];p.push(a,heightAt(a,b)+.15,b);}}for(const r of REGIONS){const ge=new THREE.BufferGeometry();ge.setAttribute('position',new THREE.Float32BufferAttribute(cells.get(r.id),3));const fill=new THREE.Mesh(ge,new THREE.MeshBasicMaterial({color:factionColor(r.owner),transparent:true,opacity:.17,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2}));fill.userData.regionId=r.id;fill.visible=false;scene.add(fill);politicalFills.push(fill);}
 for(const n of RESOURCE_NODES){const model=createResource(n.type,materials);model.position.set(n.x,heightAt(n.x,n.z),n.z);scene.add(model);nodes.set(n.id,model);targetMesh('node',n.id,n.x,n.z,4.8,2);if(n.type==='food'){const farm=createBuilding('farm',materials);farm.position.set(n.x+5,heightAt(n.x+5,n.z-5),n.z-5);farm.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,p.getY(i)+heightAt(farm.position.x+p.getX(i),farm.position.z+p.getZ(i))-farm.position.y);p.needsUpdate=true;o.geometry.computeVertexNormals();});scene.add(farm);}}
 for(const b of BRIDGE_DECKS){const g=createBridge(materials,34,8,b.deckY+1.1);g.rotation.y=Math.PI/2;g.position.set(b.x,b.deckY-.6,b.z);scene.add(g);for(const sign of[-1,1]){const points=[];for(let d=16;d<=26;d+=1)points.push([b.x+sign*d,b.z]);const ramp=new THREE.Mesh(pathGeometry(points,7.1,.01),materials.stone);ramp.receiveShadow=ramp.castShadow=true;scene.add(ramp);const wallGroup=new THREE.Group();for(let d=17;d<25;d+=1){const x=b.x+sign*d,ground=heightAt(x,b.z),top=walkHeight(x,b.z);if(top-ground>.12)box(wallGroup,materials.darkStone,x,(ground+top)/2,b.z,1.1,top-ground,7);}mergeStatic(wallGroup);scene.add(wallGroup);}}
 const pools=createPools(scene,materials),selectionGroup=new THREE.Group(),ordersGroup=new THREE.Group(),effectsGroup=new THREE.Group();scene.add(selectionGroup,ordersGroup,effectsGroup);
 const overlay=document.createElement('canvas');overlay.className='battlefield-labels';Object.assign(overlay.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'1'});canvas.parentNode?.appendChild(overlay);const ctx=overlay.getContext('2d');
 let state=null,selection=null,mapMode='terrain',inputEnabled=true,quality='high',width=1,height=1,pixelRatio=1,lastTime=0,animationTime=0,raf=0,disposed=false,frame=0,ready=false,insets={left:0,right:0,top:0,bottom:0},labelBoxes=[],pointer=null,boxSelect=null,pinch=null;
 const homeRegion=REGIONS.find(r=>r.id==='home')||REGIONS[0],view={x:homeRegion.x+10,z:homeRegion.z+12,distance:175,azimuth:.65,elevation:.86},desired={...view},keys=new Set(),pointers=new Map(),clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),projected=new THREE.Vector3(),temp=new THREE.Object3D(),matrix=new THREE.Matrix4(),local=new THREE.Matrix4(),q=new THREE.Quaternion(),v=new THREE.Vector3(),one=new THREE.Vector3(1,1,1),color=new THREE.Color();
 function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);pixelRatio=Math.min(window.devicePixelRatio||1,quality==='low'?1.25:1.65);renderer.setPixelRatio(pixelRatio);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();overlay.width=Math.round(width*pixelRatio);overlay.height=Math.round(height*pixelRatio);overlay.style.width=width+'px';overlay.style.height=height+'px';if(!ready&&width<700){view.distance=desired.distance=168;view.azimuth=desired.azimuth=.58;}}
 const resizeObserver=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;resizeObserver?.observe(canvas);resize();
 function updateCamera(dt){const f=1-Math.exp(-dt*8);for(const k of['x','z','distance','azimuth','elevation'])view[k]=mix(view[k],desired[k],f);const h=heightAt(view.x,view.z)+5,dist=view.distance,horizontal=Math.cos(view.elevation)*dist;const target=new THREE.Vector3(view.x,h,view.z);camera.position.set(view.x+Math.sin(view.azimuth)*horizontal,h+Math.sin(view.elevation)*dist,view.z+Math.cos(view.azimuth)*horizontal);camera.lookAt(target);camera.updateMatrixWorld();const offsetX=(insets.left-insets.right)/2,offsetY=(insets.top-insets.bottom)/2;camera.setViewOffset(width,height,-offsetX,-offsetY,width,height);sun.position.set(view.x-170,240+h,view.z+130);sun.target.position.set(view.x,h,view.z);sun.target.updateMatrixWorld();}
 function screenPoint(x,y,z){projected.set(x,y,z).project(camera);return{x:(projected.x+1)*width/2,y:(1-projected.y)*height/2,visible:projected.z<1&&projected.z>-1};}
 function ray(x,y){mouse.set(x/width*2-1,-y/height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster;}
 function groundAt(x,y){const hit=ray(x,y).intersectObject(terrain,false)[0];return hit?{x:clamp(hit.point.x,MAP.minX+2,MAP.maxX-2),z:clamp(hit.point.z,MAP.minZ+2,MAP.maxZ-2)}:null;}
 function pick(x,y){for(let i=labelBoxes.length-1;i>=0;i--){const a=labelBoxes[i];if(x>=a.x&&x<=a.x+a.w&&y>=a.y&&y<=a.y+a.h)return{kind:a.kind,id:a.id};}const hit=ray(x,y).intersectObjects(pickers,false);return hit.length?{kind:hit[0].object.userData.kind,id:hit[0].object.userData.id}:null;}
 function clearGroup(g){for(const a of[...g.children]){a.removeFromParent();a.geometry?.dispose();if(a.material?.userData?.transient)a.material.dispose();}}
 function circlePoints(x,z,r){const points=[];for(let i=0;i<=80;i++){const a=i*Math.PI/40,px=x+Math.cos(a)*r,pz=z+Math.sin(a)*r;points.push(new THREE.Vector3(px,walkHeight(px,pz)+.27,pz));}return points;}
 function drawSelection(){clearGroup(selectionGroup);clearGroup(ordersGroup);if(!selection||!state)return;let items=[];if(selection.kind==='army'||selection.kind==='squad'){const ids=selection.ids||[selection.id];items=state.squads.filter(s=>ids.includes(s.id)).map(s=>({...s,r:s.type==='cavalry'?5.6:4.2}));}else if(selection.kind==='region'){const r=REGIONS.find(r=>r.id===selection.id);if(r)items=[{...r,r:r.kind==='castle'?25:r.kind==='town'?19:15}];}else{const n=state.nodes.find(n=>n.id===selection.id);if(n)items=[{...n,r:6.3}];}for(const a of items){const mat=new THREE.LineBasicMaterial({color:'#e4d3a3',transparent:true,opacity:.94,depthWrite:false});mat.userData.transient=true;selectionGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(circlePoints(a.x,a.z,a.r)),mat));if(a.order&&a.order.type!=='hold'){let dest=a.order;if(dest.targetId){dest=state.squads.find(s=>s.id===dest.targetId)||REGIONS.find(r=>r.id===dest.targetId)||dest;}if(dest.regionId)dest=REGIONS.find(r=>r.id===dest.regionId)||dest;if(Number.isFinite(dest.x)&&Number.isFinite(dest.z)){const path=a.path?.length?[{x:a.x,z:a.z},...a.path]:[{x:a.x,z:a.z},{x:dest.x,z:dest.z}],p=path.map(v=>new THREE.Vector3(v.x,heightAt(v.x,v.z)+.35,v.z));const mm=new THREE.LineDashedMaterial({color:a.order.type==='attack'?'#d58365':'#ddd5b9',dashSize:1.9,gapSize:1.4,transparent:true,opacity:.64,depthWrite:false});mm.userData.transient=true;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),mm);line.computeLineDistances();ordersGroup.add(line);}}}}
 function refreshStructures(){if(!state)return;for(const r of REGIONS){const s=state.regions[r.id],g=forts.get(r.id);setFortressState(g,s,materials);if(!s)continue;for(const [type,level]of Object.entries(s.buildings||{})){for(let i=0;i<Math.min(level,4);i++){const key=r.id+':'+type+':'+i;if(growth.has(key))continue;const typeIndex=Math.max(0,Object.keys(BUILDINGS).indexOf(type)),a=(typeIndex%7)*.86+i*.3+.38,rad=(r.kind==='castle'?33:25)+Math.floor(typeIndex/7)*12+i*5;const model=createBuilding(type,materials,typeIndex+i);model.position.set(r.x+Math.cos(a)*rad,0,r.z+Math.sin(a)*rad);model.position.y=heightAt(model.position.x,model.position.z);model.rotation.y=-a+Math.PI/2;model.scale.setScalar(.78);scene.add(model);growth.set(key,model);}}}for(const line of [...territories,...politicalFills]){line.material.color.set(factionColor(state.regions[line.userData.regionId]?.owner));}
 const active=new Set;for(const job of state.jobs||[]){if(job.kind!=='build')continue;const r=REGIONS.find(r=>r.id===job.regionId);if(!r)continue;active.add(job.id);let model=construction.get(job.id);if(!model){model=new THREE.Group();const typeIndex=Math.max(0,Object.keys(BUILDINGS).indexOf(job.type)),level=state.regions[r.id]?.buildings[job.type]||0,a=(typeIndex%7)*.86+level*.3+.38,rad=(r.kind==='castle'?33:25)+Math.floor(typeIndex/7)*12+level*5;for(const x of[-2.5,2.5])for(const z of[-2.4,2.4])box(model,materials.wood,x,3,z,.14,6,.14);for(const y of[1.6,3.4,5.2]){for(const x of[-2.5,2.5])box(model,materials.wood,x,y,0,.13,.15,5.1);for(const z of[-2.4,2.4])box(model,materials.wood,0,y,z,5.3,.15,.13);}box(model,materials.stone,0,.3,0,4.5,.6,4.4);model.position.set(r.x+Math.cos(a)*rad,0,r.z+Math.sin(a)*rad);model.position.y=heightAt(model.position.x,model.position.z);mergeStatic(model);scene.add(model);construction.set(job.id,model);}model.scale.y=.45+.55*clamp(1-job.remaining/job.duration,0,1);}for(const [id,g]of construction)if(!active.has(id)){g.removeFromParent();g.traverse(o=>o.geometry?.dispose());construction.delete(id);}
 }
 function addPart(key,base,pos=[0,0,0],rotX=0,scale=[1,1,1],tint=null){const pool=pools[key];if(!pool||pool.count>=pool.mesh.instanceMatrix.count)return;temp.position.set(...pos);temp.rotation.set(rotX,0,0);temp.scale.set(...scale);temp.updateMatrix();matrix.multiplyMatrices(base,temp.matrix);pool.mesh.setMatrixAt(pool.count,matrix);if(tint)pool.mesh.setColorAt(pool.count,color.set(tint));pool.count++;}
 function soldier(x,z,yaw,owner,type,phase,walking,scale=1){const y=walkHeight(x,z),horse=type==='cavalry',lift=horse?1.68:0;temp.position.set(x,y,z);temp.rotation.set(0,yaw,0);temp.scale.setScalar(scale);temp.updateMatrix();const base=temp.matrix.clone(),cloth=factionColor(owner);if(horse){addPart('horse',base);addPart('horseArmor',base,[0,0,0],0,[1,1,1],cloth);for(const sx of[-.32,.32])for(const zz of[-.6,.63]){const sway=walking?Math.sin(phase+(sx*zz>0?Math.PI:0))*.55:0;addPart('leg',base,[sx,.66,zz],sway,[1.45,1.5,1.45]);addPart('foot',base,[sx,.14,zz+Math.sin(sway)*.25],0,[1.2,1.1,1.45]);}}
 const rider=base.clone().multiply(new THREE.Matrix4().makeTranslation(0,lift,0));addPart('torso',rider,[0,0,0],0,[1,1,1],cloth);addPart('head',rider);if(type!=='civilian'){addPart('helmet',rider);if(type!=='archer')addPart('armor',rider);}for(const s of[-1,1]){const sway=horse?0:walking?Math.sin(phase+(s<0?Math.PI:0))*.5:0;addPart('leg',rider,[s*.18,.49,0],sway,horse?[1,.8,1]:[1,1,1]);addPart('foot',rider,[s*(horse?.4:.18),horse?.2:.12,Math.sin(sway)*.35+.07]);addPart('arm',rider,[s*.4,1.3,0],-sway*.67,[1,1,1],cloth);}if(type==='spear'||horse){addPart('spear',rider);addPart('spearhead',rider);addPart('shield',rider,[0,0,0],0,[1,1,1],cloth);}else if(type==='sword'){addPart('sword',rider);addPart('shield',rider,[0,0,0],0,[1,1,1],cloth);}else if(type==='archer')addPart('bow',rider);}
 function updateTroops(time){if(!state)return;for(const p of Object.values(pools))p.count=0;const live=new Set();for(const s of state.squads){if(s.hp<=0)continue;live.add(s.id);let target=squadTargets.get(s.id);if(!target){target=targetMesh('squad',s.id,s.x,s.z,s.type==='cavalry'?5.3:4.2,2);squadTargets.set(s.id,target);}target.position.set(s.x,walkHeight(s.x,s.z)+2,s.z);target.updateMatrixWorld(true);const moving=s.activity==='moving'||s.order?.type==='move'||s.path?.length>0;let yaw=Number.isFinite(s.heading)?s.heading:0;if(s.path?.length){const next=s.path[0];if(Number.isFinite(next.x))yaw=Math.atan2(next.x-s.x,next.z-s.z);}const count=Math.max(1,Math.min(s.men||UNIT_TYPES[s.type]?.men||6,12)),spacing=s.type==='cavalry'?3.2:1.5;
 let banner=squadFlags.get(s.id);if(!banner){banner=new THREE.Group();cylinder(banner,materials.darkWood,0,2.25,0,.037,4.5,6);const cloth=new THREE.Mesh(new THREE.PlaneGeometry(1.3,.75,3,1),materials.flags[s.owner]||materials.flagNeutral);cloth.position.set(.67,3.75,0);cloth.castShadow=true;banner.add(cloth);banner.userData.cloth=cloth;scene.add(banner);squadFlags.set(s.id,banner);}banner.position.set(s.x-Math.sin(yaw)*2.7,walkHeight(s.x,s.z),s.z-Math.cos(yaw)*2.7);banner.rotation.y=yaw+.4;banner.userData.cloth.rotation.y=Math.sin(time*2.1+s.x)*.13;

 if(s.type==='ram'||s.type==='trebuchet'){let model=sieges.get(s.id);if(!model){model=createSiege(s.type,materials,s.owner);scene.add(model);sieges.set(s.id,model);}model.position.set(s.x,walkHeight(s.x,s.z),s.z);model.rotation.y=yaw;const action=s.activity==='attacking'||s.attackClock>0&&s.order?.type==='attack';if(model.userData.mechanism){if(s.type==='ram')model.userData.mechanism.position.z=action?Math.sin(time*4)*.48:0;else model.userData.mechanism.rotation.x=-.53+(action?Math.sin(time*1.12)*.25:0);}for(let i=0;i<2;i++){const side=i?1:-1,dx=Math.cos(yaw)*side*2.2,dz=-Math.sin(yaw)*side*2.2;soldier(s.x+dx,s.z+dz,yaw,s.owner,'civilian',time*7+i,moving);}}
 else for(let i=0;i<count;i++){let ox,oz;const bridgeCrossing=BRIDGE_DECKS.some(b=>Math.abs(s.x-b.x)<27&&Math.abs(s.z-b.z)<10);if(bridgeCrossing){const columns=s.type==='cavalry'?1:2;ox=(i%columns-(columns-1)/2)*1.25;oz=(Math.floor(i/columns)-1)*1.5;}else if(s.formation==='line'){ox=(i-(count-1)/2)*spacing;oz=0;}else if(s.formation==='column'){ox=(i%2-.5)*spacing;oz=(Math.floor(i/2)-1)*spacing;}else if(s.formation==='wedge'){const row=Math.floor((Math.sqrt(8*i+1)-1)/2),col=i-row*(row+1)/2;ox=(col-row/2)*spacing;oz=-row*spacing;}else{ox=(i%3-1)*spacing;oz=(Math.floor(i/3)-.5)*spacing;}const x=s.x+Math.cos(yaw)*ox+Math.sin(yaw)*oz,z=s.z-Math.sin(yaw)*ox+Math.cos(yaw)*oz;soldier(x,z,yaw,s.owner,s.type,time*(s.type==='cavalry'?10:7)+i*.73,moving);}}
 for(const [id,p]of squadTargets)if(!live.has(id)){const i=pickers.indexOf(p);if(i>=0)pickers.splice(i,1);squadTargets.delete(id);const banner=squadFlags.get(id);if(banner){banner.removeFromParent();squadFlags.delete(id);}const model=sieges.get(id);if(model){model.removeFromParent();sieges.delete(id);}}
 for(const n of state.nodes){const count=Math.min(n.workers||0,4);for(let i=0;i<count;i++){const phase=time*.55+i*2.4,a=phase*.3,r=3.5+i*.6,x=n.x+Math.cos(a)*r,z=n.z+Math.sin(a)*r;soldier(x,z,-a,n.owner||state.regions[n.regionId]?.owner||'neutral','civilian',time*6+i,true,.88);}}
 for(const r of REGIONS){if(state.regions[r.id]?.owner!=='player')continue;for(let i=0;i<3;i++){const t=time*.06+i*2.09,rad=r.kind==='castle'?27:20,x=r.x+Math.cos(t)*rad,z=r.z+Math.sin(t)*rad;soldier(x,z,-t,'neutral','civilian',time*6+i,true,.85);}}
 for(const p of Object.values(pools)){p.mesh.count=p.count;p.mesh.instanceMatrix.needsUpdate=true;if(p.mesh.instanceColor)p.mesh.instanceColor.needsUpdate=true;}
 }
 const effectModels=new Map();function updateEffects(time){if(!state)return;const live=new Set();for(const e of state.effects||[]){live.add(e.id);let model=effectModels.get(e.id);if(!model){if(e.type==='arrow'){model=new THREE.Mesh(new THREE.CylinderGeometry(.07,.05,1.7,4),materials.darkWood);model.rotation.x=Math.PI/2;}else if(e.type==='stone')model=new THREE.Mesh(new THREE.DodecahedronGeometry(.62,0),materials.rock);else model=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:e.type==='capture'?'#e4c678':'#c5b18b',transparent:true,opacity:.5,depthWrite:false,wireframe:false}));effectsGroup.add(model);effectModels.set(e.id,model);}const t=clamp(e.age/(e.life||1),0,1),tx=e.tx??e.x,tz=e.tz??e.z,x=mix(e.x,tx,t),z=mix(e.z,tz,t),h=mix(walkHeight(e.x,e.z),walkHeight(tx,tz),t);if(e.type==='arrow'||e.type==='stone'){const arc=e.type==='stone'?15:7;model.position.set(x,h+2+Math.sin(t*Math.PI)*arc,z);if(e.type==='arrow'){const tangent=new THREE.Vector3(tx-e.x,Math.cos(t*Math.PI)*arc*Math.PI,tz-e.z).normalize();model.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),tangent);}else model.rotation.set(time*3,time*2,0);}else{model.position.set(x,h+.4+t*3,z);model.scale.setScalar(.8+t*4);model.material.opacity=(1-t)*.28;}}for(const [id,m]of effectModels)if(!live.has(id)){m.removeFromParent();m.geometry.dispose();if(m.material!==materials.darkWood&&m.material!==materials.rock)m.material.dispose();effectModels.delete(id);}}
 function label(text,x,y,{small=false,color='#9eac9a',kind,id,sub,health}={}){if(x<18||x>width-18||y<5||y>height-12)return;ctx.font=`${small?'500 10':'600 11'}px Inter, system-ui, sans-serif`;const w=ctx.measureText(text).width+18,h=sub?34:21;const left=x-w/2,top=y-h;ctx.fillStyle='rgba(17,23,22,.79)';ctx.beginPath();ctx.roundRect(left,top,w,h,3);ctx.fill();ctx.fillStyle=color;ctx.fillRect(left,top,2,h);ctx.fillStyle='#ece7d9';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,top+11);if(sub){ctx.font='9px Inter,system-ui,sans-serif';ctx.fillStyle='#c0c4b3';ctx.fillText(sub,x,top+26);}if(Number.isFinite(health)){ctx.fillStyle='rgba(10,14,13,.9)';ctx.fillRect(left+4,top+h+3,w-8,3);ctx.fillStyle=color;ctx.fillRect(left+4,top+h+3,(w-8)*health,3);}if(kind)labelBoxes.push({x:left,y:top,w,h:h+6,kind,id});}
 function drawOverlay(){ctx.setTransform(pixelRatio,0,0,pixelRatio,0,0);ctx.clearRect(0,0,width,height);labelBoxes=[];if(!state)return;const mobile=width<700;
 for(const r of REGIONS){const s=state.regions[r.id];if(!s)continue;const selected=selection?.kind==='region'&&selection.id===r.id,distanceToView=Math.hypot(r.x-view.x,r.z-view.z);if(mobile&&distanceToView>view.distance*.8&&!selected)continue;const p=screenPoint(r.x,heightAt(r.x,r.z)+(r.kind==='castle'?29:21),r.z);if(!p.visible)continue;label(r.name,p.x,p.y,{color:factionColor(s.owner),kind:'region',id:r.id,health:s.fortHp/s.maxFortHp,sub:selected?(s.owner==='player'?'ΤΟ ΦΕΟΥΔΟ ΣΟΥ':FACTIONS[s.owner]?.shortName):null});}
 for(const s of state.squads){const isSelected=selection?.id===s.id||selection?.ids?.includes(s.id),p=screenPoint(s.x,walkHeight(s.x,s.z)+(s.type==='trebuchet'?8:5.2),s.z);if(!p.visible||p.x<0||p.x>width||p.y<0||p.y>height)continue;const w=isSelected?45:24;ctx.fillStyle='rgba(12,19,17,.78)';ctx.fillRect(p.x-w/2,p.y,w,4);ctx.fillStyle=factionColor(s.owner);ctx.fillRect(p.x-w/2+1,p.y+1,(w-2)*clamp(s.hp/s.maxHp,0,1),2);if(isSelected){ctx.fillStyle='#f0e9d5';ctx.font='600 10px Inter,system-ui,sans-serif';ctx.textAlign='center';ctx.fillText(UNIT_TYPES[s.type]?.name||s.type,p.x,p.y-8);}else if(view.distance>250){ctx.beginPath();ctx.arc(p.x,p.y+10,4,0,Math.PI*2);ctx.fillStyle=factionColor(s.owner);ctx.fill();}labelBoxes.push({x:p.x-17,y:p.y-7,w:34,h:22,kind:'squad',id:s.id});}
 if(mapMode==='resources'||selection?.kind==='node'){for(const n of state.nodes){if(mapMode!=='resources'&&n.id!==selection.id)continue;const p=screenPoint(n.x,heightAt(n.x,n.z)+5,n.z);if(p.visible)label(({wood:'ΞΥΛΕΙΑ',food:'ΤΡΟΦΙΜΑ',stone:'ΠΕΤΡΑ',iron:'ΣΙΔΗΡΟΣ'})[n.type],p.x,p.y,{small:true,kind:'node',id:n.id,color:'#b6a770',sub:n.workers?`${n.workers} εργάτες`:undefined});}}
 if(boxSelect){const x=Math.min(boxSelect.x0,boxSelect.x1),y=Math.min(boxSelect.y0,boxSelect.y1),w=Math.abs(boxSelect.x1-boxSelect.x0),h=Math.abs(boxSelect.y1-boxSelect.y0);ctx.strokeStyle='#d9cca9';ctx.fillStyle='rgba(201,183,140,.12)';ctx.lineWidth=1;ctx.fillRect(x,y,w,h);ctx.strokeRect(x+.5,y+.5,w,h);}
 }
 function frameLoop(now){if(disposed)return;raf=requestAnimationFrame(frameLoop);const dt=clamp((now-lastTime)/1000,0,.08);lastTime=now;if(document.hidden)return;const time=clock.getElapsedTime();if(inputEnabled){const speed=desired.distance*.46*dt,forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);desired.x+=(-Math.sin(view.azimuth)*forward+Math.cos(view.azimuth)*side)*speed;desired.z+=(-Math.cos(view.azimuth)*forward-Math.sin(view.azimuth)*side)*speed;if(keys.has('KeyQ'))desired.azimuth+=dt*.65;if(keys.has('KeyE'))desired.azimuth-=dt*.65;desired.x=clamp(desired.x,MAP.minX-30,MAP.maxX+30);desired.z=clamp(desired.z,MAP.minZ-30,MAP.maxZ+30);}materials.water.normalMap.offset.y=time*.018;materials.water.normalMap.offset.x=time*.005;updateCamera(dt);if(!state?.paused)animationTime+=dt*(state?.speed||1);updateTroops(animationTime);updateEffects(animationTime);if(frame%6===0)drawSelection();renderer.render(scene,camera);drawOverlay();frame++;if(!ready){ready=true;callbacks.onReady?.();}}
 const localPoint=e=>{const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};};
 function pointerDown(e){if(!inputEnabled||e.button>2)return;const p=localPoint(e);pointers.set(e.pointerId,p);canvas.setPointerCapture?.(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:desired.distance};if(pointer)pointer.moved=true;return;}pointer={id:e.pointerId,x:p.x,y:p.y,lastX:p.x,lastY:p.y,button:e.button,shift:e.shiftKey,moved:false};if(e.shiftKey&&e.button===0)boxSelect={x0:p.x,y0:p.y,x1:p.x,y1:p.y};}
 function pointerMove(e){if(!inputEnabled)return;const p=localPoint(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(pinch&&pointers.size===2){const[a,b]=[...pointers.values()];desired.distance=clamp(pinch.zoom*pinch.distance/Math.max(10,Math.hypot(a.x-b.x,a.y-b.y)),55,680);return;}if(!pointer||pointer.id!==e.pointerId)return;const dx=p.x-pointer.lastX,dy=p.y-pointer.lastY;pointer.lastX=p.x;pointer.lastY=p.y;if(Math.hypot(p.x-pointer.x,p.y-pointer.y)>6)pointer.moved=true;if(boxSelect){boxSelect.x1=p.x;boxSelect.y1=p.y;return;}if(pointer.moved){const scale=desired.distance*.00138;desired.x-=Math.cos(view.azimuth)*dx*scale+Math.sin(view.azimuth)*dy*scale*1.6;desired.z-= -Math.sin(view.azimuth)*dx*scale+Math.cos(view.azimuth)*dy*scale*1.6;}}
 function pointerUp(e){const p=localPoint(e);pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;pointer=null;return;}if(!pointer)return;const start=pointer;pointer=null;if(boxSelect){const b=boxSelect;boxSelect=null;if(state&&start.moved){const ids=state.squads.filter(s=>s.owner==='player').filter(s=>{const p=screenPoint(s.x,walkHeight(s.x,s.z)+1,s.z);return p.x>=Math.min(b.x0,b.x1)&&p.x<=Math.max(b.x0,b.x1)&&p.y>=Math.min(b.y0,b.y1)&&p.y<=Math.max(b.y0,b.y1);}).map(s=>s.id);callbacks.onBoxSelect?.(ids);return;}}if(!inputEnabled||start.moved)return;const selection=pick(p.x,p.y),point=groundAt(p.x,p.y);if(start.button===2){if(point)callbacks.onContext?.(point,selection);return;}if(selection)callbacks.onSelect?.(selection,{shiftKey:!!e.shiftKey,button:start.button});else if(point)callbacks.onGround?.(point,{shiftKey:!!e.shiftKey,button:start.button});}
 function wheel(e){if(!inputEnabled)return;e.preventDefault();desired.distance=clamp(desired.distance*Math.exp(e.deltaY*.001),55,680);}
 function keyDown(e){if(e.defaultPrevented||!inputEnabled||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName)||e.target?.isContentEditable)return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE'].includes(e.code)){keys.add(e.code);e.preventDefault();}}
 function keyUp(e){keys.delete(e.code);}
 const contextmenu=e=>e.preventDefault(),blur=()=>{keys.clear();pointers.clear();pointer=null;pinch=null;};canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',blur);canvas.addEventListener('contextmenu',contextmenu);canvas.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);window.addEventListener('resize',resize);canvas.style.touchAction='none';raf=requestAnimationFrame(frameLoop);
 return{
 setState(s){state=s;refreshStructures();},
 setSelection(s){selection=s;drawSelection();},
 focus(target){const p=typeof target==='string'?REGIONS.find(r=>r.id===target):target;if(p){desired.x=p.x;desired.z=p.z;desired.distance=width<700?150:165;}},
 home(){desired.x=homeRegion.x+10;desired.z=homeRegion.z+12;desired.distance=width<700?168:175;desired.azimuth=.65;desired.elevation=.86;},
 zoom(delta){desired.distance=clamp(desired.distance*Math.exp(delta*.13),55,680);},
 setMapMode(mode){mapMode=mode;for(const l of territories)l.material.opacity=mode==='political'?.8:mode==='resources'?.11:.24;for(const fill of politicalFills)fill.visible=mode==='political';},
 setQuality(q){quality=q;renderer.shadowMap.enabled=q!=='low';scene.fog.density=q==='low'?.002:.00165;resize();},
 setInsets(next){insets={...insets,...next};},
 setInputEnabled(value){inputEnabled=!!value;if(!value){blur();boxSelect=null;}},
 getDebugState(){return{ready,frame,renderer:'three-webgl',camera:{...view},desired:{...desired},viewport:{width,height},selection,mapMode,inputEnabled,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,treeCount:nature.treeCount,fortresses:forts.size,labels:labelBoxes.map(l=>({...l})),squads:state?.squads.map(s=>({id:s.id,type:s.type,x:s.x,z:s.z,y:walkHeight(s.x,s.z),screen:screenPoint(s.x,walkHeight(s.x,s.z)+1,s.z)}))||[]};},
 destroy(){disposed=true;cancelAnimationFrame(raf);resizeObserver?.disconnect();for(const [name,fn]of[['pointerdown',pointerDown],['pointermove',pointerMove],['pointerup',pointerUp],['pointercancel',blur],['contextmenu',contextmenu],['wheel',wheel]])canvas.removeEventListener(name,fn);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);overlay.remove();scene.traverse(o=>{if(o.geometry&&!o.isInstancedMesh)o.geometry.dispose();});materials.dispose();renderer.dispose();}
 };
}
