// Positions are an artistic playable layout, not surveyed house coordinates.
export const LOCATIONS = [
{id:'office',name:'Κοινοτικό γραφείο',type:'office',x:51,z:51,size:1.15,condition:62,description:'Το γραφείο του μουχτάρη. Εδώ σχεδιάζεις έργα, βλέπεις το ταμείο και ακούς τους κατοίκους.'},
{id:'square',name:'Πλατεία του χωριού',type:'square',x:54,z:44,size:1,condition:22,description:'Η καρδιά της κοινότητας. Καθαρισμός, συναντήσεις, αγορά και γιορτές.'},
{id:'church',name:'Παναγία του Μουτουλλά',type:'church',x:75,z:75,size:1.4,condition:47,description:'Το πραγματικό μνημείο του 1280, σε λόφο πάνω από το χωριό. Φροντίζουμε τον περίβολο και αναθέτουμε τη συντήρηση σε ειδικούς.',real:true},
{id:'paraskevi',name:'Αγία Παρασκευή',type:'church',x:59,z:49,size:1.15,condition:55,description:'Η εκκλησία στο κέντρο του πραγματικού χωριού. Σημείο συνάντησης της κοινότητας.',real:true},
{id:'fountain',name:'Κοινοτική βρύση',type:'fountain',x:44,z:48,size:.65,condition:15,description:'Καθαρό νερό για τα σπίτια και τα εργαστήρια. Η πρώτη επείγουσα δουλειά.'},
{id:'bridge',name:'Γεφύρι στον Σέτραχο',type:'bridge',x:38,z:57,size:1.1,condition:24,description:'Η διαδρομή ενώνει τις δύο γειτονιές του παιχνιδιού, πάνω από τον Σέτραχο.'},
{id:'wash',name:'Πλυσταριά · Τα Χλιο',type:'wash',x:29,z:34,size:.9,condition:25,description:'Παραποτάμια κληρονομιά και νερό. Εμπνευσμένο από την πραγματική τοποθεσία Τα Χλιο.',real:true},
{id:'woodshop',name:'Εργαστήρι σκαφάδων',type:'workshop',x:61,z:35,size:1.1,condition:18,description:'Το ξύλο γίνεται χειροποίητη σκάφη. Η τέχνη που συνδέθηκε με τον Μουτουλλά.'},
{id:'orchard',name:'Περιβόλια',type:'orchard',x:22,z:62,size:1.9,condition:28,description:'Οπωροφόρα σε πεζούλες. Με νερό και εργάτες δίνουν φρούτα και εισόδημα.'},
{id:'market',name:'Υπαίθρια αγορά',type:'market',x:48,z:37,size:1.1,condition:20,description:'Πώληση, αγορά και ανταλλαγές προϊόντων με εμπόρους και κατοίκους.'},
{id:'bakery',name:'Κοινοτικός φούρνος',type:'bakery',x:67,z:48,size:1,condition:31,description:'Μικρή παραγωγή για τις ανάγκες του χωριού.'},
{id:'cafe',name:'Καφενείο «Η Παρέα»',type:'cafe',x:50,z:58,size:1,condition:35,description:'Φανταστικό καφενείο. Εδώ ακούγονται παράπονα, λύνονται παρεξηγήσεις και γεννιούνται ιδέες.'},
{id:'inn',name:'Παραδοσιακός ξενώνας',type:'inn',x:70,z:59,size:1.15,condition:16,description:'Αποκατάσταση πέτρινου σπιτιού για μικρές ομάδες επισκεπτών.'},
{id:'school',name:'Σχολή παραδοσιακών τεχνών',type:'school',x:56,z:25,size:1.15,condition:24,description:'Οι έμπειροι τεχνίτες διδάσκουν σκαφική, λιθοδομή και φροντίδα του τόπου.'},
{id:'stone',name:'Αυλή λιθοξόων',type:'quarry',x:82,z:48,size:1.2,condition:35,description:'Διαλογή και επαναχρησιμοποίηση πέτρας για τις επισκευές.'},
{id:'forest',name:'Δασικό συνεργείο',type:'forest',x:80,z:24,size:1.8,condition:46,description:'Επιλεκτική συλλογή ξυλείας, κλάδεμα και αναφύτευση. Η υγεία του δάσους μετρά.'},
{id:'coop',name:'Συνεργατικό παντοπωλείο',type:'coop',x:40,z:70,size:1,condition:20,description:'Συγκεντρώνει προϊόντα και στηρίζει τις εμπορικές παραγγελίες.'},
{id:'trail',name:'Μονοπάτι της Ρήγαινας',type:'trail',x:22,z:20,size:1,condition:21,description:'Διαδρομή περιήγησης εμπνευσμένη από τις παραποτάμιες τοποθεσίες του Μουτουλλά.',real:true},
{id:'house1',name:'Πέτρινο σπίτι · Κάτω γειτονιά 1',type:'house',x:30,z:65,size:1,condition:18},
{id:'house2',name:'Πέτρινο σπίτι · Κάτω γειτονιά 2',type:'house',x:29,z:75,size:.95,condition:28},
{id:'house3',name:'Πέτρινο σπίτι · Κάτω γειτονιά 3',type:'house',x:43,z:80,size:.9,condition:21},
{id:'house4',name:'Πέτρινο σπίτι · Πάνω γειτονιά 1',type:'house',x:62,z:69,size:.9,condition:25},
{id:'house5',name:'Πέτρινο σπίτι · Πάνω γειτονιά 2',type:'house',x:58,z:79,size:1,condition:17},
{id:'house6',name:'Πέτρινο σπίτι · Πάνω γειτονιά 3',type:'house',x:82,z:66,size:.95,condition:33},
{id:'house7',name:'Πέτρινο σπίτι · Μαστόρων 1',type:'house',x:69,z:28,size:.9,condition:22},
{id:'house8',name:'Πέτρινο σπίτι · Μαστόρων 2',type:'house',x:71,z:39,size:.85,condition:31},
{id:'house9',name:'Πέτρινο σπίτι · Πλατάνου 1',type:'house',x:41,z:27,size:.9,condition:19},
{id:'house10',name:'Πέτρινο σπίτι · Πλατάνου 2',type:'house',x:47,z:21,size:.9,condition:27},
{id:'house11',name:'Πέτρινο σπίτι · Ποταμού 1',type:'house',x:23,z:46,size:.9,condition:16},
{id:'house12',name:'Πέτρινο σπίτι · Ποταμού 2',type:'house',x:28,z:53,size:.85,condition:23},
];
export const LOCATION_MAP=Object.fromEntries(LOCATIONS.map(b=>[b.id,b]));
