// Artistic playable positions, not surveyed house coordinates. IDs stay stable for existing saves.
export const LOCATIONS = [
  {
    "id": "office",
    "name": "Κοινοτικό γραφείο",
    "type": "office",
    "x": 51.34,
    "z": 52.74,
    "size": 1.15,
    "condition": 62,
    "description": "Το γραφείο του μουχτάρη. Εδώ σχεδιάζεις έργα, βλέπεις το ταμείο και ακούς τους κατοίκους.",
    "w": 5.9,
    "d": 4.4,
    "h": 5.1,
    "style": "anogi",
    "roofAxis": "z",
    "plaster": "lime",
    "roofTone": 1
  },
  {
    "id": "square",
    "name": "Πλατεία του χωριού",
    "type": "square",
    "x": 55.36,
    "z": 41.96,
    "size": 1,
    "condition": 22,
    "description": "Η καρδιά της κοινότητας. Καθαρισμός, συναντήσεις, αγορά και γιορτές."
  },
  {
    "id": "church",
    "name": "Παναγία του Μουτουλλά",
    "type": "church",
    "x": 83.5,
    "z": 83.5,
    "size": 1.4,
    "condition": 47,
    "description": "Το πραγματικό μνημείο του 1280, σε λόφο πάνω από το χωριό. Φροντίζουμε τον περίβολο και αναθέτουμε τη συντήρηση σε ειδικούς.",
    "real": true,
    "w": 6.86,
    "d": 4.55,
    "h": 2.4,
    "style": "chapel",
    "roofAxis": "x",
    "roofTone": 3
  },
  {
    "id": "paraskevi",
    "name": "Αγία Παρασκευή",
    "type": "church",
    "x": 62.06,
    "z": 48.66,
    "size": 1.15,
    "condition": 55,
    "description": "Η εκκλησία στο κέντρο του πραγματικού χωριού. Σημείο συνάντησης της κοινότητας.",
    "real": true,
    "w": 5.6,
    "d": 8.1,
    "h": 5,
    "style": "parish",
    "roofAxis": "z",
    "plaster": "stone",
    "roofTone": 0
  },
  {
    "id": "fountain",
    "name": "Κοινοτική βρύση",
    "type": "fountain",
    "x": 41.96,
    "z": 47.32,
    "size": 0.65,
    "condition": 15,
    "description": "Καθαρό νερό για τα σπίτια και τα εργαστήρια. Η πρώτη επείγουσα δουλειά."
  },
  {
    "id": "bridge",
    "name": "Γεφύρι στον Σέτραχο",
    "type": "bridge",
    "x": 33.92,
    "z": 59.38,
    "size": 1.1,
    "condition": 24,
    "description": "Η διαδρομή ενώνει τις δύο γειτονιές του παιχνιδιού, πάνω από τον Σέτραχο."
  },
  {
    "id": "wash",
    "name": "Πλυσταριά · Τα Χλιο",
    "type": "wash",
    "x": 21.86,
    "z": 28.56,
    "size": 0.9,
    "condition": 25,
    "description": "Παραποτάμια κληρονομιά και νερό. Εμπνευσμένο από την πραγματική τοποθεσία Τα Χλιο.",
    "real": true
  },
  {
    "id": "woodshop",
    "name": "Εργαστήρι σκαφάδων",
    "type": "workshop",
    "x": 64.74,
    "z": 29.9,
    "size": 1.1,
    "condition": 18,
    "description": "Το ξύλο γίνεται χειροποίητη σκάφη. Η τέχνη που συνδέθηκε με τον Μουτουλλά.",
    "w": 7.4,
    "d": 4.3,
    "h": 2.9,
    "style": "openworkshop",
    "roofAxis": "x",
    "roofTone": 2
  },
  {
    "id": "orchard",
    "name": "Περιβόλια",
    "type": "orchard",
    "x": 12.48,
    "z": 66.08,
    "size": 1.9,
    "condition": 28,
    "description": "Οπωροφόρα σε πεζούλες. Με νερό και εργάτες δίνουν φρούτα και εισόδημα."
  },
  {
    "id": "market",
    "name": "Υπαίθρια αγορά",
    "type": "market",
    "x": 47.32,
    "z": 32.58,
    "size": 1.1,
    "condition": 20,
    "description": "Πώληση, αγορά και ανταλλαγές προϊόντων με εμπόρους και κατοίκους."
  },
  {
    "id": "bakery",
    "name": "Κοινοτικός φούρνος",
    "type": "bakery",
    "x": 72.78,
    "z": 47.32,
    "size": 1,
    "condition": 31,
    "description": "Μικρή παραγωγή για τις ανάγκες του χωριού.",
    "w": 4.1,
    "d": 3.9,
    "h": 2.75,
    "style": "cottage",
    "roofAxis": "z",
    "plaster": "ochre",
    "roofTone": 1
  },
  {
    "id": "cafe",
    "name": "Καφενείο «Η Παρέα»",
    "type": "cafe",
    "x": 50,
    "z": 60.72,
    "size": 1,
    "condition": 35,
    "description": "Φανταστικό καφενείο. Εδώ ακούγονται παράπονα, λύνονται παρεξηγήσεις και γεννιούνται ιδέες.",
    "w": 7,
    "d": 3.7,
    "h": 3,
    "style": "longhouse",
    "roofAxis": "x",
    "plaster": "lime",
    "roofTone": 2
  },
  {
    "id": "inn",
    "roofShape":"hip",
    "name": "Παραδοσιακός ξενώνας",
    "type": "inn",
    "x": 76.8,
    "z": 62.06,
    "size": 1.15,
    "condition": 16,
    "description": "Αποκατάσταση πέτρινου σπιτιού για μικρές ομάδες επισκεπτών.",
    "w": 7.2,
    "d": 4.8,
    "h": 5.7,
    "style": "anogi",
    "roofAxis": "x",
    "plaster": "ochre",
    "roofTone": 0
  },
  {
    "id": "school",
    "name": "Σχολή παραδοσιακών τεχνών",
    "type": "school",
    "x": 58.04,
    "z": 16.5,
    "size": 1.15,
    "condition": 24,
    "description": "Οι έμπειροι τεχνίτες διδάσκουν σκαφική, λιθοδομή και φροντίδα του τόπου.",
    "w": 8.4,
    "d": 3.5,
    "h": 3.65,
    "style": "longhouse",
    "roofAxis": "x",
    "plaster": "ochre",
    "roofTone": 1
  },
  {
    "id": "stone",
    "name": "Αυλή λιθοξόων",
    "type": "quarry",
    "x": 92.88,
    "z": 47.32,
    "size": 1.2,
    "condition": 35,
    "description": "Διαλογή και επαναχρησιμοποίηση πέτρας για τις επισκευές."
  },
  {
    "id": "forest",
    "name": "Δασικό συνεργείο",
    "type": "forest",
    "x": 90.2,
    "z": 15.16,
    "size": 1.8,
    "condition": 46,
    "description": "Επιλεκτική συλλογή ξυλείας, κλάδεμα και αναφύτευση. Η υγεία του δάσους μετρά."
  },
  {
    "id": "coop",
    "name": "Συνεργατικό παντοπωλείο",
    "type": "coop",
    "x": 36.6,
    "z": 76.8,
    "size": 1,
    "condition": 20,
    "description": "Συγκεντρώνει προϊόντα και στηρίζει τις εμπορικές παραγγελίες.",
    "w": 5.4,
    "d": 4.2,
    "h": 3.8,
    "style": "courtyard",
    "roofAxis": "z",
    "plaster": "stone",
    "roofTone": 2
  },
  {
    "id": "trail",
    "name": "Μονοπάτι της Ρήγαινας",
    "type": "trail",
    "x": 12.48,
    "z": 9.8,
    "size": 1,
    "condition": 21,
    "description": "Διαδρομή περιήγησης εμπνευσμένη από τις παραποτάμιες τοποθεσίες του Μουτουλλά.",
    "real": true
  },
  {
    "id": "house1",
    "name": "Πέτρινο σπίτι · Κάτω γειτονιά 1",
    "type": "house",
    "x": 23.2,
    "z": 70.1,
    "size": 1,
    "condition": 18,
    "w": 6.5,
    "d": 3.5,
    "h": 2.6,
    "style": "longhouse",
    "roofAxis": "x",
    "plaster": "stone",
    "roofTone": 2,
    "description": "Μακρόστενο ισόγειο με παλιά κεραμίδια, χοντρούς πέτρινους τοίχους και κήπο. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house2",
    "roofShape":"hip",
    "name": "Πέτρινο σπίτι · Κάτω γειτονιά 2",
    "type": "house",
    "x": 21.86,
    "z": 83.5,
    "size": 0.95,
    "condition": 28,
    "w": 4.1,
    "d": 5.9,
    "h": 5.3,
    "style": "anogi",
    "roofAxis": "z",
    "plaster": "lime",
    "roofTone": 0,
    "description": "Παλιό ανώι: πέτρινο κατώι για προμήθειες και κατοικία επάνω, με ξύλινο ηλιακό. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house3",
    "name": "Πέτρινο σπίτι · Κάτω γειτονιά 3",
    "type": "house",
    "x": 40.62,
    "z": 90.2,
    "size": 0.9,
    "condition": 21,
    "w": 4,
    "d": 3.7,
    "h": 2.45,
    "style": "cottage",
    "roofAxis": "z",
    "plaster": "stone",
    "roofTone": 3,
    "description": "Χαμηλό πετρόχτιστο σπίτι, φθαρμένα ξύλινα κουφώματα και κεραμοσκεπή. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house4",
    "name": "Πέτρινο σπίτι · Πάνω γειτονιά 1",
    "type": "house",
    "x": 66.08,
    "z": 75.46,
    "size": 0.9,
    "condition": 25,
    "w": 5.8,
    "d": 4.2,
    "h": 4.8,
    "style": "courtyard",
    "roofAxis": "x",
    "plaster": "ochre",
    "roofTone": 2,
    "description": "Ακανόνιστη κάτοψη με πλευρικό δωμάτιο και μικρή περίκλειστη αυλή. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house5",
    "name": "Πέτρινο σπίτι · Πάνω γειτονιά 2",
    "type": "house",
    "x": 60.72,
    "z": 88.86,
    "size": 1,
    "condition": 17,
    "w": 6.9,
    "d": 3.3,
    "h": 2.7,
    "style": "longhouse",
    "roofAxis": "x",
    "plaster": "lime",
    "roofTone": 1,
    "description": "Μακρόστενο ισόγειο με παλιά κεραμίδια, χοντρούς πέτρινους τοίχους και κήπο. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house6",
    "name": "Πέτρινο σπίτι · Πάνω γειτονιά 3",
    "type": "house",
    "x": 92.88,
    "z": 71.44,
    "size": 0.95,
    "condition": 33,
    "w": 4.4,
    "d": 5.2,
    "h": 5.65,
    "style": "anogi",
    "roofAxis": "z",
    "plaster": "stone",
    "roofTone": 3,
    "description": "Παλιό ανώι: πέτρινο κατώι για προμήθειες και κατοικία επάνω, με ξύλινο ηλιακό. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house7",
    "name": "Πέτρινο σπίτι · Μαστόρων 1",
    "type": "house",
    "x": 75.46,
    "z": 20.52,
    "size": 0.9,
    "condition": 22,
    "w": 4.8,
    "d": 3.1,
    "h": 2.5,
    "style": "shed",
    "roofAxis": "x",
    "plaster": "stone",
    "roofTone": 1,
    "description": "Μικρό παλιό εργαστήρι με μονόριχτη κεραμοσκεπή και ξύλινα υποστυλώματα. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house8",
    "name": "Πέτρινο σπίτι · Μαστόρων 2",
    "type": "house",
    "x": 78.14,
    "z": 35.26,
    "size": 0.85,
    "condition": 31,
    "w": 4.1,
    "d": 5.6,
    "h": 3,
    "style": "courtyard",
    "roofAxis": "z",
    "plaster": "lime",
    "roofTone": 0,
    "description": "Ακανόνιστη κάτοψη με πλευρικό δωμάτιο και μικρή περίκλειστη αυλή. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house9",
    "roofShape":"hip",
    "name": "Πέτρινο σπίτι · Πλατάνου 1",
    "type": "house",
    "x": 37.94,
    "z": 19.18,
    "size": 0.9,
    "condition": 19,
    "w": 5.8,
    "d": 4.2,
    "h": 5.35,
    "style": "anogi",
    "roofAxis": "x",
    "plaster": "lime",
    "roofTone": 2,
    "description": "Παλιό ανώι: πέτρινο κατώι για προμήθειες και κατοικία επάνω, με ξύλινο ηλιακό. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house10",
    "name": "Πέτρινο σπίτι · Πλατάνου 2",
    "type": "house",
    "x": 45.98,
    "z": 11.14,
    "size": 0.9,
    "condition": 27,
    "w": 4.5,
    "d": 3.2,
    "h": 2.55,
    "style": "cottage",
    "roofAxis": "x",
    "plaster": "ochre",
    "roofTone": 0,
    "description": "Χαμηλό πετρόχτιστο σπίτι, φθαρμένα ξύλινα κουφώματα και κεραμοσκεπή. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house11",
    "name": "Πέτρινο σπίτι · Ποταμού 1",
    "type": "house",
    "x": 13.82,
    "z": 44.64,
    "size": 0.9,
    "condition": 16,
    "w": 5,
    "d": 4.6,
    "h": 2.75,
    "style": "courtyard",
    "roofAxis": "z",
    "plaster": "stone",
    "roofTone": 3,
    "description": "Ακανόνιστη κάτοψη με πλευρικό δωμάτιο και μικρή περίκλειστη αυλή. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  },
  {
    "id": "house12",
    "name": "Πέτρινο σπίτι · Ποταμού 2",
    "type": "house",
    "x": 20.52,
    "z": 54.02,
    "size": 0.85,
    "condition": 23,
    "w": 3.7,
    "d": 6.3,
    "h": 4.8,
    "style": "anogi",
    "roofAxis": "z",
    "plaster": "ochre",
    "roofTone": 2,
    "description": "Παλιό ανώι: πέτρινο κατώι για προμήθειες και κατοικία επάνω, με ξύλινο ηλιακό. Η θέση και η οικογένεια είναι μέρος του φανταστικού σεναρίου."
  }
];
export const LOCATION_MAP=Object.fromEntries(LOCATIONS.map(b=>[b.id,b]));
