import * as T from 'three';
import {MountainWorld} from './world.js';
import {ROUTE,makeBody,inflate,gumHit,advanceBody,separateBodies,telemetry,raySphere,clamp,distance} from './physics.js';
import {loadPeople,makePerson,posePerson,makeGun} from './actors.js';
import {Input} from './input.js';
const $=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const VERSION='0.5.1';
export class SummitGame{
 constructor(){
  this.canvas=$('game');this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
  this.scene=new T.Scene;this.scene.background=new T.Color(0xa9c9da);this.scene.fog=new T.FogExp2(0xa9c9da,.00048);this.camera=new T.PerspectiveCamera(64,innerWidth/innerHeight,.06,9000);this.scene.add(this.camera);
  this.scene.add(new T.HemisphereLight(0xe0f2ff,0x6f7854,2.2));this.sun=new T.DirectionalLight(0xfff0d9,3.1);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:500});this.sun.shadow.bias=-.00008;this.sun.shadow.normalBias=.18;this.scene.add(this.sun,this.sun.target);
  const sky=new T.Mesh(new T.SphereGeometry(7000,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 w;void main(){w=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 w;void main(){vec3 n=normalize(w);float h=pow(max(n.y,0.),.42);vec3 c=mix(vec3(.72,.83,.86),vec3(.18,.40,.59),h);float sun=pow(max(dot(n,normalize(vec3(-.4,.58,.4))),0.),400.);c+=sun*vec3(.9,.73,.48);gl_FragColor=vec4(c,1.);}'}));this.scene.add(sky);
  this.world=new MountainWorld(this.scene);this.running=false;this.paused=false;this.ended=false;this.mapOpen=false;this.crafting=false;this.fps=false;this.zoom=1;this.time=0;this.elapsed=0;this.penalty=0;this.charge=0;this.projectiles=[];this.splats=[];this.drops=[];this.visuals=new Map;this.bodies=[];this.loaded=false;this.raceStarted=false;this.toastUntil=0;this.audio=null;this.damage=0;this.shotClock=0;this.manual=globalThis.__SUMMIT_TEST===true||location.search.includes('test=1');this.input=new Input(this.canvas,this);this.aim=V();this.target=null;this.fixedAim=null;
  this.gun=makeGun();this.gun.rotation.y=Math.PI;this.gun.position.set(.25,-.23,-.50);this.gun.scale.setScalar(.70);this.camera.add(this.gun);this.gun.visible=false;
  this.gumGeo=new T.SphereGeometry(.11,12,8);this.gumMat=new T.MeshStandardMaterial({color:0xda88c4,roughness:.22,metalness:.07});this.foeMat=new T.MeshStandardMaterial({color:0xa9d8b7,roughness:.26});
  window.addEventListener('resize',()=>this.resize());this.boot();
 }
 async boot(){try{const [people]=await Promise.all([loadPeople(),this.world.build(t=>$('loading').textContent=t)]);this.people=people;this.reset(false);this.loaded=true;$('startBtn').disabled=false;$('loading').textContent='Έτοιμο · άνθρωποι, terrain και δάσος φορτώθηκαν.';
   this.render(.016);let prev=performance.now();const frame=now=>{const dt=Math.min((now-prev)/1000,.05);prev=now;if(!this.manual){this.tick(dt);this.render(dt);}requestAnimationFrame(frame);};requestAnimationFrame(frame);
   if(this.manual)window.__summit={game:this,version:VERSION,step:(seconds,dt=1/60)=>{for(let t=0;t<seconds;t+=dt)this.tick(Math.min(dt,seconds-t));this.render(0);},start:()=>this.start(),snapshot:()=>this.snapshot()};
  }catch(e){console.error(e);$('loading').textContent='Η φόρτωση σταμάτησε: '+e.message+'. Ανανέωσε για επανάληψη.';}}
 reset(running=true){for(const p of this.visuals.values())this.scene.remove(p.root);this.visuals.clear();for(const p of [...this.projectiles,...this.splats,...this.drops])if(p.mesh)this.scene.remove(p.mesh);this.projectiles=[];this.splats=[];this.drops=[];this.bodies=[];
  for(let i=0;i<7;i++){const p=ROUTE[0],a=makeBody(i,{x:p.x+(i-3.5)*10,y:p.y,z:p.z+7+(i%2)*8});a.name=i===0?'ΕΣΥ':['','ΝΕΦΕΛΗ','ΑΙΟΛΟΣ','ΙΡΙΔΑ','ΑΡΓΩ','ΦΟΙΒΟΣ','ΝΟΤΟΣ'][i];a.wait=1.5+i*.9;this.bodies.push(a);this.visuals.set(i,makePerson(this.people[i%2],this.scene,[0xd896c8,0xa8c3f0,0xf3ba86,0xb5dba7,0xd6c0ef,0xe6a4a2,0x89d6d7][i]));}
  let id=7;for(let s=1;s<=3;s++)for(let j=0;j<s+1;j++){const p=ROUTE[s],x=p.x+(j%2?21:-21),z=p.z-12-Math.floor(j/2)*12,a=makeBody(id,{x,y:this.world.height(x,z),z},'guard');a.site=s;a.home={x:a.x,y:a.y,z:a.z};a.name='Φρουρός '+s+'·'+(j+1);a.yaw=j%2?Math.PI*.6:Math.PI*1.4;a.ammo=64;a.wait=0;this.bodies.push(a);this.visuals.set(id,makePerson(this.people[id%2],this.scene,0xbcbb91));id++;}
  this.player=this.bodies[0];this.player.x=ROUTE[0].x;this.player.z=ROUTE[0].z+15;this.player.y=this.world.height(this.player.x,this.player.z)+.02;this.time=this.elapsed=this.penalty=0;this.input.clear();this.running=running;this.paused=this.ended=this.crafting=this.mapOpen=false;this.raceStarted=false;this.fps=false;this.charge=0;this.craft=null;this.fixedAim=null;this.damage=0;this.downed=0;this.aim.set(this.player.x,this.player.y+1.2,this.player.z-50);for(const c of this.world.chests){c.looted=new Set;c.opened=false;c.lid.rotation.x=0;}for(const id of['craftScreen','mapScreen','pauseScreen','endScreen'])show(id,false);show('hud',running);show('menu',!running);this.cameraReady=false;this.mapBase=null;
 }
 start(){if(!this.loaded)return;this.initAudio();this.reset(true);this.openCraft();}
 playing(){return this.running&&!this.paused&&!this.ended&&!this.crafting&&!this.mapOpen;}
 action(name){if(name==='start'||name==='restart'){this.start();return;}if(!this.running)return;
  if(name==='pause'){if(this.ended)return;if(this.crafting){this.closeCraft();return;}this.paused=!this.paused;this.input.clear();this.charge=0;show('pauseScreen',this.paused);if(this.paused&&document.pointerLockElement)document.exitPointerLock();return;}
  if(name==='map'){this.mapOpen=!this.mapOpen;this.input.clear();show('mapScreen',this.mapOpen);if(this.mapOpen)this.drawMap();return;}
  if(name==='closeCraft'){this.closeCraft();return;}if(name==='craftStep'){this.craftNext();return;}
  if(['balanced','strong','light'].includes(name)){if(this.craft?.step===0&&!this.craft.timer){this.craft.recipe=name;this.updateCraft();}return;}
  if(!this.playing())return;const p=this.player;
  if(name==='camera'){this.fps=!this.fps;this.cameraReady=false;this.input.ring=false;this.charge=0;$('cameraBtn').textContent=this.fps?'FPS':'TOP';if(!this.fps&&document.pointerLockElement)document.exitPointerLock();return;}
  if(name==='craft')this.openCraft();if(name==='reload'&&p.ammo<64&&p.reload<=0){p.reload=1.45;this.sound('reload');}
  if(name==='jump'&&p.grounded){p.grounded=false;p.vy=7;}if(name==='collect')this.collect(p);
  if(name==='clean'){if(!p.grounded){this.notify('Καθάρισμα μόνο όταν πατάς στο έδαφος.');return;}p.gum=Math.max(0,p.gum-12);this.notify('Αφαιρέθηκαν 12 kg πρόσθετης τσίχλας.');}
 }
 initAudio(){try{this.audio??=new(window.AudioContext||window.webkitAudioContext)();this.audio.resume();}catch{}}
 sound(kind){if(!this.audio)return;const now=this.audio.currentTime,o=this.audio.createOscillator(),gain=this.audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='hit'?130:kind==='reload'?330:540,now);o.frequency.exponentialRampToValueAtTime(kind==='reward'?820:90,now+.12);gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+.16);o.connect(gain);gain.connect(this.audio.destination);o.start();o.stop(now+.18);o.onended=()=>{o.disconnect();gain.disconnect();};}
 notify(text,seconds=3){$('toast').textContent=text;this.toastUntil=this.time+seconds;$('toast').classList.add('show');}
 look(x,y){this.player.yaw+=x;this.player.pitch=clamp(this.player.pitch+y,-1.35,1.35);}
 project(p){const v=p.clone().project(this.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2,front:v.z<1};}
 tap(x,y){let best=null,distance=55;for(const a of this.bodies){if(a===this.player||!a.alive)continue;const s=this.project(V(a.x,a.y+(a.balloon?4.2:1.3),a.z)),d=Math.hypot(s.x-x,s.y-y);if(s.front&&d<distance){distance=d;best=a;}}this.target=best;}
 updateAim(dt){const p=this.player;let at=null;
  if(this.fixedAim)at=this.fixedAim.clone();
  else if(this.fps){at=V(p.x+Math.sin(p.yaw)*Math.cos(p.pitch)*160,p.y+1.67+Math.sin(p.pitch)*160,p.z+Math.cos(p.yaw)*Math.cos(p.pitch)*160);if(this.input.touch&&Math.hypot(...this.input.aim)>.05)this.look(-this.input.aim[0]*dt*2.0,-this.input.aim[1]*dt*1.6);}
  else if(!this.input.touch&&this.input.mouseActive){
   const mouse=this.input.mouse,r=new T.Raycaster;r.setFromCamera(new T.Vector2(mouse[0]/innerWidth*2-1,1-mouse[1]/innerHeight*2),this.camera);const den=r.ray.direction.y,t=Math.abs(den)>.001?(p.y+1.3-r.ray.origin.y)/den:160;at=r.ray.origin.clone().addScaledVector(r.ray.direction,Math.max(1,t));let closest=42;this.target=null;
   for(const a of this.bodies){if(!a.alive||a===p||distance(a,p)>160)continue;const q=V(a.x,a.y+(a.balloon?1.65+a.balloon.r+.3:1.2),a.z),sc=this.project(q),dist=Math.hypot(sc.x-mouse[0],sc.y-mouse[1]);if(sc.front&&dist<closest&&this.visible(p,a)){closest=dist;this.target=a;at=q;}}
  }else{
   const mag=Math.hypot(...this.input.aim);if(mag>.15){const yaw=Math.atan2(this.input.aim[0],this.input.aim[1]);p.yaw=yaw;let best=null,score=-2;for(const a of this.bodies){if(!a.alive||a===p||distance(a,p)>150)continue;const dx=a.x-p.x,dz=a.z-p.z,d=Math.hypot(dx,dz),dot=(dx*Math.sin(yaw)+dz*Math.cos(yaw))/(d||1);if(dot>.88&&dot-d*.0008>score&&this.visible(p,a)){score=dot-d*.0008;best=a;}}this.target=best;}
   if(this.target?.alive&&distance(p,this.target)<170&&this.visible(p,this.target)){const a=this.target;at=V(a.x,a.y+(a.balloon?1.65+a.balloon.r+.3:1.2),a.z);}else{this.target=null;at=V(p.x+Math.sin(p.yaw)*110,p.y+1.5,p.z+Math.cos(p.yaw)*110);}
  }
  this.aim.copy(at);if(!this.fps)p.yaw=Math.atan2(at.x-p.x,at.z-p.z);
 }
 visible(a,b){const start=V(a.x,a.y+1.4,a.z),end=V(b.x,b.y+(b.balloon?3.7:1.2),b.z),delta=end.clone().sub(start);return !this.world.ray(start,delta.normalize(),Math.max(0,start.distanceTo(end)-(b.balloon?2.5:.5)));}
 openCraft(){const p=this.player;if(!p.grounded){this.notify('Προσγειώσου πριν φτιάξεις νέο μπαλόνι.');return;}if(this.world.ray(V(p.x,p.y+1.8,p.z),V(0,1,0),5.5)){this.notify('Χρειάζεσαι ανοιχτό χώρο για το μπαλόνι, όχι στέγη από πάνω.');return;}if(p.bag[0]<3||p.bag[1]<2||p.bag[2]<1){this.notify('Χρειάζονται 3 ρητίνη, 2 ίνες και 1 αέριο. F στα κιβώτια ή στα λάφυρα.');return;}this.input.clear();this.crafting=true;this.craft={step:0,timer:0,duration:0,recipe:'balanced',reserved:false};show('craftScreen',true);this.updateCraft();if(document.pointerLockElement)document.exitPointerLock();}
 closeCraft(){if(!this.crafting)return;if(this.craft.reserved){this.player.bag[0]+=3;this.player.bag[1]+=2;this.player.bag[2]++;}this.crafting=false;this.craft=null;show('craftScreen',false);}
 craftNext(){if(!this.crafting||this.craft.timer>0)return;const c=this.craft;if(c.step===0&&!c.reserved){this.player.bag[0]-=3;this.player.bag[1]-=2;this.player.bag[2]--;c.reserved=true;}c.duration=[1.8,1.3,1.8][c.step];c.timer=c.duration;this.updateCraft();}
 updateCraft(){const c=this.craft;if(!c)return;for(const r of['balanced','strong','light'])$(r).classList.toggle('selected',r===c.recipe);for(const [i,id]of['mixStep','chewStep','inflateStep'].entries())$(id).classList.toggle('done',i<c.step);$('craftButton').textContent=c.timer>0?['ΑΝΑΜΕΙΓΝΥΕΤΑΙ…','ΜΑΣΑΣ ΤΗΝ ΤΣΙΧΛΑ…','ΦΟΥΣΚΩΝΕΙ ΑΠΟ ΤΟ ΣΤΟΜΑ…'][c.step]:['ΑΝΑΜΕΙΞΕ →','ΒΑΛΕ ΣΤΟ ΣΤΟΜΑ & ΜΑΣΗΣΕ →','ΦΟΥΣΚΩΣΕ & ΠΕΤΑ →'][c.step];$('craftButton').disabled=c.timer>0;document.querySelector('.bowl').classList.toggle('active',c.timer>0);$('craftProgress').style.width=(c.timer>0?(1-c.timer/c.duration)*100:0)+'%';}
 finishCraft(){const c=this.craft;inflate(this.player,c.recipe);this.player.balloon.life=this.player.balloon.maxLife;this.crafting=false;this.craft=null;show('craftScreen',false);this.raceStarted=true;this.notify('SPACE / ↑ για άνοδο. Η επόμενη κορυφή είναι ο στόχος — όχι ο τελικός τερματισμός.',5);this.cameraReady=false;}
 collect(a){if(!a.grounded)return;const p=ROUTE[a.target];if(a.target<=3&&distance(a,p)<12){a.checkpoint=a.target;a.target++;if(a.id===0){a.hp=Math.min(100,a.hp+20);this.notify('ΣΦΡΑΓΙΔΑ '+a.checkpoint+'/3 · Πάρε υλικά και ετοίμασε την επόμενη πτήση.',4);this.sound('reward');}}
  for(const c of this.world.chests)if(Math.hypot(c.x-a.x,c.z-a.z)<6&&Math.abs(c.y-a.y)<2&&!c.looted.has(a.id)){
   c.looted.add(a.id);a.bag[0]+=3;a.bag[1]+=2;a.bag[2]+=1;a.hp=Math.min(100,a.hp+12);a.ammo=64;if(a.id===0){c.opened=true;this.notify('ΚΙΒΩΤΙΟ · +3 ρητίνη · +2 ίνες · +1 αέριο · αναγέμιση');this.sound('reward');}}
  for(const d of this.drops)if(!d.taken&&Math.hypot(d.x-a.x,d.z-a.z)<5&&Math.abs(d.y-a.y)<3){d.taken=true;d.mesh.visible=false;a.bag[0]+=2;a.bag[1]++;a.bag[2]++;if(a.id===0)this.notify('ΛΑΦΥΡΑ · νέα υλικά τσίχλας.');}
 }
 desiredPlayer(){const i=this.input,k=i.keys;if(!this.playing()||!this.player.alive)return{};let forward=(k.has('KeyW')||k.has('ArrowUp')?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0)-i.move[1],side=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0)+i.move[0];side+=(k.has('KeyE')?.5:0)-(k.has('KeyQ')?.5:0);const up=i.up+(k.has('Space')?1:0)-(k.has('ControlLeft')||k.has('ControlRight')?1:0);return{forward,side,yaw:this.fps?this.player.yaw:Math.PI,up:clamp(up,-1,1),sprint:k.has('ShiftLeft')||k.has('ShiftRight')};}
 npc(a,dt){if(!a.alive)return{};if(a.kind==='guard'){
   const near=this.player,home=a.home;let target=this.bodies.filter(b=>b.kind==='racer'&&b.alive&&distance(b,home)<100&&Math.abs(b.y-a.y)<85&&distance(a,b)<135&&this.visible(a,b)).sort((x,y)=>distance(x,a)-distance(y,a))[0];
   if(target){a.yaw=Math.atan2(target.x-a.x,target.z-a.z);if(a.cooldown<=0)this.fire(a,target,false);const d=distance(a,target);if(d>28&&distance(a,home)<34&&target.grounded)return{forward:1,yaw:a.yaw};return{};}
   const ang=this.time*.13+a.phase,g={x:home.x+Math.sin(ang)*5,z:home.z+Math.cos(ang)*5};a.yaw=Math.atan2(g.x-a.x,g.z-a.z);return{forward:distance(a,g)>1?.30:0,yaw:a.yaw};
  }
  if(!this.raceStarted)return{};a.wait-=dt;if(a.wait>0)return{};
  const target=ROUTE[a.target],dist=distance(a,target);
  const foes=this.bodies.filter(b=>b.id!==a.id&&b.alive&&distance(a,b)<115&&Math.abs(a.y-b.y)<75&&this.visible(a,b));if(foes.length&&a.cooldown<=0)this.fire(a,foes.sort((x,y)=>distance(a,x)-distance(a,y))[0],false);
  if(a.balloon){const yaw=Math.atan2(target.x-a.x,target.z-a.z);a.yaw=yaw;const ahead={x:a.x+Math.sin(yaw)*60,z:a.z+Math.cos(yaw)*60};let needed=Math.max(target.y+22,this.world.height(ahead.x,ahead.z)+18);if(dist<55)needed=target.y+Math.max(0,(dist-12)*.3);const up=clamp((needed-a.y)*.10-a.vy*.15,-1,1);return{forward:dist>25?1:dist>8?.30:0,yaw,up};}
  if(!a.grounded)return{};
  if(a.target===4&&a.checkpoint===3&&dist<40){this.finish(a);return{};}
  if(dist<ROUTE[a.target].r+5){if(dist>9){const yaw=Math.atan2(target.x-a.x,target.z-a.z);a.yaw=yaw;return{forward:1,yaw};}this.collect(a);}
  if(a.bag[0]<3||a.bag[1]<2||a.bag[2]<1){let best=this.world.chests.filter(c=>!c.looted.has(a.id)&&Math.abs(c.y-a.y)<12).sort((c,d)=>distance(a,c)-distance(a,d))[0];if(best){if(distance(a,best)<5)this.collect(a);else{const yaw=Math.atan2(best.x-a.x,best.z-a.z);a.yaw=yaw;return{forward:1,yaw};}}return{};}
  a.prep=(a.prep||0)+dt;if(a.prep>4.3){a.prep=0;a.bag[0]-=3;a.bag[1]-=2;a.bag[2]--;inflate(a,a.id%3===0?'strong':'balanced');}return{};
 }
 fire(a,target,heavy=false){if(!a.alive||a.cooldown>0||a.reload>0)return;if(a.ammo<=0){a.reload=1.45;return;}const cost=heavy?16:1;if(a.ammo<cost)return;
  const start=V(a.x+Math.sin(a.yaw)*.65,a.y+1.36,a.z+Math.cos(a.yaw)*.65),at=target?.isVector3?target:V(target.x,target.y+(target.balloon?1.65+target.balloon.r+.3:1.25),target.z),velocity=at.clone().sub(start).normalize().multiplyScalar(heavy?54:85);const mesh=new T.Mesh(this.gumGeo,a.id===0?this.gumMat:this.foeMat);mesh.scale.setScalar(heavy?3.3:1);mesh.position.copy(start);this.scene.add(mesh);this.projectiles.push({p:start,v:velocity,owner:a,heavy,r:heavy?.32:.13,life:2.8,mesh});a.ammo-=cost;a.cooldown=a.id===0?.16:a.kind==='guard'?1.6:1.25;a.shotFlash=.15;if(a.id===0)this.sound('shot');
 }
 chargeRelease(cancel=false){if(!cancel&&this.charge>.25&&this.playing())this.fire(this.player,this.aim,true);this.charge=0;}
 updateShots(dt){for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.life-=dt;const d=p.v.clone().normalize(),step=p.v.length()*dt;let h=this.world.ray(p.p,d,step),best=h?.t??step+1,victim=null,balloonHit=false;
   for(const a of this.bodies){if(!a.alive||a.id===p.owner.id)continue;let hit=null,ball=false;if(a.balloon){hit=raySphere(p.p,d,{x:a.x,y:a.y+1.65+a.balloon.r+.3,z:a.z},a.balloon.r+p.r,Math.min(step,best));ball=hit!==null;}for(const y of[.50,1.15,1.58]){const t=raySphere(p.p,d,{x:a.x,y:a.y+y,z:a.z},.34+p.r,Math.min(step,best));if(t!==null&&(hit===null||t<hit)){hit=t;ball=false;}}if(hit!==null&&hit<best){best=hit;victim=a;balloonHit=ball;}}
   if(best<=step){const point=p.p.clone().addScaledVector(d,best);if(victim){gumHit(victim,p.heavy?23:7,balloonHit);if(victim.id===0){this.damage=.6;this.sound('hit');}else if(p.owner.id===0)this.sound('hit');}
    else{const mesh=new T.Mesh(this.gumGeo,this.gumMat);mesh.position.copy(point);mesh.scale.set(p.heavy?5:2.4,.50,p.heavy?5:2.4);this.scene.add(mesh);this.splats.push({mesh,life:20});if(this.splats.length>80){this.scene.remove(this.splats.shift().mesh);}}
    this.scene.remove(p.mesh);this.projectiles.splice(i,1);
   }else if(p.life<=0){this.scene.remove(p.mesh);this.projectiles.splice(i,1);}else{p.p.addScaledVector(p.v,dt);p.mesh.position.copy(p.p);}}
  for(let i=this.splats.length-1;i>=0;i--){this.splats[i].life-=dt;if(this.splats[i].life<=0){this.scene.remove(this.splats[i].mesh);this.splats.splice(i,1);}}
 }
 death(a,dt){if(!a.dropSpawned){a.dropSpawned=true;const mesh=new T.Mesh(new T.OctahedronGeometry(.55),new T.MeshStandardMaterial({color:0xf5d698,emissive:0x9c7030,emissiveIntensity:.4}));mesh.position.set(a.x,this.world.height(a.x,a.z)+.7,a.z);this.scene.add(mesh);this.drops.push({x:mesh.position.x,y:mesh.position.y,z:mesh.position.z,mesh,taken:false});if(a.id===0){this.closeCraft();this.penalty+=25;this.notify('Βαριά πτώση. Επιστροφή στην τελευταία προσγείωση · +25 s.',5);}}
  if(a.kind==='guard')return;
  a.respawn-=dt;if(a.respawn>0)return;
  const site=a.kind==='guard'?a.home:ROUTE[a.checkpoint];a.x=site.x+(a.id%3-1)*4;a.z=site.z+15;a.y=this.world.height(a.x,a.z)+.02;a.vx=a.vy=a.vz=0;a.gum=0;a.hp=100;a.grounded=true;a.alive=true;a.ammo=64;a.bag=[Math.max(3,a.bag[0]),Math.max(2,a.bag[1]),Math.max(1,a.bag[2])];a.dropSpawned=false;a.wait=3;a.prep=0;a.respawn=5;if(a.id===0)this.cameraReady=false;
 }
 finish(a){if(this.ended)return;if(!a)this.ended=false;this.ended=true;this.input.clear();show('endScreen',true);const win=a.id===0;$('endTitle').textContent=win?'Πρώτος στο οροπέδιο.':'Ο '+a.name+' προσγειώθηκε πρώτος.';$('endText').textContent=(win?'Ολοκλήρωσες και τις τρεις ορεινές στάσεις. ':'Ο αγώνας τελείωσε, αλλά η επόμενη διαδρομή περιμένει. ')+`Χρόνος: ${Math.floor((this.elapsed+this.penalty)/60)}:${String(Math.floor((this.elapsed+this.penalty)%60)).padStart(2,'0')} · πρόσθετη τσίχλα ${this.player.gum.toFixed(1)} kg.`;if(document.pointerLockElement)document.exitPointerLock();}
 tick(dt){if(!this.running||this.paused||this.mapOpen||this.ended)return;dt=clamp(dt,.001,.05);this.time+=dt;if(this.raceStarted)this.elapsed+=dt;this.damage=Math.max(0,this.damage-dt*1.2);if(this.time>this.toastUntil)$('toast').classList.remove('show');
  if(this.crafting&&this.craft.timer>0){this.craft.timer=Math.max(0,this.craft.timer-dt);if(this.craft.timer===0){this.craft.step++;if(this.craft.step>=3)this.finishCraft();}this.updateCraft();}
  const desired=this.desiredPlayer();if(this.player.alive)advanceBody(this.player,desired,this.world,dt,this.time);else this.death(this.player,dt);
  this.setCamera(dt);this.updateAim(dt);
  if(this.playing()&&this.player.alive){if(this.input.right){this.charge=Math.min(1.7,this.charge+dt);}else if((this.input.left||this.input.ring)&&this.charge<=0)this.fire(this.player,this.aim,false);}
  for(const a of this.bodies.slice(1)){if(!a.alive){this.death(a,dt);continue;}const d=this.npc(a,dt);advanceBody(a,d,this.world,dt,this.time);}
  separateBodies(this.bodies,this.world);this.updateShots(dt);
  const p=this.player;if(p.alive&&p.grounded&&p.target===4&&p.checkpoint===3&&distance(p,ROUTE[4])<40)this.finish(p);
  this.world.update(this.time);
 }
 setCamera(dt=0){if(!this.player)return;const p=this.player;let eye,look;
  if(!this.running){eye=V(p.x+90,p.y+80,p.z+140);look=V(p.x+10,p.y+60,p.z-530);}
  else if(this.fps){eye=V(p.x,p.y+1.67,p.z);look=eye.clone().add(V(Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),Math.cos(p.yaw)*Math.cos(p.pitch)));}
  else{const flying=!p.grounded,scale=this.zoom;eye=V(p.x+(flying?9:0)*scale,p.y+(flying?14:8)*scale,p.z+(flying?23:12)*scale);look=V(p.x,p.y+(flying?3:1.3),p.z-(flying?24:2));
   const base=V(p.x,p.y+2,p.z),delta=eye.clone().sub(base),hit=this.world.ray(base,delta.clone().normalize(),delta.length());if(hit&&hit.t>1.6)eye=base.addScaledVector(delta.normalize(),Math.max(1.6,hit.t-.5));}
  if(!this.cameraReady||this.fps){this.camera.position.copy(eye);this.camLook=look.clone();this.cameraReady=true;}else{const rate=Math.min(1,Math.max(.02,dt)*7);this.camera.position.lerp(eye,rate);this.camLook.lerp(look,rate);}this.camera.lookAt(this.camLook);this.camera.updateMatrixWorld(true);
  this.sun.position.set(p.x-80,p.y+140,p.z+100);this.sun.target.position.set(p.x,p.y,p.z);this.gun.visible=this.running&&this.fps&&p.alive;this.gun.userData.tank.scale.y=Math.max(.04,p.ammo/64);
 }
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.input.touch?1.05:1.35));this.renderer.setSize(innerWidth,innerHeight);this.cameraReady=false;}
 updateHUD(){if(!this.player||!this.running)return;const p=this.player,dest=ROUTE[p.target],metrics=telemetry({...p,vx:p.actualVx||0,vy:p.actualVy||0,vz:p.actualVz||0},dest,this.world.height(p.x,p.z));this.metrics=metrics;
  $('speed').textContent=metrics.speed.toFixed(0);$('ascend').textContent=metrics.ascend.toFixed(1);$('descend').textContent=metrics.descend.toFixed(1);$('climbCard').classList.toggle('active',metrics.ascend>.25);$('sinkCard').classList.toggle('active',metrics.descend>.25);$('landingDistance').textContent=metrics.distance>=1000?(metrics.distance/1000).toFixed(2):Math.round(metrics.distance);$('distanceUnit').textContent=metrics.distance>=1000?'km':'m';$('altitude').textContent='Από έδαφος '+Math.round(metrics.altitude)+' m';$('verticalTarget').textContent='Στόχος '+(metrics.targetDelta>=0?'+':'')+Math.round(metrics.targetDelta)+' m';$('stateText').textContent=p.alive?metrics.status:'ΕΠΙΣΤΡΟΦΗ ΣΕ '+Math.ceil(p.respawn)+' s';$('targetName').textContent=dest.name;$('stageCount').textContent=p.checkpoint+' / 3 ΣΦΡΑΓΙΔΕΣ';$('healthFill').style.width=p.hp+'%';$('healthText').textContent=Math.ceil(p.hp);
  $('weight').textContent='+'+p.gum.toFixed(1)+' kg';const margin=p.balloon?p.balloon.lift*p.balloon.integrity/p.balloon.maxIntegrity-p.mass-p.gum:0;$('liftReserve').textContent=p.balloon?'Περιθώριο άνωσης '+margin.toFixed(1)+' kg':'H / καθάρισμα στο έδαφος';$('weight').parentElement.classList.toggle('overload',!!p.balloon&&margin<0);$('life').textContent=p.balloon?Math.max(0,p.balloon.life).toFixed(0)+' s':'—';$('lifeFill').style.width=(p.balloon?clamp(p.balloon.life/p.balloon.maxLife*100,0,100):0)+'%';$('integrity').textContent=p.balloon?'Αντοχή '+Math.round(p.balloon.integrity/p.balloon.maxIntegrity*100)+'%':'B → νέο μπαλόνι';$('ammo').innerHTML=Math.ceil(p.ammo)+' <i>/ 64</i>';$('materials').textContent=`ΡΗΤΙΝΗ ${p.bag[0]} · ΙΝΑ ${p.bag[1]} · ΑΕΡΙΟ ${p.bag[2]}`;$('reloadState').textContent=p.reload>0?'ΑΝΑΓΕΜΙΣΗ '+p.reload.toFixed(1)+' s':'';$('chargeBar').style.opacity=this.charge>0?1:0;document.querySelector('#chargeBar i').style.width=this.charge/1.7*100+'%';$('damage').style.opacity=this.damage;
  let prompt=p.grounded?'B: νέο μείγμα · F: σφραγίδα / κιβώτιο':'SPACE ↑ / CTRL ↓ · Όχι πάνω από '+Math.round(p.balloon?.life||0)+' s ακόμη';if(p.grounded&&distance(p,dest)<12)prompt='F / ΛΑΦΥΡΑ → πάρε τη σφραγίδα';else if(!p.grounded&&metrics.distance<50)prompt='Πάνω από το οροπέδιο · κατέβα και προσγειώσου';$('prompt').textContent=prompt;
  for(const k of document.querySelectorAll('[data-code]'))k.classList.toggle('pressed',k.dataset.code.split(' ').some(c=>this.input.keys.has(c)));$('mouseL').classList.toggle('pressed',this.input.left);$('mouseR').classList.toggle('pressed',this.input.right);
  const marker=this.project(V(dest.x,dest.y+6,dest.z));$('targetMarker').style.left=clamp(marker.x,55,innerWidth-55)+'px';$('targetMarker').style.top=clamp(marker.front?marker.y:innerHeight-230,110,innerHeight-220)+'px';$('markerLabel').textContent=(p.target===4?'ΤΕΡΜΑ':String(p.target).padStart(2,'0'))+' · '+Math.round(metrics.distance)+' m';
  if(this.fps||this.input.touch){$('reticle').style.left='50%';$('reticle').style.top='50%';}else{$('reticle').style.left=this.input.mouse[0]+'px';$('reticle').style.top=this.input.mouse[1]+'px';}$('reticle').classList.toggle('locked',!!this.target);
 }
 drawMap(){const canvas=$('map'),ctx=canvas.getContext('2d'),size=canvas.width;ctx.fillStyle='#122c37';ctx.fillRect(0,0,size,size);
  if(!this.mapBase){const off=document.createElement('canvas');off.width=off.height=180;const c=off.getContext('2d'),im=c.createImageData(180,180);for(let j=0;j<180;j++)for(let i=0;i<180;i++){const h=this.world.height(-1400+i/180*2800,-1800+j/180*3150),v=clamp(h/780,0,1),k=(j*180+i)*4;im.data[k]=32+v*108;im.data[k+1]=64+v*108;im.data[k+2]=68+v*112;im.data[k+3]=255;}c.putImageData(im,0,0);this.mapBase=off;}ctx.drawImage(this.mapBase,0,0,size,size);
  const pos=p=>({x:(p.x+1400)/2800*size,y:(p.z+1800)/3150*size});ctx.strokeStyle='#e1abc7';ctx.lineWidth=2;ctx.setLineDash([5,6]);ctx.beginPath();for(const [i,p]of ROUTE.entries()){const q=pos(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);}ctx.stroke();ctx.setLineDash([]);ctx.font='bold 13px system-ui';for(const [i,p]of ROUTE.entries()){const q=pos(p);ctx.fillStyle=i<=this.player.checkpoint?'#a1e5cf':i===this.player.target?'#f9de95':'#d9dfe5';ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.fill();ctx.fillText(p.name,q.x+15,q.y+5);}for(const a of this.bodies.filter(b=>b.kind==='racer'&&b.alive)){const q=pos(a);ctx.fillStyle=a.id===0?'#f09fce':'#f0f4ef';ctx.beginPath();ctx.arc(q.x,q.y,a.id===0?6:3.5,0,Math.PI*2);ctx.fill();}}
 render(dt){if(!this.player)return;this.setCamera(dt);for(const a of this.bodies){const view=this.visuals.get(a.id);posePerson(view,a,this.time,dt,a.id===0&&this.fps,distance(a,this.player)<180||!this.running);}this.renderer.render(this.scene,this.camera);this.updateHUD();}
 snapshot(){const a=this.player;return{version:VERSION,playing:this.playing(),time:this.time,player:{x:a.x,y:a.y,z:a.z,vx:a.vx,vy:a.vy,vz:a.vz,gum:a.gum,hp:a.hp,grounded:a.grounded,balloon:!!a.balloon,target:a.target,checkpoint:a.checkpoint,bag:a.bag.slice()},metrics:this.metrics,projectiles:this.projectiles.length,racers:this.bodies.filter(a=>a.kind==='racer').length,guards:this.bodies.filter(a=>a.kind==='guard').length};}
}
try{new SummitGame;}catch(e){console.error(e);$('loading').textContent='Σφάλμα εκκίνησης: '+e.message;}
