/* Bubble — tiny, original WebGL2 renderer. No external runtime dependencies. */
export const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
export const v3=(x=0,y=0,z=0)=>[x,y,z], add=(a,b)=>a.map((v,i)=>v+b[i]), sub=(a,b)=>a.map((v,i)=>v-b[i]), mul=(a,k)=>a.map(v=>v*k), dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2], cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], len=a=>Math.hypot(...a), norm=a=>mul(a,1/(len(a)||1));
export const dist=(a,b)=>len(sub(a,b)), angleDelta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
export function hex(h){return [(h>>16&255)/255,(h>>8&255)/255,(h&255)/255,1];}
export function rng(seed=42){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
export function mm(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
export function trs(p=[0,0,0],s=[1,1,1],r=[0,0,0]){let [x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);return new Float32Array([(cy*cz+sy*sx*sz)*s[0],cx*sz*s[0],(-sy*cz+cy*sx*sz)*s[0],0,(-cy*sz+sy*sx*cz)*s[1],cx*cz*s[1],(sy*sz+cy*sx*cz)*s[1],0,sy*cx*s[2],-sx*s[2],cy*cx*s[2],0,...p,1]);}
export function lookAt(eye,target,up=[0,1,0]){let z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
export function perspective(fov,aspect,near=.06,far=210){let f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
export function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}
export function point(m,p){let x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15];return[(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w,w];}
export function between(a,b,r=.1,r2=r){let y=norm(sub(b,a)),x=norm(cross(Math.abs(y[1])>.99?[1,0,0]:[0,1,0],y)),z=cross(x,y),p=mul(add(a,b),.5),h=dist(a,b);return new Float32Array([x[0]*r,x[1]*r,x[2]*r,0,y[0]*h,y[1]*h,y[2]*h,0,z[0]*r2,z[1]*r2,z[2]*r2,0,...p,1]);}
export function facing(p,n,s){let z=norm(n),x=norm(cross(Math.abs(z[1])>.99?[0,0,1]:[0,1,0],z)),y=cross(z,x);return new Float32Array([x[0]*s[0],x[1]*s[0],x[2]*s[0],0,y[0]*s[1],y[1]*s[1],y[2]*s[1],0,z[0]*s[2],z[1]*s[2],z[2]*s[2],0,...p,1]);}
function geometry(kind){let p=[],n=[];const tri=(a,b,c,na,nb=na,nc=na)=>{p.push(...a,...b,...c);n.push(...na,...nb,...nc);};const flat=(a,b,c)=>tri(a,b,c,norm(cross(sub(b,a),sub(c,a))));
 if(kind==='cube'||kind==='stone'){const b=kind==='stone'?.065:0,c=.5-b,axes=[[1,0,0],[0,1,0],[0,0,1]];
 const face=(q)=>{let no=norm(cross(sub(q[1],q[0]),sub(q[2],q[0]))),mid=mul(q.reduce((a,p)=>add(a,p),[0,0,0]),1/q.length);if(dot(no,mid)<0)q=q.slice().reverse();for(let i=1;i<q.length-1;i++)flat(q[0],q[i],q[i+1]);};
 for(let ax=0;ax<3;ax++)for(let s of[-1,1]){let n=mul(axes[ax],s*.5),u=axes[(ax+1)%3],v=axes[(ax+2)%3];face([[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>add(n,add(mul(u,a*c),mul(v,b*c)))));}
 if(b){for(let free=0;free<3;free++)for(let sa of[-1,1])for(let sb of[-1,1]){let a=(free+1)%3,z=(free+2)%3;face([[-c,.5,c],[c,.5,c],[c,c,.5],[-c,c,.5]].map(([f,x,y])=>{let p=[0,0,0];p[free]=f;p[a]=x*sa;p[z]=y*sb;return p;}));}for(let sx of[-1,1])for(let sy of[-1,1])for(let sz of[-1,1])face([[.5,c,c],[c,.5,c],[c,c,.5]].map(p=>[p[0]*sx,p[1]*sy,p[2]*sz]));}
 }else if(kind==='sphere'||kind.startsWith('shell')){let seg=kind==='sphere'?16:5,rings=kind==='sphere'?10:12,sector=kind==='sphere'?null:Number(kind.slice(5));let start=sector===null?0:sector*TAU/8-TAU/16-.025,span=sector===null?TAU:TAU/8+.05;const at=(i,j)=>{let a=start+i/seg*span,b=-Math.PI/2+j/rings*Math.PI;return[Math.sin(a)*Math.cos(b),Math.sin(b),Math.cos(a)*Math.cos(b)];};for(let j=0;j<rings;j++)for(let i=0;i<seg;i++){let a=at(i,j),b=at(i+1,j),c=at(i+1,j+1),d=at(i,j+1);tri(a,c,b,a,c,b);tri(a,d,c,a,d,c);}
 }else if(kind==='cylinder'||kind==='cone'){let count=12,top=kind==='cone'?0:1;for(let i=0;i<count;i++){let a=i/count*TAU,b=(i+1)/count*TAU,A=[Math.sin(a),-.5,Math.cos(a)],B=[Math.sin(b),-.5,Math.cos(b)],C=[Math.sin(b)*top,.5,Math.cos(b)*top],D=[Math.sin(a)*top,.5,Math.cos(a)*top],na=norm([Math.sin(a),1-top,Math.cos(a)]),nb=norm([Math.sin(b),1-top,Math.cos(b)]);tri(A,B,C,na,nb,nb);tri(A,C,D,na,nb,na);tri([0,-.5,0],B,A,[0,-1,0]);if(top)tri([0,.5,0],D,C,[0,1,0]);}}
 return {positions:new Float32Array(p),normals:new Float32Array(n)};
}
const VS=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPos;layout(location=1) in vec3 aNormal;layout(location=2) in mat4 iMatrix;layout(location=6) in vec4 iColor;layout(location=7) in vec4 iProps;
uniform mat4 uVP,uLightVP;out vec3 vWorld,vNormal;out vec4 vColor,vProps,vShadow;
void main(){vec4 w=iMatrix*vec4(aPos,1.);vWorld=w.xyz;mat3 m=mat3(iMatrix);vNormal=normalize(m*(aNormal/vec3(dot(m[0],m[0]),dot(m[1],m[1]),dot(m[2],m[2]))));vColor=iColor;vProps=iProps;vShadow=uLightVP*w;gl_Position=uVP*w;}`;
const FS=`#version 300 es
precision highp float;in vec3 vWorld,vNormal;in vec4 vColor,vProps,vShadow;out vec4 frag;
uniform sampler2D uShadow;uniform vec3 uEye,uSun,uFog;uniform float uCut,uDungeon,uShadowOn,uTime;
float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
void main(){if(vProps.z>.5&&vWorld.y>uCut)discard;vec3 N=normalize(vNormal);if(!gl_FrontFacing)N=-N;float ndl=max(dot(N,uSun),0.),shade=1.;vec3 sc=vShadow.xyz/vShadow.w*.5+.5;
 if(uShadowOn>.5&&all(greaterThan(sc,vec3(0)))&&all(lessThan(sc,vec3(1)))){float bias=max(.003*(1.-ndl),.0014);shade=0.;vec2 texel=1./vec2(textureSize(uShadow,0));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(uShadow,sc.xy+vec2(x,y)*texel).r;shade+=sc.z-bias>d?.34:1.;}shade/=9.;}
 vec3 col=pow(vColor.rgb,vec3(2.2));float rough=vProps.x;if(rough>.75){float grain=noise(vWorld*2.8)*.09+noise(vWorld*12.)*.025;col*=.95+grain;}
 if(rough>.5&&rough<.7){float grain=sin(vWorld.y*20.+noise(vWorld*3.)*6.)*.07;col*=.94+grain;}
 vec3 H=normalize(uSun+normalize(uEye-vWorld));float spec=pow(max(dot(N,H),0.),mix(110.,10.,rough))*(1.-rough)*shade;
 float hemi=N.y*.5+.5;vec3 amb=mix(vec3(.20,.16,.21),vec3(.50,.62,.68),hemi);float underground=1.-smoothstep(-3.,.3,vWorld.y);amb=mix(amb,vec3(.25,.27,.34),underground*.8);
 vec3 light=amb+vec3(1.65,1.31,.93)*ndl*shade*(1.-underground*.85);col=col*light+vec3(1.1,.95,.85)*spec+pow(vColor.rgb,vec3(1.7))*vProps.y;
 float fog=1.-exp(-pow(length(vWorld-uEye)*.007,2.));col=mix(col,uFog,fog);col=col/(col+vec3(.68));frag=vec4(pow(col,vec3(1./2.2)),vColor.a);
}`;
const DEPTHFS=`#version 300 es
precision highp float;in vec3 vWorld;in vec4 vProps;uniform float uCut;void main(){if(vProps.z>.5&&vWorld.y>uCut)discard;}`;
export class Renderer{
 constructor(canvas){let gl=this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw Error('Χρειάζεται WebGL 2. Άνοιξε το παιχνίδι σε ενημερωμένο Safari, Chrome ή Edge.');this.canvas=canvas;this.program=this.programOf(VS,FS);this.depthProgram=this.programOf(VS,DEPTHFS);this.meshes=new Map;this.staticBatches=[];this.dynamicBatches=new Map;this.overlayBatches=new Map;this.stats={calls:0,instances:0};this.sun=norm([-35,55,24]);this.lightVP=mm(ortho(-66,66,-66,66,1,170),lookAt(mul(this.sun,85),[0,0,0]));this.shadowSize=1536;this.makeShadow();gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);this.pixelRatio=1;this.shadowOn=true;}
 programOf(v,f){let gl=this.gl;const shader=(type,source)=>{let s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};let p=gl.createProgram(),vs=shader(gl.VERTEX_SHADER,v),fs=shader(gl.FRAGMENT_SHADER,f);gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(vs);gl.deleteShader(fs);return p;}
 mesh(kind){if(this.meshes.has(kind))return this.meshes.get(kind);let gl=this.gl,g=geometry(kind),vao=gl.createVertexArray();gl.bindVertexArray(vao);for(let [i,arr] of [g.positions,g.normals].entries()){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,arr,gl.STATIC_DRAW);gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,0,0);}let m={vao,count:g.positions.length/3};this.meshes.set(kind,m);return m;}
 makeShadow(){let gl=this.gl;this.shadow=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadow);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,this.shadowSize,this.shadowSize,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.shadowFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadow,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)this.shadowOn=false;gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
 batch(kind,items,layer='all',dynamic=false){let gl=this.gl,b={kind,layer,buffer:gl.createBuffer(),count:items.length,dynamic};this.upload(b,items);return b;}
 upload(b,items){let gl=this.gl,data=new Float32Array(items.length*24);for(let i=0;i<items.length;i++){let it=items[i];data.set(it.m,i*24);data.set(it.c,i*24+16);data.set(it.p||[.85,0,0,0],i*24+20);}b.count=items.length;gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.bufferData(gl.ARRAY_BUFFER,data,b.dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);}
 setStatic(nodes){for(let b of this.staticBatches)this.gl.deleteBuffer(b.buffer);let groups=new Map;for(let n of nodes){let k=n.kind+'|'+(n.layer||'all');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(n);}this.staticBatches=[...groups].map(([k,a])=>this.batch(a[0].kind,a,k.split('|')[1]));}
 setDynamic(nodes,overlay=false){let pool=overlay?this.overlayBatches:this.dynamicBatches,groups=new Map;for(let n of nodes){let k=n.kind+'|'+(n.c[3]<.99?'glass':'solid');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(n);}for(let b of pool.values())b.count=0;for(let [k,a]of groups){if(!pool.has(k))pool.set(k,this.batch(a[0].kind,[],k.split('|')[1],true));this.upload(pool.get(k),a);}}
 resize(quality='auto'){let mobile=matchMedia('(pointer:coarse)').matches;this.pixelRatio=quality==='low'?1:Math.min(devicePixelRatio||1,mobile?1.35:1.75);let w=Math.floor(innerWidth*this.pixelRatio),h=Math.floor(innerHeight*this.pixelRatio);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.shadowOn=quality!=='low';}
 uniforms(p,vp,eye,cut,time,shadow=true,dungeon=false){let gl=this.gl,U=n=>gl.getUniformLocation(p,n);gl.useProgram(p);gl.uniformMatrix4fv(U('uVP'),false,vp);gl.uniformMatrix4fv(U('uLightVP'),false,this.lightVP);gl.uniform3fv(U('uEye'),eye);gl.uniform3fv(U('uSun'),this.sun);gl.uniform3fv(U('uFog'),[.20,.28,.32]);gl.uniform1f(U('uCut'),cut);gl.uniform1f(U('uDungeon'),dungeon?1:0);gl.uniform1f(U('uShadowOn'),shadow&&this.shadowOn?1:0);gl.uniform1f(U('uTime'),time);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.shadow);gl.uniform1i(U('uShadow'),0);}
 draw(b){if(!b.count)return;let gl=this.gl,m=this.mesh(b.kind);gl.bindVertexArray(m.vao);gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);for(let i=0;i<4;i++){gl.enableVertexAttribArray(2+i);gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,96,i*16);gl.vertexAttribDivisor(2+i,1);}for(let i=6;i<8;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,4,gl.FLOAT,false,96,(i===6?16:20)*4);gl.vertexAttribDivisor(i,1);}gl.drawArraysInstanced(gl.TRIANGLES,0,m.count,b.count);this.stats.calls++;this.stats.instances+=b.count;}
 render(camera,time,cut=100,dungeon=false,overlay=false){let gl=this.gl;this.stats.calls=0;this.stats.instances=0;let stat=this.staticBatches.filter(b=>!(dungeon&&b.layer==='surface')),dyn=[...this.dynamicBatches.values()];
  if(this.shadowOn){gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.viewport(0,0,this.shadowSize,this.shadowSize);gl.clear(gl.DEPTH_BUFFER_BIT);this.uniforms(this.depthProgram,this.lightVP,camera.eye,cut,time,false,dungeon);for(let b of [...stat,...dyn])if(b.layer!=='glass'&&b.kind!=='sphere'&&b.layer!=='decor')this.draw(b);gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
  gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(dungeon?.08:.30,dungeon?.10:.40,dungeon?.14:.45,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.uniforms(this.program,camera.vp,camera.eye,cut,time,true,dungeon);gl.disable(gl.BLEND);gl.depthMask(true);for(let b of [...stat,...dyn])if(b.layer!=='glass')this.draw(b);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);for(let b of dyn)if(b.layer==='glass')this.draw(b);gl.depthMask(true);gl.disable(gl.BLEND);
  if(overlay){gl.clear(gl.DEPTH_BUFFER_BIT);this.uniforms(this.program,perspective(.95,this.canvas.width/this.canvas.height,.02,15),[0,0,0],100,time,false);for(let b of this.overlayBatches.values())if(b.layer!=='glass')this.draw(b);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);for(let b of this.overlayBatches.values())if(b.layer==='glass')this.draw(b);gl.depthMask(true);gl.disable(gl.BLEND);}
 }
}
export function node(kind,p,s,c,r=[0,0,0],props=[.85,0,0,0],layer='all'){return{kind,m:trs(p,s,r),c:typeof c==='number'?hex(c):c,p:props,layer};}
export function segment(kind,a,b,r,c,props=[.3,0,0,0],r2=r){return{kind,m:between(a,b,r,r2),c:typeof c==='number'?hex(c):c,p:props};}
export function rayBox(o,d,b,max=Infinity){let t0=0,t1=max,normal=[0,0,0];for(let k=0;k<3;k++){let mn=b.min[k],mx=b.max[k];if(Math.abs(d[k])<1e-8){if(o[k]<mn||o[k]>mx)return null;continue;}let a=(mn-o[k])/d[k],c=(mx-o[k])/d[k],sg=-Math.sign(d[k]);if(a>c)[a,c]=[c,a];if(a>t0){t0=a;normal=[0,0,0];normal[k]=sg;}t1=Math.min(t1,c);if(t0>t1)return null;}return t0>=0&&t0<=max?{t:t0,n:normal,p:add(o,mul(d,t0))}:null;}
export function raySphere(o,d,c,r,max=Infinity){let oc=sub(o,c),b=dot(oc,d),cc=dot(oc,oc)-r*r,q=b*b-cc;if(q<0)return null;let t=-b-Math.sqrt(q);if(t<0)t=-b+Math.sqrt(q);if(t<0||t>max)return null;let p=add(o,mul(d,t));return{t,p,n:norm(sub(p,c))};}
