import {TAU,clamp,lerp,v3,add,sub,mul,dot,cross,len,norm,dist,angleDelta,hex,trs,mm,point,perspective,lookAt,node,segment,facing,raySphere,Renderer} from './engine.js';
import {World} from './world.js';
import {PURPLE,GREEN,makeActor,armor,spider,splatNodes,firstPersonGun} from './actors.js';
import {hitKnight,sectorFor} from './combat.js';
const $=id=>document.getElementById(id),hidden=(id,v)=>$(id).classList.toggle('hidden',v);
const canvas=$('game'),touch=matchMedia('(pointer:coarse)').matches,TEST=new URLSearchParams(location.search).has('test');
const CAPACITY=180,COLORS=[0x51cddd,0xf79172,0xf5cd58,0x70a8ff,0xf38fc2,0x79d4a9,0xf3a446,0xe4e5ef,0xfa606b,0x66e0ee],NAMES=['AZUR','EMBER','HONEY','COBALT','ROSE','MINT','TANGERINE','PEARL','RUBY','FROST'];
let world,renderer,camera={eye:[47,33,56],target:[0,3,0],fov:.92,vp:null},player,bots=[],boss=null,mode='top',started=false,paused=false,ended=false,time=0,elapsed=0,ammo=CAPACITY,reloadTime=0,shotTimer=0,recoil=0,captures=0,shots=0,hits=0,wallSplats=[],projectiles=[],particles=[],puddles=[],eventTimer=0,hitTint=0,hitMarker=0,toastTimer=0,stageDelay=-1,aiDisabled=false,invincible=false,ambientTimer=0;
const keys=new Set(),mouse={x:innerWidth/2,y:innerHeight*.43,down:false,moved:false},stick={move:[0,0],aim:[0,0]},pointer={left:null,right:null,look:null},labels=[],dynamic=[],overlay=[],signals=[],fixedDt=1/60;
let fireTouch=false,soundOn=true,audio=null,audioMaster=null,shake=0,frameCount=0,fps=60,last=0,drawMs=0,settingsQuality='auto';
function errorScreen(e){console.error(e);$('loading').classList.remove('hidden');$('loadText').textContent='Δεν μπόρεσε να ξεκινήσει: '+(e.message||e)+'. Δοκίμασε ανανέωση ή ενημερωμένο browser.';}
window.addEventListener('error',e=>{if(!started)errorScreen(e.error||e);});
function initAudio(){if(audio){audio.resume().catch(()=>{});return;}try{audio=new (window.AudioContext||window.webkitAudioContext)();audioMaster=audio.createGain();audioMaster.gain.value=.20;audioMaster.connect(audio.destination);}catch{} }
function tone(type='shot',enemy=false){if(!audio||!soundOn)return;let now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type=type==='step'?'triangle':'sine';let fr=type==='capture'?660:type==='dizzy'?390:type==='hit'?130:type==='jump'?190:type==='boss'?60:type==='step'?95:enemy?175:360,du=type==='capture'?.55:type==='boss'?1.5:.14;o.frequency.setValueAtTime(fr,now);o.frequency.exponentialRampToValueAtTime(Math.max(22,fr*(type==='capture'?1.8:.3)),now+du);f.type='lowpass';f.frequency.value=1400;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(type==='step'?.18:.4,now+.01);g.gain.exponentialRampToValueAtTime(.001,now+du);o.connect(f);f.connect(g);g.connect(audioMaster);o.start(now);o.stop(now+du+.02);o.onended=()=>{o.disconnect();g.disconnect();f.disconnect();};}
function notify(text,duration=3){$('toast').textContent=text;$('toast').classList.add('show');toastTimer=duration;}
function reset(){player=makeActor(-1,[0,0,24],PURPLE,'ΕΣΥ');player.hp=100;player.sticky=0;player.dizzy=0;player.lastHit=-100;player.pitch=-.025;player.walk=0;player.yaw=Math.PI;bots=[];let spawns=[[0,0,12],[-10,0,6],[11,0,3],[-23,0,12],[24,0,16],[-23,0,-10],[-5,0,-19],[4,5,-21],[22,-5,-16],[27,-5,-25]];
 for(let i=0;i<10;i++){let b=makeActor(i,spawns[i],COLORS[i],NAMES[i]);b.yaw=(i*.87)%TAU;b.patrol=0;bots.push(b);}boss=null;ammo=CAPACITY;reloadTime=shotTimer=captures=shots=hits=elapsed=0;stageDelay=-1;wallSplats=[];projectiles=[];particles=[];puddles=[];ended=false;shake=0;hitTint=0;hidden('end',true);hidden('bossPanel',true);hidden('targetCard',true);for(let el of labels)el.remove();labels.length=0;for(let b of bots){let el=document.createElement('div');el.className='bot-label';el.innerHTML='<small></small><b>'+b.name+'</b><div class="tiny-track"><i></i></div><div class="small-stamina"><i></i></div>';$('worldLabels').append(el);labels.push(el);}mouse.down=fireTouch=false;keys.clear();stick.move=[0,0];stick.aim=[0,0];}
function startGame(){initAudio();reset();started=true;paused=false;hidden('menu',true);hidden('hud',false);hidden('pause',true);hidden('help',true);mode='top';updateCameraMode();notify('Μοβ τσίχλα έτοιμη. Ζάλισε τον πρώτο ιππότη!',4);last=performance.now();}
function pauseGame(value=true){if(!started||ended)return;paused=value;hidden('pause',!value);mouse.down=fireTouch=false;keys.clear();stick.move=[0,0];stick.aim=[0,0];if(value&&document.pointerLockElement)document.exitPointerLock();if(!value){initAudio();if(mode==='fp')lockPointer();}}
function lockPointer(){if(touch||TEST)return;try{let p=canvas.requestPointerLock();if(p?.catch)p.catch(()=>{});}catch{} }
function updateCameraMode(){ $('cameraLabel').textContent=mode==='fp'?'FPS':'TOP';$('cameraBtn').title=mode==='fp'?'Πρώτο πρόσωπο · C για top-down':'Top-down · C για πρώτο πρόσωπο';if(mode==='fp'){if(!touch)lockPointer();}else{if(document.pointerLockElement)document.exitPointerLock();hidden('resumeLook',true);} }
function toggleCamera(){if(!started||paused||ended)return;mode=mode==='top'?'fp':'top';mouse.down=false;updateCameraMode();notify(mode==='fp'?'Πρώτο πρόσωπο · η δεξαμενή στο όπλο δείχνει την τσίχλα σου.':'Top-down · στόχευσε με το ποντίκι ή το δεξί joystick.',2.4);}
function jump(){if(!started||paused||ended||!player.grounded)return;player.vy=7.7;player.grounded=false;player.stamina=Math.max(0,player.stamina-8);player.sticky=Math.max(0,player.sticky-.18);tone('jump');}
function refill(){if(!started||paused||ended||reloadTime>0||ammo>=CAPACITY)return;reloadTime=1.7;tone('jump');}
function makeSplash(p,n,color,size=.52,target=null){let s={p:p.slice(),n:norm(n),color,size,born:time,seed:Math.random()*6.3};if(target){let d=sub(p,target.p),c=Math.cos(target.yaw),sn=Math.sin(target.yaw);s.local=[d[0]*c-d[2]*sn,d[1],d[0]*sn+d[2]*c];s.n=[s.n[0]*c-s.n[2]*sn,s.n[1],s.n[0]*sn+s.n[2]*c];s.size=.24+Math.random()*.06;s.seed=target.id*.7+target.splats.length;target.splats.push(s);if(target.splats.length>22)target.splats.shift();}else{wallSplats.push(s);if(wallSplats.length>(touch?140:220))wallSplats.shift();}
 for(let i=0;i<5;i++)particles.push({p:p.slice(),v:add(mul(n,1.5+Math.random()*2),[(Math.random()-.5)*3,Math.random()*2,(Math.random()-.5)*3]),life:.45+Math.random()*.4,max:.8,color,size:.035+Math.random()*.04});return s;}
function captured(b){captures++;b.moving=0;b.hp=0;ammo=Math.min(CAPACITY,ammo+80);player.hp=Math.min(100,player.hp+12);player.stamina=Math.min(100,player.stamina+20);tone('capture');notify((b.pin?'ΣΤΟΝ ΤΟΙΧΟ! ':'ΠΛΗΡΕΣ ΤΥΛΙΓΜΑ! ')+b.name+' · +80 τσίχλες · +12 πανοπλία',3);if(captures===10){stageDelay=2.8;notify('10 / 10. Κάτι μεγάλο ξύπνησε κάτω από το κάστρο…',3);}}
function onBotHit(b,source,impact,n){if(b.state==='captured'){makeSplash(impact,n,PURPLE,.24,b);return;}hits++;makeSplash(impact,n,PURPLE,.25,b);let result=hitKnight(b,source,world);hitMarker=.13;hitTint=Math.max(hitTint,.06);tone('hit');if(result.justDizzy){tone('dizzy');notify(b.pin?'Τον πιάνεις στον τοίχο! Συνέχισε μέχρι 5 δεσίματα.':'Ζαλίστηκε! Γύρισέ του για κάλυψη 360°.',2.5);}if(result.captured)captured(b);}
function spawnBoss(){boss={id:99,p:[0,0,-5],yaw:0,hp:750,maxHp:750,stamina:180,dizzy:0,cooldown:2.3,phase:1,state:'active',splats:[],radius:2.0,vy:0,grounded:true,pulse:0};hidden('bossPanel',false);hidden('targetCard',true);tone('boss');shake=.5;notify('ARACHNE-09 · Απόφυγε την πράσινη τοξική τσίχλα!',4);if(player.p[1]!==0)notify('Η ARACHNE-09 σε περιμένει στη μεγάλη αυλή. Ακολούθησε τον πράσινο δείκτη.',5);}
function onBossHit(source,impact,n){if(!boss||boss.state==='captured')return;hits++;makeSplash(impact,n,PURPLE,.35,boss);let dmg=boss.dizzy>0?27:12;boss.hp=Math.max(0,boss.hp-dmg);boss.stamina-=13;hitMarker=.14;tone('hit');if(boss.stamina<=0&&boss.dizzy<=0){boss.dizzy=6.5;boss.stamina=200;notify('Η αράχνη ζαλίστηκε! Τώρα η τσίχλα κάνει περισσότερη ζημιά.',3);}if(boss.hp<=375)boss.phase=2;if(boss.hp<=0){boss.state='captured';projectiles=projectiles.filter(p=>p.owner==='player');puddles=[];tone('capture');notify('Η ARACHNE-09 έγινε μοβ καβούκι. Το κάστρο είναι δικό σου!',5);eventTimer=2.5;}}
function hurt(amount,color,poison=false){if(invincible||ended)return;player.hp=Math.max(0,player.hp-amount);player.stamina=Math.max(0,player.stamina-(poison?amount:19));player.sticky=clamp(player.sticky+(poison?.015:.13),0,.70);player.lastHit=time;hitTint=.55;shake=.08;if(!poison)tone('hit',true);if(player.stamina<=0&&player.dizzy<=0){player.dizzy=2.5;player.stamina=28;tone('dizzy');}if(player.hp<=0)finish(false);}
function finish(win){ended=true;mouse.down=fireTouch=false;if(document.pointerLockElement)document.exitPointerLock();hidden('end',false);$('endEyebrow').textContent=win?'THE CASTLE IS YOURS':'OUT OF STAMINA. NOT OUT OF GUM.';$('endTitle').textContent=win?'Κόλλησαν όλοι.':'Σε κόλλησαν.';$('endText').textContent=win?'Δέκα ιππότες και μία τεράστια ρομποτική αράχνη, ασφαλισμένοι με μοβ τσίχλα. Η πολιορκία τελείωσε.':'Πήδα για να τινάξεις την τσίχλα, χρησιμοποίησε τους τοίχους για κάλυψη και κράτα απόσταση από τις πράσινες λίμνες.';$('endStats').innerHTML='<div>ΣΥΛΛΗΨΕΙΣ<b>'+captures+'/10</b></div><div>ΧΡΟΝΟΣ<b>'+formatTime(elapsed)+'</b></div><div>ΕΥΣΤΟΧΙΑ<b>'+Math.min(100,Math.round(hits/Math.max(1,shots)*100))+'%</b></div>';}
function screenRay(x,y){let forward=norm(sub(camera.target,camera.eye)),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),f=Math.tan(camera.fov/2),nx=x/innerWidth*2-1,ny=1-y/innerHeight*2;return{origin:camera.eye.slice(),dir:norm(add(forward,add(mul(right,nx*f*innerWidth/innerHeight),mul(up,ny*f))))};}
function actorRay(o,d,max=90,includeCaptured=true){let best=null;for(let a of bots){if(!includeCaptured&&a.state==='captured')continue;for(let [yy,rr]of[[.75,.52],[1.30,.55],[1.86,.34]]){let h=raySphere(o,d,add(a.p,[0,yy,0]),rr,max);if(h&&(!best||h.t<best.t)){best={...h,actor:a};max=h.t;}}}if(boss){for(let [offset,rr]of[[[0,2.2,0],1.65],[[0,2,1.2],1.1]]){let h=raySphere(o,d,add(boss.p,offset),rr,max);if(h&&(!best||h.t<best.t)){best={...h,boss:true};max=h.t;}}}return best;}
let aim={point:[0,1.2,0],dir:[0,0,-1],target:null};
function updateAim(){let origin=add(player.p,[0,1.26,0]);if(mode==='fp'){aim.dir=[Math.sin(player.yaw)*Math.cos(player.pitch),Math.sin(player.pitch),Math.cos(player.yaw)*Math.cos(player.pitch)];let target=actorRay(camera.eye,aim.dir),ob=world.ray(camera.eye,aim.dir,target?target.t:70);aim.target=target&&(!ob||target.t<ob.t)?target:null;aim.point=target&&aim.target?target.p:ob?ob.p:add(camera.eye,mul(aim.dir,60));}
 else if(touch&&len(stick.aim)>.12){let dir=norm([stick.aim[0],0,stick.aim[1]]),best=null,score=.955;for(let b of bots){if(b.state==='captured')continue;let d=sub(add(b.p,[0,1.2,0]),origin),ln=len(d),dd=norm([d[0],0,d[2]]),v=dot(dir,dd);if(v>score&&ln<24&&Math.abs(d[1])<5.5&&!world.ray(origin,norm(d),ln-.4)){best=b;score=v;}}if(boss){let d=sub(add(boss.p,[0,2.2,0]),origin);if(dot(dir,norm([d[0],0,d[2]]))>.93)best=boss;}aim.point=best?add(best.p,[0,best===boss?2.2:1.2,0]):add(origin,mul(dir,35));aim.dir=norm(sub(aim.point,origin));aim.target=best?(best===boss?{boss:true}:{actor:best}):null;player.yaw=Math.atan2(dir[0],dir[2]);}
 else if(!touch){let ray=screenRay(mouse.x,mouse.y),target=actorRay(ray.origin,ray.dir),floorT=(player.p[1]+1.25-ray.origin[1])/ray.dir[1];aim.point=target?target.p:add(ray.origin,mul(ray.dir,Math.max(1,floorT)));aim.dir=norm(sub(aim.point,origin));let obstacle=world.ray(origin,aim.dir,target?dist(origin,aim.point)-.2:70);aim.target=target&&!obstacle?target:null;player.yaw=Math.atan2(aim.dir[0],aim.dir[2]);}
 else{aim.dir=[Math.sin(player.yaw),0,Math.cos(player.yaw)];aim.point=add(origin,mul(aim.dir,40));aim.target=null;}
 $('crosshair').style.left=(mode==='top'&&!touch?mouse.x:innerWidth/2)+'px';$('crosshair').style.top=(mode==='top'&&!touch?mouse.y:innerHeight/2)+'px';$('crosshair').classList.toggle('target',!!aim.target);}
function launch(origin,dir,color,owner,source,speed=31){if(projectiles.length>130)return;projectiles.push({p:origin.slice(),v:mul(norm(dir),speed),color,owner,source:source.slice(),life:3.2,r:owner==='boss'?.22:owner==='player'?.12:.15});}
function playerShoot(){if(shotTimer>0||reloadTime>0)return;if(ammo<=0){refill();return;}shotTimer=.145;ammo--;shots++;recoil=1;let source=add(player.p,[0,1.27,0]),target=aim.point,dir=norm(sub(target,source));if(mode==='fp'){source=add(player.p,[0,1.65,0]);dir=norm(sub(aim.point,source));}launch(source,dir,PURPLE,'player',player.p,35);tone('shot');}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){let p=projectiles[i];p.life-=dt;let step=mul(p.v,dt),length=len(step),d=norm(step),hit=world.ray(p.p,d,length);if(p.owner==='player'){let actor=actorRay(p.p,d,hit?hit.t:length);if(actor&&(!hit||actor.t<hit.t))hit=actor;}else{let h=raySphere(p.p,d,add(player.p,[0,1.02,0]),.64,length);if(h&&(!hit||h.t<hit.t))hit={...h,player:true};}
 if(hit){if(hit.actor)onBotHit(hit.actor,p.source,hit.p,hit.n);else if(hit.boss)onBossHit(p.source,hit.p,hit.n);else if(hit.player){hurt(p.owner==='boss'?8:4,p.color);makeSplash(hit.p,hit.n,p.color,.22,player);}else{makeSplash(add(hit.p,mul(hit.n,.025)),hit.n,p.color,p.owner==='boss'?.95:.52);if(p.owner==='boss'&&hit.floor){puddles.push({p:hit.p.slice(),r:1.25,born:time,life:9});if(puddles.length>18)puddles.shift();}}projectiles.splice(i,1);}else if(p.life<=0)projectiles.splice(i,1);else p.p=add(p.p,step);}
 for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.v[1]-=7*dt;p.p=add(p.p,mul(p.v,dt));if(p.life<=0)particles.splice(i,1);}for(let i=puddles.length-1;i>=0;i--){let p=puddles[i];p.life-=dt;if(p.life<=0){puddles.splice(i,1);continue;}let d=Math.hypot(player.p[0]-p.p[0],player.p[2]-p.p[2]);if(d<p.r+.18&&Math.abs(player.p[1]-p.p[1])<.5)hurt(7*dt,GREEN,true);}}
function updateBots(dt){let attackers=bots.filter(b=>b.state==='active'&&Math.abs(b.p[1]-player.p[1])<3&&dist(b.p,player.p)<22).sort((a,b)=>dist(a.p,player.p)-dist(b.p,player.p)).slice(0,3);
 for(let b of bots){b.hitFlash=Math.max(0,b.hitFlash-dt);b.moving=0;if(b.state==='captured')continue;if(b.state==='dizzy'||b.state==='pinning'){b.dizzy-=dt;if(b.dizzy<=0&&b.hp>0&&!b.pin){b.state='active';b.stamina=65;notify(b.name+' συνήλθε. Μη χάσεις το τύλιγμα!',2);}continue;}if(aiDisabled)continue;b.notice=Math.max(0,b.notice-dt);let toPlayer=sub(player.p,b.p),distance=len(toPlayer),eye=add(b.p,[0,1.28,0]),aimAt=add(player.p,[0,1.22,0]),shotDir=norm(sub(aimAt,eye)),shotDist=dist(eye,aimAt),canSee=distance<21&&!world.ray(eye,shotDir,Math.max(0,shotDist-.8));if(canSee)b.notice=10;b.pathTimer-=dt;b.cooldown-=dt;
 let goal,engaged=b.notice>0;if(engaged&&distance>7)goal=player.p;else if(engaged){let theta=Math.atan2(toPlayer[0],toPlayer[2])+(b.id%2?1.65:-1.65),step=.8;goal=add(b.p,[Math.sin(theta)*step,0,Math.cos(theta)*step]);}else{if(!b.patrol||dist(b.p,b.patrol)<1.5){let offset=[Math.sin(time*.2+b.id)*4,0,Math.cos(time*.19+b.id)*4],n=world.nearest(add(b.home,offset));b.patrol=n?.p||b.home;}goal=b.patrol;}
 if(b.pathTimer<=0){b.path=world.path(b.p,goal);b.pathTimer=engaged?.7:2.3;}let wp=b.path[0];if(wp){let d=[wp[0]-b.p[0],0,wp[2]-b.p[2]],ll=len(d);if(ll<.3)b.path.shift();else{let speed=engaged?2.05:1.15;if(distance<4&&engaged)speed=1.4;let v=mul(norm(d),speed);world.move(b,v[0]*dt,v[2]*dt,dt);b.moving=1;b.walk+=dt*7;}}else world.move(b,0,0,dt);
 let face=engaged?Math.atan2(toPlayer[0],toPlayer[2]):wp?Math.atan2(wp[0]-b.p[0],wp[2]-b.p[2]):b.yaw;b.yaw+=angleDelta(b.yaw,face)*Math.min(1,dt*5);b.stamina=Math.min(100,b.stamina+dt*2.3);
 if(canSee&&attackers.includes(b)&&b.cooldown<=0&&distance>2.2){let jitter=[(Math.random()-.5)*.055,(Math.random()-.5)*.045,(Math.random()-.5)*.055];launch(eye,add(shotDir,jitter),b.color,'bot',b.p,11.5);b.cooldown=1.75+(b.id%4)*.27;if(distance<14)tone('shot',true);}}
}
function updateBoss(dt){if(!boss||boss.state==='captured')return;if(aiDisabled)return;let b=boss,to=sub(player.p,b.p),distance=len(to);b.yaw+=angleDelta(b.yaw,Math.atan2(to[0],to[2]))*Math.min(1,dt*1.4);b.dizzy=Math.max(0,b.dizzy-dt);if(b.dizzy>0)return;let speed=distance>11?1.6:distance<6?-1.4:0,dir=norm([to[0],0,to[2]]),nx=clamp(b.p[0]+dir[0]*speed*dt,-9.5,9.5),nz=clamp(b.p[2]+dir[2]*speed*dt,-9,20);if(!world.blocked(nx,nz,0,2.0)){b.p[0]=nx;b.p[2]=nz;}b.cooldown-=dt;if(b.cooldown<=0){let origin=add(b.p,[Math.sin(b.yaw)*1.7,2.08,Math.cos(b.yaw)*1.7]),target=add(player.p,[0,1.0,0]),dd=norm(sub(target,origin));if(!world.ray(origin,dd,dist(origin,target)-.8)){for(let a of(b.phase===2?[-.19,-.095,0,.095,.19]:[-.11,0,.11])){let ca=Math.cos(a),sa=Math.sin(a),d=[dd[0]*ca+dd[2]*sa,dd[1]-.015,dd[2]*ca-dd[0]*sa];launch(origin,d,GREEN,'boss',b.p,13);} // Mortar drops leave avoidable toxic puddles in the arena.
 let groundTarget=add(player.p,[Math.sin(time*1.4)*2,-.4,Math.cos(time)*2]);launch(origin,norm(sub(groundTarget,origin)),GREEN,'boss',b.p,11);tone('boss');}b.cooldown=b.phase===2?1.15:1.75;}}
function updatePlayer(dt){let x=0,z=0;if(keys.has('KeyW')||keys.has('ArrowUp'))z--;if(keys.has('KeyS')||keys.has('ArrowDown'))z++;if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;x+=stick.move[0];z+=stick.move[1];let magnitude=Math.min(1,Math.hypot(x,z)),move=norm([x,0,z]);if(mode==='fp'){let forward=[Math.sin(player.yaw),0,Math.cos(player.yaw)],right=[-Math.cos(player.yaw),0,Math.sin(player.yaw)];move=add(mul(right,move[0]),mul(forward,-move[2]));if(touch&&len(stick.aim)>.15){player.yaw-=stick.aim[0]*dt*2.15;player.pitch=clamp(player.pitch-stick.aim[1]*dt*1.6,-1.20,1.20);}}
 let sprint=(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&player.stamina>5,speed=(sprint?7.4:5.0)*(1-player.sticky*.52)*(player.dizzy>0?.45:1);world.move(player,move[0]*magnitude*speed*dt,move[2]*magnitude*speed*dt,dt);player.moving=magnitude;player.walk+=dt*magnitude*(sprint?12:8);if(magnitude>0&&touch&&mode==='top'&&len(stick.aim)<.1)player.yaw=Math.atan2(move[0],move[2]);if(sprint&&magnitude)player.stamina=Math.max(0,player.stamina-dt*14);else player.stamina=Math.min(100,player.stamina+dt*(time-player.lastHit>2?13:4));player.dizzy=Math.max(0,player.dizzy-dt);player.sticky=Math.max(0,player.sticky-dt*.033);player.hitFlash=Math.max(0,player.hitFlash-dt);ambientTimer-=dt;if(magnitude>.3&&player.grounded&&ambientTimer<=0){tone('step');ambientTimer=sprint?.27:.38;}}
function update(dt){time+=dt;if(!started||paused||ended)return;elapsed+=dt;shotTimer-=dt;recoil=Math.max(0,recoil-dt*8);hitTint=Math.max(0,hitTint-dt*1.3);hitMarker=Math.max(0,hitMarker-dt);shake=Math.max(0,shake-dt*.7);if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('show');}if(reloadTime>0){reloadTime-=dt;if(reloadTime<=0){ammo=CAPACITY;reloadTime=0;tone('capture');}}
 updatePlayer(dt);setCamera();updateAim();if(mouse.down||fireTouch||len(stick.aim)>.24)playerShoot();updateBots(dt);updateBoss(dt);updateProjectiles(dt);if(stageDelay>0){stageDelay-=dt;if(stageDelay<=0)spawnBoss();}if(boss?.state==='captured'&&eventTimer>0){eventTimer-=dt;if(eventTimer<=0)finish(true);} }
function setCamera(){let eye,target;if(!started){let a=.56+Math.sin(time*.055)*.07;eye=[Math.sin(a)*78,42+Math.sin(time*.12)*1.4,Math.cos(a)*78];target=[0,3,-1];camera.fov=.88;}else if(mode==='top'){let distance=innerWidth<innerHeight?24:19;eye=add(player.p,[0,distance,distance*.65]);target=add(player.p,[0,.4,-2.0]);camera.fov=.96;}else{let bob=player.grounded?Math.sin(player.walk)*.031*player.moving:0;eye=add(player.p,[0,1.83+bob,0]);let pitch=player.pitch+(player.dizzy>0?Math.sin(time*3)*.035:0),yaw=player.yaw+(player.dizzy>0?Math.sin(time*2.5)*.025:0);target=add(eye,[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)]);camera.fov=1.15;}
 if(started&&shake>0){eye=add(eye,[(Math.random()-.5)*shake,(Math.random()-.5)*shake*.4,0]);}camera.eye=eye;camera.target=target;camera.vp=mm(perspective(camera.fov,innerWidth/innerHeight,.055,190),lookAt(eye,target));}
function buildDynamic(){dynamic.length=0;overlay.length=0;for(let b of bots)armor(b,time,dynamic);if(started&&mode!=='fp')armor(player,time,dynamic,true);if(boss)spider(boss,time,dynamic);for(let s of wallSplats)splatNodes(s,time,dynamic);for(let p of projectiles){dynamic.push({kind:'sphere',m:facing(p.p,norm(p.v),[p.r,p.r,p.r*1.65]),c:hex(p.color),p:[.10,.16,0,0]});let d=norm(p.v);for(let i=1;i<3;i++)dynamic.push(node('sphere',add(p.p,mul(d,-i*.16)),[p.r*(1-i*.22),p.r*(1-i*.22),p.r*(1-i*.22)],p.color,[0,0,0],[.18,.07,0,0]));}
 for(let p of particles)dynamic.push(node('sphere',p.p,[p.size,p.size*1.3,p.size],p.color,[0,0,0],[.17,.03,0,0]));for(let p of puddles){dynamic.push(node('sphere',add(p.p,[0,.025,0]),[p.r,.05,p.r],GREEN,[0,0,0],[.1,.17,0,0]));for(let i=0;i<4;i++){let a=i*TAU/4+time*.1,rr=p.r*.6;dynamic.push(node('sphere',add(p.p,[Math.sin(a)*rr,.09+Math.sin(time*4+i)*.025,Math.cos(a)*rr]),[.12,.10,.12],0xd1ff74,[0,0,0],[.1,.35,0,0]));}}
 for(let [i,p]of world.torches.entries()){let s=.16+Math.sin(time*8+i)*.04;dynamic.push(node('sphere',p,[s,s*2,s],0xffc072,[0,0,0],[.6,2.1,0,0]));dynamic.push(node('sphere',add(p,[0,.10,0]),[s*.55,s*1.7,s*.55],0xffe5a5,[0,0,0],[.5,2.5,0,0]));}
 if(started&&mode==='fp')firstPersonGun(player,time,ammo,CAPACITY,reloadTime>0?Math.sin(reloadTime/1.7*Math.PI):0,recoil,overlay,innerWidth/innerHeight);renderer.setDynamic(dynamic);renderer.setDynamic(overlay,true);}
function formatTime(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function project(p){let q=point(camera.vp,p);return {x:(q[0]*.5+.5)*innerWidth,y:(.5-q[1]*.5)*innerHeight,visible:q[3]>0&&Math.abs(q[0])<1.2&&Math.abs(q[1])<1.2};}
function updateHUD(){if(!started)return;$('captures').textContent=captures;$('healthValue').textContent=Math.ceil(player.hp);$('healthFill').style.width=player.hp+'%';$('staminaFill').style.width=player.stamina+'%';$('ammoValue').textContent=ammo;$('ammoFill').style.width=(reloadTime>0?(1-reloadTime/1.7)*100:ammo/CAPACITY*100)+'%';$('reloadLabel').textContent=reloadTime>0?'ΑΝΑΓΕΜΙΣΗ… '+reloadTime.toFixed(1)+'s':'ΔΕΞΑΜΕΝΗ ΤΣΙΧΛΑΣ';$('timer').textContent=formatTime(elapsed);$('playerState').textContent=player.dizzy>0?'ΖΑΛΙΣΜΕΝΟΣ':player.sticky>.25?'ΚΟΛΛΩΜΕΝΟΣ · ΠΗΔΑ!':player.grounded?'ΕΤΟΙΜΟΣ':'ΣΤΟΝ ΑΕΡΑ';$('hitTint').style.opacity=hitTint;hidden('dizzyText',player.dizzy<=0);let surface=world.support(player.p[0],player.p[2],player.p[1],.55);$('location').textContent=(surface?.s.name||'ΣΚΑΛΕΣ').toUpperCase();$('mapLevel').textContent=player.p[1]<-1.4?'DUNGEON / −1':player.p[1]>3.8?'ΕΠΑΛΞΕΙΣ / +1':'ΑΥΛΗ / 0';$('phase').textContent=boss?'02 — Ο ΤΕΛΙΚΟΣ ΑΡΧΗΓΟΣ':'01 — ΚΑΘΑΡΙΣΕ ΤΟ ΚΑΣΤΡΟ';$('objectiveText').textContent=boss?'ARACHNE-09: τοξική πολιορκία':'Ζάλισε. Κόλλησε. Τύλιξε.';$('objectiveSub').textContent=boss?'Απόφυγε τις πράσινες λίμνες. Χτύπα όταν ζαλιστεί.':'Τύλιξε γύρω-γύρω ή στερέωσε στον τοίχο.';let tx=mode==='top'&&!touch?mouse.x:innerWidth/2,ty=mode==='top'&&!touch?mouse.y:innerHeight/2;$('hitmarker').style.left=tx+'px';$('hitmarker').style.top=ty+'px';$('hitmarker').style.opacity=hitMarker>0?1:0;
 let target=aim.target?.actor;if(!target){let nearest=bots.filter(b=>b.state==='dizzy'||b.state==='pinning').sort((a,b)=>dist(a.p,player.p)-dist(b.p,player.p))[0];if(nearest&&dist(nearest.p,player.p)<9)target=nearest;}hidden('targetCard',!target||!!boss);if(target&&!boss){$('targetName').textContent=target.name;$('targetState').textContent=target.state==='captured'?'ΑΣΦΑΛΙΣΜΕΝΟΣ':target.pin?'ΔΕΣΙΜΟ '+target.pinHits+'/5':target.state==='dizzy'?'DIZZY':'ΠΑΝΟΠΛΙΑ';$('targetHealth').style.width=target.hp+'%';$('targetStamina').style.width=target.stamina+'%';[...$('sectors').children].forEach((el,i)=>{el.classList.toggle('filled',target.coverage[i]>=.999);el.style.opacity=.3+.7*target.coverage[i];});$('targetHint').textContent=target.pin?'Συνέχισε τις βολές στον τοίχο.':target.state==='dizzy'?'Γύρισέ του · κάλυψε και τους 8 τομείς.':'Άδειασε τη stamina για να ζαλιστεί.';}
 if(boss){$('bossHP').textContent=Math.ceil(boss.hp)+' / 750';$('bossFill').style.width=boss.hp/750*100+'%';$('bossState').textContent=boss.dizzy>0?'DIZZY — ΤΩΡΑ ΚΑΝΕΙΣ ΠΕΡΙΣΣΟΤΕΡΗ ΖΗΜΙΑ':boss.phase===2?'ΦΑΣΗ 2 · ΠΕΝΤΑΠΛΕΣ ΒΟΛΕΣ · ΠΡΟΣΕΧΕ ΤΟ ΠΑΤΩΜΑ':'ΤΟΞΙΚΗ ΤΣΙΧΛΑ · ΠΡΟΣΕΧΕ ΤΙΣ ΠΡΑΣΙΝΕΣ ΛΙΜΝΕΣ';}
 for(let i=0;i<bots.length;i++){let b=bots[i],el=labels[i],q=project(add(b.p,[0,2.65,0])),distance=dist(player.p,b.p),visible=b.state!=='captured'&&q.visible&&distance<24&&Math.abs(player.p[1]-b.p[1])<4.5;if(visible&&mode==='fp'){let d=sub(add(b.p,[0,1.8,0]),camera.eye);visible=!world.ray(camera.eye,norm(d),len(d)-.7);}el.style.display=visible?'block':'none';if(visible){el.style.left=q.x+'px';el.style.top=q.y+'px';el.querySelector('.tiny-track i').style.width=b.hp+'%';el.querySelector('.small-stamina i').style.width=b.stamina+'%';el.querySelector('small').textContent=b.pin?'ΔΕΣΙΜΟ '+b.pinHits+'/5':b.state==='dizzy'?'✦ DIZZY ✦':'';}}
 drawMap();hidden('resumeLook',mode!=='fp'||touch||!!document.pointerLockElement||paused||ended||TEST);}
function drawMap(){let c=$('minimap'),ctx=c.getContext('2d'),w=c.width;ctx.clearRect(0,0,w,w);let sx=x=>w/2+x*2.08,sz=z=>w/2+z*2.08;ctx.fillStyle='#344155';ctx.fillRect(sx(-35),sz(-31),70*2.08,62*2.08);ctx.strokeStyle='#a5b5c36b';ctx.lineWidth=1;ctx.strokeRect(sx(-35),sz(-31),70*2.08,62*2.08);ctx.fillStyle='#171e2ed9';for(let [x,z,ww,dd]of[[-28.5,7.5,9,9],[19,11.5,10,9],[-28,-15,8,10],[-13,-29,26,14]])ctx.fillRect(sx(x),sz(z),ww*2.08,dd*2.08);ctx.fillStyle='#b491df55';ctx.fillRect(sx(-18),sz(-14),4*2.08,18*2.08);ctx.fillStyle='#8b73995c';ctx.fillRect(sx(18),sz(-10),8*2.08,15*2.08);if(player.p[1]<-1.4){ctx.fillStyle='#525773';ctx.fillRect(sx(8),sz(-28),25*2.08,18*2.08);}for(let b of bots){ctx.fillStyle=b.state==='captured'?'#9878b8':b.p[1]<-2?'#d4a2fa':b.p[1]>3?'#f6d283':'#f79d91';let x=sx(b.p[0]),y=sz(b.p[2]);ctx.beginPath();ctx.arc(x,y,b.state==='captured'?1.8:2.6,0,TAU);ctx.fill();if(b.p[1]>3||b.p[1]<-2){ctx.fillStyle='#eef1f4';ctx.font='8px system-ui';ctx.fillText(b.p[1]>3?'↑':'↓',x+3,y+3);}}if(boss){ctx.fillStyle=boss.state==='captured'?'#c792ff':'#b0f562';ctx.beginPath();ctx.arc(sx(boss.p[0]),sz(boss.p[2]),5,0,TAU);ctx.fill();}let x=sx(player.p[0]),y=sz(player.p[2]);ctx.save();ctx.translate(x,y);ctx.rotate(-player.yaw);ctx.fillStyle='#e8d3ff';ctx.beginPath();ctx.moveTo(0,5);ctx.lineTo(-4,-4);ctx.lineTo(0,-2);ctx.lineTo(4,-4);ctx.closePath();ctx.fill();ctx.restore();}
function render(){setCamera();buildDynamic();let cut=started&&mode==='top'?player.p[1]+1.48:100,dungeon=started&&mode==='top'&&player.p[1]<-1.35;renderer.render(camera,time,cut,dungeon,started&&mode==='fp');updateHUD();}
function loop(now){let delta=Math.min(.033,(now-last)/1000||.016);last=now;let then=performance.now();try{update(delta);render();}catch(e){console.error(e);if(!started)errorScreen(e);return;}drawMs=performance.now()-then;fps=lerp(fps,1/Math.max(.001,delta),.05);frameCount++;requestAnimationFrame(loop);}
function setupInputs(){ $('start').onclick=startGame;$('cameraBtn').onclick=toggleCamera;$('pauseBtn').onclick=()=>pauseGame(true);$('resume').onclick=()=>pauseGame(false);$('restartPause').onclick=startGame;$('restart').onclick=startGame;$('jumpBtn').onpointerdown=e=>{e.preventDefault();jump();};$('reloadBtn').onpointerdown=e=>{e.preventDefault();refill();};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'♪':'♪̸';if(soundOn)initAudio();};$('quality').onchange=e=>{settingsQuality=e.target.value;renderer.resize(settingsQuality);};$('resumeLook').onclick=lockPointer;
 $('helpBtn').onclick=()=>hidden('help',false);$('closeHelp').onclick=()=>hidden('help',true);$('pauseHelp').onclick=()=>hidden('help',false);window.addEventListener('resize',()=>{renderer.resize(settingsQuality);mouse.x=innerWidth/2;mouse.y=innerHeight*.43;});
 window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(!started)return;pauseGame(!paused);return;}if(e.repeat){keys.add(e.code);return;}keys.add(e.code);if(e.code==='KeyC')toggleCamera();if(e.code==='Space')jump();if(e.code==='KeyR')refill();if(e.code==='Enter'&&!started)startGame();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();mouse.down=fireTouch=false;if(started&&!TEST&&!touch)pauseGame(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!TEST)pauseGame(true);});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement)mouse.down=false;});
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;if(e.button===0&&started&&!paused&&!ended){mouse.down=true;if(mode==='fp')lockPointer();}});window.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')mouse.down=false;});window.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;mouse.x=e.clientX;mouse.y=e.clientY;mouse.moved=true;if(mode==='fp'&&started&&!paused&&document.pointerLockElement){player.yaw-=e.movementX*.0025;player.pitch=clamp(player.pitch-e.movementY*.0023,-1.30,1.30);}});canvas.addEventListener('contextmenu',e=>e.preventDefault());
 let lastTap=-1000;for(let [id,type]of[['moveStick','move'],['aimStick','aim']]){let el=$(id),knob=el.querySelector('i'),active=null,origin=null,downAt=0;const move=e=>{if(e.pointerId!==active)return;let rad=el.clientWidth*.34,dx=e.clientX-origin[0],dy=e.clientY-origin[1],l=Math.hypot(dx,dy),f=Math.min(1,rad/(l||1));stick[type]=[dx*f/rad,dy*f/rad];knob.style.transform=`translate(${dx*f}px,${dy*f}px)`;e.preventDefault();};el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(active!==null)return;active=e.pointerId;el.setPointerCapture(active);let rect=el.getBoundingClientRect();origin=[rect.left+rect.width/2,rect.top+rect.height/2];downAt=performance.now();if(type==='move'&&downAt-lastTap<300)jump();move(e);});el.addEventListener('pointermove',move);const end=e=>{if(e.pointerId!==active)return;if(type==='move'&&performance.now()-downAt<230)lastTap=performance.now();active=null;stick[type]=[0,0];knob.style.transform='';};for(let ev of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,end);}
 $('fireBtn').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();fireTouch=true;$('fireBtn').setPointerCapture(e.pointerId);});for(let ev of['pointerup','pointercancel','lostpointercapture'])$('fireBtn').addEventListener(ev,()=>fireTouch=false);
 let lookId=null,lookXY=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||mode!=='fp'||e.clientX<innerWidth*.4)return;lookId=e.pointerId;lookXY=[e.clientX,e.clientY];canvas.setPointerCapture(lookId);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||paused)return;player.yaw-=(e.clientX-lookXY[0])*.005;player.pitch=clamp(player.pitch-(e.clientY-lookXY[1])*.004,-1.25,1.25);lookXY=[e.clientX,e.clientY];});for(let ev of['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{if(e.pointerId===lookId)lookId=null;});
}
function exposeTests(){if(!TEST)return;window.BUBBLE_TEST={get state(){return{started,paused,ended,mode,time,elapsed,ammo,captures,player:JSON.parse(JSON.stringify(player)),bots:JSON.parse(JSON.stringify(bots)),boss:boss?JSON.parse(JSON.stringify(boss)):null,splats:wallSplats.length,projectiles:projectiles.length,puddles:puddles.length,frameCount,drawMs,stats:renderer.stats,navNodes:world.nav.length,stoneNodes:world.nodes.length};},start:startGame,pause:v=>{paused=v;},setAI:v=>{aiDisabled=!v;},invincible:v=>invincible=v,position:p=>{player.p=p.slice();player.vy=0;setCamera();},setBot:(i,p,props={})=>{bots[i].p=p.slice();Object.assign(bots[i],props);},setCamera:m=>{mode=m;updateCameraMode();setCamera();},look:(yaw,pitch=0)=>{player.yaw=yaw;player.pitch=pitch;setCamera();},advance:seconds=>{for(let i=0;i<seconds*60;i++)update(1/60);render();},hit:(i,source)=>{let b=bots[i];onBotHit(b,source,add(b.p,[0,1.3,.3]),[0,0,1]);},captureAll:()=>{for(let b of bots)if(b.state!=='captured'){b.state='captured';b.hp=0;b.coverage.fill(1);captured(b);}stageDelay=.01;},bossHit:()=>{onBossHit(player.p,add(boss.p,[0,2,1]),[0,0,1]);},shoot:(o,d,owner='player')=>{if(owner==='player')shots++;launch(o,d,owner==='player'?PURPLE:GREEN,owner,player.p,35);},jump,refill,project:p=>project(p),render,path:(a,b)=>world.path(a,b),ray:(a,b,l=70)=>world.ray(a,b,l),support:(x,z,y)=>world.support(x,z,y),clearShots:()=>{projectiles=[];},end:finish};}
async function boot(){try{renderer=new Renderer(canvas);renderer.resize('auto');world=new World();renderer.setStatic(world.nodes);$('sectors').innerHTML='<i></i>'.repeat(8);reset();setupInputs();setCamera();buildDynamic();renderer.render(camera,0,100,false,false);hidden('loading',true);hidden('menu',false);exposeTests();last=performance.now();requestAnimationFrame(loop);}catch(e){errorScreen(e);}}
boot();
