/* Bubble / Material Siege 0.4.4. Original castle + character save, new toolkit.
 * All clocks are simulation clocks. No network, external runtime assets or ads. */
import {TAU,clamp,lerp,add,sub,mul,dot,cross,len,norm,dist,angleDelta,hex,node,segment,trs,mm,point,perspective,lookAt,raySphere} from './engine.js';
import {World} from './world.js?v=0.3.0';
import {makeActor,spider,firstPersonGun,GREEN} from './actors.js';
import {Progression} from './progression.js?v=0.3.0';
import {Renderer} from './engine.js';
import {GumVolume,GUM,attachPhysics,moveBody,TetherPhysics,deflect,propBox} from './material4.js?v=0.4.4';
import {makeKnights,REGIONS,pose,hitActor,actorRay,regionPoint,hitRegion,coating,coatedCapture,hear,updateKnight,renderKnight} from './knights4.js?v=0.4.4';
import {$,show,Armory} from './ui4.js?v=0.4.0';
import {Controls} from './controls4.js?v=0.4.4';
import {updateMobileAim,tapMobileAim} from './aim4.js?v=0.4.4';
import {TwinStickFire} from './twinfire4.js?v=0.4.4';
export const VERSION='0.4.4';
const MODES=['splat','flow','strand','erase'],MODE_LABEL=['SPLAT','ΡΟΗ','ΝΗΜΑ','ΣΒΗΣΕ'],MODE_ICON=['●','≈','⌁','×'];
const ZONES=['head','chest','arms','legs'],ZONE_LABEL={head:'ΚΕΦΑΛΙ',chest:'ΚΟΡΜΟΣ',arms:'ΧΕΡΙΑ',legs:'ΠΟΔΙΑ'};
const FORMS=['mass','wall','pad'],FORM_LABEL={mass:'ΜΑΖΑ',wall:'ΤΟΙΧΟΣ',pad:'ΜΑΞΙΛΑΡΙ'};
const CAP=180;
export class Siege{
 constructor(canvas){this.canvas=canvas;this.touch=matchMedia('(pointer:coarse)').matches;this.test=globalThis.__BUBBLE_TEST===true||new URLSearchParams(location.search).has('test');this.renderer=new Renderer(canvas);this.world=new World;this.volume=new GumVolume(this.touch?18000:26000);this.props=[];this.tethers=new TetherPhysics(this.world);this.time=0;this.frame=0;this.started=false;this.paused=false;this.ended=false;this.cameraMode='top';this.camera={eye:[50,38,65],target:[0,3,0],fov:.9,vp:null};this.groundY=0;this.tool='splat';this.zoneName='chest';this.form='mass';this.gaitMode=0;this.grade=.28;this.soundOn=true;this.audio=null;this.rng=Math.random;this.notifyTime=0;this.previous=0;this.input=null;this.projectiles=[];this.fx=[];this.loots=[];this.pads=[];this.puddles=[];this.seals=[];this.boss=null;this.aiDisabled=false;this.god=false;this.twinFire=new TwinStickFire();
  let storage=null;try{if(!this.test)storage=localStorage;}catch{}this.progress=new Progression(storage);
  this.addArchitecture();attachPhysics(this.world,this.volume,this.props);this.renderer.setStatic(this.world.nodes);this.renderer.resize(this.touch?'low':'auto');this.reset(false);
  const api={inputMode:touch=>this.setInputMode(touch),beginFire:()=>this.beginFire(),endFire:()=>this.endFire(),cancelFire:()=>this.cancelFire(),arc:v=>{if(this.fireDown)this.lob=v;},jump:()=>this.jump(),mode:()=>this.changeTool(),zone:()=>this.changeZone(),setZone:z=>{this.zoneName=z;this.refreshTools();},use:()=>this.use(),reload:()=>this.reload(),path:()=>this.togglePath(),grip:()=>{if(this.playing()){this.player.gripping=!this.player.gripping;this.refreshTools();this.notify(this.player.gripping?'GRIP · Γάντια ενεργά. Κινήσου προς τοίχο με τσίχλα.':'Αντικολλητική επένδυση · ελεύθερη κίνηση.');}},grade:()=>{this.grade=this.grade===0?.28:this.grade>0?-.28:0;this.refreshTools();},gait:()=>{this.gaitMode=(this.gaitMode+1)%3;this.refreshTools();},camera:()=>this.toggleCamera(),bag:()=>this.openBag(),pause:force=>this.pause(force),tap:(x,y)=>tapMobileAim(this,x,y),playing:()=>this.playing(),isFPS:()=>this.cameraMode==='fp',look:(x,y)=>{if(this.playing()){this.player.yaw+=x;this.player.pitch=clamp(this.player.pitch+y,-1.35,1.35);}},resize:()=>this.resize(),erase:()=>{this.tool=this.tool==='erase'?'splat':'erase';this.cancelFire();this.refreshTools();},wall:()=>{this.tool='flow';this.form='wall';this.cancelFire();this.refreshTools();}};
  this.input=new Controls(canvas,api,this.touch);this.armory=new Armory(this.progress,{closeBag:()=>this.closeBag(),stats:()=>this.refreshStats(),notify:t=>this.notify(t)});this.wireScreens();this.refreshTools();this.setCamera();$('bootStatus').textContent='Έτοιμο · 0.4.4';$('start').disabled=false;
  if(this.test){this.manualClock=true;this.installTest();}this.loop=now=>{const dt=Math.min(.05,(now-this.previous)/1000||1/60);this.previous=now;if(!this.manualClock){this.step(dt);this.render();}requestAnimationFrame(this.loop);};requestAnimationFrame(this.loop);
 }
 addArchitecture(){// Match the visible house roofs with actual underside collision.
  for(const [x,z,w,d,h]of[[-24,12,9,9,4.5],[24,16,10,9,5.1],[-24,-10,8,10,4.8]])this.world.solid(x,z,w,.0+d,.22,h-.14,true);
  // A small work gantry near the safe start gives a visible swing anchor.
  for(const x of[-7,7]){this.world.wall(x,20,.65,.65,6,0,'surface');}this.world.wall(0,20,14.6,.65,.55,6,'surface');
  for(const x of[-7,7])this.world.push('sphere',[x,6.38,20],[.22,.2,.22],0xbca1f5,[0,0,0],[.22,.25,0,0]);
 }
 reset(run=true){this.input?.clear();this.twinFire.reset();this.volume.disposeMeshes(this.renderer);this.volume.reset();this.volume.protectedBody=()=>this.player;this.touchAim=null;this.props.length=0;this.projectiles=[];this.fx=[];this.loots=[];this.pads=[];this.puddles=[];this.tethers.reset();this.knights=makeKnights(this.world,this.progress.p.tier);this.player=makeActor(-1,[0,0,27],GUM,'BUBBLE WARRIOR');Object.assign(this.player,{height:2.12,vel:[0,0,0],pitch:-.06,coat:Object.fromEntries(REGIONS.map(k=>[k,0])),gripping:false,pathOn:false,lastSafe:[0,0,27],lastHit:-100});this.refreshStats();this.player.hp=this.player.maxHp;this.ammo=CAP;this.reloadTime=0;this.charge=0;this.fireDown=false;this.lob=false;this.flowClock=0;this.pathState=null;this.elapsed=0;this.captures=0;this.collected=0;this.testAim=null;this.beam=null;this.boss=null;this.bossDelay=-1;this.bossEnd=-1;this.shake=0;this.hitTint=0;this.groundY=0;this.aim={point:[0,0,20],dir:[0,0,-1],actor:null,surface:null};this.started=run;this.paused=false;this.ended=false;this.cameraMode='top';this.makeProps();this.seals=[{p:[-24,.7,11.5],name:'ΔΥΤΙΚΗ ΟΙΚΙΑ',taken:false},{p:[7,5.7,-23.5],name:'ΑΝΩ ΦΡΟΥΡΑΡΧΕΙΟ',taken:false},{p:[29,-4.3,-25.5],name:'ΥΠΟΓΕΙΕΣ ΣΤΟΕΣ',taken:false}];
  $('worldLabels').replaceChildren();this.labels=this.knights.map(()=>{let el=document.createElement('div');el.className='world-label';el.innerHTML='<span class="mark"></span><div class="health"><i></i></div><small></small>';$('worldLabels').append(el);return el;});for(const id of['pause','inventory','end','bossHud','targetPanel'])show(id,false);show('menu',!run);show('hud',run);if(run)this.notify(this.touch?'Αριστερά: μόνο κίνηση. Δεξιά ΜΕΣΑ: στόχευση · ΕΞΩ στον δακτύλιο: βολή. Πίσω ΜΕΣΑ: σταματάς.':'WASD: κίνηση · Ποντίκι: στόχευση · Κλικ: βολή · Κράτημα: φόρτιση · C: κάμερα',5);this.refreshTools();
 }
 makeProps(){for(const [i,p]of[[-4,0,24],[4,0,23],[-26,0,20],[-21,0,19],[22,-5,-17]].entries())this.props.push({id:100+i,type:'crate',p:p.slice(),home:p.slice(),vel:[0,0,0],vy:0,grounded:true,radius:.65,height:1.2,movable:true,coat:0,color:0x98704f});
  this.gate={id:201,type:'gate',p:[-24,0,16.5],home:[-24,0,16.5],height:2.8,radius:.2,halfX:1.5,halfZ:.18,movable:false,open:0};this.props.push(this.gate);this.plate={p:[-24,.025,19.2],active:false};
  this.vaultGate={id:202,type:'gate',p:[26.4,-5,-21],home:[26.4,-5,-21],height:2.8,radius:.2,halfX:1.55,halfZ:.18,movable:false,open:0};this.lever={id:203,type:'lever',p:[28.8,-4.65,-19.9],height:.7,radius:.25,movable:false,open:false};this.props.push(this.vaultGate,this.lever);
 }
 wireScreens(){$('start').onclick=()=>{this.initSound();this.reset(true);};$('resume').onclick=()=>this.pause(false);$('restart').onclick=()=>this.reset(true);$('again').onclick=()=>this.reset(true);$('next').onclick=()=>{this.progress.p.tier=Math.min(this.progress.p.unlockedTier,this.progress.p.tier+1);this.progress.save();this.reset(true);};$('endBag').onclick=()=>this.openBag();$('pauseHelp').onclick=$('menuHelp').onclick=()=>{this.helpPrevious=this.paused;if(this.started&&!this.ended)this.paused=true;this.input.clear();show('help',true);};$('closeHelp').onclick=()=>{show('help',false);this.paused=!!this.helpPrevious;};$('quality').onchange=()=>this.resize();$('sound').onchange=e=>this.soundOn=e.target.checked;}
 setInputMode(touch){
  this.touch=touch;this.touchAim=null;this.twinFire.reset();
  this.refreshTools();
 }
 resize(){const q=$('quality').value;this.renderer.resize(q==='auto'&&this.touch?'low':q);}
 refreshStats(){if(!this.player)return;this.player.maxHp=this.progress.stats().maxHp;this.player.hp=Math.min(this.player.hp,this.player.maxHp);}
 playing(){return this.started&&!this.paused&&!this.ended;}
 pause(force){if(!this.started||this.ended)return;if(!$('help').classList.contains('hidden')){$('closeHelp').click();return;}if(!$('inventory').classList.contains('hidden')){this.closeBag();return;}this.paused=typeof force==='boolean'?force:!this.paused;this.input.clear();show('pause',this.paused);if(this.paused&&document.pointerLockElement)document.exitPointerLock();if(!this.paused&&this.cameraMode==='fp')this.input.lock();}
 openBag(){if(!this.started)return;this.bagPrevious=this.paused;this.paused=true;this.input.clear();this.armory.render();show('inventory',true);if(document.pointerLockElement)document.exitPointerLock();}
 closeBag(){show('inventory',false);this.paused=!!this.bagPrevious;this.input.clear();if(this.cameraMode==='fp'&&this.playing())this.input.lock();}
 initSound(){if(this.audio){this.audio.resume()?.catch(()=>{});return;}try{this.audio=new(window.AudioContext||window.webkitAudioContext)();}catch{}}
 tone(type='splat'){if(!this.soundOn||!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain(),now=this.audio.currentTime;o.type=type==='charge'?'triangle':'sine';let f=type==='capture'?600:type==='hit'?130:type==='jump'?220:type==='charge'?280:330;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(type==='capture'?1100:70,now+.16);g.gain.setValueAtTime(.055,now);g.gain.exponentialRampToValueAtTime(.001,now+.23);o.connect(g);g.connect(this.audio.destination);o.start(now);o.stop(now+.24);o.onended=()=>{o.disconnect();g.disconnect();};}
 notify(text,seconds=3){$('toast').textContent=text;$('toast').classList.add('show');this.notifyTime=seconds;}
 toggleCamera(){if(!this.playing())return;this.cameraMode=this.cameraMode==='top'?'fp':'top';this.cancelFire();this.input?.disarmRing();if(this.cameraMode==='fp')this.input.lock();else if(document.pointerLockElement)document.exitPointerLock();this.refreshTools();}
 changeTool(){if(!this.playing())return;this.tool=MODES[(MODES.indexOf(this.tool)+1)%MODES.length];this.cancelFire();this.refreshTools();const hint=this.touch?(this.tool==='flow'?'FLOW ∞ · εξωτερικός δακτύλιος ή FIRE για ροή. Μέσα: μόνο στόχευση.':this.tool==='strand'?'ΝΗΜΑ · E / ΣΥΝΔΕΣΗ: αντικείμενο, ντυμένος φρουρός ή ψηλή επιφάνεια.':this.tool==='erase'?'ΣΒΗΣΕ · εξωτερικός δακτύλιος ή FIRE. Μέσα: μόνο στόχευση.':'Μέσα: στόχευση. Έξω στον δακτύλιο: βολές. Επιστροφή μέσα: σταματάς.'):(this.tool==='flow'?'ΡΟΗ ∞ · κράτα αριστερό κλικ. Επίλεξε μορφή στη γραμμή εργαλείων.':this.tool==='strand'?'ΝΗΜΑ · E ή δεξί κλικ: σύνδεση / απελευθέρωση.':this.tool==='erase'?'ΣΒΗΣΕ · κράτα αριστερό κλικ για τοπική αφαίρεση τσίχλας.':'SPLAT · αριστερό κλικ: βολή · κράτημα και άφημα: φόρτιση · Alt: τόξο.');this.notify(hint,3); }
 changeZone(){if(this.tool==='flow')this.form=FORMS[(FORMS.indexOf(this.form)+1)%FORMS.length];else this.zoneName=ZONES[(ZONES.indexOf(this.zoneName)+1)%ZONES.length];this.refreshTools();}
 refreshTools(){if(!this.player)return;const trigger=$('desktopTriggerText');if(trigger)trigger.textContent=this.tool==='splat'?'Κλικ: βολή · Κράτημα: φόρτιση':this.tool==='strand'?'E / δεξί κλικ: σύνδεση':'Κράτημα κλικ: '+(this.tool==='flow'?'συνεχής ροή':'σβήσιμο');const i=MODES.indexOf(this.tool);$('modeLabel').textContent=MODE_LABEL[i];$('modeIcon').textContent=MODE_ICON[i];$('aimStick').querySelector('small').textContent='ΣΤΟΧΕΥΣΗ';$('ringCaption').textContent={splat:'ΒΟΛΗ',flow:'ΡΟΗ ∞',erase:'ΣΒΗΣΕ',strand:'ΣΥΝΔΕΣΗ · E'}[this.tool];$('aimStick').classList.toggle('ring-disabled',this.tool==='strand');$('zoneLabel').textContent=this.tool==='flow'?FORM_LABEL[this.form]:ZONE_LABEL[this.zoneName];$('zoneIcon').textContent=this.tool==='flow'?({mass:'●',wall:'▥',pad:'∩'}[this.form]):({head:'○',chest:'◇',arms:'↔',legs:'⋀'}[this.zoneName]);$('fireLabel').textContent=this.tool==='splat'?'ΦΟΡΤΙΣΗ':this.tool==='flow'?'ΡΟΗ ∞':this.tool==='erase'?'ΣΒΗΣΕ':'ΝΗΜΑ';$('cameraBtn').textContent=this.cameraMode==='fp'?'FPS':'TOP';$('pathBtn').classList.toggle('active',this.player.pathOn);$('gripBtn').classList.toggle('active',this.player.gripping);$('gaitBtn').classList.toggle('active',this.gaitMode!==0);$('gaitLabel').textContent=['WALK','RUN','SNEAK'][this.gaitMode];show('gradeBtn',this.player.pathOn);$('gradeLabel').textContent=this.grade>0?'↗':this.grade<0?'↘':'→';}
 reload(){if(!this.playing()||this.reloadTime>0||this.ammo===CAP)return;this.cancelFire();this.reloadTime=1.7;this.tone('charge');}
 beginFire(){if(!this.playing()||this.fireDown)return;this.initSound();if(this.tool==='strand'){this.use();return;}if(this.tool==='splat'&&(this.reloadTime>0||this.ammo<=0)){if(this.ammo<=0)this.reload();return;}this.setCamera();this.updateAim();this.fireDown=true;this.charge=0;this.lob=false;this.flowClock=0;this.wallBrush=null;}
 cancelFire(){this.fireDown=false;this.charge=0;this.lob=false;this.wallBrush=null;$('fireBtn').classList.remove('charging');show('chargeInfo',false);}
 chargeAmmo(){if(this.charge>=2.8)return this.ammo;return Math.min(this.ammo,this.charge<.22?1:Math.max(4,Math.floor((this.charge-.22)/2.6*CAP)));}
 endFire(){if(!this.fireDown)return;if(this.playing()&&this.tool==='splat'&&this.reloadTime<=0&&this.ammo>0)this.shoot(this.chargeAmmo(),this.lob||this.input.keys.has('AltLeft')||this.input.keys.has('AltRight'));this.twinFire.manualShot();this.cancelFire();}
 shoot(used=1,lob=false){used=Math.min(Math.max(1,used),this.ammo);if(!used)return;const origin=add(this.player.p,[0,1.50,0]),target=this.aim.point.slice(),amount=used/CAP;let v;if(lob&&used>3){const d=sub(target,origin),duration=clamp(Math.hypot(d[0],d[2])/13+.9,.9,2.4);v=[d[0]/duration,(d[1]+.5*10*duration*duration)/duration,d[2]/duration];}else v=mul(norm(sub(target,origin)),used>3?22:35);this.projectiles.push({p:origin,v,owner:'player',source:this.player.p.slice(),r:used>3?.22+amount*.48:.105,used,lob,gravity:lob&&used>3?10:0,life:4.5,color:GUM,bounces:0});this.ammo-=used;this.shake=used>3?.14:.03;this.noise(this.player.p,used>3?12:6);this.tone(used>3?'charge':'splat');}
 noise(p,r){for(const a of this.knights)hear(a,p,r,this.world);}
 setCamera(){const p=this.player;let eye,target;if(!this.started){eye=[43,35,59];target=[0,3,-2];this.camera.fov=.90;}else if(this.cameraMode==='top'){const d=innerWidth<innerHeight?22:18;if(p.grounded)this.groundY=p.p[1];if(Math.abs(p.p[1]-this.groundY)>7)this.groundY=lerp(this.groundY,p.p[1],.04);eye=add([p.p[0],this.groundY,p.p[2]],[0,d,d*.63]);target=add([p.p[0],this.groundY,p.p[2]],[0,.5,-1.9]);this.camera.fov=.94;}else{eye=add(p.p,[0,1.88+Math.sin(p.walk)*.02*p.moving,0]);target=add(eye,[Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),Math.cos(p.yaw)*Math.cos(p.pitch)]);this.camera.fov=1.08;}this.camera.eye=eye;this.camera.target=target;this.camera.vp=mm(perspective(this.camera.fov,innerWidth/innerHeight,.055,210),lookAt(eye,target));}
 screenRay(x,y){const f=norm(sub(this.camera.target,this.camera.eye)),right=norm(cross(f,[0,1,0])),up=cross(right,f),k=Math.tan(this.camera.fov/2);return{o:this.camera.eye.slice(),d:norm(add(f,add(mul(right,(x/innerWidth*2-1)*k*innerWidth/innerHeight),mul(up,(1-y/innerHeight*2)*k))))};}
 updateAim(){if(this.touch&&this.cameraMode==='top'&&!this.testAim&&this.input){updateMobileAim(this);return;}const p=this.player,origin=this.cameraMode==='fp'?this.camera.eye.slice():add(p.p,[0,1.50,0]);let d=[Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),Math.cos(p.yaw)*Math.cos(p.pitch)],target=null,surface=null,pointAt;
  if(this.testAim){pointAt=this.testAim.slice();d=norm(sub(pointAt,origin));target=actorRay(this.knights,origin,d,dist(origin,pointAt)+.4,this.time);surface=this.world.ray(origin,d,Math.max(0,dist(origin,pointAt)-.1));this.aim={dir:d,point:pointAt,actor:target?.actor,region:target?.region,surface};return;}
  if(this.cameraMode==='top'){
   if(!this.touch&&this.input.mouseActive){const r=this.screenRay(...this.input.mouse);if(r.d[1]<0){let enter=(this.groundY+2.35-r.o[1])/r.d[1];if(enter>0)r.o=add(r.o,mul(r.d,enter));}target=actorRay(this.knights.filter(a=>!a.captured),r.o,r.d,90,this.time);surface=this.world.ray(r.o,r.d,90);const tt=(p.p[1]-r.o[1])/r.d[1];pointAt=target&&(!surface||target.t<surface.t)?target.p:surface?.p||add(r.o,mul(r.d,Math.max(1,tt)));d=norm(sub(pointAt,origin));if(target&&(!surface||target.t<surface.t)){const z=regionPoint(target.actor,this.zoneName,origin,this.world,this.time);if(z){pointAt=z.p;target.region=z.region;d=norm(sub(pointAt,origin));}else target=null;}else target=null;
   }else{if(len(this.input.aim)>.18)p.yaw=Math.atan2(this.input.aim[0],this.input.aim[1]);d=[Math.sin(p.yaw),-.11,Math.cos(p.yaw)];let candidates=[];if(this.tool==='splat'||(this.tool==='flow'&&this.form==='mass')||this.tool==='strand')for(const a of this.knights){if(a.captured&&this.tool!=='strand')continue;const delta=sub(a.p,p.p),distance=len(delta);if(distance>17||Math.abs(delta[1])>4.5||dot(norm([delta[0],0,delta[2]]),norm([d[0],0,d[2]]))<.87)continue;const z=regionPoint(a,this.zoneName,origin,this.world,this.time);if(z)candidates.push({actor:a,region:z.region,p:z.p,distance});}candidates.sort((a,b)=>a.distance-b.distance);target=candidates[0]||null;if(target){pointAt=target.p;d=norm(sub(pointAt,origin));}else{surface=this.world.ray(origin,norm(d),22);pointAt=surface?.p||add(p.p,[d[0]*6,.04,d[2]*6]);d=norm(sub(pointAt,origin));}}
   p.yaw=Math.atan2(d[0],d[2]);
  }else{surface=this.world.ray(origin,d,60);target=actorRay(this.knights,origin,d,surface?surface.t:60,this.time);pointAt=target?.p||surface?.p||add(origin,mul(d,45));}
  const muzzle=add(p.p,[0,1.50,0]);d=norm(sub(pointAt,muzzle));let physical=this.world.ray(muzzle,d,Math.max(0,dist(muzzle,pointAt)-.15));if(physical){pointAt=physical.p;target=null;surface=physical;}
  this.aim={point:pointAt||add(origin,mul(d,20)),dir:d,actor:target?.actor||null,region:target?.region,surface:surface||this.world.ray(origin,d,28)};
 }
 togglePath(){if(!this.playing())return;this.player.pathOn=!this.player.pathOn;if(this.player.pathOn){if(!this.player.grounded){this.player.pathOn=false;this.notify('Ξεκίνα τη διαδρομή από σταθερή επιφάνεια.');return;}this.pathState={p:[this.player.p[0],this.player.p[1]-.28,this.player.p[2]],last:this.player.p.slice(),distance:1,unsupported:0};this.notify('ΑΡΙΣΤΕΡΟ ΓΑΝΤΙ · περπάτα και στρίψε. ΚΛΙΣΗ: άνοδος / κάθοδος / ευθεία.',4);}this.refreshTools();}
 updatePath(move,dt){const p=this.player,s=this.pathState;if(!p.pathOn||!s||len(move)<.12)return;const traveled=Math.hypot(p.p[0]-s.last[0],p.p[2]-s.last[2]);if(traveled>3){p.pathOn=false;this.refreshTools();return;}s.distance+=traveled;s.p[1]+=traveled*this.grade;s.last=p.p.slice();s.p[0]=p.p[0];s.p[2]=p.p[2];if(s.distance<.18)return;s.distance=0;
  const floor=this.world.raw.support(p.p[0],p.p[2],p.p[1],.25);if(floor&&Math.abs(floor.h-p.p[1])<.4)s.unsupported=0;else s.unsupported+=traveled;
  if(s.unsupported>18){p.pathOn=false;this.refreshTools();this.notify('Το άνοιγμα είναι πολύ μεγάλο χωρίς νέα στήριξη. Συνέχισε με SWING.',4);return;}
  const d=norm([move[0],0,move[2]]);for(let n=0;n<=1.8;n+=.24){let center=[p.p[0]+d[0]*n,s.p[1]+this.grade*n,p.p[2]+d[2]*n];const footY=center[1]+.33;if(this.world.raw.blocked(center[0],center[2],footY,.62,1.98))break;const ceiling=this.world.raw.ray([center[0],footY+.02,center[2]],[0,1,0],2.15);if(ceiling)break;this.volume.stamp(center,[1.06,.39,1.06],3.2);}
  this.beam={from:add(p.p,[-.55,.98,.4]),to:[p.p[0]+d[0]*1.45,s.p[1]+this.grade*1.45,p.p[2]+d[2]*1.45],until:this.time+.13,left:true};
 }
 jump(){if(!this.playing())return;const p=this.player;if(this.tethers.swing){this.tethers.releasePlayer();p.vy=Math.max(p.vy,3);this.notify('ΑΠΕΛΕΥΘΕΡΩΣΗ · κρατάς τη φόρα σου.',1.4);return;}if(p.gripping){p.gripping=false;this.refreshTools();}if(p.stamina<8)return;
  if(p.grounded){p.vy=this.onPad(p.p)?11:7.5;p.grounded=false;p.wallUsed=null;p.stamina-=8;this.tone('jump');return;}
  for(const d of[[1,0,0],[-1,0,0],[0,0,1],[0,0,-1]]){const h=this.world.ray(add(p.p,[0,1,0]),d,.80);if(h&&Math.abs(h.n[1])<.3){const signature=h.box||d.toString();if(p.wallUsed===signature)return;p.wallUsed=signature;p.vel[0]+=h.n[0]*7;p.vel[2]+=h.n[2]*7;p.vy=7.3;p.stamina-=8;this.tone('jump');this.notify('WALL JUMP',1);return;}}
 }
 onPad(p){return this.pads.some(b=>Math.hypot(b.p[0]-p[0],b.p[2]-p[2])<b.r&&Math.abs(p[1]-b.p[1])<2);}
 movePlayer(dt){const p=this.player,k=this.input.keys;let x=this.input.move[0]+(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0),z=this.input.move[1]+(k.has('KeyS')||k.has('ArrowDown')?1:0)-(k.has('KeyW')||k.has('ArrowUp')?1:0),mag=Math.min(1,Math.hypot(x,z)),v=norm([x,0,z]);if(this.cameraMode==='fp'){const f=[Math.sin(p.yaw),0,Math.cos(p.yaw)],r=[-Math.cos(p.yaw),0,Math.sin(p.yaw)];v=add(mul(r,v[0]),mul(f,-v[2]));if(this.touch&&len(this.input.aim)>.13){p.yaw-=this.input.aim[0]*dt*2.3;p.pitch=clamp(p.pitch-this.input.aim[1]*dt*1.5,-1.3,1.3);}}
  const sprint=(this.gaitMode===1||k.has('ShiftLeft')||k.has('ShiftRight'))&&p.stamina>5,sneak=this.gaitMode===2||k.has('ControlLeft')||k.has('ControlRight');let speed=sneak?2.0:sprint?7.2:4.7;if(p.pathOn)speed=Math.min(speed,3.4);if(p.dizzy>0)speed*=.55;
  this.updatePath(mul(v,mag),dt);this.tethers.step(dt,p,mul(v,mag));let gravity=19;
  if(p.gripping&&p.stamina>0){const handDir=mag>.1?norm([v[0],0,v[2]]):p.gripNormal?norm([-p.gripNormal[0],0,-p.gripNormal[2]]):[Math.sin(p.yaw),0,Math.cos(p.yaw)];const h=this.volume.ray(add(p.p,[0,1.4,0]),handDir,.95);if(h&&Math.abs(h.n[1])<.65){p.vy=mag>.1?2.7:0;gravity=0;p.grounded=false;p.stamina=Math.max(0,p.stamina-dt*(mag>.1?7:2));speed=.25;this.gripContact=true;p.gripNormal=norm(h.n);}else this.gripContact=false;}else this.gripContact=false;
  const result=moveBody(this.world,p,v[0]*speed*mag*dt+p.vel[0]*dt,v[2]*speed*mag*dt+p.vel[2]*dt,dt,{gravity,bounce:this.onPad(p.p)});if(result.blockedX)p.vel[0]*=.1;if(result.blockedZ)p.vel[2]*=.1;const drag=(this.tethers.swing?.body===p) ? .55 : p.grounded ? 5 : 1.1;p.vel[0]*=Math.exp(-dt*drag);p.vel[2]*=Math.exp(-dt*drag);p.moving=mag;p.walk+=dt*speed*mag*1.7;if(this.cameraMode==='top'&&this.touch&&len(this.input.aim)<.1&&mag>.2&&!this.touchAim?.hasIntent)p.yaw=Math.atan2(v[0],v[2]);if(sprint&&mag>0)p.stamina=Math.max(0,p.stamina-dt*12);else if(!this.gripContact)p.stamina=Math.min(100,p.stamina+dt*(this.time-p.lastHit>2?12:3));p.dizzy=Math.max(0,p.dizzy-dt);
  if(p.landed&&p.impactVy<-13&&!p.onGum)this.hurt(Math.min(18,(-p.impactVy-12)*2));if(p.fell){p.fell=false;this.hurt(12);this.notify('Έπεσες · επέστρεψες στην τελευταία σταθερή επιφάνεια.');}
  if(mag>.3&&!sneak&&this.time>(this.nextFootstep||0)){this.noise(p.p,sprint?7:3.3);this.nextFootstep=this.time+.45;}
 }
 use(){if(!this.playing())return;const p=this.player;if(this.tethers.swing){this.tethers.releasePlayer();this.notify('SWING · άφησες το νήμα.');return;}
  const origin=add(p.p,[0,1.5,0]),reach=28*this.progress.stats().stretch;let surface=this.world.ray(origin,this.aim.dir,reach),target=this.aim.actor;
  if(this.tethers.grab){const a=this.tethers.grab;let anchor=surface;if(this.cameraMode==='top'&&(!anchor||anchor.p[1]<a.p[1]+3))anchor=this.world.ray(add(a.p,[0,2.15,0]),[0,1,0],12*this.progress.stats().stretch);if(anchor&&anchor.p[1]>a.p[1]+3&&!anchor.prop){const chest=add(a.p,[0,1.1,0]),delta=sub(anchor.p,chest),ob=this.world.ray(chest,norm(delta),Math.max(0,len(delta)-.2));if(ob){this.notify('Η διαδρομή προς την οροφή είναι κλειστή.');return;}if(!a.coat||typeof a.coat==='number'){this.tethers.add(a,add(anchor.p,mul(anchor.n,.04)),{hanging:true});}else{if(coating(a)<.53){this.notify('Πρόσθεσε περισσότερη τσίχλα στον φρουρό πριν τον κρεμάσεις.');return;}this.tethers.add(a,add(anchor.p,mul(anchor.n,.04)),{hanging:true});}this.tethers.grab=null;this.notify('ΑΝΑΡΤΗΣΗ · το νήμα τεντώνεται και σηκώνει τον στόχο.');}else{this.tethers.grab=null;this.notify('Άφησες τον στόχο.');}return;}
  if(surface?.prop?.type==='lever'){this.lever.open=!this.lever.open;this.beam={from:origin,to:surface.p,until:this.time+.8};this.notify(this.lever.open?'Ο ΜΟΧΛΟΣ ΑΝΟΙΞΕ ΤΗΝ ΥΠΟΓΕΙΑ ΠΥΛΗ.':'Η υπόγεια πύλη κλείνει.');return;}
  if(surface?.prop?.movable&&(!target||surface.t<dist(origin,target.p))){this.tethers.grab=surface.prop;this.notify('ΤΡΑΒΑΣ ΚΙΒΩΤΙΟ · κινήσου. E ξανά: άφημα ή σύνδεση ψηλά.');return;}
  if(target){if(coating(target)<.45){this.notify('Τύλιξε πρώτα αρκετά τον φρουρό — δεν τραβάμε γυμνή πανοπλία.');return;}if(target.pin){target.pin=null;}this.tethers.grab=target;this.notify('ΤΡΑΒΑΣ ΦΡΟΥΡΟ · στόχευσε ψηλά και ξανά E για ανάρτηση.',4);return;}
  if(this.cameraMode==='top'&&(!surface||surface.p[1]<p.p[1]+2.7)){const d=norm([this.aim.dir[0],.83,this.aim.dir[2]]);surface=this.world.ray(origin,d,24*this.progress.stats().stretch);}
  if(surface&&!surface.prop&&surface.p[1]>p.p[1]+2.5){const d=sub(surface.p,origin);if(len(d)>26*this.progress.stats().stretch){this.notify('Το σημείο είναι εκτός εμβέλειας νήματος.');return;}this.tethers.add(p,add(surface.p,mul(surface.n,.04)),{swing:true});p.vy=Math.max(p.vy,6.6);p.grounded=false;this.notify('SWING · κίνηση για φόρα. JUMP ή E: απελευθέρωση.');this.tone('jump');}else this.notify('Στόχευσε κιβώτιο, τυλιγμένο φρουρό, μοχλό ή ψηλό σταθερό σημείο.');
 }
 construct(dt){const origin=add(this.player.p,[0,1.5,0]);if(this.tool==='erase'){const h=this.world.ray(origin,this.aim.dir,11);if(h?.gum)this.volume.erase(add(h.p,mul(this.aim.dir,.25)),.85);const at=h?.p||this.aim.point;this.tethers.cutNear(at,1.5);this.beam={from:origin,to:at,until:this.time+.08,erase:true};return;}
  let h=this.world.ray(origin,this.aim.dir,11),a=actorRay(this.knights,origin,this.aim.dir,h?.t??11,this.time);if(this.form==='mass'&&a){hitRegion(a.actor,a.region,this.player.p,a.p,.21*this.progress.stats().power,this.world);this.beam={from:origin,to:a.p,until:this.time+.08};this.noise(this.player.p,4);return;}
  if(this.form==='wall'){
   if(!this.wallBrush){let q=this.aim.point.slice(),delta=sub(q,this.player.p),flat=norm([this.aim.dir[0],0,this.aim.dir[2]]);if(this.cameraMode==='top'&&this.touch||len(delta)>8||Math.abs(delta[1])>3)q=add(this.player.p,mul(flat,3.2));let floor=this.world.support(q[0],q[2],this.player.p[1]+.25,.1);if(!floor||Math.abs(floor.h-this.player.p[1])>2){this.notify('Ο τοίχος χρειάζεται βάση στο έδαφος.');return;}this.wallBrush={p:[q[0],floor.h,q[2]],height:.10,yaw:Math.atan2(flat[0],flat[2])};}
   const b=this.wallBrush;b.height=Math.min(3.35,b.height+dt*2.2);const center=add(b.p,[0,b.height-.18,0]);if(!this.world.raw.blocked(center[0],center[2],center[1],.10,.15))this.volume.stamp(center,[1.90,.43,.55],2.4,b.yaw);this.beam={from:origin,to:center,until:this.time+.09};
  }else if(this.form==='pad'){if(h&&Math.abs(h.n[1])>.6&&!h.prop){this.volume.stamp(add(h.p,[0,.04,0]),[1.5,.26,1.5],1.2);if(!this.pads.some(p=>dist(p.p,h.p)<1.5))this.pads.push({p:h.p.slice(),r:1.6});this.beam={from:origin,to:h.p,until:this.time+.08};}}
  else if(h){if(h.prop){if(h.prop.movable)h.prop.coat=clamp((h.prop.coat||0)+.1,0,1.4);}else{const normal=norm(h.n),r=normal.map(v=>Math.abs(v)>.7?.27:.65);this.volume.stamp(add(h.p,mul(normal,.035)),r,2.7);}this.beam={from:origin,to:h.p,until:this.time+.08};}
  if(this.volume.full&&this.time>(this.lastLimit||0)){this.notify('Πλήρης χώρος κατασκευών. ΣΒΗΣΕ περιττή τσίχλα — η στήριξή σου παραμένει.',4);this.lastLimit=this.time+5;}
 }
 traceProjectile(p,step){const length=len(step),d=norm(step);let hit=this.world.ray(p.p,d,length);if(p.r>.2){const side=norm(cross(d,[0,1,0]));for(const off of[mul(side,p.r*.7),mul(side,-p.r*.7),[0,p.r*.7,0],[0,-p.r*.7,0]]){const h=this.world.ray(add(p.p,off),d,hit?hit.t:length);if(h&&(!hit||h.t<hit.t))hit=h;}}
  if(p.owner==='player'||p.owner==='reflected'){const a=actorRay(this.knights,p.p,d,hit?hit.t:length,this.time,p.r*.65);if(a&&(!hit||a.t<hit.t))hit=a;if(this.boss&&this.boss.state!=='captured'){const h=raySphere(p.p,d,add(this.boss.p,[0,2,0]),1.7+p.r,hit?hit.t:length);if(h&&(!hit||h.t<hit.t))hit={...h,boss:true};}}
  else{const h=hitActor(this.player,p.p,d,hit?hit.t:length,this.time,p.r*.5);if(h&&(!hit||h.t<hit.t))hit={...h,actor:null,player:true};}return hit;
 }
 impact(p,h){if(h.actor){const a=h.actor;if(p.used>3){this.burst(p,h);return;}hitRegion(a,h.region,p.source,h.p,1+this.progress.stats().damage/55,this.world);this.tone('hit');return;}if(h.boss){this.hitBoss(p,h);if(p.used>3)this.burst(p,h);return;}if(h.player){this.hurt(p.owner==='boss'?8:4);return;}
  if(h.prop){if(h.prop.movable){h.prop.coat=clamp((h.prop.coat||0)+.22+(p.used||0)/180,0,1.4);const d=norm(p.v);h.prop.vel[0]+=d[0]*1.4;h.prop.vel[2]+=d[2]*1.4;}if(p.used>3)this.burst(p,h);return;}
  if(p.used>3){this.burst(p,h);return;}if(p.owner==='player'||p.owner==='reflected'){const n=norm(h.n);this.volume.stamp(add(h.p,mul(n,.035)),n.map(v=>Math.abs(v)>.7?.26:.60),2.7);}else if(h.gum)this.volume.stamp(add(h.p,mul(norm(p.v),.1)),[.45,.45,.45],-.8);
  if(p.owner==='boss'&&h.n[1]>.65){this.puddles.push({p:h.p.slice(),r:1.15,life:8});if(this.puddles.length>24)this.puddles.shift();}
 }
 burst(p,h){const power=clamp((p.used||1)/CAP,.02,1),radius=1+power*2.1,falling=p.lob&&p.v[1]<0,origin=add(h.p,mul(norm(p.v),-.55));this.fx.push({p:h.p.slice(),life:.45,max:.45,r:radius,color:GUM,normal:h.n});
  for(const a of this.knights){if(a.captured&&a!==this.tethers.grab)continue;if(dist(add(a.p,[0,1.1,0]),h.p)>radius+1.0)continue;const bodyPose=pose(a,this.time);const area={head:bodyPose.head,chest:bodyPose.chest,armL:bodyPose.handL,armR:bodyPose.handR,legL:bodyPose.kneeL,legR:bodyPose.kneeR};let contacted=0;
   for(const [region,at]of Object.entries(area)){const delta=sub(at,origin);if(len(delta)>radius+1.4)continue;if(this.world.ray(origin,norm(delta),Math.max(0,len(delta)-.24)))continue;const strength=power*(region==='chest'?5.1:falling?(region.startsWith('leg')?2.2:4.0):3.5);hitRegion(a,region,p.source,at,strength,this.world);contacted++;}
   if(contacted){const from=norm([p.source[0]-a.p[0],0,p.source[2]-a.p[2]]);const front=Array.from({length:8},(_,i)=>({i,d:dot([Math.sin(a.yaw+i*TAU/8),0,Math.cos(a.yaw+i*TAU/8)],from)})).sort((a,b)=>b.d-a.d).slice(0,4).map(v=>v.i);for(let i=0;i<8;i++){if(falling||front.includes(i))a.coverage[i]=clamp(a.coverage[i]+power*(falling?.7:1.1),0,1);}a.pendingPin=power>.28?1.1:0;a.pushDir=norm([p.v[0],0,p.v[2]]);}
  }
  if(!h.actor&&!h.boss&&!h.prop){const n=norm(h.n);this.volume.stamp(add(h.p,mul(n,.08)),n.map(v=>Math.abs(v)>.7?.35+power*.25:radius*.7),3.4);}this.shake=.18;this.tone('hit');
 }
 updateProjectiles(dt){for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.life-=dt;p.v[1]-=(p.gravity||0)*dt;const move=mul(p.v,dt),h=this.traceProjectile(p,move);if(h){const incidence=Math.abs(dot(norm(p.v),norm(h.n)));if(h.gum&&p.owner!=='player'&&p.bounces<2&&incidence<.52){p.v=deflect(p.v,norm(h.n));p.p=add(h.p,mul(norm(h.n),.18+p.r));p.bounces++;p.owner='reflected';p.color=GUM;p.used=1;p.source=p.p.slice();this.fx.push({p:h.p,life:.2,max:.2,r:.4,color:0xffdfa1});continue;}this.impact(p,h);this.projectiles.splice(i,1);}else if(p.life<=0)this.projectiles.splice(i,1);else p.p=add(p.p,move);}for(const f of this.fx)f.life-=dt;this.fx=this.fx.filter(f=>f.life>0);for(const p of this.puddles){p.life-=dt;if(Math.hypot(p.p[0]-this.player.p[0],p.p[2]-this.player.p[2])<p.r&&Math.abs(p.p[1]-this.player.p[1])<.4)this.hurt(dt*6);}this.puddles=this.puddles.filter(p=>p.life>0);}
 hurt(damage){if(this.god||this.ended)return;damage*=1-Math.min(.4,(this.progress.gear('armor')?.armor||0)/180);this.player.hp=Math.max(0,this.player.hp-damage);this.player.stamina=Math.max(0,this.player.stamina-damage*2);this.player.lastHit=this.time;this.hitTint=Math.min(.8,this.hitTint+.2);if(this.player.stamina<=0)this.player.dizzy=1.5;if(this.player.hp<=0)this.finish(false);}
 updateProps(dt){const pressing=Math.hypot(this.player.p[0]-this.plate.p[0],this.player.p[2]-this.plate.p[2])<1.05&&Math.abs(this.player.p[1])<.6;this.plate.active=pressing||this.props.some(a=>a.type==='crate'&&Math.hypot(a.p[0]-this.plate.p[0],a.p[2]-this.plate.p[2])<1.15&&Math.abs(a.p[1])<.7)||this.volume.value(add(this.plate.p,[0,.20,0]))>.7;
  for(const [g,active]of[[this.gate,this.plate.active],[this.vaultGate,this.lever.open]]){const old=g.p[1];g.open=clamp(g.open+(active?1:-1)*dt*.85,0,1);const next=g.home[1]+g.open*3.5;let obstructed=false;if(next<old)for(const a of[this.player,...this.knights,...this.props.filter(a=>a.movable)])if(Math.abs(a.p[0]-g.p[0])<1.9&&Math.abs(a.p[2]-g.p[2])<.65&&a.p[1]+(a.height||2)>next&&a.p[1]<old+g.height)obstructed=true;if(obstructed){g.open=(old-g.home[1])/3.5;}else g.p[1]=next;}
  for(const a of this.props){if(!a.movable)continue;const before=a.p.slice(),result=moveBody(this.world,a,a.vel[0]*dt,a.vel[2]*dt,dt);if(result.blockedX)a.vel[0]*=-.15;if(result.blockedZ)a.vel[2]*=-.15;const damp=Math.exp(-dt*(a.grounded?4:1));a.vel[0]*=damp;a.vel[2]*=damp;const d=sub(a.p,this.player.p);d[1]=0;if(len(d)<a.radius+this.player.radius+.10&&this.player.moving>.1&&Math.abs(a.p[1]-this.player.p[1])<.6){const nd=norm(d);a.vel[0]+=nd[0]*dt*8;a.vel[2]+=nd[2]*dt*8;}if(dist(before,a.p)>dt*2)this.noise(a.p,3.5);}
 }
 fireEnemy(a){const start=pose(a,this.time).handR,at=add(this.player.p,[0,1.25,0]),d=norm(sub(at,start));if(this.world.ray(start,d,dist(at,start)-.3))return;this.projectiles.push({p:start.slice(),v:mul(d,13),source:a.p.slice(),r:.13,life:3,used:1,color:a.color,owner:'enemy',gravity:0,bounces:0});}
 updateEnemies(dt){for(const a of this.knights){a._move=[0,0];updateKnight(a,this.player,this.world,dt,this.time,x=>this.fireEnemy(x),{disabled:this.aiDisabled});const attached=this.tethers.grab===a||this.tethers.links.some(l=>l.body===a);if(a.pin&&!attached)continue;if(a.captured&&!attached&&a.grounded)continue;let movement=a.captured||attached||a.down>0?[0,0]:a._move;const result=moveBody(this.world,a,movement[0]+a.vel[0]*dt,movement[1]+a.vel[2]*dt,dt);
   if(a.pendingPin>0){a.pendingPin-=dt;if(result.blockedX||result.blockedZ){const d=a.pushDir||norm(a.vel),hit=this.world.ray(add(a.p,[0,1.1,0]),d,1.25,true);if(hit&&Math.abs(hit.n[1])<.3){a.pin={p:hit.p.slice(),n:hit.n};a.down=0;a.vel=[0,0,0];a.anchors={};this.capture(a,'ΣΤΟΝ ΤΟΙΧΟ');}}}
   if(result.blockedX)a.vel[0]*=.12;if(result.blockedZ)a.vel[2]*=.12;const damp=Math.exp(-dt*(a.grounded?5:.5));a.vel[0]*=damp;a.vel[2]*=damp;
   if(!a.captured){if(a.hanging&&coating(a)>.53)this.capture(a,'ΑΝΑΡΤΗΣΗ');else if(coatedCapture(a))this.capture(a,'ΠΛΗΡΕΣ ΤΥΛΙΓΜΑ');}
   // Dynamic gum is genuinely an obstacle. A sight-confirmed guard can wear down
   // nearby cover; suspicion alone never shoots blindly through a new doorway.
   if(!this.aiDisabled&&!a.captured&&a.brain.mode==='combat'&&(result.blockedX||result.blockedZ)&&a.coat.armR<.7&&this.time>(a.nextBreach||0)){const goal=a.brain.lastKnown;if(goal){const o=add(a.p,[0,1.1,0]),d=norm(sub(add(goal,[0,1.1,0]),o)),h=this.world.ray(o,d,2.0);if(h?.gum){this.volume.stamp(add(h.p,mul(d,.15)),[.55,.7,.55],-1.6);a.nextBreach=this.time+1.5;}}}
  }
 }
 gainXP(amount){const n=this.progress.xp(amount);if(n){this.refreshStats();this.player.hp=this.player.maxHp;this.player.stamina=100;this.progress.auto();this.notify('LEVEL '+this.progress.p.level+' · +'+n+' skill point',3);this.tone('capture');}}
 dropLoot(p,boss=false){for(let i=0;i<(boss?3:1);i++)this.loots.push({p:add(p,[(i-1)*.55,.3,0]),item:this.progress.item(boss,this.rng),phase:this.rng()*TAU});}
 capture(a,label){if(a.captured)return;a.captured=true;a.state=a.hanging?'suspended':'captured';a.hp=0;a.moving=0;a.down=0;a.brain.mode='captured';this.captures++;this.gainXP(32+this.progress.p.tier*3);this.dropLoot(a.p);this.ammo=Math.min(CAP,this.ammo+70);this.player.hp=Math.min(this.player.maxHp,this.player.hp+10);this.player.stamina=Math.min(100,this.player.stamina+18);this.notify(label+' · '+a.name+' · +70 τσίχλα',3);this.tone('capture');}
 pickups(dt){for(let i=this.loots.length-1;i>=0;i--){const d=this.loots[i],delta=sub(add(this.player.p,[0,.5,0]),d.p),distance=len(delta);if(distance<3.3&&!this.world.ray(d.p,norm(delta),Math.max(0,distance-.25)))d.p=add(d.p,mul(norm(delta),Math.min(distance,dt*4)));if(distance<1.3&&this.progress.pickup(d.item)){this.notify('LOOT · '+d.item.name+' +'+d.item.power,2);this.loots.splice(i,1);}}
  for(const s of this.seals)if(!s.taken&&dist(add(this.player.p,[0,.8,0]),s.p)<1.45){s.taken=true;this.collected++;this.gainXP(35);this.notify('ΣΦΡΑΓΙΔΑ '+this.collected+'/3 · '+s.name,3);this.tone('capture');if(this.collected===3)this.bossDelay=3;}
 }
 spawnBoss(){this.boss={id:99,p:[0,0,0],yaw:0,hp:Math.round(660*(1+.20*(this.progress.p.tier-1))),maxHp:Math.round(660*(1+.20*(this.progress.p.tier-1))),stamina:170,dizzy:0,cooldown:2,phase:1,state:'active',splats:[],radius:2,vy:0,grounded:true};show('bossHud',true);this.notify('ARACHNE-09 · Οι σφραγίδες άνοιξαν το θησαυροφυλάκιο. Επέστρεψε στην αυλή.',5);}
 hitBoss(p,h){const b=this.boss;if(!b||b.state==='captured')return;const power=1+(this.progress.stats().damage||0)/90,d=(p.used>3?25+95*p.used/CAP:11)*(b.dizzy>0?2.1:1)*power*this.progress.stats().power;b.hp=Math.max(0,b.hp-d);b.stamina-=(p.used>3?60:13);if(b.stamina<=0&&b.dizzy<=0){b.dizzy=5.5;b.stamina=200;this.notify('ARACHNE-09 · DIZZY · τώρα η τσίχλα καλύπτει γρηγορότερα.',3);}if(b.hp<b.maxHp*.5)b.phase=2;if(b.hp<=0){b.state='captured';this.dropLoot(b.p,true);this.gainXP(180+25*this.progress.p.tier);this.projectiles=this.projectiles.filter(x=>x.owner==='player');this.puddles=[];this.bossEnd=2.5;this.notify('ARACHNE-09 ΑΣΦΑΛΙΣΜΕΝΗ · 3 Legendary αντικείμενα!',4);}}
 updateBoss(dt){const b=this.boss;if(!b||b.state==='captured'||this.aiDisabled)return;b.dizzy=Math.max(0,b.dizzy-dt);if(b.dizzy>0)return;const delta=sub(this.player.p,b.p),distance=len(delta);b.yaw+=angleDelta(b.yaw,Math.atan2(delta[0],delta[2]))*Math.min(1,dt*1.6);if(Math.abs(delta[1])>3.5||distance>25)return;const d=norm([delta[0],0,delta[2]]),speed=distance>11?1.35:distance<6?-1.1:0,nx=clamp(b.p[0]+d[0]*speed*dt,-9,9),nz=clamp(b.p[2]+d[2]*speed*dt,-10,18);if(!this.world.blocked(nx,nz,0,1.8,3.1)){b.p[0]=nx;b.p[2]=nz;}b.cooldown-=dt;if(b.cooldown>0)return;const start=add(b.p,[Math.sin(b.yaw)*1.8,2.05,Math.cos(b.yaw)*1.8]),target=add(this.player.p,[0,1.2,0]),aim=norm(sub(target,start));if(!this.world.ray(start,aim,dist(start,target)-.5))for(const angle of b.phase===2?[-.16,-.08,0,.08,.16]:[-.10,0,.10]){const c=Math.cos(angle),s=Math.sin(angle);this.projectiles.push({p:start.slice(),v:mul([aim[0]*c+aim[2]*s,aim[1],aim[2]*c-aim[0]*s],14),owner:'boss',source:b.p.slice(),life:4,r:.22,used:1,color:GREEN,gravity:0,bounces:0});}const drop=norm(sub(add(this.player.p,[Math.sin(this.time),-.15,Math.cos(this.time)]),start));this.projectiles.push({p:start.slice(),v:mul(drop,12),owner:'boss',source:b.p.slice(),life:4,r:.2,used:1,color:GREEN,gravity:1,bounces:0});b.cooldown=b.phase===2?1.25:1.9;}
 finish(win){if(this.ended)return;if(win){for(const d of this.loots)this.progress.pickup(d.item);this.loots=[];this.progress.complete();this.progress.auto();}this.progress.save();this.ended=true;this.input.clear();if(document.pointerLockElement)document.exitPointerLock();$('endTitle').textContent=win?'Το κάστρο είναι δικό σου.':'Μία ακόμη προσπάθεια.';$('endSummary').textContent=(win?'ARACHNE-09 ασφαλισμένη. ':'Οι περίπολοι σε σταμάτησαν. ')+this.captures+' / '+this.knights.length+' φρουροί · '+this.collected+'/3 σφραγίδες · '+Math.floor(this.elapsed/60)+':'+String(Math.floor(this.elapsed%60)).padStart(2,'0')+'. Ο εξοπλισμός και το level διατηρούνται.';show('next',win);show('end',true);}
 step(dt){dt=clamp(dt,0,.05);if(!this.playing())return;this.time+=dt;this.elapsed+=dt;this.frame++;this.shake=Math.max(0,this.shake-dt);this.hitTint=Math.max(0,this.hitTint-dt*1.3);$('hitTint').style.opacity=this.hitTint;this.notifyTime-=dt;if(this.notifyTime<=0)$('toast').classList.remove('show');if(this.reloadTime>0){this.reloadTime=Math.max(0,this.reloadTime-dt);if(this.reloadTime===0){this.ammo=CAP;this.refreshTools();}}
  if(this.fireDown&&this.tool==='splat'&&this.reloadTime===0)this.charge=Math.min(2.82,this.charge+dt);this.movePlayer(dt);this.setCamera();this.updateAim();this.twinFire.step(this,dt);if((this.fireDown||this.twinFire.toolActive)&&(this.tool==='flow'||this.tool==='erase')){this.flowClock+=dt;if(this.flowClock>=.055){const amount=this.flowClock;this.flowClock=0;this.construct(amount);}}else{this.flowClock=0;if(!this.fireDown)this.wallBrush=null;}
  this.updateProps(dt);this.updateEnemies(dt);this.updateBoss(dt);this.updateProjectiles(dt);this.pickups(dt);if(this.bossDelay>0){this.bossDelay-=dt;if(this.bossDelay<=0)this.spawnBoss();}if(this.bossEnd>0){this.bossEnd-=dt;if(this.bossEnd<=0)this.finish(true);}if(this.player.pathOn&&this.volume.full){this.player.pathOn=false;this.refreshTools();this.notify('Όριο ενεργού υλικού — σβήσε περιττές κατασκευές για να συνεχίσεις.');}
 }
 project(p){const q=point(this.camera.vp,p);return{x:(q[0]+1)*innerWidth/2,y:(1-q[1])*innerHeight/2,visible:q[3]>0&&Math.abs(q[0])<1.07&&Math.abs(q[1])<1.1};}
 updateHUD(){if(!this.started)return;const p=this.player;$('aimStick').classList.toggle('firing',this.twinFire.firing);$('hpText').textContent=Math.ceil(p.hp);$('hpFill').style.width=(100*p.hp/p.maxHp)+'%';$('staminaFill').style.width=p.stamina+'%';$('level').textContent='LV '+this.progress.p.level;$('captureCount').textContent=this.captures+'/'+this.knights.length;$('objective').textContent=this.boss?'ARACHNE-09':'ΣΦΡΑΓΙΔΕΣ '+this.collected+'/3';const s=this.world.support(p.p[0],p.p[2],p.p[1],.15);$('location').textContent=s?.s.name||'ΣΤΟΝ ΑΕΡΑ';const aware=this.knights.some(a=>a.brain.mode==='combat'&&a.sees),curious=this.knights.some(a=>a.brain.mode==='investigate'&&dist(a.p,p.p)<14);$('awareness').textContent=aware?'ΣΕ ΒΛΕΠΟΥΝ':curious?'? ΕΡΕΥΝΑ':'ΑΘΕΑΤΟΣ';$('awareness').className=aware?'danger':curious?'curious':'';
  $('ammoText').textContent=this.tool==='flow'||this.tool==='erase'?'∞':this.reloadTime>0?'↻':Math.floor(this.ammo);const charge=this.fireDown&&this.tool==='splat';show('chargeInfo',charge);$('chargeFill').style.width=(this.chargeAmmo()/CAP*100)+'%';$('chargeText').textContent='ΦΟΡΤΙΣΗ '+this.chargeAmmo()+' / '+this.ammo;$('chargeHint').textContent=this.lob?'ΤΟΞΟ ↗ · άφησε για βολή':this.touch?'Σύρε ↑ για τόξο · άφησε για βολή':'Alt: τόξο · Άφησε το κλικ για βολή';
  for(let i=0;i<this.knights.length;i++){const a=this.knights[i],el=this.labels[i],pos=this.project(add(a.p,[0,2.65,0])),d=sub(add(a.p,[0,1.2,0]),add(p.p,[0,1.5,0])),visible=pos.visible&&len(d)<20&&Math.abs(a.p[1]-p.p[1])<4.2&&!this.world.ray(add(p.p,[0,1.5,0]),norm(d),Math.max(0,len(d)-.5));el.style.display=visible?'block':'none';if(visible){el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.querySelector('.mark').textContent=a.hanging?'⌁':a.captured?'✓':a.brain.mode==='investigate'?'?':a.brain.mode==='combat'?'●':'';el.querySelector('.mark').className='mark '+(a.brain.mode==='combat'?'combat':'');el.querySelector('i').style.width=(100*(1-Math.min(1,coating(a))))+'%';el.querySelector('small').textContent=a.hanging?'ΚΡΕΜΑΣΜΕΝΟΣ':a.captured?'ΑΣΦΑΛΙΣΜΕΝΟΣ':a.down>0?'ΕΚΤΟΣ ΙΣΟΡΡΟΠΙΑΣ':a.coat.head>.72?'ΔΕΝ ΒΛΕΠΕΙ':a.coat.armR>.72?'ΟΠΛΟ ΔΕΜΕΝΟ':Object.keys(a.anchors).length?'ΠΟΔΙΑ ΚΟΛΛΗΜΕΝΑ':'';}}
  const a=this.aim.actor;show('targetPanel',!!a);if(a){$('targetName').textContent=a.name;if($('targetParts').children.length!==6)$('targetParts').replaceChildren(...REGIONS.map(k=>{const b=document.createElement('i');b.className='region-meter';b.title=k;b.textContent={head:'Κ',chest:'Σ',armL:'Χ',armR:'Χ',legL:'Π',legR:'Π'}[k];return b;}));REGIONS.forEach((k,i)=>$('targetParts').children[i].style.setProperty('--fill',Math.min(100,a.coat[k]*100)+'%'));$('targetHint').textContent=a.captured?'ΝΗΜΑ → τράβα → οροφή → κρέμασε':this.cameraMode==='top'?ZONE_LABEL[this.zoneName]+' · ΚΛΕΙΔΩΜΕΝΟΣ':'Η βολή χτυπά το πραγματικό σημείο';}
  const ret=this.cameraMode==='top'?this.project(this.aim.point):{x:innerWidth/2,y:innerHeight/2,visible:true};$('reticle').style.left=ret.x+'px';$('reticle').style.top=ret.y+'px';$('reticle').classList.toggle('locked',!!a);$('reticleLabel').textContent=this.tool==='flow'?FORM_LABEL[this.form]:this.tool==='strand'?'ΝΗΜΑ':this.tool==='erase'?'ΣΒΗΣΕ':a&&this.cameraMode==='top'?ZONE_LABEL[this.zoneName]:'';if(this.boss){$('bossFill').style.width=this.boss.hp/this.boss.maxHp*100+'%';$('bossState').textContent=this.boss.dizzy>0?'DIZZY '+this.boss.dizzy.toFixed(1)+'s':this.boss.phase===2?'ΦΑΣΗ 2':'ΤΟΞΙΚΗ ΦΡΟΥΡΑ';}
 }
 drawProps(out){for(const a of this.props){if(a.disabled)continue;if(a.type==='crate'){out.push(node('stone',add(a.p,[0,.6,0]),[1.3,1.2,1.3],a.color,[0,0,0],[.61,0,0,0]));for(const y of[.19,.98])out.push(node('cube',add(a.p,[0,y,0]),[1.34,.13,1.34],0x443b3d));if(a.coat>.05)out.push(node('sphere',add(a.p,[0,1.18,0]),[.55,.10+a.coat*.1,.55],GUM,[0,0,0],[.12,0,0,0]));}else if(a.type==='gate'){for(let i=-3;i<=3;i++)out.push(node('cylinder',add(a.p,[i*.42,1.4,0]),[.065,2.8,.065],0x505a6b));for(const y of[.25,1.7,2.65])out.push(node('cube',add(a.p,[0,y,0]),[3.0,.16,.25],0x927752));}else if(a.type==='lever'){out.push(node('stone',add(a.p,[0,.05,0]),[.65,.3,.65],0x667384));out.push(segment('cylinder',add(a.p,[0,.1,0]),add(a.p,[a.open?.3:-.3,.65,0]),.085,0xdac18a));out.push(node('sphere',add(a.p,[a.open?.3:-.3,.65,0]),[.16,.16,.16],a.open?0x8cf4ba:0xffbc6a));}}
  out.push(node('cube',this.plate.p,[2,.08,2],this.plate.active?0x71cfac:0xa69261));for(const x of[-.85,.85])out.push(node('cube',add(this.plate.p,[x,.055,0]),[.06,.025,1.6],0xeff1c3));for(const s of this.seals)if(!s.taken){const y=Math.sin(this.time*2.4)*.10;out.push(node('sphere',add(s.p,[0,y,0]),[.24,.32,.24],0xe7c27c,[0,0,0],[.14,.6,0,0]));out.push(node('cube',add(s.p,[0,y,0]),[.58,.58,.12],0xf4db9e,[0,this.time*.6,Math.PI/4],[.28,.25,0,0]));}
 }
 visibleActor(a){if(!this.started)return true;const origin=add(this.player.p,[0,1.85,0]);if(dist(a.p,this.player.p)>32||Math.abs(a.p[1]-this.player.p[1])>5)return false;for(const h of[1.85,.9]){const d=sub(add(a.p,[0,h,0]),origin);if(!this.world.ray(origin,norm(d),Math.max(0,len(d)-.35)))return true;}return false;}
 render(){this.setCamera();this.volume.upload(this.renderer,this.touch?3:5);const out=[],overlay=[];for(const a of this.knights)if(this.visibleActor(a))renderKnight(a,this.time,out);if(this.started&&this.cameraMode!=='fp')renderKnight(this.player,this.time,out,true);if(this.boss)spider(this.boss,this.time,out);out.push(...this.volume.renderNodes(this.renderer));this.drawProps(out);out.push(...this.tethers.nodes(this.player,this.time));for(const p of this.projectiles){out.push(node('sphere',p.p,[p.r,p.r,p.r],p.color,[0,0,0],[.12,.12,0,0]));out.push(segment('cylinder',p.p,add(p.p,mul(norm(p.v),-.40)),p.r*.45,p.color,[.12,.15,0,0]));}
  for(const f of this.fx){const u=1-f.life/f.max;out.push(node('sphere',f.p,[f.r*(.3+u*.7),f.r*.35,f.r*(.3+u*.7)],[...hex(f.color).slice(0,3),Math.max(.03,f.life/f.max*.6)],[0,0,0],[.12,.10,0,0]));}for(const p of this.puddles)out.push(node('sphere',add(p.p,[0,.03,0]),[p.r,.055,p.r],GREEN,[0,0,0],[.14,.2,0,0]));for(const d of this.loots){const q=add(d.p,[0,.14+Math.sin(this.time*3+d.phase)*.12,0]);out.push(node('stone',q,[.3,.3,.3],d.item.color,[0,this.time,0],[.20,.6,0,0]));out.push(node('cylinder',add(q,[0,.30,0]),[.025,.45,.025],d.item.color,[0,0,0],[.15,.6,0,0]));}
  if(this.beam?.until>this.time){const b=this.beam,from=b.left?pose(this.player,this.time).handL:b.from,d=sub(b.to,from);for(let i=0;i<9;i++){const a=add(from,mul(d,i/9)),z=add(from,mul(d,(i+1)/9));a[1]+=Math.sin(i*.8+this.time*15)*.022;out.push(segment('cylinder',a,z,b.erase?.035:.065,b.erase?0xa4ffe0:GUM,[.12,.15,0,0]));}out.push(node('sphere',b.to,[.14,.12,.14],b.erase?0xafffdd:GUM));}
  for(const [i,p]of this.world.torches.entries())out.push(node('sphere',p,[.14,.27+Math.sin(this.time*7+i)*.045,.14],0xffc578,[0,0,0],[.4,1.3,0,0]));if(this.started&&this.cameraMode==='fp'){firstPersonGun(this.player,this.time,this.ammo,CAP,this.reloadTime>0?Math.sin(this.reloadTime/1.7*Math.PI):0,this.fireDown?Math.min(.12,this.charge*.04):0,overlay,innerWidth/innerHeight);if(this.player.pathOn)overlay.push(node('sphere',[-.46,-.39,-.8],[.11,.10,.16],0xa1f3dc,[0,0,0],[.22,.06,0,0]));}
  this.renderer.setDynamic(out);this.renderer.setDynamic(overlay,true);const cut=this.started&&this.cameraMode==='top'?this.groundY+2.6:100;this.renderer.render(this.camera,this.time,cut,this.groundY<-1.35,this.started&&this.cameraMode==='fp');this.updateHUD();
 }
 installTest(){const game=this;window.__bubble={version:VERSION,game,step:(seconds=1,dt=1/60)=>{game.manualClock=true;for(let t=0;t<seconds-1e-8;t+=dt)game.step(Math.min(dt,seconds-t));game.render();return window.__bubble.snapshot();},start:()=>{game.manualClock=true;game.reset(true);game.setCamera();game.render();},snapshot:()=>({version:VERSION,player:{p:game.player.p.slice(),hp:game.player.hp,stamina:game.player.stamina,vy:game.player.vy,grounded:game.player.grounded,path:game.player.pathOn},ammo:game.ammo,charge:game.charge,tool:game.tool,region:game.zoneName,volume:game.volume.values.size,dirty:game.volume.dirty.size,captures:game.captures,seals:game.collected,knights:game.knights.map(a=>({id:a.id,p:a.p.slice(),coat:{...a.coat},state:a.state,brain:a.brain.mode,sees:a.sees||false,captured:a.captured,hanging:!!a.hanging,down:a.down})),ropes:game.tethers.links.length,projectiles:game.projectiles.length,paused:game.paused,ended:game.ended}),aimAt:p=>{game.testAim=p.slice();game.updateAim();}};}
}
try{window.addEventListener('error',e=>{const el=document.getElementById('bootStatus');if(el&&!document.getElementById('menu').classList.contains('hidden'))el.textContent='Σφάλμα: '+e.message;});new Siege(document.getElementById('game'));}catch(e){console.error(e);document.getElementById('bootStatus').textContent='Δεν ξεκίνησε: '+e.message;}
