import {clamp,hex} from './engine.js';
import {RARITIES} from './progression.js';
export const $=id=>document.getElementById(id);
export const show=(id,v)=>$(id).classList.toggle('hidden',!v);
export class Controls{
 constructor(canvas,api,touch){this.api=api;this.canvas=canvas;this.touch=touch;this.keys=new Set;this.move=[0,0];this.aim=[0,0];this.mouse=[innerWidth/2,innerHeight*.5];this.mouseActive=false;this.firePointer=null;this.lookPointer=null;this.lastMoveTap=-1000;
  for(const [id,type]of[['moveStick','move'],['aimStick','aim']])this.stick(id,type);
  const fire=$('fireBtn');fire.addEventListener('pointerdown',e=>{e.preventDefault();if(this.firePointer!==null)return;this.firePointer=e.pointerId;this.fireY=e.clientY;fire.setPointerCapture(e.pointerId);api.beginFire();});fire.addEventListener('pointermove',e=>{if(e.pointerId===this.firePointer&&this.fireY-e.clientY>28)api.arc(true);});fire.addEventListener('pointerup',e=>{if(e.pointerId!==this.firePointer)return;e.preventDefault();this.firePointer=null;api.endFire();});const cancel=e=>{if(e.pointerId===this.firePointer){this.firePointer=null;api.cancelFire();}};fire.addEventListener('pointercancel',cancel);fire.addEventListener('lostpointercapture',cancel);
  const buttons={jumpBtn:'jump',modeBtn:'mode',zoneBtn:'zone',useBtn:'use',reloadBtn:'reload',pathBtn:'path',gripBtn:'grip',gradeBtn:'grade',gaitBtn:'gait',cameraBtn:'camera',bagBtn:'bag',pauseBtn:'pause'};
  for(const [id,fn]of Object.entries(buttons))$(id).addEventListener('click',e=>{e.preventDefault();api[fn]();});
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){if(api.isFPS()&&e.clientX>innerWidth*.40&&this.lookPointer===null){this.lookPointer=e.pointerId;this.look=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);}return;}if(e.button===0){this.mouseDown=true;api.beginFire();}if(e.button===2)api.use();if(api.isFPS()&&api.playing())this.lock();});
  window.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'&&this.mouseDown){this.mouseDown=false;api.endFire();}if(e.pointerId===this.lookPointer)this.lookPointer=null;});canvas.addEventListener('pointercancel',e=>{if(e.pointerId===this.lookPointer)this.lookPointer=null;});
  window.addEventListener('pointermove',e=>{if(e.pointerType==='touch'){if(e.pointerId===this.lookPointer){api.look(-(e.clientX-this.look[0])*.004,-(e.clientY-this.look[1])*.004);this.look=[e.clientX,e.clientY];}return;}this.mouse=[e.clientX,e.clientY];this.mouseActive=true;if(document.pointerLockElement===canvas&&api.isFPS())api.look(-e.movementX*.0027,-e.movementY*.0024);});
  window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.repeat)return;const calls={Space:'jump',KeyC:'camera',KeyT:'mode',KeyE:'use',KeyR:'reload',KeyB:'path',KeyG:'grip',KeyV:'grade',KeyI:'bag',Escape:'pause',KeyX:'erase',KeyF:'wall'};if(calls[e.code])api[calls[e.code]]();if(/^Digit[1-4]$/.test(e.code))api.setZone(['head','chest','arms','legs'][Number(e.code.slice(-1))-1]);if(e.code==='AltLeft'||e.code==='AltRight')api.arc(true);});window.addEventListener('keyup',e=>this.keys.delete(e.code));
  window.addEventListener('blur',()=>{this.clear();if(api.playing())api.pause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.clear();if(api.playing())api.pause(true);}});window.addEventListener('resize',()=>api.resize());window.visualViewport?.addEventListener('resize',()=>api.resize());
 }
 stick(id,type){const el=$(id),knob=el.querySelector('i');let active=null,origin=[0,0];const update=e=>{if(e.pointerId!==active)return;const radius=el.clientWidth*.34,dx=e.clientX-origin[0],dy=e.clientY-origin[1],length=Math.hypot(dx,dy),scale=Math.min(1,radius/(length||1));this[type]=[dx*scale/radius,dy*scale/radius];knob.style.transform=`translate(${dx*scale}px,${dy*scale}px)`;e.preventDefault();};el.addEventListener('pointerdown',e=>{e.preventDefault();if(active!==null)return;active=e.pointerId;el.setPointerCapture(active);const r=el.getBoundingClientRect();origin=[r.left+r.width/2,r.top+r.height/2];if(type==='move'){const now=performance.now();if(now-this.lastMoveTap<280)this.api.jump();this.lastMoveTap=now;}update(e);if(type==='aim')this.api.beginFire();});el.addEventListener('pointermove',update);const end=e=>{if(active!==e.pointerId)return;if(type==='aim'){if(e.type==='pointerup')this.api.endFire();else this.api.cancelFire();}active=null;this[type]=[0,0];knob.style.transform='';};for(const evt of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(evt,end);el.addEventListener('resetstick',()=>{active=null;this[type]=[0,0];knob.style.transform='';});}
 clear(){this.keys.clear();this.move=this.aim=[0,0];this.mouseDown=false;this.firePointer=this.lookPointer=null;this.api.cancelFire();for(const id of['moveStick','aimStick'])$(id).dispatchEvent(new Event('resetstick'));}
 lock(){if(this.touch||!this.api.playing())return;try{const p=this.canvas.requestPointerLock();p?.catch?.(()=>{});}catch{}}
}
export class Armory{
 constructor(progress,api){this.progress=progress;this.api=api;$('closeBag').onclick=()=>api.closeBag();$('inventoryGrid').onclick=e=>{const card=e.target.closest('[data-item]');if(card){progress.equip(card.dataset.item);api.stats();this.render();}};$('inventoryGrid').oncontextmenu=e=>{const card=e.target.closest('[data-item]');if(card){e.preventDefault();const item=progress.p.items.find(x=>x.id===card.dataset.item);item.locked=!item.locked;progress.save();this.render();}};
  for(const el of document.querySelectorAll('[data-skill]'))el.onclick=()=>{progress.spendSkill(el.dataset.skill);api.stats();this.render();};$('forgeBase').onchange=()=>this.feeds();$('forgeFeed').onchange=()=>this.preview();$('forgeConfirm').onclick=()=>{const plan=progress.forge($('forgeBase').value,$('forgeFeed').value);api.notify(plan.error||'FORGED · '+plan.base.name);api.stats();this.render();};$('autoForge').onchange=e=>{progress.p.autoForge=e.target.checked;progress.save();};
 }
 options(el,items,label){el.replaceChildren();let option=document.createElement('option');option.value='';option.textContent=label;el.append(option);for(const x of items){option=document.createElement('option');option.value=x.id;option.textContent=x.name+' · '+x.power+(this.progress.isEquipped(x)?' [EQUIPPED]':'');el.append(option);}}
 render(){const p=this.progress.p,s=this.progress.stats();$('characterStats').textContent=`LV ${p.level} · XP ${p.xp}/${p.xpNext} · HP ${s.maxHp} · GUM +${s.damage} · STRETCH ${Math.round(s.stretch*100)}%`;$('gearSummary').textContent=['weapon','armor','charm'].map(k=>this.progress.gear(k)?.name||'—').join(' / ');$('resources').textContent=`${p.gold} GOLD · ${p.dust} DUST · ${p.skillPoints} SP · BAG ${p.items.length}/120 · SIEGE ${p.tier}`;for(const k of['power','elastic','vitality']){$(k+'Skill').textContent=p.skills[k];document.querySelector(`[data-skill="${k}"]`).disabled=p.skillPoints<1;}
  $('inventoryGrid').replaceChildren();for(const x of p.items){let b=document.createElement('button');b.className='loot';b.dataset.item=x.id;b.style.setProperty('--rarity','#'+RARITIES[x.rarity].c.toString(16));let rarity=document.createElement('small');rarity.textContent=RARITIES[x.rarity].n+' · '+x.type.toUpperCase();let title=document.createElement('b');title.textContent=x.name;let power=document.createElement('span');power.textContent='POWER '+x.power;let state=document.createElement('em');state.textContent=this.progress.isEquipped(x)?'EQUIPPED':x.locked?'LOCKED':'ΠΑΤΗΣΕ ΓΙΑ ΕΞΟΠΛΙΣΜΟ';b.append(rarity,title,power,state);$('inventoryGrid').append(b);}if(!p.items.length)$('inventoryGrid').textContent='Μάζεψε σφραγίδες, εξερεύνησε ή αιχμαλώτισε φρουρούς για loot.';
  const old=$('forgeBase').value;this.options($('forgeBase'),p.items,'Διάλεξε αντικείμενο');$('forgeBase').value=p.items.some(x=>x.id===old)?old:(this.progress.gear('weapon')?.id||p.items[0]?.id||'');this.feeds();$('autoForge').checked=p.autoForge;$('saveStatus').textContent=this.progress.storageFailed?'Η τοπική αποθήκευση απέτυχε.':this.progress.storage?'Η πρόοδος αποθηκεύεται σε αυτόν τον browser, χωρίς λογαριασμό ή cloud.':'Χωρίς αποθήκευση σε αυτή τη συνεδρία.';
 }
 feeds(){const p=this.progress.p,base=$('forgeBase').value;this.options($('forgeFeed'),p.items.filter(x=>x.id!==base&&!this.progress.isEquipped(x)&&!x.locked).sort((a,b)=>a.power-b.power),'Διάλεξε θυσία — θα χαθεί');this.preview();}
 preview(){const p=this.progress.plan($('forgeBase').value,$('forgeFeed').value);$('forgePreview').textContent=p.error||`${p.base.name}: ${p.base.power} → ${p.base.power+p.gain}. Χάνεται: ${p.feed.name}. Κόστος ${p.cost} Gold + 2 Dust.`;$('forgeConfirm').disabled=!!p.error;}
}
